### ISSUE TITLE
Cannot use export function with stated API token scopes, missing slo.read and others

### ISSUE THREAD

**Issue by 163a** [dynatrace-oss/terraform-provider-dynatrace#101]
When I run the export function on v1.9.1 I get a HTTP 403 response.

In the README it says `Read configuration` and `Capture request data` scopes are required. I needed to add more token scopes, as I kept getting HTTP 403 when exporting configuration.

Edit to lines 68-69 of README.md:

```
### Command Line Syntax
Invoking the export functionality requires
* The environment varibale `DYNATRACE_ENV_URL` as the URL of your Dynatrace Environment
* The environment variable `DYNATRACE_API_TOKEN` as the API Token with the permissions:
    -  `Read configuration`
    -  `Capture request data`
    -  `Read SLO`
    -  `Read settings`
    -  `Read synthetic monitors, locations, and nodes`
* Optionally the environment variable `DYNATRACE_TARGET_FOLDER`. If it's not set, the output folder `./configuration` is assumed
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for contributing. With the upcoming release the README contains your proposed changes.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Good news - release [v1.10.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.10.0) takes care of this issue. Thank you for your patience!
