### ISSUE TITLE
[Error] "no such file or directory" caused by whitespace at the end of alerting profile name

### ISSUE THREAD

**Issue by arnauagithub** [dynatrace-oss/terraform-provider-dynatrace#102]
When trying to export e.g. alerting_profiles the following error is thrown:

![attch](https://user-images.githubusercontent.com/90315468/149330891-be07d7f2-4ebf-4971-a02b-e74f9d917085.png)

It seems that the whitespace at the end of the exported alerting profile name causes this issue. This issue happens on windows and linux.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @arnauagithub 
I wasn't able to reproduce that behavior with normal space characters. I WAS able to get an error when using the tabulator character within the name. The export functionality in the upcoming release replaces now several white space characters (except SPACE itself) with underscores.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Good news - release [v1.10.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.10.0) takes care of this issue. Thank you for your patience!
