### ISSUE TITLE
[BUG] - Azure Supporting Services has an arbitrary limit of 10

### ISSUE THREAD

**Issue by Forcebyte** [dynatrace-oss/terraform-provider-dynatrace#103]
When attempting to create a bunch of supporting services for an Azure integration, we get various errors on resource constraints

for example:
```
 on main.tf line 59, in resource "dynatrace_azure_credentials" "azure_dyna_integration_nonp":

        content {

No more than 10 "monitored_metrics" blocks are allowed
```

I have a PR in the functional GoLang code here: https://github.com/dtcookie/dynatrace/pull/8 to fix this, seems related to this issue: https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/73 and I proposed to fix it in the same manner - adding an issue here for reporting just in case :)

**Comment by Forcebyte** [comment]
for now will use the 'unknowns' block just to unblock my current needs - but the PR might be helpful to others so will leave it up just in case

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Forcebyte ,

Thanks for the PR.
A new release will get pushed out within the week of Feb 14. It will contain this fix.
