### ISSUE TITLE
Error when trying to export any resource

### ISSUE THREAD

**Issue by jpandres** [dynatrace-oss/terraform-provider-dynatrace#104]
Hi there, I am trying to export dashboards and SLOs from one tenant.

I am using:
- macos 11.2.3
- terraform 1.1.5
- terraform-provider-dynatrace 1.9.1
- token generated with the required scopes: read slo, wrirte slo, read configuration, capture request data

Steps to reproduce:
1. Create project with provider resource
2. terraform init
3. terraform apply
4. export required env vars.
5. run terraform-provider- dynatrace_1.9.1 generated locally: `.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.9.1/darwin_amd64/terraform-provider-dynatrace_v1.9.1 export dynatrace_dashboard`

Result:
`The environment variable DYNATRACE_TARGET_FOLDER has not been set - using folder 'configuration' as default
invalid character '<' looking for beginning of value
`
and an empty folder created: `configuration/dashboards`

Expected result: 
folder configuration populated with all existent dashboards in the tenant.

Notes:

- i tried with dashborads and SLOs. no luck
- when I run the command it does not seem to reach the tenant because the token wasn't being marked as used in the dynatace access token dashboard.
- I tested the token to get dashboards with the REST API and it works.

Any ideas? What am I doing wrong? 
Thanks

**Comment by jpandres** [comment]
Nevermind....my problem was that I added a `/` at the end of the URL....maybe you want to explicitly mention not to put a ending `/`  in the README

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I just experimented around for an hour locally, trying to reproduce it. Finally I remembered that this is an issue that's on my backlog already :)
I'll introduce validation and auto-correct of flawed values for the environment URL with the next release.
