### ISSUE TITLE
Download not possible if "/" is in the name

### ISSUE THREAD

**Issue by ARZ-SagA** [dynatrace-oss/terraform-provider-dynatrace#11]
The download function is aborting if it's downloading a configuration with slash "/" in the Name.

It tries to write it in the directory after the /.

Best regards

Alex

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks Alex. Will be taken care of with the next release.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Fixed with [v1.0.6](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.6)
