### ISSUE TITLE
can't apply dynatrace_calculated_service_metric due to condition type error

### ISSUE THREAD

**Issue by JefersonGoncalves** [dynatrace-oss/terraform-provider-dynatrace#111]
Hi, I'm trying to convert the resource displayed in the 'API get result' but the error below is happening. Since the result of the get API returned one condition block and no mention of the condition types described in the error I believe that we might have a bug here.

If there is no bug, would it be possible to point out what is missing to replicate that resource through Terraform?
Thanks in advance!

## Error
```bash
Error: {
  "code": 400,
  "message": "Constraints violated.",
  "constraintViolations": [
    {
      "parameterLocation": "PAYLOAD_BODY",
      "location": "",
      "message": "At least one condition of the following types must be used: [SERVICE_DISPLAY_NAME, SERVICE_PUBLIC_DOMAIN_NAME, SERVICE_WEB_APPLICATION_ID, SERVICE_WEB_CONTEXT_ROOT, SERVICE_WEB_SERVER_NAME, SERVICE_WEB_SERVICE_NAME, SERVICE_WEB_SERVICE_NAMESPACE, REMOTE_SERVICE_NAME, REMOTE_ENDPOINT, AZURE_FUNCTIONS_SITE_NAME, AZURE_FUNCTIONS_FUNCTION_NAME, CTG_GATEWAY_URL, CTG_SERVER_NAME, ACTOR_SYSTEM, ESB_APPLICATION_NAME, SERVICE_TAG, SERVICE_TYPE, PROCESS_GROUP_TAG, PROCESS_GROUP_NAME]",
      "path": "conditions"
    }
  ]
}
```

##  Terraform resource
```terraform
resource "dynatrace_calculated_service_metric" "calc_svc_metric" {
  enabled = false
  metric_key = "calc:service.xyz"
  name = "xyz"
  unit = "COUNT"
  metric_definition {
    metric = "REQUEST_COUNT"
  }
  conditions {
    condition {
      attribute = "SERVICE_REQUEST_ATTRIBUTE"
      comparison {
        string_request_attribute {
          request_attribute = "xyz"
          operator = "EXISTS"
        }
      }
    }
  }
  dimension_definition {
    name = "Dimension"
    dimension = "{RequestAttribute:xyz}"
    top_x = 10
    top_x_direction = "DESCENDING"
    top_x_aggregation = "SINGLE_VALUE"
  }
}
```

## API get result
```json
{
  "metadata": {
    "configurationVersions": [
      0
    ],
    "clusterVersion": "1.235.149.20220221-150413"
  },
  "tsmMetricKey": "calc:service.xyz",
  "name": "xyz",
  "enabled": true,
  "metricDefinition": {
    "metric": "REQUEST_COUNT",
    "requestAttribute": null
  },
  "unit": "COUNT",
  "unitDisplayName": "",
  "entityId": "SERVICE-XYZ",
  "managementZones": [],
  "conditions": [
    {
      "attribute": "SERVICE_REQUEST_ATTRIBUTE",
      "comparisonInfo": {
        "type": "STRING_REQUEST_ATTRIBUTE",
        "comparison": "EXISTS",
        "value": null,
        "values": null,
        "negate": false,
        "requestAttribute": "xyz",
        "caseSensitive": false,
        "matchOnChildCalls": false,
        "source": null
      }
    }
  ],
  "dimensionDefinition": {
    "name": "Dimension",
    "dimension": "{RequestAttribute:xyz}",
    "placeholders": [],
    "topX": 10,
    "topXDirection": "DESCENDING",
    "topXAggregation": "SINGLE_VALUE"
  }
}
```

## Environment
```bash
[root@devops terraform-workspaces]# terraform --version
Terraform v0.14.11

Your version of Terraform is out of date! The latest version
is 1.1.6. You can update by downloading from https://www.terraform.io/downloads.html
```
Dynatrace provider version: 1.9.1

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JefersonGoncalves 

Sorry for the VERY late response here.

The issue you are facing stems from a limitation that's enforced when creating Calculated Service Metrics.

Take a look at the screenshot of me trying to create your configuration via WebUI.
![service-metric](https://user-images.githubusercontent.com/8580947/161250524-78514e9b-beca-4736-9068-bf80d3fbe49b.png)

The button "Create metric" is greyed out. You are getting forced to either specify a management zone or add a condition that narrows down the services this metric will be correlated with. Reason for that limitation is to ensure that there aren't Service Metrics getting created that apply to ALL services - essentially reducing the load on the Dynatrace Cluster.

What I would suggest to do is to create your Service Metric first in the WebUI and then download it using `terraform-provider-dynatrace export` functionality. That saves you quite some headaches with a lot of configurations.

**Comment by JefersonGoncalves** [comment]
Hi @Dynatrace-Reinhard-Pilz no problem and thank you very much for the answer. I'll try as you have recommended.
