### ISSUE TITLE
Doc error on dynatrace_k8s_credentials resource for events_field_selectors

### ISSUE THREAD

**Issue by dthomasag** [dynatrace-oss/terraform-provider-dynatrace#112]
The docs on the current version ([1.10.0](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/1.10.0/docs/resources/k8s_credentials)) of `dynatrace_k8s_credentials` for the `events_field_selectors` argument states the following:

> **events_field_selectors** (Block List) The check of SSL certificates is enabled (`true`) or disabled (`false`) for the Kubernetes cluster. If not set on creation, the `true` value is used. If the field is omitted during an update, the old value remains unaffected. (see [below for nested schema](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/k8s_credentials#nestedblock--events_field_selectors))

This is the same description as `certificate_check_enabled`, with a link to the correct nested block config appended.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
This issue has been fixed with [Release v1.11.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.11.0).
