### ISSUE TITLE
[Feature Request] Custom Extension

### ISSUE THREAD

**Issue by nickattardgsys** [dynatrace-oss/terraform-provider-dynatrace#114]
Quite simple, need to add the ability to create custom extensions via the operator. Currently this can be achieved by posting a zip file with the plugin.json.

In this particular case the extensions are JMX extensions, but I'm sure this can apply to any other type.

Would be convenient to add this functionality to the provider.

Cheers

**Comment by Dynatrace-Reinhard-Pilz** [comment]
That one will be a challenge. Uploading binary files is not necessarily something a Terraform Provider is supposed to do.
I will however look into the possibility to narrow things down to JMX Extensions only. Perhaps the plugin.json can get embedded into the .tf file using jsonencode.

**Comment by nickattardgsys** [comment]
Uploading a binary file via terraform is not easy indeed. However if the provider expects a json input, then providing the json document as-is from dynatrace-ui or custom then referencing it in the code is a vaild solution in my mind. something on the lines of local_file resource with jsondecode, then reference that resource as the payload for creating the custom extension.

thanks!
