### ISSUE TITLE
user_action_and_session_properties should allow more than 1 property

### ISSUE THREAD

**Issue by TigerC10** [dynatrace-oss/terraform-provider-dynatrace#116]
Just bumped into this one, I believe this should be `Min: 1` and not `Max: 1`:

> ### Nested Schema for `user_action_and_session_properties`
> 
> Optional:
> 
> - **property** (Block List, **Max: 1**) User action and session properties settings (see [below for nested schema](#nestedblock--user_action_and_session_properties--property))

https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/60972905ca6719a56e5f75754e62263adcc30123/docs/resources/web_application.md#nested-schema-for-user_action_and_session_properties

I was trying to automate setting multiple session properties across multiple apps.  The TF resource sees all of the properties added via the Dynatrace web UI and wants to _delete_ the properties beyond the first one.

**Comment by js-benchmarkcorp** [comment]
I have the same issue. Trying to create TF and have multiple properties for my app.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I'm planning to push out a new release this Friday. A fix for that will be included.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
This issue has been fixed with [Release v1.11.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.11.0).
