### ISSUE TITLE
description field not written when adding/changing SLO

### ISSUE THREAD

**Issue by reneforstner** [dynatrace-oss/terraform-provider-dynatrace#119]
Hi,
when adding/changing an SLO the "description" field is not getting written to dynatrace

- Provider Version 1.10.0
- Resource Used: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/slo

Propably this is due to the a change in the API, as the description field is called "customDescription" on the API documentation (and it works, when doing a POST directly towards the API with customDescription

**Comment by Dynatrace-Reinhard-Pilz** [comment]
This issue has been fixed with [Release v1.11.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.11.0).
