### ISSUE TITLE
Not all Dashboards are downloaded

### ISSUE THREAD

**Issue by Karthikeyanraman94** [dynatrace-oss/terraform-provider-dynatrace#12]
Hi Team,

when tried to do 
./terraform-provider-dynatrace download env_url  env_token [folder],

I could see that all auto-tags, alerting profile are getting downloaded, but only one dashboard is downloaded "Kubernetes cluster overview.dashboard.tf" and no other dashboards are getting downloaded

Our most of the Dashboard uses auto-tags, and we use Dynatrace enterprise

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I'll look into that before pushing out 1.0.6 early next week. Perhaps it's just a regression bug that got in during testing.
If it's not reproducible on our side I'd suggest we take a look at it together in your environment.

**Comment by Karthikeyanraman94** [comment]
Thanks Reinhard.. If needed let me know, I can share you the dashboard json to you personally...

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Fixed with [v1.0.6](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.6)
