### ISSUE TITLE
Is there an option to set the SLO Tile % decimal point to 2 digits?

### ISSUE THREAD

**Issue by kannanbalaji** [dynatrace-oss/terraform-provider-dynatrace#120]
Issue: 
In UI, we can see the option to modify the % decimal points on SLO Tile.
But using terraform, I do not see that option.
Refer to the snapshot - Decimal_points_issue_SLO_Tile

Please point me to a sample, if we have an option in terraform to set the decimal points.

Regards,
Balaji Kannan

![Decimal_points_issue_SLO_Tile](https://user-images.githubusercontent.com/86503013/160656048-1a6f2427-4096-4b71-8d10-f00db81b1e9f.jpg)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @kannanbalaji 
That's indeed a bit quirky at the moment. The JSON representation of a Dashboard (both via REST API and exported via WebUI) doesn't reflect that configuration at the moment.
I will reach out to Dynatrace R&D about when this can get configured in an automated way.
I'll keep that ticket open until then.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @kannanbalaji ,

It is meanwhile possible to define the number of decimal points for an SLO.
You can utilize the resource `dynatrace_json_dashboard` for that.

```
resource "dynatrace_json_dashboard" "SLO_owned_by_reinhard_pilz_dynatrace_com" {
  contents = jsonencode({
      "dashboardMetadata": {
        "hasConsistentColors": false,
        "name": "SLO",
        "owner": "reinhard.pilz@dynatrace.com",
        "preset": false,
        "shared": true
      },
      "tiles": [
        {
          "assignedEntities": [
            "${var.dynatrace_slo.xtgeifgyqv.id}"
          ],
          "bounds": {
            "height": 152,
            "left": 38,
            "top": 38,
            "width": 684
          },
          "configured": true,
          "isAutoRefreshDisabled": false,
          "metric": "METRICS=true;LEGEND=false;PROBLEMS=true;decimals=10;customTitle=xtgeifgyqv;",
          "name": "Service-level objective",
          "tileFilter": {
            "timeframe": "-5m"
          },
          "tileType": "SLO"
        }
      ]
    })
}
```
The decimal points are hidden within the property `metric`:
`"metric": "METRICS=true;LEGEND=false;PROBLEMS=true;decimals=10;customTitle=xtgeifgyqv;",`
