### ISSUE TITLE
Dashboard resources id dependency failure when using export functionality

### ISSUE THREAD

**Issue by jpandres** [dynatrace-oss/terraform-provider-dynatrace#121]
**Action**: exporting a dashboard with sharing configuration from one tenant and importing it in a new tenant
**Outcome:** the dashboard  sharing configuration creation fails because the id does not match.
**Desired outcome**: It should create the dashboard in the new tenant with the same configuration.

See exported dashboard `tf` file

![image](https://user-images.githubusercontent.com/29607133/161046387-2a953006-9309-4eba-8b23-31c70f8ea04a.png)

See terraform error log when creating sharing configuration/resource
![image](https://user-images.githubusercontent.com/29607133/161049451-0d34247a-4d9f-4809-8bc2-8c9b56021458.png)

We found a workaround and we believe that this could be managed in the logic of the `export` functionality. See below.
![image](https://user-images.githubusercontent.com/29607133/161049647-d978722f-4494-4120-9b9b-3ee58860440b.png)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for the hint. I will look into that. If it's feasible to implement it will be part of one of the next releases.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
[Release v1.13.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.13.1) takes care of this issue - essentially generates the resource `dynatrace_dashboard_sharing` exactly like you've suggested.

**Comment by jpandres** [comment]
Perfect, thanks!
