### ISSUE TITLE
supporting_services of resource which dynatrace_azure_credentials  cannot workable

### ISSUE THREAD

**Issue by JayChanggithub** [dynatrace-oss/terraform-provider-dynatrace#124]
Modules version: 1.11.0

```bash
resource "dynatrace_azure_credentials"  "shoot--cs--cic-cs-prod-us" {
    active = true
    monitor_only_tagged_entities = true
    /* monitorOnlyTaggedEntities = true */
    app_id = "xxxxxxx"
    auto_tagging = true
    directory_id = "xxxxxxx"
    key = "xxxxxxx"
    label = "shoot--cs--cic-cs-prod-us"

    monitor_only_tag_pairs {
       name = "shoot--cs--cic-cs-prod-us"
       value = "true"
    }

    monitor_only_tag_pairs {
       name = "production"
       value = "true"
    }

   supporting_services {
      name = "Azure HDInsight Cluster"

   }

   supporting_services {
      name = "Azure DB for PostgreSQL - Server"
   }

}
```
The above is code. However it would be response error as following
```bash
│ Error: {
│   "code": 400,
│   "message": "Constraints violated.",
│   "constraintViolations": [
│     {
│       "parameterLocation": "PAYLOAD_BODY",
│       "location": "",
│       "message": "Invalid generic services configuration: service Azure HDInsight Cluster not defined",
│       "path": "genericServices"
│     }
│   ]
│ }
│ 
│   with dynatrace_azure_credentials.shoot--cs--cic-cs-prod-us,
│   on azure.tf line 1, in resource "dynatrace_azure_credentials" "shoot--cs--cic-cs-prod-us":
│    1: resource "dynatrace_azure_credentials"  "shoot--cs--cic-cs-prod-us" {
```

**Comment by kishikawa12** [comment]
Hi @JayChanggithub,

Thank you for the details. Based off of the snippet that you provided, there is an incorrect reference to the Azure service which is causing the issue. For example, Azure HDInsight Cluster is referenced as “cloud:azure:hdinsight:cluster” via the API. The full list of Azure support services available along with the unique services names can be found by running the [/api/config/v1/azure/supportedServices](https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/azure-supported-services) REST call. 

The corrected resource block would be..
`resource "dynatrace_azure_credentials"  "shoot--cs--cic-cs-prod-us" {
    active = true
    monitor_only_tagged_entities = true
    /* monitorOnlyTaggedEntities = true */
    app_id = "xxxxxxx"
    auto_tagging = true
    directory_id = "xxxxxxx"
    key = "xxxxxxx"
    label = "shoot--cs--cic-cs-prod-us"

    monitor_only_tag_pairs {
       name = "shoot--cs--cic-cs-prod-us"
       value = "true"
    }

    monitor_only_tag_pairs {
       name = "production"
       value = "true"
    }

   supporting_services {
      name = "cloud:azure:hdinsight:cluster"

   }

   supporting_services {
      name = "cloud:azure:postgresql:server"
   }

}`

I hope that helps!

Regards,
Kodai
