### ISSUE TITLE
[Bug] Issue with dynatrace_application_error_rules module

### ISSUE THREAD

**Issue by sv-benchmarkcorp** [dynatrace-oss/terraform-provider-dynatrace#125]
Hello,

I am facing a weird behaviour with the `dynatrace_application_error_rules` module. In fact, every time I am modifying a value in the terraform configuration and then apply my change, it seems that all the `errors rules` gets deleted in Dynatrace for the application.

## Default state for an application

**In Dynatrace:**

| Request errors | Custom errors |
|:---------------:|:--------------:|
| ![Screen Shot 2022-04-27 at 1 49 19 PM](https://user-images.githubusercontent.com/99672106/165591116-9a724a4b-4156-41b6-a10c-94e04dadf642.png) |  ![Screen Shot 2022-04-27 at 1 49 34 PM](https://user-images.githubusercontent.com/99672106/165591088-bc55fc59-536a-4af1-a8f4-9d9f9b7dd21b.png) |

**In terraform (values retrieved thanks to `./terraform-provider-dynatrace export dynatrace_application_error_rules` cmd):**

```
resource "dynatrace_application_error_rules" "my_app" {
  # ignore_custom_errors_apdex = false
  # ignore_http_errors_apdex = false
  # ignore_js_errors_apdex = false
  web_application_id = "APPLICATION-***"
  custom_errors {
    rule {
      capture = true
      custom_alerting = true
      # impact_apdex = false
    }
  }
  http_errors {
    rule {
      # capture = false
      # consider_blocked_requests = false
      # consider_for_ai = false
      # consider_unknown_error_code = false
      error_codes = "404"
      filter = "ENDS_WITH"
      filter_by_url = true
      # impact_apdex = false
      url = "favicon.ico"
    }
    rule {
      capture = true
      # consider_blocked_requests = false
      consider_for_ai = true
      # consider_unknown_error_code = false
      error_codes = "404"
      filter = "ENDS_WITH"
      filter_by_url = true
      impact_apdex = true
      url = ".js"
    }
    rule {
      capture = true
      # consider_blocked_requests = false
      consider_for_ai = true
      # consider_unknown_error_code = false
      error_codes = "404"
      filter = "ENDS_WITH"
      filter_by_url = true
      impact_apdex = true
      url = ".css"
    }
    rule {
      capture = true
      # consider_blocked_requests = false
      # consider_for_ai = false
      # consider_unknown_error_code = false
      error_codes = "400-499"
      # filter_by_url = false
      impact_apdex = true
    }
    rule {
      capture = true
      # consider_blocked_requests = false
      consider_for_ai = true
      # consider_unknown_error_code = false
      error_codes = "500-599"
      # filter_by_url = false
      impact_apdex = true
    }
    rule {
      capture = true
      # consider_blocked_requests = false
      # consider_for_ai = false
      # consider_unknown_error_code = false
      error_codes = "970-979"
      # filter_by_url = false
      impact_apdex = true
    }
    rule {
      capture = true
      # consider_blocked_requests = false
      # consider_for_ai = false
      consider_unknown_error_code = true
      # filter_by_url = false
      # impact_apdex = false
    }
    rule {
      capture = true
      consider_blocked_requests = true
      consider_for_ai = true
      # consider_unknown_error_code = false
      # filter_by_url = false
      impact_apdex = true
    }
  }
}
```

## Steps to reproduce the issue

1) Export the application rules for an application using the `terraform-provider-dynatrace` cmd

2) Run terraform `terraform apply`

3) Observe the changes in Dynatrace

| Request errors | Custom errors |
|:---------------:|:--------------:|
| ![Screen Shot 2022-04-27 at 1 53 33 PM](https://user-images.githubusercontent.com/99672106/165592650-c4a9fa36-7051-47f4-ad4e-9f8b22c0cb0f.png) | ![Screen Shot 2022-04-27 at 1 53 27 PM](https://user-images.githubusercontent.com/99672106/165592693-1de38db0-763a-490d-8f59-a7ff15ac5da0.png) |

#### notes

I can observe the same behaviour even when I reset the default rules by clicking on the `Use defaults` button located in the top right corner of the Dynatrace UI. Then if I re-apply or try to apply a single change like the following, all the rules are deleted again. E.g:

```bash
  - # ignore_js_errors_apdex = false 
  + ignore_js_errors_apdex = true
```

## Various

- Terraform version: `Terraform v1.1.5`
- Modules version: `1.11.0`

Thanks in advance for looking at this issue and please let me know if you need more details.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @sv-benchmarkcorp 
This is not weird behavior, this is a terrible bug - origin is hasty implementation and an incomplete test case :(

Sorry about the late response here, my time was very limited in the past few weeks.

I have fixed that bug locally already. I might need until Monday before pushing out the new release, but hour fix will be included.
