### ISSUE TITLE
featReq: Create API Tokens through Terraform

### ISSUE THREAD

**Issue by reneforstner** [dynatrace-oss/terraform-provider-dynatrace#128]
Hi,
I'm wondering if there is a timeline for getting the Access/API Token API also included in the Terraform provider anytime soon?

best
René

**Comment by kishikawa12** [comment]
Hi @reneforstner,

We appreciate your patience, this feature is planned to be introduced in our release this week.

Thanks!
Kodai

**Comment by kishikawa12** [comment]
Hi @reneforstner,

Thank you for your patience. [Release 1.16.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.16.0) includes the ability to create API tokens via the resource `dynatrace_api_token` . Note that this resource will introduce sensitive data (tokens) within your Terraform state as plain text. 

Thanks!
Kodai
