### ISSUE TITLE
Cant export terraform config as per manual

### ISSUE THREAD

**Issue by hhminh** [dynatrace-oss/terraform-provider-dynatrace#129]
According to https://github.com/dynatrace-oss/terraform-provider-dynatrace terraform-provider-dynatrace.exe export option can be run as standalone but its not working anymore

 

Now run with the env variables for url and keys like this

 

terraform-provider-dynatrace.exe export *[<resourcename>[=<id>]]

 

will just result in error "This binary is a plugin. These are not meant to be executed directly."

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @hhminh 

* Typing in `terraform-provider-dynatrace.exe export` (without the `*[[=]]`) will export all currently supported resources.
* Typing in `terraform-provider-dynatrace.exe export dynatrace_management_zone` will export just the management zones.

You ticket is unfortunately rather old - apologies for not reacting earlier. But with the most recent version you should not have any troubles.
