### ISSUE TITLE
[Fix/Improvement] dynatrace_key_requests resource missing export feature

### ISSUE THREAD

**Issue by adriangonciarz** [dynatrace-oss/terraform-provider-dynatrace#130]
```
terraform-provider-dynatrace_v1.11.0 export dynatrace_key_requests
```
Yields an error
```
Unknown resource `dynatrace_key_requests`
```
As per https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/68 the functionality of export is not supported since 0.10.0. Also, I wasn't able to find a good example on how to use the resource in the docs or in tests directory, I don;t see any tests added when merging 
https://github.com/dynatrace-oss/terraform-provider-dynatrace/commit/530d382a354db4ed2e381e30343e4cbb3787a936

**Comment by thehogfather** [comment]
Any updates on this? It would be really helpful.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Incidentally I was working on that this morning. Prerequisite for that functionality was the data source `dynatrace_service`, which had been introduced with the most recent version.

The next release will allow you use the export functionality for key requests. 
The one restriction here: Only Key Requests for Services that were visible within the last 72 hours within Dynatrace will get exported.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
You're correct @adriangonciarz , there don't exist automatic tests for key requests at the moment. Reason behind that is, that this resource is tightly bound to the existence of a service within the current topology. That's not a luxury when working against a generic dynatrace environment. Therefore that functionality is getting tested manually for the time being.

An example for a key request looks like this:

```
resource "dynatrace_key_requests" "my_service" {
  names = ["/ctx/random/bycicle", "/ctx/random/bycicle1"] 
  service = "SERVICE-D892CFE7DFAB0D08" 
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,

Exporting Key Requests is now possible with the most recent version of the Terraform Provider.
