### ISSUE TITLE
browser monitor keystrokes event link credentials vault

### ISSUE THREAD

**Issue by xcheng75** [dynatrace-oss/terraform-provider-dynatrace#131]
Could not find how to set keystrokes value to use dyntrace credentials vault?

**Comment by msmost** [comment]
@Dynatrace-Reinhard-Pilz @kishikawa12 This is something that we would also be interested in. Today, it looks like only a raw text option is available for the keystrokes events. In the GUI, we can either input text or select a credential from the credentials vault. Would it be possible to include this functionality as part of the next release?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @xcheng75 and @msmost 

Thanks for the reminder. We DID include credential support for HTTP monitors in our previous release, but couldn't remember where they are not supported for Browser Monitors.

A bit of a background for why we didn't support that until now. The Script Content for Monitors is unfortunately not documented via REST API. Our support here stems indeed from reverse engineering existing configurations - where we unfortunately never thought about configuring authentication.

We're releasing 1.13.2 today, this issue will be covered.

**Comment by msmost** [comment]
@Dynatrace-Reinhard-Pilz @kishikawa12 Thank you so much for the quick turn around!
