### ISSUE TITLE
Update documentation on Terraform Module Registry

### ISSUE THREAD

**Issue by moseskt** [dynatrace-oss/terraform-provider-dynatrace#133]
Please enhance the documentation to enable faster getting started and for users to prefer infrastructure as code which is a DevOps best practice. Welcome updates include 
- descriptions on the resources and links to relevant sections in main Dynatrace documentation
- accurate getting started examples like most major providers

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @moseskt ,

We've now begun with improving our documentation. Check out the documentation page for `dynatrace_mq_manager` within the documentation pages of the [Terraform Registry](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/queue_manager). Like for this resource we're planning to add at least one example, links to the Dynatrace Docs and a hint for how to export existing resources to all the other supported resources and data sources. Any feedback for improvement here would be very welcome!

**Comment by kishikawa12** [comment]
Hi @moseskt,

[Release v1.13.2](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.13.2) published today contains improved documentation on all resources and data sources including the suggestions that you provided. Please let us know of any feedback, thanks!
