### ISSUE TITLE
data source dynatrace_credentials does not work

### ISSUE THREAD

**Issue by xcheng75** [dynatrace-oss/terraform-provider-dynatrace#135]

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @xcheng75 

You were right, the data source `dynatrace_credentials` was pretty useless until now.
The upcoming release contains functionality for that data source that allows you to query by the most common properties.

**Comment by kishikawa12** [comment]
`dynatrace_credentials` now has the ability to query by type, name, and scope. Closing the ticket for now, please re-open if additional support is needed. Thanks!
