### ISSUE TITLE
[Feature Request] Create New Environment

### ISSUE THREAD

**Issue by Satak** [dynatrace-oss/terraform-provider-dynatrace#14]
It would be great to support environment resource so we could create new Dynatrace environments with Terraform (+`createToken` param value):
[example](https://www.dynatrace.com/support/help/shortlink/api-cluster-environments-create-new#example)

**Comment by Satak** [comment]
hcl mockup:

```hcl
resource "dynatrace_environment" "my_environment" {
  name        = "MyNewTeam"
  state       = "ENABLED"
  tags        = {
    owner      = "john.wicked@dynatrace.com"
    department = "finance"
  }
  trial       = false
  createToken = true
}
```

btw. It would be good to have this kind of examples for all resources!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Satak,

That feature is already on our radar. We'd like to cover a few more important settings first, but Environment Creation is definitely something we're going to support in the future.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everybody,

Release [v1.7.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.7.0) allows for the creation of Environments on Managed Dynatrace Clusters.
