### ISSUE TITLE
[Question] Use terraform to manage resources which already manually set up before

### ISSUE THREAD

**Issue by JayChanggithub** [dynatrace-oss/terraform-provider-dynatrace#140]
Have any possible be able to use these framework to manage already exist resources. For example `terraform import`. If so can raise a sample code for reference? Thank you.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JayChanggithub 
Sorry for not responding earlier here.
But I believe we've clarified your questions in #141 am I right?

**Comment by JayChanggithub** [comment]
Yes, Thanks!
