### ISSUE TITLE
Support arm architecture again

### ISSUE THREAD

**Issue by jtymes** [dynatrace-oss/terraform-provider-dynatrace#143]
**Is your feature request related to a problem? Please describe.**
Arm support was removed in 81701f3f2ff39af295fe6ef8139188ef18c0c21d with no explanation in the commit. Are there concerns with supporting arm64 for the project? 

**Describe the solution you'd like**
To have arm architecture be supported going forward. 

**Describe alternatives you've considered**
Overriding the provider locally can work to run through Rosetta, but it's not ideal. 

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hell @jtymes 

For some reason go-releaser failed when pushing out the latest release. On short notice I just saw the possibility to remove arm support.
But, yes, I'm planning to re-add ARM support again.

**Comment by jtymes** [comment]
Thank you!
