### ISSUE TITLE
Maintenance windows exports are not usable

### ISSUE THREAD

**Issue by daniel-lewis-kwb** [dynatrace-oss/terraform-provider-dynatrace#145]
**Describe the bug**
Very closely related to https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/138. An error occurs on terraform apply when using exported maintenance windows from dynatrace that doesn't contain tags. It seems that trying to apply the exact same exported resource(once removed from Dynatrace) will fail with errors about requiring tags(declared optional in provider documentation).

**To Reproduce**
1. Export all Maintenance Windows via 1.12.1 provider
2. Select a maintenance window(an export) that looks like 
```
resource "dynatrace_maintenance_window" "maintenance_test" {
  name        = "maintenance_test"
  description = "test"
  type        = "PLANNED"
  # suppress_synth_mon_exec = false 
  suppression = "DETECT_PROBLEMS_DONT_ALERT"
  schedule {
    end             = "2022-08-12 04:00"
    recurrence_type = "ONCE"
    start           = "2022-08-11 20:00"
    zone_id         = "Pacific/Auckland"
  }
  scope {
    matches {
      type            = "CUSTOM_DEVICE"
      tag_combination = "AND"
    }
  }
}

```
3. Run `terraform plan` and then `terraform apply`
4. See error below about missing tags:
```
dynatrace_maintenance_window.maintenance_test: Creating...
╷
│ Error: {
│   "code": 400,
│   "message": "Constraints violated.",
│   "constraintViolations": [
│     {
│       "parameterLocation": "PAYLOAD_BODY",
│       "location": "",
│       "message": "must not be null",
│       "path": "scope.matches[0].tags"
│     }
│   ]
│ }
│ 
│   with dynatrace_maintenance_window.maintenance_test,
│   on maintenance_test.tf line 1, in resource "dynatrace_maintenance_window" "maintenance_test":
│    1: resource "dynatrace_maintenance_window" "maintenance_test" {
```

**Expected behaviour**
A maintenance window to be created in Dynatrace SaaS that reflects the exported resource - these have been proven and created successfully using the UI in Dynatrace.

**Screenshots**
Below is the configuration that can be exported successfully, although this cannot be applied.

![image](https://user-images.githubusercontent.com/94332069/185001434-555e67fe-1347-4e08-9f9f-1248268e6e29.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Terraform Version: v1.0.11
 - Dynatrace Provider Version: 1.12.1

**Comment by daniel-lewis-kwb** [comment]
I have found another instance of an exported maintenance window that is failing:

```
resource "dynatrace_maintenance_window" "test_scope" {
  name = "test_scope" 
  type = "PLANNED" 
  # suppress_synth_mon_exec = false 
  suppression = "DETECT_PROBLEMS_DONT_ALERT" 
  schedule {
    end = "2022-07-10 05:00" 
    recurrence_type = "ONCE" 
    start = "2022-07-10 00:50" 
    zone_id = "Pacific/Auckland" 
  }
  scope {
  }
}
```

The error message below suggests scope should include more details although this is not provided in the UI or from the export above:

```
Error: { "code": 400, "message": "Constraints violated.", "constraintViolations": [ { "parameterLocation": "PAYLOAD_BODY", "location": "", "message": "The scope must contain at least one entity or one matches filter.", "path": "scope" } ] }
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,

Release 1.13.1 is scheduled for coming Friday. It will be able to handle maintenance windows without tags / scope specified. The export functionality will furthermore omit the whole scope block in case it doesn't contain any content.

regards,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
[Release v1.13.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.13.1) takes care of this issue.
