### ISSUE TITLE
The dependency libraries need licenses

### ISSUE THREAD

**Issue by xcheng75** [dynatrace-oss/terraform-provider-dynatrace#146]
the dependency libary https://github.com/dtcookie/dynatrace does not have a license. Please add one.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @xcheng75 ,

We are planning to gradually switch to a different version for the dependency libraries, which eventually will be located also on `dynatrace-oss`. These new libraries will then run under the same license as the terraform provider.

**Comment by xcheng75** [comment]
@Dynatrace-Reinhard-Pilz is there estimated timeline for adding a license file to the dependency repo?
