### ISSUE TITLE
Add OAuth2 authorization request type for dynatrace_http_monitor resource

### ISSUE THREAD

**Issue by ekleiner14** [dynatrace-oss/terraform-provider-dynatrace#149]
Hey @Dynatrace-Reinhard-Pilz and @kishikawa12 

Apologies if this is already an issue or future enhancement I missed, but I'm wondering if there's any plans to extend the dynatrace_http_monitor resource to include the OAuth2 authorization request type. I noticed that exporting an http monitor resource with OAuth2 request type worked but it just defaulted to using the http request type config instead. Then I took a closer look in the http monitor resource documentation [here](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/http_monitor#nested-schema-for-script) and didn't see anything for OAuth2. The pattern for this works in the UI as documented [here](https://www.dynatrace.com/support/help/how-to-use-dynatrace/synthetic-monitoring/general-information/synthetic-authentication#oauth2) so it would be awesome if the provider could eventually do the same. Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ekleiner14 

You have apparently stumbled across a limitiation of the Dynatrace REST API.
I just retraced your steps (using the REST API directly, not the provider). Essentially I created a HTTP monitor that uses OAuth2 and then duplicated it via REST API.
That "clone" suffers from the same shortcomings than what you've described when using the Terraform Provider.

My understanding is, that an OAuth2 Request is as a matter of fact nothing else than a normal HTTP Request - the WebUI just prepopulates the necessary properties for you as a convenience. 

Based on your findings it's however clear that the WebUI must maintain a tiny bit of information that's not available via REST API - and therefore also not to the provider.

As a next step I need to reach out to Dynatrace R&D. I suspect that with a few changes in the Schema for HTTP Monitors we can add proper support for OAuth2.

**Comment by ekleiner14** [comment]
Thank you @Dynatrace-Reinhard-Pilz - please keep me updated :)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ekleiner14 ,

I've received response from R&D about this.
They confirm our findings - when created via REST API the WebUI is not clearly stating, that one of the requests is being used for OAuth2 authentication for another request. They also are assuring that it doesn't affect the actual functionality.

In other words, if you export such a HTTP Monitor using the provider, that `dynatrace_http_monitor` resource will produce an HTTP Monitor with working OAuth2 functionality. What matters are the pre- and post-execution scripts.

Makes sense?

**Comment by ekleiner14** [comment]
Hey @Dynatrace-Reinhard-Pilz - I see where I went wrong. At first the output wasn't what I expected and I had a different issue that prevented it from working. After trying again and taking a closer look with R&D's feedback I was able to get what I need. Thanks!
