### ISSUE TITLE
Dashboards setup in terraform have some parameters changed without user modifying them whenever pipelines are run

### ISSUE THREAD

**Issue by saadrafique768** [dynatrace-oss/terraform-provider-dynatrace#150]
**Describe the bug**
The parameter "preset" that is set in dynatrace_dashboard_sharing resource has its value changed whenever we run pipeline in the environment where dashboards are configured in terraform. It randomly changes preset boolean value from false to true and some times from true to false

**To Reproduce**
1. Run pipelines for environment where dashboards configured in terraform exist
2. make sure to have some dashboards preset value set to true and some to false.
3. make sure to include "TF_LOG=debug" for more logs 
4. you can find in logs information regarding preset values being changed with header "Terraform detected the following changes made outside of Terraform since the last "terraform apply"

Terraform version running in CI/CD is `1.1.2`

**Expected behavior**
preset value changes from false to true and vice versa without user modification

**Screenshots**
```
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
  # dynatrace_dashboard_sharing.x has changed
  ~ resource "dynatrace_dashboard_sharing" "x" {
        id           = "x.id"
      ~ preset       = true -> false
        # (2 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
  # dynatrace_dashboard_sharing.y will be updated in-place
  ~ resource "dynatrace_dashboard_sharing" "y" {
        id           = "y.id"
      ~ preset       = false -> true
        # (2 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
```

**Additional context**
We also found some warnings that could be relatable but not necessarily the main root cause here.
```
2022-10-13T14:32:15.411Z [WARN]  Provider "registry.terraform.io/dynatrace-oss/dynatrace" produced an invalid plan for dynatrace_dashboard_sharing.z, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .preset: planned value cty.False for a non-computed attribute
      - .permissions[0].permission[0].id: planned value cty.StringVal("") for a non-computed attribute
```

Really need help with above issue as it is affecting visibility for team on dashboards that need be viewable at all times for all members in the organization.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Saad,

Thanks for the additional information. If you don't mind, let's continue working on this here on GitHub instead of using a Dynatrace Support ticket.

Next steps:
* We will hold the release we've scheduled for today until Monday.
* That we we can take care of the warnings terraform spits out with `TF_LOG=debug` turned on.

Could you check, whether your CI/CD pipeline invokes terraform with the `-parallelism=1` argument? We DO have a known issue that in certain situations running too many calls in parallel against the REST API produced unreliable results.
I will nevertheless re-implement the `dynatrace_dashboard_sharing` resource, so there are no warnings anymore, but I'd like to be extra sure that `-parallelism=1` may be the ACTUAL solution here.

**Comment by saadrafique768** [comment]
We ran CI/CD pipeline using `-parallelism=1` argument to see how it impacts.

1 - ran a job to apply on prod environment > One of the dashboards has preset = true

```
{
      "mode": "managed",
      "type": "dynatrace_dashboard_sharing",
      "name": "slo_dashboard_sharing",
      "provider": "provider[\"registry.terraform.io/dynatrace-oss/dynatrace\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "dashboard_id": "x.id",
            "enabled": true,
            "id": "x.id",
            "permissions": [
              {
                "permission": [
                  {
                    "id": "",
                    "level": "VIEW",
                    "type": "ALL"
                  }
                ]
              }
            ],
            "preset": true,
            "public": []
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "dynatrace_dashboard.slo_dashboard",
            "dynatrace_slo.error_rate_slo",
            "dynatrace_slo.response_rate_slo"
          ]
        }
      ]
    },
```

2 - Next we ran the plan for the same environment to see how if preset values reverse for some as they did before > 

```
[0m[1mdynatrace_dashboard_sharing.slo_dashboard_sharing: Refreshing state... [id=x.id][0m
2022-10-14T14:27:31.281Z [WARN]  Provider "registry.terraform.io/dynatrace-oss/dynatrace" produced an unexpected new value for dynatrace_dashboard_sharing.slo_dashboard_sharing during refresh.
      - .preset: was cty.True, but now cty.False
2022-10-14T14:27:31.288Z [WARN]  Provider "registry.terraform.io/dynatrace-oss/dynatrace" produced an invalid plan for dynatrace_dashboard_sharing.slo_dashboard_sharing, but we are tolerating it because it is using the legacy plugin SDK.
```

So it seems like the preset values are still getting changed without user modification as seen from above sample. The above dashboard right now on prod environment is not visible to all users since preset = false even though its set to true.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @saadrafique768 ,

The next release (will be pushed out either today or tomorrow) will contain a couple of changes here:
* `TF_LOG=debug` will not produce warnings anymore.
* `TF_LOG_PROVIDER_DYNATRACE=debug` (needs to be accompanied by `TF_LOG=debug`) will produce output about the HTTP activity for the resource `dynatrace_dashboard_sharing`.
  * Look for output like `PUT /dashboards/b6e91995-1753-4306-a3cc-de051b359f53/shareSettings
    {"id":"b6e91995-1753-4306-a3cc-de051b359f53","permissions":[{"type":"ALL","permission":"VIEW"}],"publicAccess":{"managementZoneIds":[]},"preset":false,"enabled":true}`
* A resource of type `dynatrace_dashboard_sharing` is no longer "borrowing" the ID of the dashboard its Dashboard within the Terraform State. The ID of such a resource will now be unique globally within the state.

Once the the new version has been release, please exacute another test run with `TF_LOG=debug` and `TF_LOG_PROVIDER_DYNATRACE=debug`. In case you're worried about confidential data within these logs, feel free to reach out via email to me.

**Comment by saadrafique768** [comment]
with Terraform version: 1.1.2 and provider version: v1.14.0 (the latest update)

We tried to run pipelines again and this time as well several dashboards had their preset status reversed. 

we looked for logs containing information regarding sharesettings change and found 2 only >

```
2022-10-18T09:59:42.915Z [INFO]  Starting apply for dynatrace_dashboard_sharing.aggregators_performance
2022-10-18T09:59:42.926Z [DEBUG] dynatrace_dashboard_sharing.aggregators_performance: applying the planned Update change
2022-10-18T09:59:42.929Z [DEBUG] provider.terraform-provider-dynatrace_v1.14.0: 
PUT /dashboards/x.id/shareSettings
    {"id":"x.id","permissions":[{"type":"ALL","permission":"VIEW"}],"publicAccess":{"managementZoneIds":[]},"preset":true,"enabled":true}
: @caller=github.com/dtcookie/dynatrace/api/config/dashboards/sharing@v1.0.2/service_client.go:44 @module=provider tf_resource_type=dynatrace_dashboard_sharing tf_rpc=ApplyResourceChange tf_provider_addr=provider tf_req_id=bd22b901-f2e8-d49f-d578-da599b5ef572 timestamp=2022-10-18T09:59:42.929Z
```
second one >

```
2022-10-18T09:59:30.673Z [INFO]  Starting apply for dynatrace_dashboard_sharing.rejections_cancellations
2022-10-18T09:59:30.680Z [DEBUG] dynatrace_dashboard_sharing.rejections_cancellations: applying the planned Update change
2022-10-18T09:59:30.683Z [DEBUG] provider.terraform-provider-dynatrace_v1.14.0: 
PUT /dashboards/y.id/shareSettings
    {"id":"y.id","permissions":[{"type":"ALL","permission":"VIEW"}],"publicAccess":{"managementZoneIds":[]},"preset":true,"enabled":true}
: tf_provider_addr=provider tf_rpc=ApplyResourceChange tf_req_id=71a260ac-d0f3-ba99-29e2-4048cfcc0579 tf_resource_type=dynatrace_dashboard_sharing
```

both these dashboards had correct status preset = true. However, there were other dashboards for which we did not find any information on preset status change but its value got reversed. Even though in the logs we could see output having preset = true, on dynatrace the dashboard status switched. 

Here is one example >

DEBUG: Request s3/PutObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /dynatrace.tfstate HTTP/1.1

```
"mode": "managed",
      "type": "dynatrace_dashboard_sharing",
      "name": "command_codered",
      "provider": "provider[\"registry.terraform.io/dynatrace-oss/dynatrace\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "dashboard_id": "id",
            "enabled": true,
            "id": "id",
            "permissions": [
              {
                "permission": [
                  {
                    "id": "",
                    "level": "VIEW",
                    "type": "ALL"
                  }
                ]
              }
            ],
            "preset": true,
            "public": []
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "dynatrace_dashboard.command_codered"
```

In order to investigate further, I manually changed preset status on dynatrace for all required dashboards to true and then we ran pipelines again. 4 dashboards preset status changed from true to false. To conclude, Warnings have reduced but the issue with preset value getting changed is still happening. Let me know if there is any other info/detail you need to look into this further.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @saadrafique768 

Thanks for these helpful diagnostic steps - they finally have led us into the right direction.
Share Settings for Dashboards did not always have their own Endpoint within the Dynatrace REST API. They were included within the Dashboard itself.
Back in these days, these Share Settings also contained a `preset` flag - but it was read-only. That flag is *not* read-only any more - I tested that out a few minutes ago.

A remainder of these properties is still contained within the structures that are used by the resource `dynatrace_dashboard` - the ability to configure the `preset` flag is however not anymore part of the schema for dashboards.

In other words: The resource `dynatrace_dashboard_sharing` is perfectly ok. But once the `dynatrace_dashboard` is also configured when `terraform apply` is getting invoked, the `preset` value is getting overwritten - and the decision whether the flag is getting switched depends likely on a race condition.

The short term solution here will be, that we will temporarily introduce the ability for configuring the `preset` flag also for the resource `dynatrace_dashboard`. I'm not particularly happy about offering the same property in two places, but based on my test runs by directly accessing the REST API, Dynatrace will interpret just omitting the information as `preset=false`. So, until these things have been sorted out properly, that workaround will have to suffice.

I'm not sure if we can push out a new release still this week. Might have to ask for patience until Monday.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @saadrafique768 ,

Please let me know if [Release 1.14.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.14.1) indeed takes care of your issues.
You should now also be able to specify the `preset` attribute within the `dashboard_metadata` section of the resource `dashboard`.

**Comment by saadrafique768** [comment]
Hello @Dynatrace-Reinhard-Pilz we ran pipelines now with preset = true added in dashboard meta data. The results are great as all required dashboards keep their preset status in all environments.

Thank you for your help ! I will suggest to keep this bug open until end of week and then we can close it out.
