### ISSUE TITLE
Add Support for local API Configuration for dynatrace_k8s_credentials resource

### ISSUE THREAD

**Issue by ekleiner14** [dynatrace-oss/terraform-provider-dynatrace#151]
Hey @Dynatrace-Reinhard-Pilz 

This gap is really with the API itself (confirmed the same with support), but I was hoping if it could be added here that there could be more visibility to this gap to hopefully lead to a faster resolution time. If you could make R&D aware on your end like you did for my other issue I would greatly appreciate it! We also have [this RFE](https://community.dynatrace.com/t5/Dynatrace-product-ideas/API-update-to-Kubernetes-Credential-Config-API-s-to-support/idi-p/196548#M33305) with the following information to try and help too but again anything that you can do on your end would be greatly appreciated. Thanks!

"It appears that the current API's for Kubernetes Credential Config only enforce url endpoints, and do not support the local API configuration that is allowed in console.  This is a request to update the API (and the Terraform provider) to support this configuration, so we can manage our resources as code."

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ekleiner14 

First of all I've upvoted your RFE - if PM stumbles across it it always helps if the RFE doesn't appear a request of one single customer.
I've also reached out to PM about that topic. That's needless to say no guarantee that it's going to get implemented immediately, but it raises awareness of that gap.

Thanks for the feedback, greatly appreciated!

**Comment by ekleiner14** [comment]
Awesome, that's all I can ask for. Thanks @Dynatrace-Reinhard-Pilz !

**Comment by kishikawa12** [comment]
Hi @ekleiner14, I've also upvoted your RFE. I'll close this ticket for the time being since this enhancement is product related and not an issue with the provider. 

Thanks!
Kodai
