### ISSUE TITLE
Network Zone not imported

### ISSUE THREAD

**Issue by MaudVandevelde** [dynatrace-oss/terraform-provider-dynatrace#154]
**Describe the bug**
I use terraform-provider-dynatrace export dynatrace_network_zones which is supposed to downloads all existing network zone configuration

**To Reproduce**
1. launch terraform-provider-dynatrace export dynatrace_network_zones
2. Check downloaded network zone
3. I just have: resource "dynatrace_network_zones" "NetworkZones" {
  enabled = true 
}

**Expected behavior**
List of all the existing network zone.

**Desktop (please complete the following information):**
 - OS: windows

**Additional context**

**Comment by kishikawa12** [comment]
Hi @MaudVandevelde, thank you for your feedback. The Settings 2.0 endpoint for Network Zones that we currently use in Terraform only provides the setting to enable/disable this feature. The ability to configure further is available in the old environment API v2 so we'll look into adding that as a resource in a future release - targeting for sometime in December. Thank you for your patience.

**Comment by kishikawa12** [comment]
Hi @MaudVandevelde, 

Thank you for your patience. [Release 1.16.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.16.0) includes the ability to configure network zones via 'dynatrace_network_zone`. This resource is based off of environment API v2 and will have additional functionality beyond the previous `dynatrace_network_zones` which only included the ability to enable/disable.

Thanks!
Kodai
