### ISSUE TITLE
dynatrace_management_zone rules are still unordered

### ISSUE THREAD

**Issue by rpionke** [dynatrace-oss/terraform-provider-dynatrace#155]
**Describe the bug**
We are deploying several management zones with terraform.
The changelog of version [v1.12.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.12.1) enforces the order of rules in a management zone.
We now see a lot of changes regarding management_zones due to the order of rules.

**To Reproduce**
1. Create a management zone with two rules with terraform apply.
2. Execute terraform apply again

**Expected behavior**
If a management zone has no changes, the provider should update them in-place.

**Screenshots**
![image](https://user-images.githubusercontent.com/11491375/199720910-3304797d-6b4c-4379-8c10-9495cf9b08c3.png)

**Versions used:**
 - Terraform v1.3.3
 - provider registry.terraform.io/dynatrace-oss/dynatrace v1.14.1

**Comment by kishikawa12** [comment]
Hi @rpionke , 

Thank you for your patience. [Release 1.16.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.16.0) includes a new resource `dynatrace_management_zone_v2` which covers configuration of Management Zones based on the Settings 2.0 REST API. The rules/conditions within this new resource are no longer an ordered list. This is a similar change to what was done previously for rules in Auto Tags. 

Copying the comment from the previous post on behavior (Issue #132):

> That change DOES come with a price. Any changes within one of the rules will create a plan that LOOKS like all the existing rules will be removed and then replaced with other ones that have the same content. That's because of a rather poor handling for unordered sub-resources within Terraform. That behavior wont affect how the REST API is getting addressed.

Thanks!
Kodai
