### ISSUE TITLE
[Feature Request] - Ability to configure Settings Objects 

### ISSUE THREAD

**Issue by robertchgo** [dynatrace-oss/terraform-provider-dynatrace#157]
**Is your feature request related to a problem? Please describe.**
We are trying to configure availability monitoring for process groups which is available via the API already.

**Describe the solution you'd like**
Resource Per Schema ID would be ideal to configure.

**Describe alternatives you've considered**
Resource Per Object would also work.

**Additional context**
Preview of we're testing via the API
![image](https://user-images.githubusercontent.com/14215751/200893791-b7ce60b0-a86d-4ed3-b65b-1a74befc5a88.png)

**Comment by kishikawa12** [comment]
Hi @robertchgo,

Just to provide an update - we are fully aware of the missing resources for Settings 2.0. We've added a handful of requested resources under Settings 2.0 over the last few months, but there is still a large amount to cover. 

We're planning on putting a large focus on closing this gap over the upcoming releases based off of new and improved code. We'll make sure to prioritize availability monitoring for process groups as one of our first ones to tackle.

Thanks for the feedback and we appreciate your patience!

Regards,
Kodai

**Comment by kishikawa12** [comment]
Hi @robertchgo,

The option to configure availability monitoring for process groups will be introduced in our release next week. We'll continue to introduce new Settings 2.0 configuration in our future releases. Thanks for the feedback!

Regards,
Kodai
