### ISSUE TITLE
Custom_anomalies "Allow merge" Setting

### ISSUE THREAD

**Issue by EitanKhiyaev** [dynatrace-oss/terraform-provider-dynatrace#159]
Currently, On the terraform resource Custom_anomalies there is no way to "allow merge" Which essentially attaches an anomaly to an existing problem.  This exist under Settings -> anomaly detection -> metric events

**Comment by kishikawa12** [comment]
Hi @EitanKhiyaev, thank you for your feedback. That particular setting is not available with the current API endpoint that we use for the custom anomalies resource but is available in the new Settings 2.0 API. We'll be looking into introducing this as a new and improved resource in a future release - targeting sometime in December. Thank you for your patience.

**Comment by kishikawa12** [comment]
Hi @EitanKhiyaev , 

Thank you for your patience. [Release 1.16.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.16.0) includes a new resource `dynatrace_metric_events` which is a new custom anomalies resource based off of the Settings 2.0 API. This new resource will allow merge via the field `davis_merge` - [link](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/metric_events#nested-schema-for-event_template) to docs.

Thanks!
Kodai
