### ISSUE TITLE
Ability to manage custom-tags thanks to terraform

### ISSUE THREAD

**Issue by MaudVandevelde** [dynatrace-oss/terraform-provider-dynatrace#160]
I'd like to be able to configure custom tags thanks to terraform.
Like it is possible with API : https://www.dynatrace.com/support/help/dynatrace-api/environment-api/custom-tags/post-tags

**Comment by kishikawa12** [comment]
Hi @MaudVandevelde,

Thanks for the feedback, we'll look to introduce this feature by the end of January.

Thanks!
Kodai

**Comment by kishikawa12** [comment]
Hi @MaudVandevelde - Release [v1.18.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.18.0) introduces `dynatrace_custom_tags` regarding this enhancement. Thanks!
