### ISSUE TITLE
Provider's Terraform Registry entry doesn't exist

### ISSUE THREAD

**Issue by iuliancristea** [dynatrace-oss/terraform-provider-dynatrace#162]
**Describe the bug**
The Terraform Registry shows a 404 when trying to access the documentation of the provider.

**To Reproduce**
1. Go to https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs
2. See error

**Expected behavior**
See the provider documentation

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @iuliancristea 

I can reach that page without problems.
Any chance it was a temporary problem on the terraform.io server?
Or are you still experiencing the 404 error?

**Comment by iuliancristea** [comment]
> Hello @iuliancristea
> 
> I can reach that page without problems. Any chance it was a temporary problem on the terraform.io server? Or are you still experiencing the 404 error?

@Dynatrace-Reinhard-Pilz It's not temporary. It's the same across all networks I've tried with (home, office, VPN) and I'm pretty sure nothing is cached for me in particular. I believe it may be worth reaching out to HashiCorp.

**Comment by iuliancristea** [comment]
@rpionke @Dynatrace-Reinhard-Pilz I have found the issue. For some reason, I only get the 404 when using Brave. Works fine on Safari (haven't tried other browsers)
