### ISSUE TITLE
Issue with the new dynatrace_maintenance resource

### ISSUE THREAD

**Issue by ekleiner14** [dynatrace-oss/terraform-provider-dynatrace#163]
The optional disable_synthetic parameter within general_properties throws an error. 

You can reproduce the issue being on the latest provider version (1.14.1) and regardless of the value for disable_synthetic, or even if it's commented out since it's not required, the following is observed.

`"error":{"constraintViolations":[{"parameterLocation":"PAYLOAD_BODY","message":"Given property 'disableSyntheticMonitorExecution' with value: 'null' does not comply with required NonNull of schema","path":"builtin:alerting.maintenance-window/0/generalProperties/disableSyntheticMonitorExecution"}],"message":"Validation failed for 1 Validators.","code":400},"code":400}`

The payload also doesn't include disable_synthetic but it does have all the others in general_properties. Maybe an issue with the "mapping" between this "disableSyntheticMonitorExecution" in the error message to the actual disable_synthetic where all the others are fine?

Please let me know if I can provide any additional information. Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ekleiner14 

Yes, this is a known bug - we already have fixed it on the main branch. You won't have any issues once the upcoming release has been pushed out.

**Comment by ekleiner14** [comment]
Thanks @Dynatrace-Reinhard-Pilz - I'll continue to check in for a new release and test again once it's available. Thanks!

**Comment by ekleiner14** [comment]
Thanks @Dynatrace-Reinhard-Pilz - I'll continue to check in for a new release and test again once it's available. Thanks!

**Comment by ekleiner14** [comment]
Hey @Dynatrace-Reinhard-Pilz - do you have an ETA for the new release?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Perfect timing: We just pushed out 1.15.0

**Comment by ekleiner14** [comment]
Thanks @Dynatrace-Reinhard-Pilz - I got past this issue so I'll close this. Thanks!
