### ISSUE TITLE
No longer found on terraform registry

### ISSUE THREAD

**Issue by mbruno-kr** [dynatrace-oss/terraform-provider-dynatrace#166]
**Describe the bug**
This is no longer found on the terraform registry

**To Reproduce**
1. Go to https://registry.terraform.io/search/providers?q=dyna
2. You can see it in the list 
3. Clicking on it you get a 404

**Expected behavior**
See provider on terraform registry

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 98christianp** [comment]
Seems to work for me on firefox on Windows 11.

**Comment by nicholas-marchini** [comment]
Works for me on Mac in Chrome

**Comment by kishikawa12** [comment]
Hi @mbruno-kr,

I hope you were able to regain access to the provider in the Terraform Registry. Please try a different browser/network if you continue to encounter issues. Closing the ticket for the time being.

Thanks!
Kodai
