### ISSUE TITLE
Data lookup for management zones not working

### ISSUE THREAD

**Issue by paulmorar** [dynatrace-oss/terraform-provider-dynatrace#167]
**Describe the bug**
Data lookup for management zones is not working due to an unsupported protocol scheme error.

**To Reproduce**
1. Create a management zone either in the UI or via terraform - you can pick your poison
2. In your main.tf try to do a simple data lookup as in the example from the [documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/management_zone#schema)
3. Run `terraform plan` command to verify the result
4. See error:
![image](https://user-images.githubusercontent.com/12514384/207889510-f84779d3-b551-46ee-9812-c79aacb6f8ac.png)

**Expected behavior**
Data lookup should return to correct values of that specific management zone.

**Screenshots**
The code I was trying to run:
![image](https://user-images.githubusercontent.com/12514384/207889970-e69c6a9d-8918-4f39-9553-4941e395f7e2.png)

**Additional context**
This happens on any machine - it seems like you are having some issues with the API. I have been trying both v1.14.1 and 1.15.0 of the provider, resulting in the same issue.

**Comment by kishikawa12** [comment]
Hi @paulmorar,

Thank you for reaching out. Are you able to confirm that you have the [provider block](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs#configure-the-dynatrace-provider) configured in your module? I'm able to replicate the exact error if I remove the provider configuration. The error message is unfortunately not very helpful here, we'll look into adding additional validation in an upcoming release.

I hope that helps!

Regards,
Kodai

**Comment by paulmorar** [comment]
I have found the issue. I was using an alias for the provider and that is what caused this to happen.
