### ISSUE TITLE
[Feature] Process Group availability monitoring

### ISSUE THREAD

**Issue by 98christianp** [dynatrace-oss/terraform-provider-dynatrace#169]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to configure process group availability monitoring via the terraform provider.  There is an endpoint available for `/anomalyDetection/processGroups/{id}` via the configuration api, however this is tagged as "Early Adopter" so I don't know how this will  affect the request. 
![image](https://user-images.githubusercontent.com/27136738/208450585-eacb0b1e-e03c-43d3-b407-7adf4af5d0b0.png)

**Describe the solution you'd like**
Ideally a resource that allows for configuring the schema `builtin:availability.process-group-alerting`  via a resource named `dynatrace_pg_monitoring` or similar where you can set `AVAILABILITY_MONITORING_METHOD` as "ON" "OFF" or "MINIMUM_THRESHOLD"  and then minimum threshold requires a number value, "THRESHOLD". 

**Describe alternatives you've considered**
Having a seperate list of process-group ids and the desired state, and building a custom script to keep the configuration up to date. Else if we look away and say IaC isn't important we could configure these manaully in the UI (not very scalable friendly)

**Comment by kishikawa12** [comment]
Hi @98christianp,

This will be included in the release this week, thanks for the feedback!

Regards,
Kodai

**Comment by kishikawa12** [comment]
[Release v1.17.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.17.0) is now available which includes the `dynatrace_pg_anomalies` resource regarding this enhancement. Thanks!
