### ISSUE TITLE
Link to the terraform-provider-dynatrace executable

### ISSUE THREAD

**Issue by cpanet** [dynatrace-oss/terraform-provider-dynatrace#170]
I see a lot of people talking about import errors when they run a command invoking the terraform-provider-dynatrace executable. This executable would be very useful to me but I am unable to get my hands on it.

I'm probably missing something, but I contacted support via chat, and they were unable to answer either.

Where is this executable? Can you add to the documentation to explain where to find it/how to compile it?

Thanks in advance,

Sincerely,

**Comment by kishikawa12** [comment]
Hi @cpanet,

Thanks for reaching out, I believe you're talking about the export utility? I've included a couple links below, I hope that helps!

[Exporting existing configuration from a Dynatrace Environment (Overview)](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs#exporting-existing-configuration-from-a-dynatrace-environment)

[Export Utility](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/guides/export-v2#export-utility)

Regards,
Kodai

**Comment by Dynatrace-Reinhard-Pilz** [comment]
There are two ways how to get to the executable.

First you can simply download the pre-built binaries here from GitHub - the [Releases](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases) contain all of them in zip form.

The other option is to rely on the terraform CLI to download it for you. If you execute `terraform init` within a folder that includes our Terraform Provider, a subfolder named `.terraform` will automatically created. Within this folder you can find the executable.

**Comment by cpanet** [comment]
Ok, well I was on the right track, but unfortunately it didn't work when I tried yesterday:
![image-1671466035480](https://user-images.githubusercontent.com/121049299/208619489-ce355874-4aab-49a7-8c3e-286b9d74bf02.png)

Thanks for the link, I was able to download the correct binary and it works fine.

Thank you for the link, I was able to download the correct binary and it works very well,

**Comment by 98christianp** [comment]
@cpanet seems likeyou're on version v1.13.2, run it only with `export` omitting the "-" 

See the corresponding docs https://registry.terraform.io/providers/dynatrace-oss/dynatrace/1.13.2/docs#exporting-existing-configuration-from-a-dynatrace-environment
