### ISSUE TITLE
Expand HTTP Monitor Request Configuration

### ISSUE THREAD

**Issue by msmost** [dynatrace-oss/terraform-provider-dynatrace#171]
**Is your feature request related to a problem? Please describe.**
The http_monitor [request configuration](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/http_monitor#configuration) only allows for the following parameters:
* accept_any_certificate
* follow_redirects
* headers
* user_agent

**Describe the solution you'd like**
We would like to be able to configure other http_monitor request configuration settings such as the following (listed in our order of priority):

1. Adapt request timeout
2. Enable pre-execution script
3. Enable post-execution script
4. Add client certificate
5. SSL certificate expiration date verification
6. Do not store and display request and response bodies and header values in execution details

*Alternative solution*
Add the `unknowns` parameter to this resource so that the configuration can be handled as JSON

**Describe alternatives you've considered**
The only alternative is to manually make the change in the GUI after the resource has been created. This is not ideal.

**Comment by FinUD** [comment]
The extra configurations would be ideal as we are looking at creating monitors that contain sensitive data with terraform but this is becoming a blocker.

**Comment by kishikawa12** [comment]
Hi @msmost, @FinUD - this enhancement will be in the next release.

**Comment by msmost** [comment]
@kishikawa12 - I will follow up if we notice any issues; thank you so much for quickly adding this!!
