### ISSUE TITLE
Error while executing  terraform-provider-dynatrace_1.16.0_windows_amd64

### ISSUE THREAD

**Issue by MaudVandevelde** [dynatrace-oss/terraform-provider-dynatrace#173]
**Describe the bug**
An error occured: 

panic: unsupported type []*string

goroutine 1 [running]:
github.com/dtcookie/hcl.Properties.Encode(0xc00056b028?, {0x19840a1, 0x11}, {0x180c4a0, 0xc00051ab88?})
        github.com/dtcookie/hcl@v1.0.2/properties.go:409 +0x1ff9
github.com/dtcookie/hcl.Properties.EncodeAll(0x18681c0?, 0xc00056b0d8?)
        github.com/dtcookie/hcl@v1.0.2/properties.go:213 +0xac
github.com/dtcookie/dynatrace/api/config/networkzones.(*NetworkZone).MarshalHCL(0xc0005d20f0)
        github.com/dtcookie/dynatrace/api/config/networkzones@v1.0.1/network_zone.go:60 +0x2ca
github.com/dynatrace-oss/terraform-provider-dynatrace/hclgen.(*HCLGen).Export(0x1b6?, {0x1d2d6260880, 0xc0005d20f0}, {0x1b14920, 0xc0000cadc0}, {0x198a17d, 0x16}, {0xc000394520, 0x1a}, {0x0, ...})
        github.com/dynatrace-oss/terraform-provider-dynatrace/hclgen/hclgen.go:270 +0x66
github.com/dynatrace-oss/terraform-provider-dynatrace/hclgen.Export({0x1d2d6260880, 0xc0005d20f0}, {0x1b14920, 0xc0000cadc0}, {0x198a17d, 0x16}, {0xc000394520, 0x1a}, {0x0, 0x0, ...})
        github.com/dynatrace-oss/terraform-provider-dynatrace/hclgen/hclgen.go:264 +0xd8
github.com/dynatrace-oss/terraform-provider-dynatrace/download.ResourceData.WriteResource(0x0?, {{0xc000030450, 0x23}, {0xc0000380e0, 0x60}, {0x197ff28, 0xd}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
        github.com/dynatrace-oss/terraform-provider-dynatrace/download/resource_write.go:57 +0x305
github.com/dynatrace-oss/terraform-provider-dynatrace/download.ProcessWrite({{0xc000030450, 0x23}, {0xc0000380e0, 0x60}, {0x197ff28, 0xd}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/dynatrace-oss/terraform-provider-dynatrace/download/write.go:41 +0x425
github.com/dynatrace-oss/terraform-provider-dynatrace/download.Download({0xc000030450, 0x23}, {0xc0000380e0, 0x60}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
        github.com/dynatrace-oss/terraform-provider-dynatrace/download/download.go:147 +0x750
main.exportv2({0xc0000963a0?, 0x2?, 0xc000068000?})
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:254 +0x657
main.main()
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:788 +0x76
Error: 

**To Reproduce**
1. Launch: .\terraform-provider-dynatrace_v1.16.0.exe -export

**Expected behavior**
Getting terraform files 

**Screenshots**

**Desktop (please complete the following information):**
 - Using: terraform-provider-dynatrace_1.16.0_windows_amd64

**Comment by kishikawa12** [comment]
Hi @MaudVandevelde,

Thank you for the ticket, I apologize for the inconvenience. The fix for this will be in the release this week. In the meantime a temporary workaround would be to use `.\terraform-provider-dynatrace_v1.16.0.exe -export -exclude dynatrace_network_zone`. 

Thanks!
Kodai

**Comment by kishikawa12** [comment]
[Release v1.17.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.17.0) is now available which contains the fix for this issue. Thank you for the feedback!
