### ISSUE TITLE
`dynatrace_azure_credentials` Pause managing state of certain resources 

### ISSUE THREAD

**Issue by jeevanions** [dynatrace-oss/terraform-provider-dynatrace#176]
**Is your feature request related to a problem? Please describe.**

Ref: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/azure_credentials

We provide landing zone resources to various internal teams (think of it as a product). As part of this, we only deploy changes/requirements that are common to various other internal teams. For example, provisioning Azure subscriptions, Creating basic infrastructure, etc. As part of this setup, we would like to leverage Azure Integration with Dynatrace. We are using Terraform for provisioning these landing zone resources.  We have used the Terraform provider for Dynatrace to automatically integrate Azure subscription with Dynatrace (refer to resource `dynatrace_azure_credentials`). The issue is that this resource has a repeating block to define the `supporting_services` and `monitored_metrics`. Since each team has their own requirement to monitor the supported services/metrics, our common Terraform script would overwrite all the changes done directly in the Web UI.  

**Describe the solution you'd like**
It would be good to make these `supporting_services` and `monitored_metrics` as non-overwriting blocks / ignore state/merge state, so we keep the changes manually done in the Web UI. By doing this, we will be able to establish the connection automatically with our setup and let the user decide which services and metrics to monitor. This will give us much more flexibility and control.

**Describe alternatives you've considered**
We did not find any alternative solution. But we explored the export function of the provider, which has a manual intervention.  We wanted it to be fully automated.

**Additional context**
![dynatrace_azure_credentials](https://user-images.githubusercontent.com/95138087/213773357-85e4b861-3987-42c4-95d0-6db5878127a6.png)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @jeevanions 
Would you be willing to share one of your `dynatrace_azure_credentials` with us for internal tests? The enhancement you're asking for is actually not that difficult to implement. We're unfortunately struggling a bit with are credentials for Azure, that allow us to create a configuration set like yours. You can, of course, remove the actual credentials. What would be useful are the `supporting_service` sections.
Based on that I can look into a solution like:

```
supporting_services{
    name = "cloud:azure:datafactory:v2"
    managed_in_dynatrace = true
}
```

**Comment by jeevanions** [comment]
@Dynatrace-Reinhard-Pilz  do you have a secure place where i can drop in the creds?

**Comment by jeevanions** [comment]
@Dynatrace-Reinhard-Pilz  I have emailed you the details.

**Comment by jeevanions** [comment]
@Dynatrace-Reinhard-Pilz  any updates. If you're done with your testing, I would like to revoke the permission.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @jeevanions 

Thank you for the sample. I DO have a local setting now I can work with.
The solution will unlikely make it into the release we're planning for Monday, but you can expect for the release after that option `supporting_services_managed_in_dynatrace` to be available.

Thanks alot for allowing me to use your credentials. Much appreciated!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Please disregard my message. Mondays release will contain you solution.

**Comment by kishikawa12** [comment]
Hi @jeevanions - Release [v1.18.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.18.0) contains this enhancement. Please feel free to reopen the ticket if you have any issues with the resource, thanks!
