### ISSUE TITLE
New Terraform resource to add rules to an existing management zone

### ISSUE THREAD

**Issue by jeevanions** [dynatrace-oss/terraform-provider-dynatrace#179]
**Is your feature request related to a problem? Please describe.**
We have separate automation that ties the management group with the AD group and stays outside our Terraform configuration. But we can add new rules to group the Dynatrace resource through the Web UI. 
We would like to automate these rule setting through Terraform and could not find a Terraform resource to achieve this. 

**Describe the solution you'd like**
New resource like `dynatrace_management_zone_rules`

**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @jeevanions, I'm closing this ticket until further notice, since you didn't respond. Just drop us a message here and we will re-open it.
