### ISSUE TITLE
New Attribute support for management zone through terraform-provider-dynatrace plugin

### ISSUE THREAD

**Issue by Karthikeyanraman94** [dynatrace-oss/terraform-provider-dynatrace#18]
@Dynatrace-Reinhard-Pilz : Thanks a lot for the great quick fixes, The important thing we dependent from this provider is the config downloader plugin

Since we are heavily dependent on terraform-provider-dynatrace  plugin to download the terraform-configurations, after the release of 1.0.7, when we apply the downloaded configurations, we receive the warning

22:30:53  Warning: Deprecated Attribute
22:30:53  
22:30:53    on modules.tf line 147, in resource "dynatrace_management_zone" "test-all":
22:30:53   147: resource "dynatrace_management_zone" "test-all" {
22:30:53  
22:30:53  `metadata` exists for backwards compatibility but shouldn't get specified
22:30:53  anymore
22:30:53  
22:30:53  (and 61 more similar warnings elsewhere)
22:30:53

**Comment by Dynatrace-Reinhard-Pilz** [comment]
`terraform download` doesn't produce the `metadata` attribute anymore with [v1.0.8](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.8).
