### ISSUE TITLE
Can't config dashboard sharing with resource "dynatrace_dashboard_sharing" in new release 1.18.1

### ISSUE THREAD

**Issue by MinsonTFW** [dynatrace-oss/terraform-provider-dynatrace#184]
**Describe the bug**
I tried with the new release 1.18.1
Now terraform has issue while config the dashboard sharing with resource "dynatrace_dashboard_sharing"
When running the terraform apply, it shows an error status code: 204 and expected 201.
However, when I navigate to the Dynatrace dashboard, the sharing does create by terraform but looks like terraform itself doesn't know this, therefore, there is no dashboard sharing resource be updated to the state file.

**To Reproduce**
1. Prepare the code for the resource "dynatrace_dashboard_sharing"
2. Run "terraform apply"
3. Enter the "yes" value to apply the changes

**Expected behavior**
Terraform apply should run without any error output.

**Screenshots**
![image](https://user-images.githubusercontent.com/40206092/215654332-87150841-8298-492f-9f0f-c7b1db6e78ee.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04.1 LTS

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for reporting that bug. We're planning to push out a release still this week that takes care of this issue.

**Comment by MinsonTFW** [comment]
> Thanks for reporting that bug. We're planning to push out a release still this week that takes care of this issue.
Thanks for the heads up🤞

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Release [1.19.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.19.0) takes care of this issue.
