### ISSUE TITLE
Issue while creating Shared Dashboards in New provider version - 1.18.1

### ISSUE THREAD

**Issue by kvaidy01** [dynatrace-oss/terraform-provider-dynatrace#187]
With the new release 1.18.1, we are seeing errors while creating the shared dashboards using terraform. The plan is successful, however the apply fails. 

Error details: 
```
Error: status code 204 (expected: [201])
with module.dynatrace_dashboard["platform_kv"].dynatrace_dashboard_sharing.this
on ../modules/configuration/dashboard/dashboard.tf line 51, in resource "dynatrace_dashboard_sharing" "this":
resource "dynatrace_dashboard_sharing" "this" {
```
We did a Dynatrace export and compared  dynatrace_dashboard_sharing between 1.18.1 and 1.17.0, please find the below details

Version 1.18.1
```
resource "dynatrace_dashboard_sharing" "ShareSettings_for_dash_1" {
  enabled      = true
  dashboard_id = "${var.dynatrace_json_dashboard.dash_1.id}"
  preset       = false
  permissions {
  }
}
```
Version 1.17.0
```
"#" DEFINE dynatrace_dashboard_sharing.dash_1.id = 2845-4b46-42cc-28341
resource "dynatrace_dashboard_sharing" "dash_1" {
  enabled      = true
  dashboard_id = dynatrace_dashboard.dash_1.id
 "#"  preset     = false
  permissions {
    permission {
      type  = "ALL"
      level = "VIEW"
    }
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @kvaidy01 

You're stumbled across two separate regression bugs here, apologies for that.
Your issues will be addressed with the upcoming release.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Release [1.19.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.19.0) takes care of this issue.
