### ISSUE TITLE
[Feature Request] Adding additional options to "dynatrace_service" data source 

### ISSUE THREAD

**Issue by 98christianp** [dynatrace-oss/terraform-provider-dynatrace#188]
**Is your feature request related to a problem? Please describe.**
Hello guys, I am starting to use the `dynatrace_service` data source and have found it slightly underwhelming, in the sense that the query options are quite limited. 

**Describe the solution you'd like**
To make it more useful I'd like the option to add the `Operator` field i.e when querying by name we can select from various options; `CONTAINS` `BEINGS_WITH`  `EQUALS` etc.

Another nice thing to have would be the option to filter by the the serviceType field that is available in the API schema.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @98christianp 
You're right, the current data source doesn't offer a lot of functionality. We've introduced it for a very specific use case (migrating settings from one environment to another), and here matching against tags was sufficient enough for a start.

But we ARE working on functionality that's a bit more flexible. The REST endpoint
`https://#####.live.dynatrace.com/rest-api-doc/index.jsp?urls.primaryName=Environment%20API%20v2#/Monitored%20entities/getEntities` allows for specifying a `metricSelector` and for choosing the fields you'd like to get. Eventually this would allow you to narrow down results already via `metricSelector` and later on filter using HCL functionality.

**Comment by 98christianp** [comment]
> Hello @98christianp You're right, the current data source doesn't offer a lot of functionality. We've introduced it for a very specific use case (migrating settings from one environment to another), and here matching against tags was sufficient enough for a start.
> 
> But we ARE working on functionality that's a bit more flexible. The REST endpoint `https://#####.live.dynatrace.com/rest-api-doc/index.jsp?urls.primaryName=Environment%20API%20v2#/Monitored%20entities/getEntities` allows for specifying a `entitySelector` and for choosing the fields you'd like to get. Eventually this would allow you to narrow down results already via `entitySelector` and later on filter using HCL functionality.

Sounds promsing! To align my understanding of what you are saying;  you will add the `entitySelector` param that is available in the API to the data sources? 🤔

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Exactly. We "kind" of have that already under the hoods, but not explicitly.
But we were internally already talking about offering the `entitySelector` as an input property and offering a fixed set of properties as results (depending on what kind of entity some of them would be populated, some of them would be empty).

**Comment by 98christianp** [comment]
Sweet, I'll close this for now as I got what I need in the release, thank you 😀
