### ISSUE TITLE
Exported custom service fails to be imported into state with "unable to determine technology"

### ISSUE THREAD

**Issue by gmichels** [dynatrace-oss/terraform-provider-dynatrace#191]
**Describe the bug**
Performed a fresh dump of my environment using the export functionality. Grabbed one of the `dynatrace_custom_service` resources from the export and performed a state import using the appropriate id, which ultimately fails with **Error: unable to determine technology**

```
➜  ops-dynatrace-settings git:(dev) ✗ terraform import -var-file=data/qa.tfvars dynatrace_custom_service.My_Custom_Service aa561e43-0313-401a-885f-ec265cd926ea
data.azurerm_key_vault.ops: Reading...
data.azurerm_key_vault.ops: Read complete after 0s [id=/subscriptions/<scrubbed>/resourceGroups/<scrubbed>/providers/Microsoft.KeyVault/vaults/<scrubbed>]
data.azurerm_key_vault_secret.dt_api_token: Reading...
data.azurerm_key_vault_secret.dt_api_token: Read complete after 1s [id=https://<scrubbed>.vault.azure.net/secrets/dt-api-token-qa/d1841e0d41904713a227e2ff140825a2]
dynatrace_custom_service.My_Custom_Service: Importing from ID "aa561e43-0313-401a-885f-ec265cd926ea"...
dynatrace_custom_service.My_Custom_Service: Import prepared!
  Prepared dynatrace_custom_service for import
dynatrace_custom_service.My_Custom_Service: Refreshing state... [id=aa561e43-0313-401a-885f-ec265cd926ea]
╷
│ Error: unable to determine technology
│ 
│ 
╵
```

**Expected behavior**
The exported resource should be imported successfully

**Additional context**
Terraform version 1.3.7
Provider version 1.18.1

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @gmichels 
Custom Services are a bit of a special case. You won't be able to import them using just the ID offered by the REST API or the WebUI.
When you execute `terraform-provider-dynatrace -export -id` the generated `.tf` files will contain a comment on top with the ID that will work.
```
# ID 84dec17f-40b5-4150-9117-37472e0b15fb#MULTI#PART#ID#go
resource "dynatrace_custom_service" "ABC" {
  name              = "ABC"
  enabled           = true
....
}
```
In other words, the ID terraform stores locally for a custom service currently requires the technology being encoded.

We're planning to split up `dynatrace_custom_service` into separate resources per technology in the future. From this point on that special handling won't be necessary anymore.

**Comment by gmichels** [comment]
Hi @Dynatrace-Reinhard-Pilz thanks for the update, seems like this changed recently as I used to have custom services exported and imported using only the uuid of the custom service as the id. I wasn't aware of the `id` flag on the export command, guess that's a new thing as well.

Thanks for the assistance, all works as expected now.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Yes, you're correct. We had a major refactoring before pushing out 1.18. That multi part ID was a temporary solution for making everything as generic as possible. Not really what we are aiming for on the long run, I must admit.

**Comment by czomo** [comment]
We also facing `Error: unable to determine technology` but we didn't use export method. Just used latest terraform provider. @Dynatrace-Reinhard-Pilz any ideas?
```terraform
resource "dynatrace_custom_service" "kafka__service" {
  name                   = "kafka_l_service"
  enabled                = true
  technology             = "java"
  queue_entry_point      = true
  queue_entry_point_type = "KAFKA"
  rule {
    enabled = true
    class {
      name  = "org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer"
      match = "EQUALS"
    }
    method {
      name      = "invokeOnMessage"
      arguments = ["org.apache.kafka.clients.consumer.ConsumerRecord"]
      returns   = "void"
      unknowns  = "{\"modifiers\":[],\"visibility\":\"STH\"}"
    }
  }
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@czomo are you trying to import the resource (`terraform import`) or are you trying to create (`terraform apply`) it?
If it's about importing you could simply execute
`terraform import dynatrace_custom_service.kafka__service <uuid-from-dynatrace>#MULTI#PART#ID#java`

**Comment by czomo** [comment]
This happens during `terraform plan`, no import used.  I can confirm that this works normally with older version of provider 1.17

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Ok, that last piece of information makes sense now. We didn't think of existing resources when switching to this "multipart" syntax for custom services.
If you have access to the state file, you could on short notice append that `#MULTI#PART#ID#java` suffix manually in there.

I will however find a way within the next two days that fixes things automatically.
Apologies for the troubles here.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @gmichels and @czomo,

Just a heads up here.

The next release will support both ways to address a custom service (new resources will be using the "multipart -id").

We are however eventually (in a future release) planning to split up that resource into `dynatrace_custom_java_service`, `dynatrace_custom_go_service`, ...

The resource `dynatrace_custom_service` from that point on will be flagged as deprecated, but will get maintained until further notice.
