### ISSUE TITLE
Minor v1.19.0 release documentation error

### ISSUE THREAD

**Issue by reespozzi** [dynatrace-oss/terraform-provider-dynatrace#192]
**Describe the bug**
In the release notes for [terraform-provider-dynatrace v1.19.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.19.0), it is stated that `dynatrace_dashboard` has `"introduced "auto_refresh_enabled" for dashboard tiles"`. 
This is incorrect, as the resource has introduced `"auto_refresh_disabled"` as per the codebase and [documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/dashboard#auto_refresh_disabled).

**To Reproduce**
1. Go [release notes](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.19.0)
2. Scroll down to `Additional Improvements
3. Compare this dynatrac_dashboard feature change with the [documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/dashboard#nestedblock--tile--filter)

**Expected behavior**
This should be updated in the release notes to reflect the actual behaviour of this nested schema for `dynatrace_dashboard`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Comment by kishikawa12** [comment]
Hi @reespozzi,

Thanks for the heads up, fixed! 😄 

Regards,
Kodai
