### ISSUE TITLE
[BUG] - Rate limiting in the Dynatrace Tenant fails plan for a resource instead of backing off

### ISSUE THREAD

**Issue by Forcebyte** [dynatrace-oss/terraform-provider-dynatrace#193]
**Describe the bug**
When applying over 50 objects to Dynatrace, a `429` backoff occurs, aksing the client to wait a specified period of time before trying again

Dynatrace client doesn't appear to honor the backoff and instead propagates the error into the plan

(this is specific to the type of tenant and the rate limit already applied on the API token configured to use Dynatrace)

**To Reproduce**
1. Create more than 'x' amount of resources within Dynatrace TFE
2. run a plan/apply build

**Expected behavior**
Dynatrace uses something similar to the hashicorp [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) library in its requests and backs off when 429's or other responses occur

**Screenshots**
Error propagated from Dynatrace OSS library:
```
 Error: { "code": 429, "message": "Too many requests.", "constraintViolations": null } 
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Forcebyte ,

As a matter of fact, the current HTTP client built into the Terraform Provider DOES come with the ability to [react on HTTP Response Code 429](https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/dynatrace/rest/request.go#L296).

The issue we were having was, that none of the Dynatrace Environments every responded back with that error code, no matter how hard we hammered them. We even began to believe that this limitation might be an artifact of the past.

We eventually ended up implementing that feature against a server that mocks the behavior that's explained within the Dynatrace Documentation.

Is there a chance you could reproduce the behavior on your side with the environment variable `DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log` defined? That would produce valuable output for us.

I have also reached out to our dev team about reasons why that rate limitation doesn't kick in on every tenant - hoping to have a chance to eventually debug locally.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,

A quick update here. I have seriously tried to reproduce this issue, without any success. Even 500 resources applied in parallel didn't produce a return code `429` with the endpoints I am able to work with.

After reaching out to R&D I was told that a possible reason for your issues may be, that the HTTP Response Headers `X-RateLimit-Limit` and `X-RateLimit-Reset` are not necessarily always present even if the rate limit has been reached. These headers are supposed to hint to the client for how long it's likely required to wait until another successful attempt can get started.

So, although I'm not able to reproduce your exact problem locally, I made a few modifications to our REST client.
* In case of a `429` the REST client will now wait as a fallback for 30 seconds (unless said HTTP Response Headers contain a more specific hint)
* The number of attempts in case consecutive attempts still produce a `429` has been raised. Currently the REST Client chooses after 5 minutes of unsuccessful attempts to return that `429` back to the caller. This is imho most likely the cause for your issues in your specific environment.
* The number of parallel HTTP requests can get limited using the environment variable `DYNATRACE_MAX_HTTP_WORKERS`. It was currently hardcoded to `20`. It's more or less another throttle you may utilize in addition to `-parallelism=n` when executing `terraform apply`.

We're planning to push out that change by Monday. Should you still encounter similar issues after that, I'd be glad to connect with you via zoom, so we can investigate that directly in your environment.

**Comment by Forcebyte** [comment]
thank you Richard, apologies for the late reply here

That works on my side - I've been fairly busy here so I'll get back to you on detailed logs or types of resources this occurs with (completely my fault, we can leave this issue closed for now until I can get such data / reproduce the issue after the new release)

Thank you so much for your help; I'll take the last point as well as the debug point back and report if I see the issue again 🙏
