### ISSUE TITLE
[help wanted] Web application data privacy and error rules IDs misalignment between provider version 1.18.1 and older version

### ISSUE THREAD

**Issue by cyang1001** [dynatrace-oss/terraform-provider-dynatrace#194]
**Describe the bug**
I created web applications as well as their data privacy rules and error rules using provider version 1.14.1. While creating them, the IDs for data privacy and error rules have the prefixes of "data-privacy-" or "error-rules-". However, when I tried to upgrade the provider version to 1.18.1 and plan the changes (which will fetch the configurations of the states), the errors came in. The IDs now have suffixes rather than prefixes, so there are errors when using the old ID to GET the information. 

The problem might come from the state itself. Is there a way to cope without destroying the resource and recreating it?

**To Reproduce**
1. create a web application, its data privacy and error rules using provider version 1.14.1
2. upgrade the provider version to 1.18.1
3. `terraform init -upgrade` and `terraform plan`

**Expected behavior**
Maybe can refresh the states...and plan successfully

**Screenshots**
![tempsnip2](https://user-images.githubusercontent.com/122544857/217573099-06ebd8f1-f9dd-4306-8de8-9dcc5247affc.png)

![tempsnip](https://user-images.githubusercontent.com/122544857/217567184-159777be-c06e-44b4-b291-eb509575d609.png)

**Version**
Terraform version: 1.1.3
Dynatrace cluster version: 1.254

**Additional context**
 Any help over here will be great. Thanks.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @cyang1001 

Our code has undergone a major refactoring with 1.18.1 - and in this specific case we apparently didn't pay enough attention. Apologies for the troubles.

On short notice: Do you have access to the `terraform.tfstate` file? You could modify the IDs in there to match the new syntax.

I will however also find a way to support both, the old and the new IDs in parallel until our next release (planned for Monday).

**Comment by cyang1001** [comment]
> Hello @cyang1001
> 
> Our code has undergone a major refactoring with 1.18.1 - and in this specific case we apparently didn't pay enough attention. Apologies for the troubles.
> 
> On short notice: Do you have access to the `terraform.tfstate` file? You could modify the IDs in there to match the new syntax.
> 
> I will however also find a way to support both, the old and the new IDs in parallel until our next release (planned for Monday).

Hi @Dynatrace-Reinhard-Pilz , thank you for the information! I will try to edit the `tfstate` file.
