### ISSUE TITLE
Resource dynatrace_api_token not returning token on versions 1.18.1 and up

### ISSUE THREAD

**Issue by wojciechka** [dynatrace-oss/terraform-provider-dynatrace#195]
**Describe the bug**

Resource `dynatrace_api_token` does not return `token` for provider version 1.18.1 and 1.19.0.

The token is correctly returned for version 1.17.0.

Tested against Dynatrace version 1.259.275.20230203-181100.

**To Reproduce**

Use the snippet below and `terraform apply` it, providing a valid values for `dt_env_url`, `dt_api_token` and `token_name`.

`main.tf` file:

```hcl
terraform {
  required_providers {
    dynatrace = {
      source  = "dynatrace-oss/dynatrace"
      version = "1.18.1"
    }
  }
}

variable "dt_env_url" {
  type = string
}

variable "dt_api_token" {
  type = string
}

variable "token_name" {
  type = string
}

provider "dynatrace" {
  dt_env_url   = var.dt_env_url
  dt_api_token = var.dt_api_token
}

resource "dynatrace_api_token" "dynatrace_token" {
  name                  = var.token_name
  enabled               = true
  scopes                = ["events.ingest", "logs.ingest", "metrics.ingest", "openTelemetryTrace.ingest"]
}

output "id" {
  value = dynatrace_api_token.dynatrace_token.id
}

output "token" {
  value = nonsensitive(dynatrace_api_token.dynatrace_token.token)
}
```

**Expected behavior**
The expected output should include `token = "dt0c01...."`, but instead it returns `token = ""`.

Downgrading to `version = "1.17.0"` and running same code against that will return a valid token.

**Desktop (please complete the following information):**

`Terraform v1.3.7` on macOS 13.2, M1 CPU.

**Comment by kishikawa12** [comment]
Hi @wojciechka,

Thanks for the feedback, the code went through a major refactoring with 1.18.1 and it looks like the special handling required for this resource was missed. We apologize for the inconvenience, the fix for this issue will be in the release on Monday.

Regards,
Kodai
