### ISSUE TITLE
Empty synthetic locations when upgrading from 1.14.0 to 1.20.0

### ISSUE THREAD

**Issue by Darksadik** [dynatrace-oss/terraform-provider-dynatrace#197]
**Describe the bug**

To upgrade to newest version, we had to adapt our code. We want to simply get synthetic locations available in output. 
Before changes we could get theses locations:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/33859824/218716552-23127b87-656f-4e1a-a5a9-836ab84756e2.png">
After the upgrade :
![image](https://user-images.githubusercontent.com/33859824/218715640-a71f646d-da5d-4833-adc1-55dd9c71c9af.png)

**To Reproduce**
1. Make sure version 1.20.0 is set and synthetic monitoring enabled.
2. Create a new data:
```
data "dynatrace_synthetic_locations" "synthetic_location" {
}
```
3. Get output:
```
output "test" {
  value = data.dynatrace_synthetic_locations.synthetic_location
}
```
4. Run terraform apply

**Expected behavior**
The list of different locations should appear.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser : chrome
 - Version : 21H2

**Additional context**

**Comment by kishikawa12** [comment]
Hi @Darksadik,

Thanks for the feedback, the code went through a major refactoring with 1.18.1 and it looks there was a typo in the data source. We apologize for the inconvenience, the fix for this issue will be in the next release.

Regards,
Kodai
