### ISSUE TITLE
Unable to modify the custom application configuration due to "IconType"

### ISSUE THREAD

**Issue by cyang1001** [dynatrace-oss/terraform-provider-dynatrace#198]
**Describe the bug**
When creating a custom application using the provider, there is no place to define the application iconType (e.g. desktop, IoT). It also seems like the default application type will be IoT (i can find this iconType when using GET in API). Later when I apply changes for other configurations, the system wants to make changes to the custom application as well, as it wants to remove the application id. However, there will be a 400 error for the custom application to prevent me from making other changes:
_status code 400 (expected: [204]): {"code":400,"message":"Constraints violated!","constraintViolations":[{"path":"iconType","message":"Payload does not include all required properties!","parameterLocation":"PAYLOAD_BODY","location":null}]}_ 

**To Reproduce**
1. create a custom application:
```
resource "dynatrace_mobile_application" "test" {
  name                    = "test"
  application_type        = "CUSTOM_APPLICATION"
  beacon_endpoint_type    = "CLUSTER_ACTIVE_GATE"
  user_session_percentage = 100
  apdex {
    frustrated          = 12000
    frustrated_on_error = true
    tolerable           = 3000
  }
}
```
2. `terraform plan` and `terraform apply`
3. add other configurations or just re-apply the changes again

**Expected behavior**
1. ability to define the custom application iconType
2. when re-apply the changes, the changes/in-line update will be applied successfully.

**Screenshots**
Error message: 
![image](https://user-images.githubusercontent.com/122544857/218782590-c8c0e6a7-9ce0-4079-8728-a5d3ef281e5d.png)

API GET response body:
![tempsnip3](https://user-images.githubusercontent.com/122544857/218783628-c8ccd89c-2513-4ca2-8599-160a9f12d1e4.png)

**Versions**
- Provider version: 1.19.0
- Managed Cluster version: 2.256

**Comment by kishikawa12** [comment]
Hi @cyang1001,

Thank you for the feedback, the fixes for this issue will be in the next release. The field `icon_type` has been added and `application_id` will no longer trigger a change/update.

Thanks!
