### ISSUE TITLE
Terraform sporadically failing in CI after upgrade from 1.17.0 to 1.20.0

### ISSUE THREAD

**Issue by wojciechka** [dynatrace-oss/terraform-provider-dynatrace#199]
**Describe the bug**
After updating from version 1.17.0 to 1.20.0 our CI pipelines started failing from time to time with an error like:

```
Error: open /tmp/.terraform-provider-dynatrace/v1.config.json-dashboards/data.tar: no such file or directory
```

The pipeline is using `terragrunt` to orchestrate `terraform` workflows. The pipeline has 3 different directories workflows and is using `--terragrunt-parallelism 5` flag for `terragrunt`, which calls `terraform` 3 times in parallel, with an empty cache.

The error happens around once every 2-3 runs of the pipeline. I cannot reproduce it with version 1.17.0.

I suspect it's some sort of race condition with https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/dynatrace/settings/services/cache/tar_folder.go that is responsible for the error.

**To Reproduce**
1. Call `terraform` multiple times with empty cache directory - either via `terragrunt` with `--terragrunt-parallelism 5` or in any other way
2. One of the invocations should crash with the error about opening `data.tar`

**Expected behavior**
The `terraform` command should run properly.

terragrunt v0.39.1
terraform v1.3.4

CI pipeline running as GitHub action

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @wojciechka ,
We didn't factor in terraform being executed in parallel when implementing certain caching mechanisms. The upcoming release will make sure that multiple instances of the provider launched in parallel won't share their caching directories anymore.
