### ISSUE TITLE
Changes are planned unnecessarily due to whitespace diffs

### ISSUE THREAD

**Issue by mjooz** [dynatrace-oss/terraform-provider-dynatrace#202]
**Describe the bug**
Although I don't have any config changes, the 'terraform plan' shows changes due to whitespace diffs.
Code is deploying a simple dashboard using the `dynatrace_json_dashboard` resource.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'terraform apply'
2. Without changing the config run 'terraform plan'
3. Plan is showing changes:
```yaml
~ resource "dynatrace_json_dashboard" "dashboard" {
      ~ contents = jsonencode( # whitespace changes
            {
                dashboardMetadata = {
                    dashboardFilter     = {
                        timeframe = "-24h to now"
                    }
```

**Expected behaviour**
When I run 'terraform plan' I expect:

`Plan: 0 to add, 0 to change, 0 to destroy.`

**Desktop:**
 - OS: macOS 13.2.1
 - Terraform version: v1.3.9
 - Provider version: v1.21.0

**Additional context**
Similar behaviour for a different provider is already reported [here](https://github.com/hashicorp/terraform/issues/23928#issuecomment-577781506)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mjooz ,

Could you provide an example that replicates this issue?
Reason for the ask: The current implementation DOES take white spaces into consideration already (or at least should).
I'm also unable to create an example locally that complains about whitespace changes.

**Comment by mjooz** [comment]
Hello @Dynatrace-Reinhard-Pilz 

Thanks for the fast response.

Here is the code, `dashboards.tf` and `dashboard.json.tpl` files:

```yaml
locals {
  dashboard = templatefile("${path.module}/templates/dashboard.json.tpl", {
    dashboardName  = "TF Dashboard"
    dashboardOwner = "IaC"
  })
}

resource "dynatrace_json_dashboard" "dashboard" {
  contents = local.dashboard
}
```

```json
{
  "dashboardMetadata": {
    "name": "${dashboardName}",
    "shared": true,
    "owner": "${dashboardOwner}",
    "dashboardFilter": {
      "timeframe": "-24h to now"
    },
    "tags": [
      "IaC"
    ],
    "preset": false,
    "hasConsistentColors": false
  },
  "tiles": [
    {
      "name": "Top web applications",
      "tileType": "APPLICATIONS_MOST_ACTIVE",
      "configured": true,
      "bounds": {
        "top": 76,
        "left": 494,
        "width": 304,
        "height": 304
      },
      "tileFilter": {},
      "isAutoRefreshDisabled": false
    }
  ]
}
```
