### ISSUE TITLE
[Error] Performed terraform apply with massive slo services setting error

### ISSUE THREAD

**Issue by JayChanggithub** [dynatrace-oss/terraform-provider-dynatrace#206]
Hi Team. 

We found weird symptoms that when we apply tf with resources which `dynatrace_slo` around 200+ services slo setting. it would be occurred error like following statement. We need getting some support here. Thanks.

```
dynatrace-tf_1  | │ Error: Bad Request (GET) https://apm.cf.us21.hana.ondemand.com/e/e97de59d-391a-494c-a027-3dfde5508bf2/api/v2/slo?sloSelector=id("144c9412-83a7-397f-9494-00bd4ab55aeb")&pageSize=10000&sort=name&timeFrame=CURRENT&pageIdx=1&demo=false&evaluate=false
dynatrace-tf_1  | │ 
dynatrace-tf_1  | │   with module.dynatrace_slo.dynatrace_slo.SERVICE-D3CD2EFF847378C1,
dynatrace-tf_1  | │   on ../modules/dynatrace_slo/dynatrace_slo.tf line 2102, in resource "dynatrace_slo" "SERVICE-D3CD2EFF847378C1":
dynatrace-tf_1  | │ 2102: resource "dynatrace_slo" "SERVICE-D3CD2EFF847378C1" {
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JayChanggithub 

Does this problem occur if you're applying `-parallelism` to 1 when using applying the resources?
I'm currently assuming, that this issue occurs when there are too many resources getting applied at the same time.

**Comment by JayChanggithub** [comment]
Hi @Dynatrace-Reinhard-Pilz, 

Actually, as you guessed, We used API `/api/v1/entity/services` to get all of service entity also generate `tf` file to append one file with resource object of `dynatrace_slo`. After `terraform apply` it occurred error as above. Did you know how to get rid of these error or any workaround? Thanks you.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JayChanggithub 
Would you be available for a Zoom call early next week? First, I'd like to replicate what you're doing locally, hoping for similar results. Second, I want to make sure there's no misunderstanding. We may safe ourselves a few ping pong cycles if we jump on a call.
Feel free to reach out to me at reinhard.pilz@dynatrace.com with a few time slots that would work for you.

**Comment by JayChanggithub** [comment]
@Dynatrace-Reinhard-Pilz  
Sure, Could you accepted invitation.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JayChanggithub ,

Quick summary of our zoom call today:
* I am going to reproduce your issue by generating a terraform module with several 100 SLOs. I'm hoping to get the same response from my test cluster than you are from yours.
* You will attempt to call `terraform apply -auto-approve -parallelism=1` when applying your module. If that succeeds this looks like an issue where the provider is overloading the cluster node.

**Comment by JayChanggithub** [comment]
@Dynatrace-Reinhard-Pilz 

Thanks for your supporting. Also i'd like to update after my `attempt to call terraform apply -auto-approve -parallelism=1 ` its' looks good and expected. In additional. I also has been adopted [SLO API ](https://www.dynatrace.com/support/help/dynatrace-api/environment-api/service-level-objectives/post-slo) to implement success. We need to evaluate which approaches is better. Thanks again.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Closed until further notice
