### ISSUE TITLE
White Space changes in Entity Selectors of dynatrace_management_zone may lead to non empty plan

### ISSUE THREAD

**Issue by pgudalewicz** [dynatrace-oss/terraform-provider-dynatrace#207]
Hi,

I've exported ~6000 resources with terraform-provider-dynatrace -export utility (management zones, alerting profiles and dashboards). All resources were imported into state file using ids provided during export.

During each plan and apply terraform wants to update almost half of them, even if none of .tf files was changed. This happens every time, even after I perform apply including those "changes".

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @pgudalewicz 
Would you be available for a Zoom Session where we can take a closer look at this?

**Comment by pgudalewicz** [comment]
Sure, when would you like to call?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
If you have time right now, please reach out to me at reinhard.pilz@dynatrace.com so you don't have to publish your email address here in the public.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @pgudalewicz , the upcoming release will take care of this issue.
