### ISSUE TITLE
Getting error beyond v1.17.0 : Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by ashishamway** [dynatrace-oss/terraform-provider-dynatrace#210]
**Describe the bug**
I am using several resources of dynatrace like dynatrace_calculated_service_metric, dynatrace_alerting_profile, dynatrace_slo, dynatrace_custom_anomalies. But when I try to update tf-provder version beyond 1.17.0 (1.18.0, 1.19.0, 1.20.0, 1.21.0) etc
, I see error as given below. I don't know why it happen but the error indicate that it should check by the developer.

Error:
`
TestSLO 2023-03-07T16:33:21+05:30 retry.go:144: 'terraform [apply -input=false -auto-approve -lock=false]' failed with the error 'error while running command: exit status 1; ╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ module.dynatrace_test_slo.dynatrace_slo.availability_slo[0], provider
│ "module.dynatrace_test_slo.provider[\"http://registry.terraform.io/dynatrace-oss/dynatrace%5C%22%5D%22 
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵' but this error was expected and warrants a retry. Further details: Provider eventual consistency error.
`

**To Reproduce**
1. Simply execute your testcases for these modules and you will notice an error: dynatrace_calculated_service_metric, dynatrace_alerting_profile, dynatrace_slo, dynatrace_custom_anomalies
2. In case you need my implementation then let me know I will share my code with testcase.

**Expected behavior**
Expectation is resource should be created without any error. Tried many times but it fail with same error all the time.

**Additional context**
I am using terraform version: 1.3.3. I am running my testcases using terratest@v0.41.11.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ashishamway, this issue will be taken care of with the next release

**Comment by ashishamway** [comment]
Thanks for answering. 
I can say, I am not creating many SLO's, metrics, dashboards, but yes definitely there number is given below.
It would be my pleasure to run my testcase against that fix and confirm you. 

Testcase 1: Calculated service metrics = 7
Testcase 2: Service-level objective definitions = 12 
Testcase 3: Custom anomaly = 1
Testcase 4: alerting_profiles = 1
