### ISSUE TITLE
Facing Issue while using credentials in keystrokes Synthetic Browser Monitor V1.17.0

### ISSUE THREAD

**Issue by kanwar25** [dynatrace-oss/terraform-provider-dynatrace#211]
Tried creating synthetic browser monitor in V1.17.0 By providing crdentials in keystrokes event using provider version 1.17.0.
But facing below issue : 
│   "code": 400,
│   "message": "Script validation failed: {\"violations\":[{\"path\":\"/events/3/credential/field\",\"message\":\"Field \\\"username\\\" is not allowed for token credentials\"}]}",
│   "constraintViolations": null
│ }
 This is the block passed : 
credential {
                          + field    = "username"
                          + vault_id = "CREDENTIALS_VAULT-5FEA3688D9B1EB7D"
                        }

**Comment by kanwar25** [comment]
Thanks @Dynatrace-Reinhard-Pilz , the provided suggestion worked. But I figured out one more issue, in my terraform variables file, I am passing field="password", but while applying it is by default taking it as username always.
Below is my variables script: 
{
    description = "Enter Password"
    event_type  = "keystrokes"
    //form_text   = "qxtr2019"
    credentials= [ {
      credentials_field = "password"
      credentials_valut_id = "CREDENTIALS_VAULT-6DC6143831A47ECD"
    }
    ]
   

But while applying, it is returning below : 
 event {
                  + description = "Enter Password"

                  + keystrokes {
                      + masked              = false
                      + simulate_blur_event = true

                      + credential {
                          + field    = "username"
                          + vault_id = "CREDENTIALS_VAULT-6DC6143831A47ECD"
                        }

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @kanwar25 ,

I would have to see in detail how you refer to your variables within the resource to tell what's going wrong here.

When applying a resource `dynatrace_browser_monitor` containing this event
```
      event {
        description = "my_key_stroke_event"
        keystrokes {
          masked              = false
          simulate_blur_event = true
          text                = ""
          credential {
            field    = "password"
            vault_id = "CREDENTIALS_VAULT-XXXXXXXXXXXXXX"
          }
        }
      }
```
in other words without referring to variables, it is getting applied as expected.

Without knowing more about how your module looks like, I'm left to assumptions here. Perhaps you can share the whole resource section and the variables you're using?

**Comment by kanwar25** [comment]
Hi @Dynatrace-Reinhard-Pilz , Thank you for your help. It is working fine now, there was some issue in the code. 
You can close this ticket..
