### ISSUE TITLE
NEW data source dynatrace_iam_user

### ISSUE THREAD

**Issue by stevebowerman** [dynatrace-oss/terraform-provider-dynatrace#212]
**Describe the solution you'd like**
Hi, we are just looking at moving over to this provider over Monaco and some home grown tools, it's great, so thank you for building this provider. Particularly the recent change for `dynatrace_iam_users` and `dynatrace_iam_groups` - works a charm!

Hopefully this use case may be similar for others. 

When migrating users over (ie terraform import) we aren't able to bring across existing groups (for each user). Having a data source providers that returns a collection of existing users (and their group ID's) would allow us to merge existing groups with new groups and hence provide a smooth migration path. It would also be useful for comparing users that are non-Terraform managed with those that are - some orgs may choose to delete this users, hence automating a process to kill off anything that isn't managed as IaC.

To give some context behind this:

1. Our current automation is based on a YAML config file (which contains list of users)
2. When we cut over we do a bulk terraform import of each user (email), which won't contain any groups per user, eg `terraform import `'dynatrace_iam_user["a@b.com"]' 'a@b@com'`
3. Using this suggested approach means that we can read in existing groups (that aren't Terraformed) and merge those with Terraformed groups. Over time we'd gradually phase out non-Terraformed groups and have all config managed as IaC

Looking at the mechanics and how we did something similar with a self-rolled cli tool:

API: `https://api.dynatrace.com/iam/v1/accounts/{accountUuid}/users/{email}`

So it would be need the IAM creds from the provider like dynatrace_iam_user etc

Example use:

```
data "dynatrace_iam_user" "users" {
  for_each = local.users
  email = each.key
}

resource "dynatrace_iam_user" "new_user" {
 for_each = local.users
  email = each.key
  groups = distinct(concat(local.old_groups[each.key], data.dynatrace_iam_user[each.key].groups))
}
```
We'd probably need to flatten/shape the .groups output to a list of groups GUIDs in our case.

We are doing a similar thing with the `dynatrace_management_zones` data source which is great for listing all Terraform and non-Terraform managed management zones.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @stevebowerman ,
Because that request was quite easy to fulfill, I went on and implemented it right away.
The next release will contain the data source `dynatrace_iam_user`. Usage will be exactly as you described it - the required attribute `email` identifies the user, and the computed attribute `groups` will as a result contain a sorted list of the IDs of the groups that user is currently assigned to.

**Comment by stevebowerman** [comment]
Amazing, thank you!
