### ISSUE TITLE
[Feature request] K8s Anomaly Detection

### ISSUE THREAD

**Issue by FinUD** [dynatrace-oss/terraform-provider-dynatrace#214]
Using the provider to integrate with K8s clusters and AWS environments automatically is great as it removes alot of manual configuration but this could be greatly improved with new anomaly detection resources for them as well similar to those released in v1.19 for hosts, services etc. This would enable those settings to be defined during setup and deployment and not retroactively applied. It would also enable developers and those working with the infrastructure to define their own anomaly detection settings based on what they're interested in without diving into Dynatrace every time to do it.
Cheers

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Schemata:
* builtin:anomaly-detection.kubernetes.cluster
* builtin:anomaly-detection.kubernetes.namespace
* builtin:anomaly-detection.kubernetes.node
* builtin:anomaly-detection.kubernetes.workload

**Comment by kishikawa12** [comment]
Hi @FinUD, thank you for the feedback - we'll introduce these resources in the next release, targeting early next week. Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Release [v1.24.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.24.0) introduced the resources
* `dynatrace_k8s_cluster_anomalies`
* `dynatrace_k8s_namespace_anomalies`
* `dynatrace_k8s_node_anomalies`
* `dynatrace_k8s_workload_anomalies`
