### ISSUE TITLE
[Feature request] Service Key Request Anomaly Configuration

### ISSUE THREAD

**Issue by mjooz** [dynatrace-oss/terraform-provider-dynatrace#215]
Trying to configure anomaly detection per key request on the service level. This is possible using console but can not find the way to accomplish the same using Terraform resources. 
`scope` parameter of dynatrace_service_anomalies_v2 can not be used with key request.

Console setup is shown here: https://community.dynatrace.com/t5/Alerting/Alert-on-availability-of-key-request-in-web-service-in-Dynatrace/td-p/38880

**Comment by julianxhokaxhiu** [comment]
@Dynatrace-Reinhard-Pilz Can you please help us here? I'm facing the same problem, and unless this is doable already, let us know how because I wasn't able to grasp this from the documentation or code either. Thank you in advance!
