### ISSUE TITLE
dynatrace_metric_events metadata block ignored on apply

### ISSUE THREAD

**Issue by estif95** [dynatrace-oss/terraform-provider-dynatrace#218]
**Describe the bug**
metadata block from dynatrace_metric_events resource is ignored on apply, plan show changes.

**To Reproduce**
Declare a dynatrace_metric_events resource using "metadata" block
Terraform plan show changes
Terraform apply creates the resource without "metadatas"

**Expected behavior**
Declare a dynatrace_metric_events resource using "metadata" block
Terraform plan show changes
Terraform apply creates the resource with "metadata"

**Screenshots**
![image](https://user-images.githubusercontent.com/25502990/227212135-dd889c87-3250-4838-a3c7-d5e675f18f0c.png)

**Additional context**
The export functionallity works well and exports the metadata block correctly, however they are ignores on Terraform apply.

A log file named: terraform-provider-dynatrace.log appears on working directory with the following content:
[WARN] *[]*metricevents.MetadataItem metadata NOT covered

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @estif95 , thanks for bringing that to our attention. The next release will contain a fix for this issue.
