### ISSUE TITLE
[Feature Request] Calculated service metric support

### ISSUE THREAD

**Issue by Karthikeyanraman94** [dynatrace-oss/terraform-provider-dynatrace#22]
Our organisation also maintaining few Dashboard Depends on Calculated service metrics..
It would be great once all fixes are done, if you can add the Calculated service metric support, along with SLO, custom anamalog detection support, service naming rules(ASAP would be too much to ask for I know) .. This provider will be used by so many peoples

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for showing that amount of interest in this provider. All the resources you've mentioned are as a matter of fact planned to get supported - but as you said, it's going to happen step by step, not to mention that fixing the current shortcomings have priority.

**Comment by Karthikeyanraman94** [comment]
Thanks for the great support and awesome work.. Just would like to let you know (1) - Calculated service metric, (2) - Custom anomaly detection are the two things we need for now on priority..

**Comment by Karthikeyanraman94** [comment]
Is it possible for (1) - Calculated service metric, (2) - Custom anomaly detection within end of May ?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
You've likely realized that we're currently rewriting all of the resources in order to ensure proper behavior in all situations. That has unfortunately pushed back plans for adding new resource settings.
I don't want to promise it, but Calculated Service Metrics and Custom Anomaly Detection are within reach for the end of May, yes.

**Comment by Karthikeyanraman94** [comment]
Thanks a lot.. you guys are awesome

**Comment by Karthikeyanraman94** [comment]
Hi Team, just would like to check Calculated Service Metrics and Custom Anomaly Detection if possible within upcoming friday

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @Karthikeyanraman94,
Yes, we're planning to release these functionctionalities by Friday.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Karthikeyanraman94, 
I need to ask for patience for Anomaly Detection until early next week. The implementation is done, but I don't feel comfortable yet with pushing out the release before I've done a bit more testing.
You will be getting more than you've asked for, btw. These resources will be available:
* `dynatrace_service_anomalies`
* `dynatrace_application_anomalies`
* `dynatrace_host_anomalies`
* `dynatrace_database_anomalies`
* `dynatrace_custom_anomalies`
* `dynatrace_disk_anomalies`

**Comment by Karthikeyanraman94** [comment]
Just would like to know if Calculated Service Metrics is possible as well

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Yes, as a matter of fact it is already in being worked on. I was hoping to push it out already with this release, but it turned out to be a bit more work than expected.

**Comment by Karthikeyanraman94** [comment]
Hi @Dynatrace-Reinhard-Pilz : I know u guys are working on very busy schedule and hard.. Would be great this calculated service metric also released soon.. This is one of the last expected feature for us..

**Comment by Dynatrace-Reinhard-Pilz** [comment]
It's almost done. I just didn't feel confident enough to push it out with todays release. Fixing the bugs that got introduced with Anomaly Detection had priority. Hoping to fulfill your request still this week.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Karthikeyanraman94 

Release [v1.3.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.3.0) finally adds support for Calculated Service Metrics. It took a bit longer than expected.
