### ISSUE TITLE
dynatrace_aws_credentials resource creating massive diffs, incorrectly reporting changes

### ISSUE THREAD

**Issue by FinUD** [dynatrace-oss/terraform-provider-dynatrace#220]
**Describe the bug**
For the "dynatrace_aws_credentials" resource when adding new supporting services to an already existing account with already monitored services, the order returned by the API is drastically different. For example we have services ABCDE initially applied. When applied they were ordered ABCDE. Now if we add F and still present them in the initial order adding F at the end like ABCDEF, they get returned jumbled by the API, for example as CBAFDE. This causes a massive diff to be created making it difficult to ensure that ABCDEF services were correctly applied.

**To Reproduce**
1. Create an initial "dynatrace_aws_credentials" resource and apply it, including several monitored services and their metrics.
2. Add a new monitored service and new metrics to the configuration.
3. Apply the new configuration, observe the massive diff as it thinks more has changed than just the new monitored service.

**Expected behavior**
Only the new monitored services to be reported in the diff.

**Additional context**
Reordering of services by the API has actually happened in the past where it used to be alphabetical and now its unpredictable causing these huge diffs to be created even when there was no change. If this could be changed to be order-agnostic this would be massively helpful for configurations including hundreds of metrics spanning 50+ services.

Cheers

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @FinUD , this issue will be taken care of with the upcoming release.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @FinUD , this issue will be taken care of with the upcoming release.
