### ISSUE TITLE
Dashboard popularity attribute causes non empty plans

### ISSUE THREAD

**Issue by mjooz** [dynatrace-oss/terraform-provider-dynatrace#224]
**Describe the bug**
Although I don't have any config changes, the 'terraform plan' shows changes due to dynamic changes of `popularity` attribute value. `popularity` attribute is omitted from dashboard json but plan reports that vaule is going to be reverted to null. 

Sample code:

```json
{
  "dashboardMetadata": {
    "name": "${dashboardName}",
    "shared": true,
    "owner": "${dashboardOwner}",
    "dashboardFilter": {
      "timeframe": "-24h to now"
    },
    "preset": true,
    "hasConsistentColors": false
  },
"tiles": [
```

**To Reproduce**
Steps to reproduce the behaviour:

1.Run 'terraform apply'
2.Without changing the config run 'terraform plan'

3.Plan is showing changes:

```
~ resource "dynatrace_json_dashboard" "dashboard" {
      ~ contents = jsonencode(
          ~ {
              ~ dashboardMetadata = {
                    name                = "Test Dashboard"
                  - popularity          = 1 -> null
                   }
            }
        )
        id       = "85d27a48-0835-446a-8bc4-bfb24f9efac4"
    }
```

**Expected behavior**
Expected is that Terraform ignores `popularity` attribute as it is configured dynamically outside Terraform.
When I run 'terraform plan' I expect:

Plan: 0 to add, 0 to change, 0 to destroy.

**Desktop**:

* OS: macOS 13.2.1
* Terraform version: v1.3.9
* Provider version: v1.24.0

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mjooz, the upcoming release will ignore the property `popularity`.
Odd fact: That property `popularity` isn't part of any schema of the REST API or mentioned within the documentation. It's apparently getting sent along nevertheless.
