### ISSUE TITLE
key_user_actions configuration drift on terraform apply

### ISSUE THREAD

**Issue by ruslanakchurin** [dynatrace-oss/terraform-provider-dynatrace#229]
Hi,

In our organization we use Key User Actions (part of dynatrace_web_application resource) a lot. We also try to utilize IaC approach and keep configuration up to date and consistent across the environments and products.

The problem is, no matter if key_user_actions block has been changed or not, terraform will always show a change in configuration.

Here is an output of a regular `terraform apply` with unchanged key_user_actions resource
```
 # module.dynatrace-web-application-adm.dynatrace_web_application.dynatrace_web_application will be updated in-place
  ~ resource "dynatrace_web_application" "dynatrace_web_application" {
        id                                   = "APPLICATION-1D4F63F413835AB6"
        name                                 = "qa-qa5-am-adm"
        # (5 unchanged attributes hidden)


      ~ key_user_actions {
          ~ action {
              ~ name   = "load bonus packages page" -> "load messaging page"
                # (2 unchanged attributes hidden)
            }
          ~ action {
              ~ name   = "load discover page" -> "load conversation page"
                # (2 unchanged attributes hidden)
            }
          ~ action {
              ~ name   = "load messaging page" -> "load bonus packages page"
                # (2 unchanged attributes hidden)
            }
          ~ action {
              ~ name   = "load conversation page" -> "load discover page"
                # (2 unchanged attributes hidden)
            }
        }
```

Not seeing the actual drift makes our daily tasks more complicated and we would appreciate a fix or improvement with this. Thank you.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ruslanakchurin, with the upcoming release of the provider the key user actions will be treated as an unordered list. That will take care of the drift issue. Thanks for the hint!
