### ISSUE TITLE
[Feature request] Process Group Availability Monitoring

### ISSUE THREAD

**Issue by mjooz** [dynatrace-oss/terraform-provider-dynatrace#233]
Would be nice to have an option to configure availability monitoring per process group.

Described here: https://www.dynatrace.com/support/help/platform-modules/infrastructure-monitoring/process-groups/monitoring/process-group-availability-monitoring-and-alerting#enable-process-group-availability-monitoring

**Comment by julianxhokaxhiu** [comment]
@Dynatrace-Reinhard-Pilz Hello, sorry to ping you again. We're stuck in the middle of something we're building and we ended up finding out that we missed this feature. May I kindly ask if you can consider adding this to your next sprint? I think it's a valuable addition as without this it will be difficult to monitor a specific PG and it won't be possible to receive alerts in case something goes wrong until we manually click that checkbox ( and it's extremely painful when you have to do this on 100+ PG ).

Thank you in advance in any case 🙏🏻
