### ISSUE TITLE
missing k8s cpu and memory workload anomalies?

### ISSUE THREAD

**Issue by ekleiner14** [dynatrace-oss/terraform-provider-dynatrace#234]
I tried deploying what's documented [here](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/k8s_workload_anomalies) using the latest provider version (1.27.0) just to get something out there which gave me the error below. This error message makes me think the latest release supports these newer anomalies, but I'm not sure what they should be since the documentation doesn't mention them yet. Is that accurate or is it not quite supported yet? Looking at the [release notes](https://www.dynatrace.com/support/help/whats-new/release-notes) it seems that the cpu anomalies have been a thing for about a month and the memory just released so I thought maybe it wasn't supported but this error message makes me think otherwise. 

│ Error: Given property 'highMemoryUsage' with value: 'null' does not comply with required NonNull of schema
│ Given property 'highCpuThrottling' with value: 'null' does not comply with required NonNull of schema
│ Given property 'highCpuUsage' with value: 'null' does not comply with required NonNull of schema

Any additional information or things for me to try would be greatly appreciated. thank you!

**Comment by kishikawa12** [comment]
Hi @ekleiner14,

It looks like a breaking change was introduced in the schema for K8s workload anomalies and a few others in the last update. I've pushed the updated schema, targeting a release this week. We apologize for the inconvenience. 

We're currently in discussions with the Dynatrace API dev team to find a solution regarding this issue to prevent breaking changes from happening with schema updates, more to come on that soon!
