### ISSUE TITLE
504 response codes from Account management API

### ISSUE THREAD

**Issue by edfenergy-stevebowerman** [dynatrace-oss/terraform-provider-dynatrace#235]
**Describe the bug**
We have observed that our pipeline fails periodically with a 504 error on iam objects (users or groups).

```
╷
--
892 | │ Error: response code 504 (expected: 200)
893 | │
894 | │   with dynatrace_iam_group.management_zone_iam_group["service_customer common services apis_grp_architect"],
895 | │   on user-groups.tf line 1, in resource "dynatrace_iam_group" "management_zone_iam_group":
896 | │    1: resource "dynatrace_iam_group" "management_zone_iam_group" {
897 | │
898 | ╵
899 | make: *** [Makefile:22: plan] Error 1
```

**To Reproduce**
Inconsistent behaviour

**Additional context**
work around is to re-run the pipeline

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Steve,

Unsurprisingly I cannot easily reproduce the issue you experience here.

What I've implemented for the upcoming release is a change in our IAM Client. In case a `504 Gateway Timeout` is getting received, the client attempts a retry of the request after one second (up to 5 times in a row).

I'd be really grateful if you could monitor the behavior with release v1.29.0 further and provide feedback whether that fix indeed solves the issue for you.

best regards,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @edfenergy-stevebowerman, I'm closing this issue until further notice. In case the changes implemented haven't really solved your problem, please drop a note here and we will re-open it.
