### ISSUE TITLE
Documentation missing important details

### ISSUE THREAD

**Issue by narora138** [dynatrace-oss/terraform-provider-dynatrace#236]
**Describe the bug**
Documentation of management_zone_v2 does not say what the possible values look like for the rule types for management zones. I can see it in the UI, but there's no information on how to properly add that to terraform. Very, very, very frustrating.

**To Reproduce**
N/A

**Expected behavior**
Options in documentation provided

**Screenshots**

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by kishikawa12** [comment]
Hi @narora138,

We apologize for the inconvenience, the schema documentation in general was being created with what was returned by the Dynatrace API. There were recent enhancements that were made on our end to include additional pieces of information including the possible values based off of the defined enums. 

Unfortunately, management_zone_v2 was one of the older resources that were created without this improvement. I'll update the documentation for management_zone_v2 to be included in our next release. We'll be reviewing all of the other older resources to improve documentation in future releases but it may take some time as it will be a manual effort, we appreciate your patience.
