### ISSUE TITLE
dynatrace_json_dashboard issue with null values

### ISSUE THREAD

**Issue by wanieldilson** [dynatrace-oss/terraform-provider-dynatrace#239]
I'm trying to create dashboards by editing them in the UI, exporting the JSON and using that to inform the `dynatrace_json_dashboard` resource.  The dashboards build and deploy as expected, but terraform plan is littered with all values in the JSON that are currently set to `null`

**To Reproduce**
1. Export the JSON of the Kubernetes Cluster Health dashboard that is available out of the box with Dynatrace SaaS.
2. Observe the block for `heatmapSettings` under any panel. It will only be populated with:
```json         
"heatmapSettings": {
          "yAxis": "VALUE"
        }
```
3. Use this as the json for a `dynatrace_json_dashboard` (omitting the id field as this is populated for you).
5. Run `terraform apply`
6. Now run `terraform apply` again.  There are a tonne of fields that aren't present in the original JSON export that show up in the plan.
```
~ heatmapSettings     = {
      - showLabels   = null -> null
      - xAxisBuckets = null -> null
      - yAxisBuckets = null -> null
      # (1 unchanged element hidden)
    }
```
7. If I then go back into the JSON, and explicitly add these in with null values, they disappear from the plan.  It seems like, for whatever reason, when fields are excluded from a JSON file, they are populated in the underlying state with `null` so if these fields are missing from your JSON template, you'll always be "removing" them each time you terraform apply.

**Expected behavior**
When provisioning a dashboard with JSON, only the fields that are included in the JSON should be maintained in the state.  So when applying again, there should be no changes.

**Desktop (please complete the following information):**
 - OS: Mac OS ventura 13.2
 - Browser Chrome Version 112.0.5615.137 (Official Build) (arm64)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @wanieldilson, you're right, the version of the JSON exported via WebUI and the JSON the REST API are currently everything but identical - which essentially defies the purpose of the resource `dynatrace_json_dashboard`. We've noticed slight differences right after we've introduced that resource and they were handled one by one with custom code. But apparently recently a lot of more differences (all related to properties that are allowed to get omitted) have popped up.

I cannot promise a solution right away for the next release, but we will revisit that resource as soon as possible. Goal is to again have a resource that produces an empty plan no matter whether optional attributes are set or not, an no matter whether the export came from the WebUI or from the REST  API.
