### ISSUE TITLE
Declarative Process Grouping report attribute does not work

### ISSUE THREAD

**Issue by stevenspawn** [dynatrace-oss/terraform-provider-dynatrace#241]
**Describe the bug**
When trying to create a declarative process grouping Dynatrace resource, it requires that the report attribute be filled. When using any of the accepted values, the Terraform output will throw an error `Given property 'report' with value: 'always' was not found in the schema`.

**To Reproduce**
1. I have tried to use lower case and upper case `"Always`" and `"always"`
2. I have tired to use empty string: `""`

**Desktop (please complete the following information):**
 - Using the windows exe provider

**Comment by kishikawa12** [comment]
Hi @stevenspawn,

Thank you for the feedback. `dynatrace_declarative_grouping` had an incorrect schema and documentation for the report field, it should have been camel case which will be included in the next release. Even without the fix, all lowercase `always` should have produced a successful result, are you able to share the resource that you are trying to apply?

Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Fixed with v1.29.0
