### ISSUE TITLE
dynatrace_application (Data Source): An argument named "tags" is not expected here.

### ISSUE THREAD

**Issue by lmmarsano** [dynatrace-oss/terraform-provider-dynatrace#243]
**Describe the bug**
Contrary to [documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/application), parameter `tags` appears to be unsupported.
I recommend
- [ ] supporting it
- [ ] making parameter `name` optional.

**To Reproduce**
Attempt `terraform plan` with
```terraform
terraform {
  required_version = ">=1.4.0,<2.0.0"

  required_providers {
    dynatrace = {
      source  = "dynatrace-oss/dynatrace"
      version = ">=1.28.0,<2.0.0"
    }
  }
}

variable "token_api_environment_dynatrace" {
  type      = string
  sensitive = true
}

variable "uri_environment_dynatrace" {
  type = string
}

provider "dynatrace" {
  dt_env_url   = var.uri_environment_dynatrace
  dt_api_token = var.token_api_environment_dynatrace
}

data "dynatrace_application" "default" {
  name = ""
  tags = []
}

output "id_application" {
  value = data.dynatrace_application.default.id
}
```

Shell session
```shellsession
$ terraform plan
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 48, in data "dynatrace_application" "default":
│   48:   tags = []
│ 
│ An argument named "tags" is not expected here.
╵
``` 

**Expected behavior**
Output no error.

**Desktop (please complete the following information):**
 - OS: linux

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Luis,
You're correct, the documentation here is outdated.
We're planning to add support for tags etc. to the datasources `dynatrace_entity` and `dynatrace_entities` in one of our next releases. That would essentially deprecate a couple of datasources (`dynatrace_application`, `dynatrace_host`, `dynatrace_service`, ...).
Works for you?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Luis, with the upcoming release the data source `dynatrace_entity` will support to query via `entity_selector` - which includes the ability to specify tags.
