### ISSUE TITLE
management zone permission set up for resource 'dynatrace_user_group'

### ISSUE THREAD

**Issue by MinsonTFW** [dynatrace-oss/terraform-provider-dynatrace#245]
**Is your feature request related to a problem? Please describe.**
Currently the resource 'dynatrace_user_group' only support for environment level permission setup.

**Describe the solution you'd like**
It would be really nice if the management zone level permission setup is also available here.

**Describe alternatives you've considered**

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @MinsonTFW, I believe you're looking for the resource [dynatrace_mgmz_permission](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/mgmz_permission).

**Comment by MinsonTFW** [comment]
@Dynatrace-Reinhard-Pilz  this is what exactly I need, thank you so much!
