### ISSUE TITLE
dynatrace_maintenance_window drops 'metadata' on subsequent runs

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#25]
When upgrading to v1.0.10 I noticed that our maintenance windows show up as needing changed on subsequent runs of Terraform.  In every case, terraform reports that it is dropping the content within 'metadata'.  Even after applying the update, subsequent runs report they are making the same change.

I also tested this using a new project with brand new maintenance windows and the behavior is the same.  The resources are created without any mention of metadata, but subsequent plans indicate the data must be removed.

The attached log shows my test project.  It contains the init, plan/apply to create the windows and a subsequent plan showing pending changes.  These were all executed in series.

[dynatrace_maintenance_window-logs.txt](https://github.com/dynatrace-oss/terraform-provider-dynatrace/files/6454279/dynatrace_maintenance_window-logs.txt)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Joseph,

The real reason for why the ` metadata` section issues you observe is likely that the Dynatrace Environment you're pushing the changes to might have been updated to a newer version than the one you've pulled the original configuration settings from.

The data within that section is being offered by the Dynatrace REST API for pretty much all configuration settings. It's however meant for debugging purposes and eventually not being persisted, even if you send it along with the configuration settings (e.g. maintenance windows).

The initial approach for `terraform-provider-dynatrace` for translating the REST API for configuration settings into HCL was (an still is for Maintenance Windows) to stick closely to the OpenAPI Spec offered for the REST API. For the most part this used to be convenient, but for a couple of exceptions like `metadata` it's counter productive.

While most of the resources supported by the provider already have been rewritten (and with that not even offering the `metadata` section), Maintenance Windows, Request Attributes and Notifications are still running with the old approach.

I'm hoping to get all supported resources reimplemented within the next two releases (until end of May). Is it ok if I ask for patience until then, or does this prevent you from using the provider effectively?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
[v1.0.11](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.11) will allow you to drop the `metadata` section within `dynatrace_maintenance_windows` resources without terraform to complain about it.
The section `metadata` is still supported but is flagged as `deprecated`.

**Comment by JosephHobbs** [comment]
looks good here as well.  I do still see some issues with management zones, but I'll open a new issue for it as it's unrelated to this item!

Thank you!
