### ISSUE TITLE
no rule order option for dynatrace_application_detection_rule_v2 

### ISSUE THREAD

**Issue by ekleiner14** [dynatrace-oss/terraform-provider-dynatrace#250]
I'm not sure if this technically qualifies as a bug for the provider, but I wanted to make sure that I'm not missing something as far as how to manage the order of the detection rules goes. 

- Is this a limitation of the v2 environment api? 
- It doesn't look like it has ordering like the configuration api option did/does (/api/config/v1/applicationDetectionRules/order). Is this to be expected? 
- Are there plans to add this to the v2 environment API? 
- Should we stay on the "dynatrace_application_detection_rule" resource for the time being or is there a different workaround that would cover while still using dynatrace_application_detection_rule_v2?

Thanks for your time!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ekleiner14,

You're right, when it comes to ordered settings, the Settings 2.0 API currently represents a bit of a challenge for us. There DOES exist a way to determine the order, but using that via Terraform Provider would inflict a lot of unnecessary traffic. We're working on getting this sorted out together with PM, will however take a while.

In a way you ARE able to influence the order already using Terraform built-in functionality, though. Here is an example for that.
```
resource "dynatrace_application_detection_rule_v2" "rule_a" {
...
}

resource "dynatrace_application_detection_rule_v2" "rule_b" {
  depends_on = [  dynatrace_application_detection_rule_v2.rule_a ]
...
}
```
In case none of these rules exists yet, Terraform will be required to first create `rule_a` and afterwards create `rule_b`. Additional settings where the order matters are guaranteed to get appended to the end of the list.

What that workaround doesn't cover, is changing/maintaining the order via Terraform. Terraform would also not realize any changes in order triggered from outside of Terraform. So, in other words, the workaround is not a golden bullet.

In your specific case (concerning the resource `dynatrace_application_detection_rule_v2`) I would recommend to stick with `dynatrace_application_detection_rule` until further notice. The counterpart (utilizing the v2 Environment API) currently doesn't offer any additional functionality, and the REST endpoint for `dynatrace_application_detection_rule` includes ordering out of the box.

Makes sense?

**Comment by ekleiner14** [comment]
Hey @Dynatrace-Reinhard-Pilz - thanks for the information! Given the options, I would agree with you that it's best for us to stick with dynatrace_application_detection_rule until further notice since it has ordering and v2 doesn't have any additional functionality. 

I'm ok if you want to close this issue until the v2 schema supports ordering or leave it open until then if you prefer. Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Just wanted to wait for your response. We have an internal ticket running that's dealing with ordering. I will close this ticket here.
Thanks!
