### ISSUE TITLE
dynatrace_http_monitor - cannot set `accept_any_certificate` to false

### ISSUE THREAD

**Issue by spr0ut** [dynatrace-oss/terraform-provider-dynatrace#251]
**Describe the bug**
In the resource dynatrace_http_monitor, setting the value for `accept_any_certificate` to false does not effect any change in the resource after running apply.

**To Reproduce**

1. Create a synthetic with script.request.configuration.accept_any_certificate = false
2. Terraform apply
3. Accept any SSL certificate is set to true in Dynatrace API but false in the terraform state

**Expected behavior**
Accept any SSL certificate is set to false.

**Desktop (please complete the following information):**
- Terraform version: Terraform v1.4.6 on linux_amd64
 - Provider version: 1.30.1

Seems similar to https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/231, and was hoping it was also resolved in latest release.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @spr0ut ,

You're right root cause is exactly the same as for #231. But we just spotted the behavioral change for `follow_redirects`. I just have taken care of it. With the next release `accept_any_certificate = false` will be properly synchronized.

Thanks for reporting!
