### ISSUE TITLE
Why can't I export dynatrace_k8s_workload_anomalies?

### ISSUE THREAD

**Issue by KarolSzawlis** [dynatrace-oss/terraform-provider-dynatrace#252]
During export dynatrace_k8s_workload_anomalies I recieve error unknown resource `dynatrace_k8s_workload_anomalies`.

**Comment by KarolSzawlis** [comment]
.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.22.2/darwin_amd64/terraform-provider-dynatrace_v1.22.2 -export dynatrace_k8s_workload_anomalies
then I recieved
unknown resource `dynatrace_k8s_workload_anomalies`

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @KarolSzawlis ,
The resource `dynatrace_k8s_workload_anomalies` has gotten introduced with [v1.24.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.24.0). You're currently using v1.22.2. 
If you update your provider section to use the most recent version and the export will work.

```
terraform {
  required_providers {
    dynatrace = {
      source = "dynatrace-oss/dynatrace"
      version = "1.30.1"
    }
  }
}
```

**Comment by KarolSzawlis** [comment]
thanks!
