### ISSUE TITLE
Provider export fails with 'Terraform CLI not installed - skipping import' on Linux

### ISSUE THREAD

**Issue by endofcake** [dynatrace-oss/terraform-provider-dynatrace#253]
**Describe the bug**

When I try to import Dynatrace configuration following the [latest documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs), the provider fails with the error:

```txt
Terraform CLI not installed - skipping import
```

Looking at the source code, it appears that the `export` command is hard coded to look for Windows `terraform.exe` binary:
https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/dynatrace/export.go#L63

It's unclear how this is supposed to work on non-Windows OS.

If I symlink `terraform` to `terraform.exe`, the error goes away.

**To Reproduce**

1. Run `./terraform-provider-dynatrace -export` on Linux.

**Expected behavior**

Provider successfully discovers the location of Terraform binary on non Windows OS and the export / import succeeds.

**Desktop (please complete the following information):**
 - OS: Alpine Linux

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @endofcake, thanks for reporting. This will be fixed with the next release.
