### ISSUE TITLE
Add a dynatrace_host_group (Data Source)

### ISSUE THREAD

**Issue by MaudVandevelde** [dynatrace-oss/terraform-provider-dynatrace#257]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to set up anomaly detection for a hostgroup thanks to dynatrace_host_anomalies_v2 (Resource) but the link to the host_group is done thanks to the host group ID in the scope ((String) The scope of this setting (HOST HOST_GROUP environment)) .  
But the user do not know the host group id. Moreover the host group is not created thanks to terraform so no output can be use.

**Describe the solution you'd like**
I'd like to have the same thing that dynatrace_host (Data Source) https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/host but for hostgroup

**Describe alternatives you've considered**
Instead of an id in the scope of dynatrace_host_anomalies_v2 the name could have been used

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @MaudVandevelde,
The upcoming release of the provider introduces the attribute `entity_selector` to the data source `dynatrace_entity`. That allows you to query for pretty much every kind of runtime entity.
So, in your case, you will be able to use that snippet.
```
data "dynatrace_entity" "my_host_group" {
  entity_selector = "type(HOST_GROUP),entityName.equals\"(hostgroupname\")"
}
```
