### ISSUE TITLE
[Feature] Cannot available to invoke binary of  terraform-provider-dynatrace

### ISSUE THREAD

**Issue by JayChanggithub** [dynatrace-oss/terraform-provider-dynatrace#262]
Hi Team, 

We'd like to use binary of `./terraform-provider-dynatrace` to export our environment some settings. And follow up [docs](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs) to setup binary file. The following is our steps. Unfortunately it's seems not available. Hope someone help here. Thanks. 

```
$ git clone https://github.com/dynatrace-oss/terraform-provider-dynatrace.git 
$ cd terraform-provider-dynatrace
$ go build . 

# The binary file generate in directory 
#####

# Declare requirement environment variables 
$ export DYNATRACE_ENV_URL=xxxxx
$ export DYNATRACE_API_TOKEN=xxxx

# We using default folder ./configuration

#### Tried to run export something 
$ ./terraform-provider-dynatrace -export dynatrace_monitored_technologies_go
```

Error output. 

```
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JayChanggithub ,
What OS are you working with? I tried the exact same commands locally on Ubuntu and it worked as expected.

It is by the way not really necessary to build the executable manually. Just create an empty Terraform Module that utilizes this provider. Navigate into that directory and type in `terraform init`. You now should be able to find the prebuilt version within a subdirectory named `.terraform`. I would recommend to use that approach instead of building manually.

**Comment by JayChanggithub** [comment]
@Dynatrace-Reinhard-Pilz

Thanks for your kindly response. I am working on MacOS. After i retried with subdirectory named `.terraform`. it would be workable and error not showing up again. However `./configuration` regarding contents whole empty. Does it make sense?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
If you know for sure that there exists configuration on your environment that's reflected by the resource `dynatrace_monitored_technologies_go` then my first bet would be that the API Token you've configured doesn't have permissions to get them.

For diagnosis I would suggest to set these two environment variables:
```
export DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
export DYNATRACE_HTTP_RESPONSE=true
```
That should produce a file `terraform-provider-dynatrace.http.log` (and potentially `terraform-provider-dynatrace.http.err.log`) during the export, covering the HTTP traffic against the Dynatrace REST API. That should reveal whether you're indeed not receiving any contents or whether there exists an authentication issue.

**Comment by JayChanggithub** [comment]
@Dynatrace-Reinhard-Pilz  
Thanks for your clarifying. After i retried to following steps. It's seems workable. 

```
export DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
export DYNATRACE_HTTP_RESPONSE=true
export DYNATRACE_ENV_URL=https://apm.cf.us21.hana.ondemand.com/e/53ee4c3e-9a2c-45ff-bae6-6db5c995a784
export DYNATRACE_API_TOKEN=dt0c01.xxxxxxxxxxx (grant all of scopes permmisions)

.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.30.2/darwin_amd64/terraform-provider-dynatrace_v1.30.2 -export dynatrace_monitored_technologies_go

The environment variable DYNATRACE_TARGET_FOLDER has not been set - using folder 'configuration' as default
Downloading "dynatrace_monitored_technologies_go"
Post-Processing Resources ...
- dynatrace_monitored_technologies_go
Writing ___resources___.tf
Writing ___datasources___.tf
- dynatrace_monitored_technologies_go
Writing main.tf
Writing ___variables___.tf
Writing ___providers___.tf
- dynatrace_monitored_technologies_go
Executing 'terraform init'

cat ./configuration/modules/monitored_technologies_go/environment.monitored_technologies_go.tf    
resource "dynatrace_monitored_technologies_go" "environment" {
    enabled                      = true
    enabled_go_static_monitoring = true
    host_id                      = "environment"
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @JayChanggithub, I'm not 100% sure if I understand the question you're asking. Is your question about whether you have to export every type of resource one by one?

**Comment by JayChanggithub** [comment]
@Dynatrace-Reinhard-Pilz  

If we manually setup something configuration firstly. Whether can adopt above approaches to export so that management by automatically after that. That's what i mean. Thanks.
