### ISSUE TITLE
dynatrace_entities return empty list

### ISSUE THREAD

**Issue by MaudVandevelde** [dynatrace-oss/terraform-provider-dynatrace#263]
**Describe the bug**
I wanted to get the list of kubernetes cluster so I tried with data dynatrace_entities. It did'n work, the return list is empty. I did a test with the example provided with service and the pb is the same

**To Reproduce**
In terraform: 
data "dynatrace_entities" "kubernetes" {
  type = "KUBERNETES_CLUSTER"
}
output "kubernetes_List" {
  value = data.dynatrace_entities.kubernetes
}

data "dynatrace_entities" "Test" {
  type = "SERVICE"
}
output "Service_List" {
  value = data.dynatrace_entities.Test
}

**Expected behavior**
Get info in kubernetes_List and Service_List

**Screenshots**
  Service_List = {
    "entities" = tolist(null) /* of object */
    "id" = "v2:environment:entities-SERVICE"
    "type" = "SERVICE"
  }
  kubernetes_List = {
    "entities" = tolist(null) /* of object */
    "id" = "v2:environment:entities-KUBERNETES_CLUSTER"
    "type" = "KUBERNETES_CLUSTER"
  }

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for reporting this issue. We unfortunately don't have automatic tests for Data Sources yet. Otherwise we would have spotted this bug immediately.
We're about to release a new version still today. It will take care of your issue.
