### ISSUE TITLE
resource host_anomalies_v2 does not behave as documented

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#264]
**Describe the bug**
The documentation for this resource: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/host_anomalies_v2#nested-schema-for-host

States that only the parameter "enabled" is required for the sub-blocks of the "host" and "network" blocks.
When attempting to apply a configuration in this way, application fails with errors:
"Given property 'detectionMode' with value: 'null' does not comply with required NonNull of schema"
"Given property 'customThresholds' with value: 'null' does not comply with required NonNull of schema"

**To Reproduce**
1. Apply resource as described above
2. See error

**Expected behavior**
As per the documentation, the user should be able to configure only the anomaly detection rules desired and not define the rest.

**Additional context**
Tested with provider version 1.30.2

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Unfortunately Dynatrace expects you to specify ALL the settings, as soon as you're not using the environment defaults.
But I believe I understand the use case you're describing. Our Terraform Provider doesn't layer any additional logic on top of the Dynatrace API at the moment - I will nevertheless create an enhancement ticket for that.

Until then you may have to rely on Terraform / HCL to configure such a form of "inheritance" - e.g. using dynamic blocks like in the example below. It's, of course, a lot more difficult to maintain that way. 

```terraform
resource "dynatrace_host_anomalies_v2" "TERRAFORM_TEST_001_ENV" {
  scope = "environment"
  host {
    connection_lost_detection {
      enabled               = true
      on_graceful_shutdowns = "DONT_ALERT_ON_GRACEFUL_SHUTDOWN"
    }
    high_cpu_saturation_detection {
      enabled        = true
      # ....
    }
    # ....
  }
  network {
    high_network_detection {
      enabled        = false
    }
    network_dropped_packets_detection {
      enabled        = false
    }
    network_errors_detection {
      enabled        = false
    }
    network_high_retransmission_detection {
      enabled        = false
    }
    network_tcp_problems_detection {
      enabled        = false
    }
  }
}

resource "dynatrace_host_anomalies_v2" "TERRAFORM_TEST_001_HOST" {
  scope = "HOST-################"
  host {
    dynamic "connection_lost_detection" {
      for_each = dynatrace_host_anomalies_v2.TERRAFORM_TEST_001_ENV.host
      content {
        enabled = true
        on_graceful_shutdowns = connection_lost_detection.value.connection_lost_detection[0].on_graceful_shutdowns
      }      
    } 
    high_cpu_saturation_detection {
      enabled        = false
    }
    # ....
  }
}
```

**Comment by mattBaumBeneva** [comment]
That's what I thought. Thank you for opening an ehnhancement.
