### ISSUE TITLE
Documentation is no longer available?

### ISSUE THREAD

**Issue by nwalke** [dynatrace-oss/terraform-provider-dynatrace#265]
Is there another link I should be using to find the documentation for this provider?

I tried this: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest

Currently only getting back a 404.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @nwalke, this 404 error happens every now and then - it's unfortunately out of our control. The Terraform Registry is getting hosted by Hashicorp.

Right now the documentation is reachable for me. In the future, just a hint:
The documentation shown on the Terraform Registry is actually getting pulled from this repository. So, technically you can also pull the .md files from [here](https://github.com/dynatrace-oss/terraform-provider-dynatrace/tree/main/docs).
