### ISSUE TITLE
metric_events.event_template.metadata appears broken in v1.31.0

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#267]
**Describe the bug**
metric_events.event_template.metadata now requires a sub-block "item", and Terraform returns a validation error if it is not provided.

When I add the "item" block, Terraform apply returns the following error:
**Error: Given property 'metadataKey' with value: '' violates the following constraint: Must contain at least 1 non-whitespace character.**

The code looks like:
```
resource "dynatrace_metric_events" "metric_event" {
  enabled = true
  summary = "${var.proprietaire} - ${var.titre}"
  event_template {
    description = "The {metricname} value was {alert_condition} normal behavior."
    davis_merge = true
    event_type  = "CUSTOM_ALERT"
    title       = var.titre

    # niveau de severite de l'evenement
    metadata {
      item {
        metadata_key   = "globale-regle_severite"
        metadata_value = var.severite
      }
    }
  }
...
```

When we use the CLI to extract a metric_events resource, it returns text without the "item" block. For ex.:
```
    metadata {
      metadata_key   = "foo"
      metadata_value = "bar"
    }
    metadata {
      metadata_key   = "importance"
      metadata_value = "haute"
    }
```

**Expected behavior**
Either the module should correctly handle the "item" sub-block, or that block should not exist (which was the previous behavior.

**Comment by mattBaumBeneva** [comment]
@Dynatrace-Reinhard-Pilz , this seems to have been broken by today's release.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for reporting this issue. We've been a bit too overzealous with streamlining the handling of list-blocks here. I've reverted back to how the `meta_data` block was handled in the past.
We're planning for a bug fix release on Wednesday this week, your issue will be dealt with.

**Comment by mattBaumBeneva** [comment]
I can confirm the build now passes. Thanks.
