### ISSUE TITLE
dynatrace_management_zone reordering of propagation_types

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#27]
After creating a management zone, subsequent executes result in a reordering of propagation_types in cases where two or more are specified.

![image](https://user-images.githubusercontent.com/43007348/118045734-4dd7c100-b346-11eb-92c7-bedfc7e617fd.png)

I tried setting the order in both ways in Terraform, but it seems like it's always swapping order.  

![image](https://user-images.githubusercontent.com/43007348/118046189-fab23e00-b346-11eb-84b1-3ef23ed344f2.png)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
The order of propagation types shouldn't matter to Terraform at all - thanks for letting me know.
I've included the fix already into [v1.0.12](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.12).

**Comment by JosephHobbs** [comment]
I can confirm this is fixed in 1.0.12!  Thank you!
