### ISSUE TITLE
Dynamic_key documentation

### ISSUE THREAD

**Issue by narora138** [dynatrace-oss/terraform-provider-dynatrace#270]
**Is your feature request related to a problem? Please describe.**
No documentation regarding use of dynamic_key and dynamic_key_source on "dynatrace_management_zone_v2".

**Describe the solution you'd like**
Please add documentation regarding use of dynamic_key and dynamic_key_source on "dynatrace_management_zone_v2".

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/93150518/9ab7a87a-c7a8-47b9-8d1a-8643e1254a9c)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @narora138,

The properties `dynamic_key` and `dynamic_key_source` are indeed a bit of a black box when it comes to the documentation of the Dynatrace API.
They are only relevant if the attribute `key` is either one of these values:
* `CLOUD_APPLICATION_LABELS`
* `CLOUD_APPLICATION_NAMESPACE_LABELS`
* `HOST_KUBERNETES_LABELS`
* `PROCESS_GROUP_PREDEFINED_METADATA`
* `CUSTOM_DEVICE_METADATA`
* `ENTERPRISE_APPLICATION_METADATA`
* `DATA_CENTER_SERVICE_METADATA`
* `HOST_CUSTOM_METADATA`
* `PROCESS_GROUP_CUSTOM_METADATA`

What makes these keys special (as opposed to e.g. `CUSTOM_APPLICATION_NAME`) is the fact, that such a key alone doesn't reflect what needs to get evaluated. Here the attributes `dynamic_key_source` and `dynamic_key` are required.
Let's look at an example via WebUI here:
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/8580947/c7373c77-2371-407d-9fe8-c2ff843926d6)
In this case the `key` is `HOST_CUSTOM_METADATA`. For this kind of metadata there exist various key sources - one of them `Environment` (=> `dynamic_key_source`), which offers the `OperatorVersion` (=> `dynamic_key`).

Unfortunately the Dynatrace API doesn't contain any documentation about valid combinations of `key`, `dynamic_key` and `dynamic_key_source`. 
Our recommendation here is to configure the desired result via WebUI - where the possible values within the drop down boxes are dynamically getting queried from the Dynatrace Server. You can then use the [export functionality](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/guides/export-v2) to generate the correct HCL file for that Management Zone. (`terraform-provider-dynatrace_<version>.exe -export -flat dynatrace_management_zone_v2` will produce HCL files for all of them).

With the next release the documentation of the resource `dynatrace_management_zone_v2` will contain the same explanation for the attributes `dynamic_key` and `dynamic_key_source`.
