### ISSUE TITLE
Terraform Registry Dynatrace OSS documentation not available (404)

### ISSUE THREAD

**Issue by jpandres** [dynatrace-oss/terraform-provider-dynatrace#272]
**Describe the bug**
No documentation available. The link in the README.md is not working: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs 

Neither works searching for dynatarce in terraform registry website.

**To Reproduce**
1. Go to '[...'](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs)
4. See error 404

**Expected behavior**
Dynatrace provider documentation

**Screenshots**
<img width="1411" alt="image" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/29607133/44ebca55-9691-48a6-8410-5c83cfb3f965">

**Comment by ozaal** [comment]
Disable ublock origin adblocker for this page and it will work

**Comment by jpandres** [comment]
uow...sorry for that!

**Comment by jpandres** [comment]
My bad...the 404 confused me and did not think of ublock.
