### ISSUE TITLE
Private location with type Kubernetes asks for non-existent attributes

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#278]
**Describe the bug**

When trying to create a private `dynatrace_synthetic_location` resource with `deployment_type=KUBERNETES`, the provider returns this error:

```
Error: MinActiveGateCount, maxActiveGateCount and nodeSize must be set for a containerized location.
```

I would provide these values but I don't see them available as attributes in the resource documentation: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/synthetic_location

**To Reproduce**
1. Create a dynatrace_synthetic_location resource with deployment_type set to KUBERNETES.
2. Run terraform apply to observe error.

**Expected behavior**

These 3 additional attributes should be added to the resource, documented, and made into required attributes when deployment_type is set to that value, so the resource fails planning and validation, rather than at apply time.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @agentreno, 
Thanks for reporting this. Odd thing here is that the OpenAPI Schema hasn't even changed. We wouldn't have noticed that without you.
The next version of the Terraform Provider will contain the additional attributes for the resource `dynatrace_synthetic_location`.
