### ISSUE TITLE
Browser monitor optional attribute is actually required

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#279]
**Describe the bug**

Creating a `dynatrace_browser_monitor` resource without the `key_performance_metrics` block causes the error: `Error: Key performance metrics are missing`

It's listed as optional in the provider documentation, this is probably just a small documentation fix.

**To Reproduce**
1. Create a dynatrace_browser_monitor resource without key_performance_metrics block.
2. Terraform apply and observe error.

**Expected behavior**

That block listed as required in provider documentation and required in the provider.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for the hint. With the next release the block `key_performance_metrics` will be required as part of the Terraform Schema.
