### ISSUE TITLE
dynatrace_notification reorders receivers on subsequent runs

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#28]
After creating a dynatrace_notification, subsequent executes result in a reordering of `receivers` in cases where two or more are specified.

![image](https://user-images.githubusercontent.com/43007348/118046961-1407ba00-b348-11eb-8f09-5420814ff34e.png)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Joseph,

The resource `dynatrace_notification` is one of the three remaining resources that haven't gotten migrated to manual serialization (still uses golang reflection). I'd have to confirm to be certain, but it looks like it suffers from the same issues that led me to re-implement all resources in the first place.

By the end of next week I'm hoping to have all currently supported resources migrated. I'll take a close look at your example before releasing that version.
