### ISSUE TITLE
Lack of provider credentials hard to diagnose from error message

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#280]
**Describe the bug**

If there are no credentials available to the provider, it returns errors like:

```
Error: Get "/api/v1/<resource>": unsupported protocol scheme ""
```

This makes it hard to diagnose the issue, especially in CICD environments where it may be difficult to check the availability of credentials.

**To Reproduce**
1. Remove all sources of credential e.g. environment, in provider definition etc.
2. Try to terraform plan with any dynatrace resource.

**Expected behavior**

Assuming the API returns an unauthorized response e.g. 401, then the provider should return a message to this effect in terraform output to speed up diagnosis for end users.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for the reminder, @agentreno - a sanity check here was long overdue.

The provider already comes back with the error message `Token authentication failed` for an unknown token and even with details in case the scope of the token doesn't match the requirements of the resource ( e.g. `Token is missing required scope. Use one of: ExternalSyntheticIntegration (Create and read synthetic monitors, locations, and nodes`).

The upcoming release will check in addition for an environment URL and API Token to be configured (either via environment variable or provider configuration attribute). It will also perform a basic sanity check to ensure that it's indeed a URL.
