### ISSUE TITLE
Failed to create the latest daynatrace dashboard by the Terraform resource dynatrace_json_dashboard

### ISSUE THREAD

**Issue by weherdh** [dynatrace-oss/terraform-provider-dynatrace#289]
**Describe the bug**
Failed to create the latest dashboard by the terraform of resource `dynatrace_json_dashboard`

**To Reproduce**
Steps to reproduce the behaviour:
1. Switch to the latest dynatrace page and create a new dashboard
2. Download the JSON file of the dashboard
3. Using `dynatrace_json_dashboard` to create another new dashboard 

```
resource "dynatrace_json_dashboard" "wehe_test_lastetdashboard_owned_by_wehe_redhat_com" {
  contents = jsonencode({
    "version": 10,
    "variables": [],
    "tiles": {
        "0": {
            "type": "data",
            "title": "Chart average CPU across all hosts",
            "query": "timeseries avg(dt.host.cpu.usage)",
            "visualization": "lineChart",
            "visualizationSettings": {
                "chartSettings": {
                    "gapPolicy": "connect"
                },
                "singleValue": {
                    "showLabel": true,
                    "label": "",
                    "autoscale": true
                },
                "table": {
                    "enableLineWrap": true,
                    "hiddenColumns": [],
                    "lineWrapIds": []
                }
            }
        }
    },
    "layouts": {
        "0": {
            "x": 0,
            "y": 0,
            "w": 8,
            "h": 6
        }
    }
})
}
```

5. Failed and see errors as

```
Plan: 1 to add, 0 to change, 0 to destroy.
dynatrace_json_dashboard.wehe_test_lastetdashboard_owned_by_wehe_redhat_com: Creating...
╷
│ Error: Could not map JSON at 'tiles' near line 1 column 52
│
│   with dynatrace_json_dashboard.wehe_test_lastetdashboard_owned_by_wehe_redhat_com,
│   on wehe_test_owned_by_wehe_redhat_com.json_dashboard.tf line 1, in resource "dynatrace_json_dashboard" "wehe_test_lastetdashboard_owned_by_wehe_redhat_com":
│    1: resource "dynatrace_json_dashboard" "wehe_test_lastetdashboard_owned_by_wehe_redhat_com" {
```

**Expected behavior**
The `dynatrace_json_dashboard` works for new dashboard creating not only for classic ones

**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/17265947/efcd7138-1b01-4ad7-9a5b-cac12ce031ad)
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/17265947/99c6cdbd-a4f0-4630-b2c6-f5de5cec766f)

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @weherdh,

Dashboards created within the Dynatrace Platform are unfortunately not yet supported by our provider. We are planning to work on that soon, though.

best regards,
Reinhard

**Comment by rendhalver** [comment]
Given this is not fixed yet can we please reopen this bug or is there another way to track the progress on this?
