### ISSUE TITLE
User group management zone permissions

### ISSUE THREAD

**Issue by PatMis16** [dynatrace-oss/terraform-provider-dynatrace#292]
**Is your feature request related to a problem? Please describe.**
Allthough we can create user groups with the Terraform provider for Dynatrace and we can set permissions for environments, we cannot set permissions for specific Management Zones. At least the [documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/user_group) does not cover permissions to management zones.

**Describe the solution you'd like**
We would like to configure permissions on Management Zone level with the Terraform provider for Dynatrace. Probably this has to be added to the resource "dynatrace_user_group". 

**Describe alternatives you've considered**
Create the user group via Terraform and configure the permissions later via UI. This renders the automation a bit less useful.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @PatMis16,
I believe what you're looking for is the resource [dynatrace_mgmz_permission](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/mgmz_permission). Am I right?

**Comment by PatMis16** [comment]
Hi @Dynatrace-Reinhard-Pilz 
Yes, you are probably right. In this case, this issue can be closed.
