### ISSUE TITLE
dt_env_url and dt_api_token not optional in provider

### ISSUE THREAD

**Issue by OliviaHY** [dynatrace-oss/terraform-provider-dynatrace#295]
**Describe the bug**
dt_env_url and dt_api_token are supposed to be optional in provider configuration based on the documentation. But getting errors like below when they are missing:
```
╷
│ Error: No Environment URL has been specified. Use either the environment variable `DYNATRACE_ENV_URL` or the configuration attribute `dt_env_url` of the provider for that.
│ 
```
```
╷
│ Error: No API Token has been specified. Use either the environment variable `DYNATRACE_API_TOKEN` or the configuration attribute `dt_api_token` of the provider for that.
│ 
```
**To Reproduce**
Configuration
```
terraform {
  required_providers {
    dynatrace = {
      version = "1.34.0"
      source  = "dynatrace-oss/dynatrace"
    }
  }
  required_version  = "~> 1.4.6"
  backend "s3" {
    bucket = "dynatrace-terraform-awsaccountnumber"
    key    = "dynatrace-config.tfstate"
    region = "us-east-1"
    profile = "dynatrace-config"
  }
}

provider "dynatrace" {
  iam_client_id     = data.vault_kv_secret.someoauth-client.data.client_id
  iam_account_id    = data.vault_kv_secret.someoauth-client.data.account_uid
  iam_client_secret = data.vault_kv_secret.someoauth-client.data.client_secret
}
```

**Expected behavior**
The above configuration should not yield errors 
**Screenshots**

<img width="1289" alt="image" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/8557703/b81869c3-3fcc-4fac-9294-55a2f6186bcc">
After adding `dt_env_url`:
<img width="1276" alt="image" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/8557703/c8548009-28c1-4c98-96d3-f38c74497479">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Ventura 13.4

**Additional context**
This wasn't a problem in 1.28.0

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for reporting this issue. It will be fixed with the upcoming release.

**Comment by OliviaHY** [comment]
Works great! Thank you for fixing it! @Dynatrace-Reinhard-Pilz
