### ISSUE TITLE
Resource `dynatrace_azure_credentials` how it is linked to particular azure subscription

### ISSUE THREAD

**Issue by jeevanions** [dynatrace-oss/terraform-provider-dynatrace#296]
Looking at the resource `dynatrace_azure_credentials` which takes the `app_id` and `tenant_id` and doesn't take the subscription Id. How this resource is establishing a connection a particular Azure subscription?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @jeevanions,

You need to create a Service Principal that grants Dynatrace proper access. Details for that are described in our documentation for
[Microsoft Azure Monitoring](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-cloud-platforms/microsoft-azure-services/azure-integrations/azure-monitoring-guide#azure-roles-and-permissions).

That step is required in either case - whether you're configuring via WebUI or via REST/Terraform.

Let me know if that help,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @jeevanions, I'm closing this ticket, assuming the information I've provided was helpful. In case there are further questions, just drop us a message, and we will re-open the ticket.
