### ISSUE TITLE
management zones are not possible if case_sensitive = false

### ISSUE THREAD

**Issue by ARZ-SagA** [dynatrace-oss/terraform-provider-dynatrace#3]
Hello!

I ran into a bug where you can't create management zones if the case_sensitive attribute is false.

`resource "dynatrace_management_zone" "test-mmz" {
	name = "test-case-sensitive-false"
	rules {
		conditions {
			string_comparison {
				operator = "CONTAINS"
				type = "STRING"
				negate = false
				case_sensitive = false
				value = "test"
			}
			base_condition_key {
				attribute = "PROCESS_GROUP_NAME"
			}
		}
		enabled = true
		propagation_types = [ "PROCESS_GROUP_TO_SERVICE", "PROCESS_GROUP_TO_HOST" ]
		type = "PROCESS_GROUP"
	}
}`

Will create the following error:
`Error: {
  "code": 400,
  "message": "Constraints violated.",
  "constraintViolations": [
    {
      "parameterLocation": "PAYLOAD_BODY",
      "location": "",
      "message": "caseSensitive must be null if the operator 'EXISTS' is specified, for any other operator it must be set.",
      "path": "rules[0].conditions[0].comparisonInfo.caseSensitive"
    }
  ]
}`

if you set it to true, it's working fine.

Provider Version = "1.0.3"
DT Managed Cluster Version = 1.210.108.20210217-151038

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for bringing that to our attention. Bug confirmed. Release 1.0.4 will contain a fix for that.
