### ISSUE TITLE
dynatrace_management_zone - Terraform removes ip_address condition unknowns caseSensitive on subsequent runs

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#30]
One more scenario identified that looks to persist in 1.0.12.  On subsequent runs there is an unknowns > caseSensitive flag that is removed.  I'm guessing it's just not mapped to the new case_sensitive flag.

![image](https://user-images.githubusercontent.com/43007348/118152044-4534c880-b3e2-11eb-8cbc-12d85f8681d9.png)

Thank you!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for the bug report. This is now fixed with [v1.0.14](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.14).
