### ISSUE TITLE
data "dynatrace_management_zone" fails: unsuported protocol scheme

### ISSUE THREAD

**Issue by PatMis16** [dynatrace-oss/terraform-provider-dynatrace#300]
**Describe the bug**
When fetching a management zone with

```
data "dynatrace_management_zone" "my_mz" {
    name = "My Management Zone"
}
```

We get the following error:

```
Error: Get "/api/config/v1/managementZones": unsupported protocol scheme ""
with data.dynatrace_management_zone.my_mz
```

**To Reproduce**
1. Try to fetch data for a management zone with 

```
data "dynatrace_management_zone" "my_mz" {
    name = "My Management Zone"
}
```

2. Run `terraform apply`
3. See error

**Expected behavior**
Data for management zone can be fetched.

**Screenshots**
![Terraform_DT_Provider_data_management_zone](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/23382221/52f15f9f-b1d6-4879-9e1b-316ff46bfc70)

**Desktop (please complete the following information):**
Does not apply

**Smartphone (please complete the following information):**
Does not apply

**Additional context**
Terraform Dynatrace Provider Version: 1.35.3

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @PatMis16,

Have you set the environment variables
```
DYNATRACE_ENV_URL=https://######.live.dynatrace.com
DYNATRACE_API_TOKEN=#############################
```
or used the provider attributes for credentials?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @PatMis16,

The error message you're getting always pops up in case there no environment URL has been configured.
Until now only a subset of our resources were performing sanity checks regarding the configuration settings. Data Sources were not covered by that, unfortunately.
With the next release *all* resources and *all* data sources will print out a meaningful error message, hinting which environment variables / provider attributes are missing. That hopefully takes care of confusing situations like yours.

Should you still experience the same issue, even after specifying `DYNATRACE_ENV_URL`, drop us a message here and we'll re-open the ticket.

**Comment by PatMis16** [comment]
Hi Reinhard,

I found the issue. We had configured a provider for the cluster only. 
We had to configure an additional provider (alias) for the environment. 
Now all works fine. 

Thank you very much!

Best Regards,
Patrick
