### ISSUE TITLE
Getting issue while Creating IAM policy

### ISSUE THREAD

**Issue by shobhaagarwal** [dynatrace-oss/terraform-provider-dynatrace#302]
Trying to create Dynatrace IAM policies with the Terraform Documentation:
```
resource "dynatrace_iam_policy" "iampolicy" {
  name            = "storage bucket creation"
  statement_query = "ALLOW storage:bucket-definitions:write;ALLOW storage:bucket-definitions:read;ALLOW storage:bucket- 
       definitions:truncate"
  environment     = "https://******.live.dynatrace.com"
}
```

**We get the following error:**

```
Error: Incorrect Authorization header in request - expected `Bearer`!
 
   with module.dynatrace_log_bucket.dynatrace_iam_policy.iampolicy,   on `dt_buckets/iam_policy.tf` line 1, in resource "dynatrace_iam_policy" "iampolicy":
   1: resource "dynatrace_iam_policy" "iampolicy" {

Error: Process completed with exit code** 1.
```
-  We have provided the Dynatrace Access token as Environment variable.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @shobhaagarwal,

In order to use the *iam* resources, you need to specify oAuth credentials.
The environment variables for that are `DT_CLIENT_ID`, `DT_ACCOUNT_ID` and `DT_CLIENT_SECRET`.

The values for these environments variables will be presented to you once you create an oAuth Client for your account. I'd recommend to start [here](https://www.dynatrace.com/support/help/manage/account-management/identity-access-management/account-api-oauth) in the Dynatrace documentation for further details here.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
One additional comment about the configuration you've provided:
```
resource "dynatrace_iam_policy" "iampolicy" {
  name            = "storage bucket creation"
  statement_query = "ALLOW storage:bucket-definitions:write;ALLOW storage:bucket-definitions:read;ALLOW storage:bucket- 
       definitions:truncate"
  environment     = "https://******.live.dynatrace.com"
}
```
The value for `environment` here specifies the whole environment URL. This won't work. If e.g. your environment is reachable via `https://abc123.live.dynatrace.com` then the value for `environment` you should specify here should be `abc123`.

**Comment by shobhaagarwal** [comment]
Hi Reinhard,

I am already having the Oauth 2.0 client id and secret and Dynatrace URN. But I could not see in the resource block  to specify it as the required value was [name and Statement query]. Do we need to set it  as Environment Variable?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
You can specify the three values either via environment variable or you can use attributes to configure the provider like in this example:
```
provider "dynatrace" {
  dt_env_url   = "https://########.live.dynatrace.com/"
  dt_api_token = "######.########################.################################################################"  

  iam_client_id = "######.########"
  iam_account_id = "########-####-####-####-############"
  iam_client_secret = "######.########.################################################################"  
}
```
The documentation for this resource block is unfortunately just the bare minimum at the moment, apologies for that.
You may want to look at the [prerequisites](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/iam_user#prerequisites) for the resource `dynatrace_iam_user` instead. The same rules apply to both resources.

**Comment by shobhaagarwal** [comment]
Hi Team,

We have provided the required 3 value as stated above. Still receiving the error for Authorization bearer while creating the IAM policy.

Thanks
Shobha
