### ISSUE TITLE
CLOUD_APPLICATION_NAMESPACE entities not returned by dynatrace_entities datasource

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#304]
**Describe the bug**
Querying the dynatrace_entities datasource with the CLOUD_APPLICATION_NAMESPACE type does not seem to return anything, event though the Dynatrace REST API correctly returns entities for this type.

**To Reproduce**
1. Query the datasource as follows:
```
data "dynatrace_entities" "namespaces" {
  type = "CLOUD_APPLICATION_NAMESPACE"
}
```
2. Output the result
3. The result returned is null:
```
test_output_entities = {
  entities = null
  id       = "v2:environment:entities-CLOUD_APPLICATION_NAMESPACE"
  type     = "CLOUD_APPLICATION_NAMESPACE"
}
```

**Expected behavior**
The namespace entities should be returned as the REST API returns them.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Matt,

I am getting entries back when running this module

```
data "dynatrace_entities" "namespaces" {
  type = "CLOUD_APPLICATION_NAMESPACE"
}

output "cloud" {
  value = data.dynatrace_entities.namespaces
}
```

Could you please record the HTTP traffic when executing the same configuration?
When setting these environment variables
```
DYNATRACE_DEBUG=true
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
DYNATRACE_HTTP_RESPONSE=true
```
the provider will produce log files with HTTP traffic.

**Comment by mattBaumBeneva** [comment]
The issue seems fixed, and we are using the entity_selector now that that value has been added.
