### ISSUE TITLE
Export error without Internet access

### ISSUE THREAD

**Issue by hvad** [dynatrace-oss/terraform-provider-dynatrace#309]
Hello,

**Describe the bug**

Export failed with message "Error: Failed to query available provider packages"  when you don't have Internet access.  

**To Reproduce**
1. Export token var and environnment 
export DYNATRACE_API_TOKEN=dt0c01.xxxxxxxxxxxxxxxxxx.yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
export DYNATRACE_ENV_URL=https://server/e/env_id

2. Execute command like below : 
./terraform-provider-dynatrace_v1.36.1 -export

3. See error
...
- dynatrace_log_storage
- dynatrace_os_services
Writing main.tf
Writing ___variables___.tf
Writing ___providers___.tf
Executing 'terraform init'

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
dynatrace-oss/dynatrace: could not connect to registry.terraform.io: Failed
to request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": dial tcp: lookup
registry.terraform.io on 220.4.48.22:53: no such host

**Desktop (please complete the following information):**
 - OS: RHEL 8
 - Version v1.36.1

**Additional context**
Server where provider is execute don't have Internet access due security behaviour. 

Best regard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @hvad, with the next release of the Terraform Provider you will be able to specify the flag `-skip-terraform-init` alongside `-export`. The execution of `terraform init` is just meant to be a convenience feature. The generated .tf files will be exactly the same.
