### ISSUE TITLE
[Bug] Configuring multiple resources at the same time requires the -parallelims argument

### ISSUE THREAD

**Issue by jonormann** [dynatrace-oss/terraform-provider-dynatrace#31]
When creating multiple aws_credentials (e.g. 5) only some of them are realy created in Dynatrace. But the terraform provider says the config was successfull and they are listed in the state.
Result is an unconsistent terraform state.
![2021-05-17_screenshot 001](https://user-images.githubusercontent.com/72552324/118474076-f7360280-b70a-11eb-9d1b-a0b26aa2a0cc.jpg)
![2021-05-17_screenshot 002](https://user-images.githubusercontent.com/72552324/118474341-40865200-b70b-11eb-8750-7e4108d91f37.jpg)
![2021-05-17_screenshot 003](https://user-images.githubusercontent.com/72552324/118474081-f8672f80-b70a-11eb-9bef-5cbe132c49bd.jpg)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@jonormann is there a chance you could share your module with me (perhaps with confidential data anonymized) so we can sort this out?

**Comment by jonormann** [comment]
module "int" {
  source = "./modules/environment"
  account_ids = [
    { name = "Security", account_id = var.account_ids["int-sec"] },
    { name = "IOV", account_id = var.account_ids["int-iov"] },
    { name = "TSM", account_id = var.account_ids["int-tsm"] },
    { name = "Network", account_id = var.account_ids["int-net"] },
    { name = "Shared Services", account_id = var.account_ids["int-shared"] }]
  base_url = var.base_url
  env_id = var.env_ids["int"]
  token = var.tokens["int"]
  monitoring_role = var.monitoring_role
}

resource "dynatrace_aws_credentials" "aws" {
  count = length(var.account_ids)

  label = var.account_ids[count.index].name
  tagged_only = false
  authentication_data {
    account_id = var.account_ids[count.index].account_id
    iam_role = var.monitoring_role
  }
  partition_type = "AWS_DEFAULT"
}

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@jonormann you've stumbled across a limitation of the Dynatrace REST API for the credentials endpoint. Apparently pushing in two or more of these settings at the same time leads to these symptoms.
Could you try `terraform apply -parallelism=1` for your module and check if you're still seeing the same results? That turned out to be a workaround during my local test runs.
I will keep this issue open until we've found a valid solution that doesn't require special parametrization of terraform.

**Comment by jonormann** [comment]
> terraform apply -parallelism=1

@Dynatrace-Reinhard-Pilz looks that it works. Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
This issue doesn't apply to releases 1.18.1 and newer.
