### ISSUE TITLE
dynatrace_aws_credentials resource bug

### ISSUE THREAD

**Issue by ekleiner14** [dynatrace-oss/terraform-provider-dynatrace#310]
**Describe the bug**
We have had issues with running a terraform apply for the dynatrace_aws_credentials resource since version 1.36.0. It looks like that release contained a bug fix (Added validation to verify external ID is populated in dynatrace_aws_credentials resource) that may be the culprit?

**To Reproduce**
You can create a new dynatrace_aws_credentials resource with the config below (it has to have the supporting_services_to_monitor 
 param) but when you run a second deploy/apply it will fail.

CONFIG:
```
resource "dynatrace_aws_credentials" "account_name" {
  label          = "account_name"
  partition_type = "AWS_CN"
  tagged_only    = false
  authentication_data {
    account_id = "account_name"
    iam_role   = "role_name"
  }
  supporting_services_to_monitor {
    name = "route53"
  }
  supporting_services_to_monitor {
    name = "route53resolver"
  }
  supporting_services_to_monitor {
    name = "ssm-runcommand"
  }
}
```
ERROR:
```
╷
│ Error: must be null
│ 
│   with module_path.dynatrace_aws_credentials.resource_name,
│   on module_path/resource_name.tf line 1, in resource "dynatrace_aws_credentials" "resource_name":
│    1: resource "dynatrace_aws_credentials" "resource_name" {
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```
**Expected behavior**
Continue to deploy/apply after resource has already been added

**Additional context**
I'm not 100% sure if the data_source for aws_creds is nested or used by the actual resource, but I'm wondering if this bug was somehow introduced here > https://github.com/dynatrace-oss/terraform-provider-dynatrace/commit/539e513bebe973b34d79922645ad560408c8496f#diff-fd38a6b9f303511c298863a145fdc8a443e1e6c27743a5ffb5d2b7aa2a927a9fR60

based on the behavior it would seem that it does a query of the creds before running so there's no issues if new but if NOT new it breaks.

it's also worth mentioning that this problem only exists for dynatrace_aws_credential resources that have the optional supporting_services_to_monitor param. However, we were using this config as it's listed above without issues prior to v1.36.0 where we just list the service name but not the monitored_metrics and let it add the default options.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ekleiner14, we're planning for a release tomorrow. The bug you've identified will be fixed with that release.
Apologies for the inconvenience.

**Comment by ekleiner14** [comment]
No problem @Dynatrace-Reinhard-Pilz - thanks for your help!
