### ISSUE TITLE
Allow multiple teams to manage dynatrace_autotag_v2

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#311]
**Is your feature request related to a problem? Please describe.**
We use auto-tagging rules to associate product-team software components to their management zones.
We would like teams to be fully autonomous inconfiguring their settings in Dynatrace. To do so, we would like to allow them to add/modify rules under an auto-tagging configuration.
This actually seems impossible, because dynatrace_autotag_v2 is a single object with a unique tag name.

**Describe the solution you'd like**
We would like a resource to be provided (ex.: dynatrace_autotag_rule_v2) to allow teams to independently manage auto-tagging rules associated with an auto-tagging configuration for a specific tag.
For example:

1. The resource could take a mandatory "auto_tagging_id" argument specifying the ID of the configuration to which the rule should be added
2. In reality, this resource could still GET the entire object, append to it (or remove from it), and PUT the object back via the API

**Describe alternatives you've considered**

1. Our current alternative is to manage auto-tagging rules centrally in our admin team, which prevents product teams from being completely autonomous.
2. Another alternative would be to allow teams to manually edit the rules, but this runs counter to our efforts to standardize and automated configuration.

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva, 

A new resource `dynatrace_autotag_rules` will be included in the next release. This resource will address your exact use case of allowing you to manage a subset of tags of a given auto tag ID. 

Thanks!

**Comment by mattBaumBeneva** [comment]
Thanks!
