### ISSUE TITLE
Dynatrace activegate token support

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#315]
**Describe the bug**

I'm trying to turn [the instructions for creating a containerised activegate](https://www.dynatrace.com/support/help/platform-modules/digital-experience/synthetic-monitoring/private-synthetic-locations/containerized-locations#deploy-location) into something automated and reproducable with terraform.

Specifically I'm trying to create the secret activegate will use.

I think I've got the wrong resource because `dynatrace_activegate_token` doesn't look like it generates tokens, rather controls token handling more generally. But I can't see another resource which would produce the same kind of secret I get from the location settings page in the UI, i.e. a `tenant-token` and an `auth-token` with a prefix of `dt0g02`.

Apologies, this may not be a bug as such, but before I spend longer can I just confirm if there is support in the provider for what I'm trying to do?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @agentreno, you're correct, the resource `dynatrace_activegate_token` wouldn't be the right thing here. In hindsight, we've chosen the name for that resource pretty poorly.

I believe what you're looking for is a resource that targets the REST endpoint `/api/v2/activeGateTokens`. A resource for that endpoint didn't exist yet. With the next release you will be able to use the resource `dynatrace_ag_token`.

Let me know if that works for you.

**Comment by agentreno** [comment]
That would be wonderful @Dynatrace-Reinhard-Pilz , thank you, particularly if it outputs both tenant and API tokens, I'm not sure those should both be part of this new resource, but the tenant token didn't look like something I could derive in code currently, it looks different to the first part of environment URLs.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I need to make sure we're talking about the same thing here.
Are you trying to automate the creation of these two tokens here, when you add a Synthetic Location via `Settings / Web and mobile monitoring / Private Synthetic locations / Add Kubernetes / OpenShift location`?
 
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/8580947/ec206bf7-4e7a-4188-b64c-8ad799453016)

In that case you could simply use the already existing resource `dynatrace_api_token`.
```
resource "dynatrace_api_token" "MetricsToken" {
  name                    = "MetricsToken"
  enabled                 = true
  scopes                  = [ "metrics.read" ]
}

resource "dynatrace_api_token" "PaasToken" {
  name                    = "PaasToken"
  enabled                 = true
  scopes                  = [ "InstallerDownload" ]
}
```
Let me know if my hunch is right.

**Comment by agentreno** [comment]
If you hit the create token buttons on the page in your screenshot, and then check commands in step 1 for location deployment below that, you'll see it creates a secret called `dynatrace-tokens` which contains a tenant-token and auth-token with new values that don't match the previous API tokens. Perhaps this page is using the PaaS or Metrics API tokens to generate these new secrets? I don't know what to refer to them as, but I've been calling them 'activegate tokens' because it looks like they're required for a synthetic activegate deployment.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Ok, after reading your last comment again, it looks like you're after the values for the kubctl command, am I right?

```
kubectl -n dynatrace create secret generic dynatrace-tokens --from-literal=tenant-token=################ --from-literal=auth-token=dt0g02.########.################################################################
```

The `auth-token` will be taken care of by the resource `dynatrace_ag_token`.
The `tenant-token` is available via a different REST endpoint. But it won't be difficult to add that as a computed attribute as a convenience to the new resource.

Am I right this time?

**Comment by agentreno** [comment]
Race condition! Yes I think we've got the same understanding now.
