### ISSUE TITLE
http_monitor resource drifting based on rule-based tags

### ISSUE THREAD

**Issue by ggreen05** [dynatrace-oss/terraform-provider-dynatrace#316]
**Describe the bug**
I have about 20 http_monitors defined in terraform and everytime there is a plan it triggers a change to remove a rule_based tag. 

This tag is set by a tagging rule and not on the http_monitor itself so there's nothing that can be done about this from the http monitor end and I would like to keep the autotag rule in place.

**To Reproduce**
1. Create an HTTP monitor via Terraform
2. Create an autotagging rule that applies to the http monitor
3. Run an empty plan and you should see that the plan is trying to remove the autotag

**Expected behavior**
I would like the provider to ignore rule_based tags on http_monitors

**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/88698711/99206ab2-0e85-45a2-8542-e15809df745b)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ggreen05, thanks for reporting this issue. It will be fixed with the next release.

**Comment by ggreen05** [comment]
Awesome thanks for all the hard work!
