### ISSUE TITLE
Export and Apply duplicating configurations

### ISSUE THREAD

**Issue by FinUD** [dynatrace-oss/terraform-provider-dynatrace#318]
Not sure if this is a bug or not but we are looking at migrating several configurations to being managed by Terraform to make it easier to manage the deployment of SLOs, alerts, quality gates and a bunch of other things. At the moment we are looking at exporting and managing applications but once exported, if we then `terraform apply` we get duplicate applications. Is this intended? Is there any way of making it so we can retroactively start managing configurations with Terraform?
Cheers

**Comment by kishikawa12** [comment]
Hi @FinUD,

Thanks for reaching out. If I'm understanding you correctly, you are looking to manage an existing tenant with configuration via Terraform, is that correct? If so, we have a functionality built in the export utility (documentation pending), which will allow you to export existing configuration and automatically generate a state file. This is similar to the `terraform import` functionality but has been optimized to run much faster. The flag that is required is `-import-state`.

Example for web applications:`terraform-provider-dynatrace.exe -export -id -import-state dynatrace_web_application`
The example above will export all existing configuration from a tenant, and then automatically generate a statefile.

With this process, you should be able immediately start managing existing configuration via Terraform.

Hope that helps!

**Comment by FinUD** [comment]
Hey @kishikawa12 that is exactly what I was looking for, this is going to allow us to expand our configuration management massively! Cheers
