### ISSUE TITLE
'dynatrace_kubernetes' object appears to require 'scope' option, even when attempting to create a net-new cluster configuration

### ISSUE THREAD

**Issue by Forcebyte** [dynatrace-oss/terraform-provider-dynatrace#320]
**Describe the bug**
Today, we use Dynatrace OSS to create new external-API integrated 'dynatrace_kubernetes' (i.e. the `Connect Manually` equivalent on the Dynatrace UI

Using the older Dynatrace provider, this can be done fairly easily, however with this setting it appears that the Dynatrace OSS provider requires providing the Kubernetes dynatrace entitiy ID

This is normally not an issue, but if you're creating a net-new K8s integration, this ID cannot be provided, and is created by dynatrace itself

To be specific, im referring to this setting: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/kubernetes#scope

Ideally; keeping the option as `optional` should solve this

**Comment by kishikawa12** [comment]
Hi @Forcebyte,

Thanks for the feedback. It looks like at some point Settings 2.0 introduced an option to omit the scope on creation of an object if the schema supports scope generation. Tested and confirmed that scope can be set to optional and undefined with a successful result for `dynatrace_kubernetes`. The fix will be included in the next release.

Thanks!
