### ISSUE TITLE
Dynatrace Cluster Configuration missing

### ISSUE THREAD

**Issue by PatMis16** [dynatrace-oss/terraform-provider-dynatrace#322]
**Is your feature request related to a problem? Please describe.**
No, there is no related problem.

**Describe the solution you'd like**
While checking the doumentation, I discovered, that not all configurations for the Dynatrace Cluster can be managed with the provider. The configuration we miss are:

- E-Mail settings such as SMTP server, sender e-mail address, etc.
- Internet Proxy
- Public endpoints
- Preferences such as Mission control settings
- Remote Access permissions
- Backup

**Describe alternatives you've considered**
Cluster APIs but then we would have to code the automation ourselves. 

**Additional context**
We would like to do the whole configuration for Dynatrace via Terraform as it is considered as the standard provisioning tool at the company.

**Comment by kishikawa12** [comment]
Hi @PatMis16,

Thank you for the feedback. The next release will introduce the new resources below which should address the configuration you are looking to manage via Terraform. 

- `dynatrace_managed_smtp`
- `dynatrace_managed_internet_proxy`
- `dynatrace_managed_public_endpoints`
- `dynatrace_managed_preferences`
- `dynatrace_managed_remote_access`
- `dynatrace_managed_backup`

Note that the API does not offer a HTTP DELETE for all of the new resources except `dynatrace_managed_internet_proxy`, therefore on `destroy` the configuration will no longer be managed by Terraform but will still be present on the Dynatrace cluster.

I hope that helps!

**Comment by PatMis16** [comment]
Great! Thank you so much @kishikawa12 !
