### ISSUE TITLE
Allow configuration of apdex and anomaly detection for Key User Actions of a dynatrace_mobile_application

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#326]
**Is your feature request related to a problem? Please describe.**
The dynatrace_mobile_application currently allows configuration of Key User Actions by name, via a set of strings, but KUAs also support configuring individual apdex and anomaly detection for each action, which is not currently supported by the provider.

**Describe the solution you'd like**
We would like to be able to provide apdex and anomaly detection configuration for these KUAs in the dynatrace_mobile_application resource. 

**Describe alternatives you've considered**
The only alternative we are aware of is to configure this manually and reproduce the configuration on each environment, which is difficult to maintain.

**Comment by mattBaumBeneva** [comment]
This doesn't event seem to be supported by the REST API.
I have opened a product idea:
https://community.dynatrace.com/t5/Product-ideas/Allow-REST-API-configuration-of-apdex-and-anomaly-detection-for/idi-p/221947

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva,

Thanks for the feedback. This is actually possible via the Settings 2.0 API schemas `builtin:rum.mobile.key-performance-metrics` and `builtin:anomaly-detection.rum-mobile`. It looks like we currently have the resource `dynatrace_mobile_app_anomalies` which covers the first schema, but the second schema seems to have mistakenly been tagged as overlap with `dynatrace_mobile_application` in our internal tracking (which in this case it is not a complete overlap since you are able to set a key user action scope). The scope ID would be something like `DEVICE_APPLICATION_METHOD-XXXXXXXXXXXXXXXX`.

Targeting for a release sometime next week to cover the missing second resource. 

Thanks!

**Comment by mattBaumBeneva** [comment]
Thank you!

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva,

[Release v1.41.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.41.0) contains the new resource `dynatrace_mobile_app_key_performance` which should provide you full coverage with your use cases.

The existing `dynatrace_entity` resource can also be used to retrieve the `DEVICE_APPLICATION_METHOD` ID.

```
resource "dynatrace_mobile_app_key_performance" "example_key_performance" {
  frustrating_if_reported_or_web_request_error = true
  scope                                        = data.dynatrace_entity.example_key_user_action.id
  thresholds {
    frustrating_threshold_seconds = 12
    tolerable_threshold_seconds   = 3
  }
}

data "dynatrace_entity" "example_key_user_action" {
	type = "DEVICE_APPLICATION_METHOD"
	name = "KeyUserActionExample"
}
```

I hope this addresses your issue! I'll close this ticket as completed for the time being, please feel free to reopen as necessary.

Thanks!

**Comment by mattBaumBeneva** [comment]
@kishikawa12 , is there any way to create a new mobile app with KUAs, and configure the apdex values all in a single Apply?
Because the mobile Application does not expose the IDs of its KUAs, we have to query them through a data source, but "depends_on" doesn't seem to work correctly on data sources (I see a few Terraform bug tickets on this).
Or maybe it's a timing issue in Dynatrace.

When I first apply something like this:
```
resource "dynatrace_mobile_application" "app_mobile" {
  // other fields omitted

  apdex {
    frustrated          = var.apdex_frustrant
    frustrated_on_error = true
    tolerable           = var.apdex_tolerable
  }

  key_user_actions = [for kua in var.key_user : kua.nom]
}

data "dynatrace_entity" "kua" {
  depends_on = [dynatrace_mobile_application.app_mobile]
  count      = length(local.kua_with_apdex)

  type = "DEVICE_APPLICATION_METHOD"
  name = local.kua_with_apdex[count.index].nom
}

output "kuas" {
  value = data.dynatrace_entity.kua
}
```

The output contains null values:
```
kuas = [
  {
    "entity_selector" = tostring(null)
    "id" = tostring(null)
    "name" = tostring(null)
    "properties" = tomap(null) /* of string */
    "type" = tostring(null)
  },
  {
    "entity_selector" = tostring(null)
    "id" = tostring(null)
    "name" = tostring(null)
    "properties" = tomap(null) /* of string */
    "type" = tostring(null)
  },
]
```

But if I run it a second time wihtout destroying, I obtain content:
```
kuas = [
  {
    "entity_selector" = tostring(null)
    "id" = "DEVICE_APPLICATION_METHOD-6ACF9093D719D24D"
    "name" = "Test 02"
    "properties" = tomap({
      "detectedName" = "Test 02"
    })
    "type" = "DEVICE_APPLICATION_METHOD"
  },
  {
    "entity_selector" = tostring(null)
    "id" = "DEVICE_APPLICATION_METHOD-7E206B7F9DF4D840"
    "name" = "Test 03"
    "properties" = tomap({
      "detectedName" = "Test 03"
    })
    "type" = "DEVICE_APPLICATION_METHOD"
  },
]
```

Is there any work-around? We'd like to avoid having to force our users to run their pipelines twice and potentially run into issues by passing the variables at the wrong times.

**Comment by mattBaumBeneva** [comment]
When creating the KUAs, is it possible to wait for the API to return the IDs of the created elements?

**Comment by mattBaumBeneva** [comment]
And can we then recover these in a deterministic way before configuring other aspects of the KUAs?

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva,

I've added a validation to our mobile application creation to verify that the key user action entities are available upon creation. Unfortunately this has doubled the time it takes for a mobile application resource to be created, but I believe it is a necessary limitation we have to live with. The improvement will be in the next release which is planned for late or early next week. 

Thanks!

**Comment by mattBaumBeneva** [comment]
Hi, @kishikawa12 .
I think this should be fine. I prefer correctness over performance in this case.
Thanks!

**Comment by mattBaumBeneva** [comment]
@kishikawa12 , our tests confirm this issue is fixed. Thanks!
