### ISSUE TITLE
Error: Your supplied key '<removed>' is either not a valid key, or came from a different server version (that is not compatible with this one). Please try fetching a new key.

### ISSUE THREAD

**Issue by anspereira-mck** [dynatrace-oss/terraform-provider-dynatrace#328]
**Describe the bug**
Error when  fetching data from slo datasource (data dynatrace_slo). 

Error message:
Error: Your supplied key '<removed>' is either not a valid key, or came from a different server version (that is not compatible with this one). Please try fetching a new key.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a terraform code: 

data "dynatrace_slo" "slos" {
  name  = "yoursloname"
}

terraform init ; terraform plan

**Expected behavior**
It should return the SLO object data.

**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/104066368/a444bc39-61cd-4218-a11c-e33711d1a27f)

**Desktop (please complete the following information):**
 - OS: OS
 - Browser [None, CLI terraform]
 - Version:  terraform "~> 1.2" and dynatrace-oss/dynatrace"  "> 1.41.0"

**Additional context**
The behaviour is intermittent as print screen shows.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @anspereira-mck, I'm having troubles reproducing the issue you're describing.
Based on the screenshot you've provided it looks like a subsequent `terraform plan` eventually succeeds, am I right?
Is the key mentioned in the error message identical to the `id` that's being used when the output states `reading complete after 1s [id=....]`?

**Comment by anspereira-mck** [comment]
Yes, the error was intermittent but now it seems to be solved.
