### ISSUE TITLE
v1.1.0 dynatrace_notification apply 

### ISSUE THREAD

**Issue by ARZ-SagA** [dynatrace-oss/terraform-provider-dynatrace#33]
Hi,

with provider v1.1.0 it's not possible to apply a notfication with the alertingprofile id of annother resource

```
resource "dynatrace_notification" "onlinebankingsolutions-notification-webex" {
	web_hook {
		name = "WebEx - BS290 Dynatrace OnlineBanking-Solutions"
		active = true
		alerting_profile = dynatrace_alerting_profile.onlinebankingsolutions-alertingprofile.id
		accept_any_certificate = true
		payload = "{\"markdown\" : \"{ProblemDetailsMarkdown} \\n Tags: {Tags}\"}"
		url = "https://api.ciscospark.com/v1/webhooks/incoming/test"
	}
}
```

error on apply

```
Error: {
  "code": 400,
  "message": "Constraints violated.",
  "constraintViolations": [
    {
      "parameterLocation": "PAYLOAD_BODY",
      "location": "",
      "message": "may not be null",
      "path": "alertingProfile"
    }
  ]
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
You're right, the alerting profile never gets transmitted. I'm afraid I was a bit overzealous with shooting out the remaining resource using manual serialization. Apologies for that.
XMatters Notifications were affected aswell. A unit test for WebHooks has been added to the repo now.
[v1.1.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.1.1) takes care of that.
