### ISSUE TITLE
Expose User Management Resources to public Dynatrace cloud User management API

### ISSUE THREAD

**Issue by kyleian** [dynatrace-oss/terraform-provider-dynatrace#330]
**Is your feature request related to a problem? Please describe.**
Presently, some services on the User Management API are only provided for self managed dynatrace instances, rather than the web hosted Dynatrace. 

For example, creating usergroups here explicitly specifies an onpremise slug when called; this is the same on the user resource (and perhaps many other places).
https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/fee6c9ddf9318005851a39a6f1885021f42fbb5f/resources/usergroups/resource.go#L48

**Describe the solution you'd like**
Update these resources to either: 
- generate the route for the given resource based on a variable on the resource or provider stating the target is the public Dynatrace instance
- consume a slug variable to allow user to specify the route (less favorable)

eg, the target ends up being something like: `https://api.dynatrace.com/iam/v1/accounts/${myCoolTenantId}/users/Kyle.Ian@${companyDomain}'`

**Describe alternatives you've considered**
The only other workable solution right now is to hit the public dynatrace user management  api directly, leveraging an oauth client created within the account space (I believe this is considered "cluster" on the self managed instance). I am using the pulumi provider that derives from this terraform provider, and am running calls against the api to get my object outputs, rather than using provider resources.

**Additional context**
It is likely that the provider will need to generate the access bearer token by way of setting the oauth client's variables (user provided in lieu of the `cluster_api_token`) as provider variables, and fetching/storing the temporary bearer token before execution.

**Comment by kishikawa12** [comment]
Hi @kyleian,

I believe the existing IAM resources should address your use cases (eg. [dynatrace_iam_user](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/iam_user)). The resources prefixed with `dynatrace_iam` should all point to SaaS account management which I believe is what you are looking for. 

Please let us know if the above resources addresses your concern. Thanks!
