### ISSUE TITLE
dynatrace_web_application application completes before Key User Actions are available

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#334]
**Describe the bug**
We must create applications with key user actions and configure apdex thresholds in the same "apply" operation.
dynatrace_web_application seems to suffer from the same timing issue that was fixed for Mobile Application here: https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/326#issuecomment-1709020734 

**To Reproduce**
1. Create a dynatrace_web_application with key user actions
2. Recover the key user actions via the dynatrace_entities data source
3. The fields for those entities (ex. "id") are sometimes null (Key User Action creation is not complete)

**Expected behavior**
It should be possible to configure apdex limits for Key User Actions in a deterministic way.

**Additional context**
We are not able to consistently reproduce the issue, given its nature.

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva,

Thanks for the feedback, the fix will be included in the next release.
