### ISSUE TITLE
Data source dynatrace_remote_environments

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#336]
**Is your feature request related to a problem? Please describe.**

There's a resource for this entity right now, but no data source. I have a set of terraform stacks, one per customer, and in each one it makes sense to create a dynatrace API token and register it with a 'global' dynatrace environment using dynatrace_remote_environments resource. All good so far, but then the global environment is managed by a separate stack and needs to read all of the remote environments there, as a basis for creating a global dashboard i.e. using the `remoteEnvironmentUri` field in a dynatrace_json_dashboard resource. 

**Describe the solution you'd like**

I would like a dynatrace_remote_environments data source to exist which lists all remote environments. Filtering fields would be only a nice to have - but requiring filtering fields would be highly undesirable e.g. requiring me to specify some information about the remote environment I'm interested in like it's environment URL.

**Describe alternatives you've considered**

I could find ways to get the environment URLs over to the global stack but it would add complexity and I think it would be an enhancement for this provider in general to add data sources for existing resources.

**Comment by kishikawa12** [comment]
Hi @agentreno,

Thank you for your patience, the release planned next week will include the new data source `dynatrace_remote_environments` based off of your feedback.
