### ISSUE TITLE
User Tagging and User Action / Session Properties

### ISSUE THREAD

**Issue by mbrunn** [dynatrace-oss/terraform-provider-dynatrace#337]
I would really like to create User Tagging rules and User Action / Session Properties via the Terraform Provider.
This is one of the puzzle pieces missing to fully automate the onboarding of a new application.

Would be great if this could be implemented. However, I believe that those are settings, not yet ported to Settings 2.0 (for whatever reason) and therefore this might not be a high priority I guess. Maybe after the port to settings 2.0 happened?

KR
Michael

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mbrunn,

The settings you're asking for are part of the resource [dynatrace_web_application](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/web_application). You can find both of them within the example HCL code on that page.

Is it that what you were looking for?

**Comment by mbrunn** [comment]
Yes. Thanks a lot. I completely missed that. I assumed that this would only allow us to set up the application detection rule. Classic case of rtfm I guess.

KR
Michael
