### ISSUE TITLE
Create the latest dynatrace dashboard by the Terraform

### ISSUE THREAD

**Issue by mkhatiri** [dynatrace-oss/terraform-provider-dynatrace#342]
**Is your feature request related to a problem? Please describe.**
We are migrting from old dynatrace version to new version, so we need to migrate our dashboards, All our current dashboard are deployed using terraform, so we need to use terraform to automate the deployment of our dashboard in the latest version

**Describe the solution you'd like**
"We need to know if it is currently possible to use the latest Terraform provider to create a Dynatrace dashboard. If not, do you have an estimate of when it will be supported?"

**Describe alternatives you've considered**
If terrafom is not supported now, it is possible to use API call to create/update latest dynatrace dashboard

**Comment by mattBaumBeneva** [comment]
To add some info, our Dynatrace representative has told us that Gen 3 dashboards are actually only configurable via the new Documents API (ex.: /documents), which is generic in nature.
I think the Provider should eventually expose a resource specific to modern dashboards, allowing each tile to be individually configured (even if it internally calls the Document API, which takes a raw file (JSON in this case)).
We don't know if Dynatrace has any plans to further develop these APIs.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mattBaumBeneva,

We've been looking into Gen3 Dashboards already. Showstopper is at the moment, that currently the REST API allows only the owner of a Dashboard / Document to manage them. In other words, a resource that would allow a specific user to manage his/her Dashboards would be possible, but it is at the moment not possible to maintain all dashboards for everyone via REST.

I'll keep you posted about progress here - as I said, it **is** on our todo list, but we have to wait until Dynatrace R&D opens up a few limitations.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everybody,
Starting with [v1.55.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.55.0) the resources [dynatrace_document](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/document) and [dynatrace_direct_shares](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/direct_shares) are supported.

As mentioned in the release notes, this won't be the final version of these resources. We're still waiting for the REST API to offer the possibility to manage **all** documents and not just the ones owned by the user the credentials apply to.
