### ISSUE TITLE
Provider produced inconsistent final plan activity

### ISSUE THREAD

**Issue by SebastianWilhelm** [dynatrace-oss/terraform-provider-dynatrace#344]
**Describe the bug**
During the Terraform apply step, I’m getting the following error message

    Error: Provider produced inconsistent final plan activity
    ….
    This is a bug in the provider, which should be reported in the provider's own issue tracker.

I'll provide the .tf files and error logs via mail.

**To Reproduce**
1. terraform init was successful
2. terraform plan was successful
3. terraform apply failed with the error message.

**Expected behavior**
I expected, that the terraform apply is working without any errors.

**Desktop (please complete the following information):**
- Terraform provider: dynatrace-oss/dynatrace 1.44.1
- Executed in Azure DevOps Pipeline

**Comment by SebastianWilhelm** [comment]
By the way: we have downgraded the used terraform provider to v1.42.0 again and don't see any errors here, anymore.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Sebastian,
You're getting that message for Dashboards, am I right?

**Comment by SebastianWilhelm** [comment]
> Hello Sebastian, You're getting that message for Dashboards, am I right?

Yes, I also included the logs in my email, I've sent to you.

module.EagleEye_Dashboards.data.template_file.DB_Discovery_Overview: Read complete after 0s [id=b096e377d408e6fb54f02a38192271199f4c84051c8805868f84d76f6cc15ff0]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.EagleEye_Dashboards.dynatrace_json_dashboard.Dashboard_Discovery_Overview
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/dynatrace-oss/dynatrace" produced an invalid new
│ value for .contents: was cty.StringVal(""), but now
│ cty.StringVal("{\"dashboardMetadata\":{\"dashboardFilter\"...

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Yes, that's exactly what I expected. I got the same results when using your examples in order to fix #333.
It also makes sense that downgrading to 1.42.0 prevents the error from happening.

The release scheduled for tomorrow will handle the non-empty plans and also prevents the inconsistent final plan. As mentioned in the other ticket, it only occurs when templates are in used.

**Comment by SebastianWilhelm** [comment]
Works as expected... Thanks a lot @Dynatrace-Reinhard-Pilz!
