### ISSUE TITLE
dynatrace_key_user_action occasionally produces inconsistent results

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#345]
**Describe the bug**
The error is not systematic, but the new resource dynatrace_key_user_action occasionally fails to apply with the following error.
It may be due to a timing issue.

```
14:33:17  ╷
14:33:17  │ Error: Provider produced inconsistent result after apply
14:33:17  │ 
14:33:17  │ When applying changes to
14:33:17  │ module.Application_test-de-base.dynatrace_key_user_action.kua_without_apdex["loading
14:33:17  │ of page /test/transaction1"], provider
14:33:17  │ "provider[\"registry.terraform.io/dynatrace-oss/dynatrace\"]" produced an
14:33:17  │ unexpected new value: Root resource was present, but now absent.
14:33:17  │ 
14:33:17  │ This is a bug in the provider, which should be reported in the provider's
14:33:17  │ own issue tracker.
14:33:17  ╵
```

**To Reproduce**
1. Apply the resource like so:

```
resource "dynatrace_key_user_action" "kua_without_apdex" {
  for_each = local.kua_without_apdex

  application_id = dynatrace_web_application.application.id
  domain         = each.value[0].domain
  name           = each.key
  type           = "Load"
}
```

2. Occasionally get the error.

**Expected behavior**
This error should never occur.

**Other info**
Provider version 1.45.0

**Comment by mattBaumBeneva** [comment]
In our environments with many Applications, we often get this issue and it causes our builds to fail.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mattBaumBeneva, we're currently battling against the "laziness" of the Dynatrace REST API. Especially when creating multiple key user actions at once it sometimes pretends to have accepted it, but struggles to synchronize the existence across all cluster nodes.

I BELIEVE I have found a way now to work around that properly, but I need to ask for patience until next week before I commit that new code. I'd like to run a few more local tests this time - but it does look promising.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Just one more comment, to make it clear that the REST API is not the only one to blame here:
We considered local testing with just **_one single_** key user action to be sufficient enough - despite past experiences with this endpoint. Apologies for the laziness here. I'm applying now 50 KUAs at once, making sure it works as expected no matter what.

**Comment by mattBaumBeneva** [comment]
Thanks! That sounds good. 👍
