### ISSUE TITLE
slo_v2 showing an Leading and trailing whitespaces are not allowed.. error after export - can be formatting rows issue

### ISSUE THREAD

**Issue by VatslauX** [dynatrace-oss/terraform-provider-dynatrace#349]
**Describe the bug**
export multiline SLO 

Error point:
`  metric_expression =<<-EOT
    (uscm.shop_b2c_srt_status_stage:filter(or(eq("stringProperties.test_result","passed"),eq("stringProperties.test_result","warning"))):splitBy():count)/(uscm.shop_b2c_srt_status_stage:filter(and(ne("stringProperties.test_result","failed retrying"))):splitBy():count)*100
  EOT`

terraform apply result
│ Error: Given property 'metricExpression' with value: '(uscm.shop_b2c_srt_status_stage:filter(or(eq("stringProperties.test_result","passed"),eq("stringProperties.test_result","warning"))):splitBy():count)/(uscm.shop_b2c_srt_status_stage:filter(and(ne("stringProperties.test_result","failed retrying"))):splitBy():count)*100
│ ' violates the following constraint: Leading and trailing whitespaces are not allowed..
│ 
│   with module.slo_v2.dynatrace_slo_v2.stage_occb2c_error_rate_srt,
│   on configuration/modules/slo_v2/stage_occb2c_error_rate_srt.slo_v2.tf line 3, in resource "dynatrace_slo_v2" "stage_occb2c_error_rate_srt":
│    3: resource "dynatrace_slo_v2" "stage_occb2c_error_rate_srt" {
│ 
╵

**To Reproduce**
1. Go to 'export slo_v2'
2. 'terraform plan'
3. 'terraform apply'

**Expected behavior**
Object applied w/o errors
**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/17797084/60c1a615-46a3-437d-a99b-dd81fd6fbaf5)

**Comment by kishikawa12** [comment]
Hi @VatslauX, apologies for the inconvenience, the fix will be included in the next release. Thanks!
