### ISSUE TITLE
Documentation error dynatrace_azure_supported_services

### ISSUE THREAD

**Issue by aiden-liu** [dynatrace-oss/terraform-provider-dynatrace#350]
**Describe the bug**

**To Reproduce**
1. Go to page 'https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/azure_supported_services'
1. Scroll down to line 2 in the middle section
4. See error: "The **AWS** supported service ..."

**Expected behavior**
"The Azure supported service"

**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/49363522/adb8fca7-0817-464e-ad44-a8d1a471aa9a)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: safari
 - Version 16.6

**Comment by kishikawa12** [comment]
@aiden-liu Thank you for the heads up! This will be fixed in the next release.
