### ISSUE TITLE
Wrong behaviour when exporting using OAuth token (1.45.0)

### ISSUE THREAD

**Issue by ackjewtn** [dynatrace-oss/terraform-provider-dynatrace#351]
**Describe the bug**
According to the documentation, all you need to do to export for example `dynatrace_iam_*` is to set the following environment variables: `DT_ACCOUNT_ID`, `DT_CLIENT_ID`, `DT_CLIENT_SECRET` and run `terraform-provider-dynatrace_v1.45.0 -export dynatrace_iam_user`

This however, fails with:
```
the environment variable DYNATRACE_ENV_URL or DYNATRACE_SOURCE_ENV_URL needs to be set
```

And if i set this to something (a dummy value) `DYNATRACE_ENV_URL="https://foobar.com"`, it fails with
```
the environment variable DYNATRACE_API_TOKEN or DYNATRACE_SOURCE_API_TOKEN needs to be set
```

And to finally make it work, i set `DYNATRACE_API_TOKEN` to a dummy value `DYNATRACE_API_TOKEN="dummy-token"`

Working command:
```
DYNATRACE_ENV_URL=https://foobar.com DYNATRACE_API_TOKEN=dummy-token DT_ACCOUNT_ID=urn:dtaccount:deadbeef-dead-dead-dead-deaddeafbeef DT_CLIENT_ID=dt0s02.{REDACTED} DT_CLIENT_SECRET=dt0s02.{REDACTED} terraform-provider-dynatrace_v1.45.0 -export dynatrace_iam_user
```

It's also worth mentioning that defining `DYNATRACE_DEBUG=true` doesn't give me any debug information when these two variables aren't provided.

**To Reproduce**
```
$ DT_ACCOUNT_ID=urn:dtaccount:deadbeef-dead-dead-dead-deaddeafbeef DT_CLIENT_ID=dt0s02.{REDACTED} DT_CLIENT_SECRET=dt0s02.{REDACTED} terraform-provider-dynatrace_v1.45.0 -export dynatrace_iam_user
...
the environment variable DYNATRACE_ENV_URL or DYNATRACE_SOURCE_ENV_URL needs to be set
```
```
$ DYNATRACE_ENV_URL="https://foobar.com" DT_ACCOUNT_ID=urn:dtaccount:deadbeef-dead-dead-dead-deaddeafbeef DT_CLIENT_ID=dt0s02.{REDACTED} DT_CLIENT_SECRET=dt0s02.{REDACTED} terraform-provider-dynatrace_v1.45.0 -export dynatrace_iam_user
....
the environment variable DYNATRACE_API_TOKEN or DYNATRACE_SOURCE_API_TOKEN needs to be set
```

```
$ DYNATRACE_ENV_URL="https://foobar.com" DYNATRACE_API_TOKEN="dummy-token" DT_ACCOUNT_ID=urn:dtaccount:deadbeef-dead-dead-dead-deaddeafbeef DT_CLIENT_ID=dt0s02.{REDACTED} DT_CLIENT_SECRET=dt0s02.{REDACTED} terraform-provider-dynatrace_v1.45.0 -export dynatrace_iam_user
....
Downloading "dynatrace_iam_user"
Post-Processing Resources ...
- [POSTPROCESS] dynatrace_iam_user
Writing ___resources___.tf
Writing ___datasources___.tf
Writing main.tf
Writing ___variables___.tf
Writing ___providers___.tf
Executing 'terraform init'

```

**Expected behavior**
Set `DT_ACCOUNT_ID`, `DT_CLIENT_ID`, `DT_CLIENT_SECRET`, run the export utility and get the generated terraform files.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.0 (M1)

**Additional context**

**Comment by kishikawa12** [comment]
Hi @ackjewtn, thanks for the heads up! The fix will be included in the next release.
