### ISSUE TITLE
Problem exporting dynatrace_slo_v2 resources

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#352]
**Describe the bug**

I'm using the export feature to get terraform definitions of manually created SLOs. It looks like it has found the resources because the export stdout shows it going through 1 of 8 -> 8 of 8 which is exactly the number of SLOs I have defined. But no code is created in the resulting configuration folder, there's an empty main.tf and the standard stuff like provider definition etc.  

**To Reproduce**

1. Run ./.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.44.0/linux_amd64/terraform-provider-dynatrace_v1.44.0 -export dynatrace_slo_v2
2. Examine files in configuration folder, no code containing SLO definitions found.

**Expected behavior**

It should create a file somewhere containing SLO definitions as code.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by kishikawa12** [comment]
Hi @agentreno, similar to the other ticket, are you able to set the following environment variables and send the generated logs to [terraform@dynatrace.com](mailto:terraform@dynatrace.com)?

```
DYNATRACE_DEBUG=true
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
DYNATRACE_HTTP_RESPONSE=true
```

Thanks!

**Comment by agentreno** [comment]
This was probably just some issue for me alone, perhaps missing SLO scopes in my credentials or something. I just re-tested it with the latest version of the provider and regenerated creds and it's correctly exporting all of the SLO resources. Apologies!
