### ISSUE TITLE
Ability to apply Terraform without certificate verification

### ISSUE THREAD

**Issue by cpanet** [dynatrace-oss/terraform-provider-dynatrace#355]
Hello,

I'm having problems with my certificates on my workstation. I've tried everything but there's no solution. As a workaround I run all my tasks without certificate verification. Unfortunately this is not possible with this provider.

I'd like it to be possible to add an option when configuring the provider, like this:
`provider "dynatrace" {
  insecure = true
}
`

This is a common option (eg : https://registry.terraform.io/providers/hashicorp/aws/latest/docs#insecure) and will help me a lot in my tasks.

Also, if possible, it would help a lot if the terraform-provider-dynatrace export script had an option to run without the certificates as well.

Thanks in advance,

Sincerely,

Christian PANETIER

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @cpanet,

If you set the environment variable `DYNATRACE_HTTP_INSECURE` to `true` the HTTP requests won't verify certificates. It's an undocumented feature - needless to say, we don't recommend it for production use.

Let me know if that helps,
Reinhard

**Comment by cpanet** [comment]
Hello,

Thank you very much for this input, it helps me a lot, it works very well.

Christian
