### ISSUE TITLE
Timing issue creating application_detection_rule_v2 after web_application

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#361]
**Describe the bug**

When creating an application_detection_rule_v2 resource, using the application ID of a web_application resource as an input, the apply can fail with an error like:

```
Error: Given property 'applicationId' with value: 'APPLICATION-<ID>' is not a valid value in datasource. Value must be one of [APPLICATION-<ID>, APPLICATION-<ID>]
```

Running another apply a short time later succeeds. I suspect the resource simply needs more time to be created and perhaps the provider would benefit from polling a short time afterwards to confirm or something similar.

**To Reproduce**
1. Create a web_application resource and an application_detection_rule_v2 resource which takes the application ID as an input.
2. Apply
3. Observe error
5. Apply again, observe success

**Expected behavior**

It would be good if it applied in one pass, even if it takes a little longer to confirm the web_application resource creation.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for bringing that to our attention @agentreno.
The upcoming release of the provider will contain routines that recognize this specific error message. In such a case it will perform a sanity check on the `applicationId` passed during creation, validate that the Web Application indeed exists and if that's the case it will retry to apply the detection rule until the cluster accepts it.
