### ISSUE TITLE
custom_device no longer found

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#363]
**Describe the bug**
We aren't sure of the cause of this issue, but it may be linked to the rollout of Dynatrace 1.279.145 to our SaaS Tenants.

Since a few hours ago, our pipelines with dynatrace_custom_device elements, like so:
```
resource "dynatrace_custom_device" "workflow_guardian" {
  display_name     = "workflow_guardian"
}
```

Fail to apply, with the following error:
```
13:16:10  │ Error: Custom device with ID:5da0678d-2d4c-4a2a-9f63-620069e4e264 not found!
13:16:10  │ 
13:16:10  │   with dynatrace_custom_device.workflow_guardian,
13:16:10  │   on CUSTOM-workflow_guardian.tf line 1, in resource "dynatrace_custom_device" "workflow_guardian":
13:16:10  │    1: resource "dynatrace_custom_device" "workflow_guardian" {
```

Strangely, these custom devices not longer appear in teh Dynatrace Web UI, and are no longer returned by the /entities REST endpoint.

If we recover the entity_id from our statefile, like so:
```
    {
      "mode": "managed",
      "type": "dynatrace_custom_device",
      "name": "workflow_guardian",
      "provider": "provider[\"registry.terraform.io/dynatrace-oss/dynatrace\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "config_url": null,
            "custom_device_id": "5da0678d-2d4c-4a2a-9f63-620069e4e264",
            "display_name": "workflow_guardian",
            "dns_names": [],
            "entity_id": "CUSTOM_DEVICE-FF302B84CD5C957C",
            "favicon_url": "",
            "group": "workflow_guardian",
            "id": "5da0678d-2d4c-4a2a-9f63-620069e4e264",
            "ip_addresses": [],
            "listen_ports": [],
            "properties": null,
            "props": null,
            "type": "CUSTOM_DEVICE"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }
```

And execute a GET on the /entities/{entityId} REST endpoint, we indeed obtain a response like:
```
{
  "entityId": "CUSTOM_DEVICE-FF302B84CD5C957C",
  "type": "CUSTOM_DEVICE",
  "displayName": "workflow_guardian",
  "firstSeenTms": 1700076711431,
  "lastSeenTms": 1700076711431,
  "properties": {
    "detectedName": "5da0678d-2d4c-4a2a-9f63-620069e4e264",
    "customizedName": "workflow_guardian"
  },
  "tags": [
    {
      "context": "CONTEXTLESS",
      "key": "globale-proprietaire",
      "value": "equipe-monitoring",
      "stringRepresentation": "globale-proprietaire:equipe-monitoring"
    }
  ],
  "managementZones": [],
  "icon": {
    "primaryIconType": "host"
  },
  "fromRelationships": {},
  "toRelationships": {}
}
```

**Expected behavior**
This error should not appear.

**Additional context**
Dynatrace Saas 1.279.145
Terraform Provider 1.47.1

**Comment by mattBaumBeneva** [comment]
We have also opened a ticket with Dynatrace support, in case this is a bug introduced in the API layer:
https://one.dynatrace.com/hc/en-us/requests/249834

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mattBaumBeneva,

Like it's the case for a couple of other resources, a Custom Device that has just been created via REST API is not fully known to all cluster nodes right away. And in addition to that the resource `dynatrace_custom_device` is required to query for information that is getting determined by the Dynatrace Server right after creation. As a result the Provider needs to poll until that has happened - which is currently hardcoded to up to 40 seconds. After that the error you've noticed will be thrown. 

I've now raised that timeout to 100 seconds and also introduced an environment variable `DT_CUSTOM_DEVICE_APPLY_TIMEOUT` that allows you to raise that timeout up to 500 seconds. I'm planning to release a minor release with these on Monday - it will also  contain additional routines to diagnose #354.

**Comment by mattBaumBeneva** [comment]
@Dynatrace-Reinhard-Pilz , alright. Just to clarify, we are talking about custom devices first created weeks ago, but that Terraform is apparently trying to read/update, but not finding the object with the specified ID.
We can always try again once the next version of the provider is released and see if this issue is resolved.

**Comment by mattBaumBeneva** [comment]
We ran our build with the latest version and the custom devices were correctly found.
I think we can close this issue.
