### ISSUE TITLE
Terraform plans with Disabled SLOs fail

### ISSUE THREAD

**Issue by Forcebyte** [dynatrace-oss/terraform-provider-dynatrace#365]
**Describe the bug**
Hi there

When disabling an SLO within the Dynatrace provider, future consecutive plans error with the following:
```
Error: cannot access a disabled SLO
```

We currently manage SLOs in Dynatrace; meaning someone flipping an SLO state to 'Disabled' is fairly common via the Dynatrace provider. Which prevents it from being modified again, breaking the pipeline until someone forcefully purges the resources from Terraform State

Reproduction is as follows
- Create a Dynatrace_slo_v2 resource
- make a change to set enabled to False
- perform two terraform applies, second Terraform apply would fail to complete the plan and throw the error above

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Forcebyte,

I've reached out to Dynatrace R&D about that. The limitation you've identified has something to do with the way the provider queries for SLOs - and the REST API offers multiple ways to do that. On short notice we cannot change that, as we need to maintain backwards compatibility.

But with the upcoming release the provider will be able to handle these error messages at least quietly. That solution is not entirely satisfying - essentially any changes outside of Terraform won't get recognized that way. But it will take care of the errors when running `terraform plan`.

We will have to re-visit the topic "SLOs" for a final solution. That will have to wait until we've figured out how to maintain backwards compatibility at the same time.

best regards,
Reinhard
