### ISSUE TITLE
dynatrace_aws_credentials causing a long apply after removing metrics

### ISSUE THREAD

**Issue by FinUD** [dynatrace-oss/terraform-provider-dynatrace#368]
**Describe the bug**
After removing metrics from `dynatrace_aws_credentials` and trying to apply the config we notice that it takes the same amount of time as if it was trying to apply those metrics. This seems like it would be related to this issue https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/222 which we opened a while ago for it taking a long time to apply metrics. This occurred during our discovery of this issue https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/367.

**To Reproduce**
1. First configure an AWS account using the `dynatrace_aws_credentials` resource. On this account, configure 71+ supporting services and their metrics. Use the `dynatrace_aws_credentials` resource for the metrics/services too.
2. Remove the metrics/services and apply the new configuration.
3. Change the value of `supporting_services_managed_in_dynatrace` to `true` and apply again.

**Expected behavior**
The apply to take the same amount of time as it would to configure a new AWS integration.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - version: 1.46.1

**Additional context**
Would this be caused by it needing to loop through every metric to then remove it?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @FinUD,
Yes, I believe you're right. As long as the local state contains the metrics, I would expect to see a huge delay even during removal. Are you seeing performance issues during subsequent applies after removing these metrics also?

**Comment by FinUD** [comment]
Hey @Dynatrace-Reinhard-Pilz, no we aren't seeing it on subsequent applies so it isn't a huge issue, it was just something we noticed and thought it was worth reporting.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
That's good to know and relieving on our side. So, yes, the performance overhead is to be expected as long as Terraform insists on comparing these huge sets, which includes the deletion of all the services.
With the introduction of the resource `dynatrace_aws_service` we are hoping that the performance overhead gets reduced to a certain extent. I don't expect it to be quick as hell nevertheless - a single rest call will still require lots of comparisons. But we were able to decouple one hierarchy of unsorted lists from the Terraform CLI that way and are taking care of it within the provider.

Is it ok if we close this ticket until further notice?
