### ISSUE TITLE
Replace special characters in resource names

### ISSUE THREAD

**Issue by smc87** [dynatrace-oss/terraform-provider-dynatrace#37]
Similar to the issue encountered with whitespace and resource names.
Please could you add in something to remove any special characters.

 1: resource "dynatrace_dashboard" "GROUP_-_IIB_&_MQ_Stats" {
│ 
│ A name must start with a letter or underscore and may contain only letters,
│ digits, underscores, and dashes.

Many thanks.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I'll modify the routine so that only letters, dashes and underscores will be used. Everything else will get replaced by underscores.

**Comment by colinsidi** [comment]
We are getting this issue too with "()" characters

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Any character that is not a letter, digit, underscore or dash will be covered by the upcoming release.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @smc87 and  @colinsidi ,
Release [v1.2.2](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.2.2) now allows for letters, digits, underscores and dashes ONLY within the resource names. Everything else will get replaced by underscores.
The names of the `.tf` files still allow for a larger subset of characters, though.
