### ISSUE TITLE
HTTP 400 from API when applying a Workflow with CRON trigger

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#371]
**Describe the bug**
We are attempting to apply an automation workflow with a trigger configured as follows, which should be valid according to the documentation:
```
  trigger {
    schedule {
      active = false
      trigger {
        cron = "*/10 * * * *"
      }
    }
  }
```

The provider receives an API error indicating it may have provided an incomplete trigger configuration:

```
14:39:42  │ Error: Failed to upsert automation object (HTTP 400)
14:39:42  │ 	Response was:{"error":{"message":"Invalid request.","code":400,"details":{"trigger":{"schedule":{"trigger":["No match for discriminator 'type_' and value '' (allowed values: 'cron', 'time', 'interval')"],"rule":["Must be a valid UUID."],"timezone":["\"\" is not a valid choice."]}}}}}
14:39:42  │ 
14:39:42  │   with dynatrace_automation_workflow.easyTravel_guardian_Validation_terraform,
14:39:42  │   on testWorkflow.tf line 1, in resource "dynatrace_automation_workflow" "easyTravel_guardian_Validation_terraform":
14:39:42  │    1: resource "dynatrace_automation_workflow" "easyTravel_guardian_Validation_terraform" {
```

When we apply the workflow without the above code, the ressource is applied correctly.

**Additional context**
Provider v1.47.2

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva 

Looks like we got caught with a small schema change with the workflow API. Thank you for raising the issue, the fix will be included in the next release.
