### ISSUE TITLE
No escaping or percentage sign for jsonencode of log processing -> sample log

### ISSUE THREAD

**Issue by dcryans** [dynatrace-oss/terraform-provider-dynatrace#372]
**Describe the bug**
When running -export for log processing, if the sample log contains a %{text} for example, terraform expects a %{if or %{else
An error comes out:
Error: Invalid template control keyword 

**To Reproduce**
add a %{variable} to a log sample
use -export for dynatrace_log_processing

**Expected behavior**
Escaping of the percentage sign by doubling it: %%{variable}

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks, David. Will be fixed with the upcoming release.
