### ISSUE TITLE
dynatrace_maintenance does not wait for management zone to be ready

### ISSUE THREAD

**Issue by amirasyraf** [dynatrace-oss/terraform-provider-dynatrace#375]
**Describe the bug**

The resource `dynatrace_maintenance` sometimes fail on first apply run when using management_zones filter. I suspect this is due to improper wait on the dependency resource: `dynatrace_management_zone_v2` as it may not be ready or returning the correct ID by the time `dynatrace_maintenance` is executed. 

So far, from 4 deploys, 3 had failed on the same issue requiring a second run, while the other applied successfully the first time.

**To Reproduce**
The following usually fails to apply on the **first** apply, but is successful on subsequent applies:

```
resource "dynatrace_management_zone_v2" "mgmt_zone" {
  ...
}

resource "dynatrace_maintenance" "maintenance" {
  enabled = true
  general_properties { ... }
  schedule { ... }
  filters {
    filter {
      management_zones = [dynatrace_management_zone_v2.mgmt_zone.legacy_id]
    }
  }
}
```

**Expected behavior**
Apply successfully the first time

**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/15522007/ecb7ee46-2335-4862-a968-3fe411522e6f)

**Desktop (please complete the following information):**
GitHub Actions Ubuntu runner

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @amirasyraf,

If you change `dynatrace_management_zone_v2.mgmt_zone.legacy_id` to `dynatrace_management_zone_v2.mgmt_zone.id` the maintenance window will get applied correctly.

```terraform
resource "dynatrace_maintenance" "maintenance" {
  enabled = true
  general_properties { ... }
  schedule { ... }
  filters {
    filter {
      management_zones = [dynatrace_management_zone_v2.mgmt_zone.id]
    }
  }
}
```

I need to assume a bit here, but most likely the REST API HAS been accepting both kinds of IDs here in the past, and at a certain point now enforces the settings 2.0 ID (which is `dynatrace_management_zone_v2.mgmt_zone.id`).

Just leave us a message, in case that doesn't work out and we will re-open the ticket.
