### ISSUE TITLE
dynatrace_entity does not always provide the latest service ID when using type=SERVICE

### ISSUE THREAD

**Issue by julianxhokaxhiu** [dynatrace-oss/terraform-provider-dynatrace#377]
**Is your feature request related to a problem? Please describe.**

In our current solution, we are trying to fetch the latest service ID available in a management zone using the [`dynatrace_entity`](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/entity) data source, so we can use it on some Dashboard widgets to make sure they always reflect the latest service ID for a specific Web Server that is being monitored. Still, to our surprise, we found out that Dynatrace does not always provide the list ordered by `lastSeenTms` criteria, and randomly provides either the latest, sometimes the oldest, and sometimes neither of them.

**Describe the solution you'd like**

Ideally, we would like to have some kind of `sortBy` attribute on the `dynatrace_entity` data source, since it will return always the first element of the list, which will then allow us to decide the criteria "of the first element". In this case we'd use something like `sortBy = "lastSeenTms"`.

**Describe alternatives you've considered**

Another way we could tackle this would be by being able to access the `lastSeenTms` value for each service (`type=SERVICE`) returned by [`dynatrace_entities`](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/entities). We would then do the ordering in Terraform on our own.

**Additional context**

I'm more than happy to provide more context if needed. Feel free to ask.

**Comment by kishikawa12** [comment]
Hi @julianxhokaxhiu,

Thank you for the feedback. Out of the box the entities API only allows sorting by name which wouldn't resolve your issue. So I've went ahead and implemented the alternative of introducing the `lastSeenTms` field that can be used to manipulate the data, it will be included in the next release.

I hope that helps!

**Comment by julianxhokaxhiu** [comment]
Thank you @kishikawa12 really appreciated! This will help us being unblocked. Looking forward to the next release.
