### ISSUE TITLE
`docs` on dynatrace_pg_alerting is lacking 

### ISSUE THREAD

**Issue by ceng-p** [dynatrace-oss/terraform-provider-dynatrace#380]
**Describe the bug**
There's lacking documentation for the `dynatrace_pg_alerting` resource 
**Expected behavior**
When there are variables that are string type that only accept a constrained amount choices, the docs should be clear on what those values are. In other examples I have seen this, but for the `dynatrace_pg_alerting` resource it doesn't apply.
**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/27136738/13e55115-3da7-4cc0-9a6d-6fb7401c8cc8)

**Comment by kishikawa12** [comment]
@ceng-p Thank you for the feedback, the updated documentation with possible values will be included in the next release.
