### ISSUE TITLE
Documentation bug: aws_service

### ISSUE THREAD

**Issue by k5njm** [dynatrace-oss/terraform-provider-dynatrace#383]
**Describe the bug**
There appears to be a few documentation bugs on the Provider page for: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/aws_service

The example has the first resource `dynatrace_aws_service`, which appears to be the contents of `dynatrace_aws_credentials` resource. It looks like the wrong resource name was put in the example.

Further down on the page, the `credential_id` description references an Azure credential, which is incorrect.
`[credentials_id](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/aws_service#credentials_id) (String) the ID of the azure credentials this supported service belongs to`

**Comment by k5njm** [comment]
This looks to be a regression of: https://github.com/dynatrace-oss/terraform-provider-dynatrace/pull/293/files

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @k5njm, thanks for making us aware of that bug. The upcoming release will come with an example that has been corrected.
