### ISSUE TITLE
Documentation report for alerting service.

### ISSUE THREAD

**Issue by susiesolis** [dynatrace-oss/terraform-provider-dynatrace#384]
The Terraform registry for the resource `dynatrace_alerting` shows that the following:

[operator](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/alerting#operator) (String) Operator of the comparison. You can reverse it by setting negate to true. Possible values are BEGINS_WITH, CONTAINS, CONTAINS_REGEX, ENDS_WITH and EQUALS.

A `terraform apply` results in an error stating that `EQUALS` needs to be `STRING_EQUALS`

* https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/docs/resources/alerting.md?plain=1#L119

This request is to update the documentation to reflect the new operator.

**Comment by susiesolis** [comment]
![Uploading Screenshot 2023-12-19 at 8.28.30 AM.png…]()

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @susiesolis,

Thanks for reaching out about that. You're correct, the documentation is incorrect here. Also `CONTAINS_REGEX` is not correct. It should state `REGEX_MATCHES`.

The documentation will get corrected with the next release.
