### ISSUE TITLE
Improve `dynatrace_opentelemetry_metrics` resource

### ISSUE THREAD

**Issue by KevinThompsonYCRX** [dynatrace-oss/terraform-provider-dynatrace#389]
**Is your feature request related to a problem? Please describe.**

The current implementation of the `dynatrace_opentelemetry_metrics` resource will entirely replace the existing configuration, rather than add the provided `additional attributes` to the settings. This means it will delete the default `dt.` dimensions that the docs recommend not to, without any warning.

I've adding the default values to my list of custom attributes to at least get this working, but other teams will need to make updates to this list outside of my own Terraform code & this will cause issues down the line. To be able to manage our infrastructure effectively, this needs to be modularized further.

**Describe the solution you'd like**

1. Create a new `dynatrace_opentelemetry_metrics_attributes_allow_list` resource to replace the functionality for `additional_attributes`. This will have the same behavior as the existing `dynatrace_attribute_allow_list` resource.
2. Create a new `dynatrace_opentelemetry_metrics_attributes_deny_list` resource to replace the functionality for `to_drop_attributes`.
3. Remove the `additional_attributes` and `to_drop_attributes` blocks from the `dynatrace_opentelemetry_metrics` resource. 
Keep this resource simply to manage the `additional_attributes_to_dimension_enabled` and `meter_name_to_dimension_enabled` settings.

**Describe alternatives you've considered**

Could keep this all in one resource if:
1. The `additional_attributes_to_dimension_enabled` and `meter_name_to_dimension_enabled` settings are made optional
2. Existing config is not replaced, but extended by the provided attributes. 
 
However, for consistency with the `dynatrace_attributes_allow_list`, the other solution seems better to me.

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @KevinThompsonYCRX,

You're right, the current behavior of that resource doesn't reflect at all what you can do via WebUI.
That behavior (getting rid of defaults) is unfortunately not rooted within the Terraform Provider. The REST API currently only offers to default the FULL list - which replaces the default settings of the environment. 
I've already reached out to Dynatrace R&D about that topic. If the REST API offered a way to query for the defaults we could work around that limitation. But that's currently not possible.

About your suggestion for a separate resource `dynatrace_opentelemetry_metrics_attributes_allow_list`:
Based on your explanation I have to assume that multiple teams would be maintaining separate Terraform modules with different allow lists. Is your expectation that multiple instances of `dynatrace_opentelemetry_metrics_attributes_allow_list` should be additive (i.e. must not replace what has been applied via different Terraform modules)?

**Comment by KevinThompsonYCRX** [comment]
Yes that's my understanding, although in recent updates the default behavior has changed to include all metric attributes, so the allow_list doesn't need to be managed unless specifically enabled.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @KevinThompsonYCRX,

The upcoming release of the Provider introduces the optional attribute `mode` to the resource `dynatrace_opentelemetry_metrics`.
* When the attribute isn't specified it defaults to the value `EXPLICIT`. In that case the resource behaves like it has before.
* When `mode` is set to `ADDITIVE` the blocks `additional_attributes` and `to_drop_attributes` will leave any attributes that have already been configured alone. 

In other words, you're now able to have multiple instances of the resource `dynatrace_opentelemetry_metrics` configured, like in the example below. The requirement for that to produce consistent results is that all of these resource instances are using `mode = "ADDITIVE"`. 

```hcl
resource "dynatrace_opentelemetry_metrics" "test" {
  additional_attributes_to_dimension_enabled = true
  meter_name_to_dimension_enabled            = true

  mode = "ADDITIVE"

  additional_attributes {
    additional_attribute {
      enabled       = true
      attribute_key = "terraform.test.add"
    }
    additional_attribute {
      enabled       = true
      attribute_key = "terraform.X.add"
    }
  }

  to_drop_attributes {
    to_drop_attribute {
      enabled       = true
      attribute_key = "terraform.test.drop"
    }
  }
}

resource "dynatrace_opentelemetry_metrics" "test2" {
  mode = "ADDITIVE"

  additional_attributes {
    additional_attribute {
      enabled       = true
      attribute_key = "terraform.test2.add"
    }
    additional_attribute {
      enabled       = true
      attribute_key = "terraform.test3.add"
    }
  }
}


resource "dynatrace_opentelemetry_metrics" "test3" {
  mode = "ADDITIVE"

  additional_attributes {
    additional_attribute {
      enabled       = true
      attribute_key = "terraform.C.add"
    }
    additional_attribute {
      enabled       = true
      attribute_key = "terraform.D.add"
    }
  }
  to_drop_attributes {
    to_drop_attribute {
      enabled       = true
      attribute_key = "terraform.F.drop"
    }
  }  
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
We've also ran experiments for a solution for the issue, that the environment-default attributes are gone, once you're using the resource `dynatrace_opentelemetry_metrics`.
There exists unfortunately no easy way to query for the default values via REST API. The only way to get to that list would be to temporarily clear what is currently configured. 
In other words, the approach you're already using - configuring the default values manually - is currently the best solution.
