### ISSUE TITLE
Database insights for Oracle

### ISSUE THREAD

**Issue by agentreno** [dynatrace-oss/terraform-provider-dynatrace#391]
**Is your feature request related to a problem? Please describe.**

Can I just check if there any terraform resources covering this part of the dynatrace UI (setting up the deprecated database insights for Oracle feature):
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/3884999/21d13083-1ed9-49e8-b00c-ad853e5f0ec3)

I had a look through the existing resources but I couldn't see anything obvious. It's possible I've overlooked it though. 

**Describe the solution you'd like**

Ideally I'd be able to create database configurations in database insights for Oracle, using this provider.

I'm aware the feature is deprecated but there's a very big drawback of the succeeding Oracle Extensions 2.0 replacement, which is that only non-containerised ActiveGates can use it.

**Describe alternatives you've considered**

I'd be forced to either create these configurations manually, or possibly look at null resource API calls :/

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @agentreno,

Being able to - at least manage configuration settings - for OneAgent and Active Gate Extensions is one of the few remaining REST APIs the Terraform Provider doesn't address yet. That feature has been requested multiple times already. We just didn't have a chance yet to work on it.  The fact, that your specific extension is already deprecated is irrelevant - neither the REST API nor the Provider would treat it differently from other extensions.

I'm closing your ticket in favor of [#114](https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/114). At the moment I don't dare to give you an ETA for when the provider will support extension configuration, though.
