### ISSUE TITLE
Export utility v1.49.0 no longer exports all ressources

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#392]
**Describe the bug**
Upon upgrading to the latest version, the export utility only exports the following ressources when executed with the `-export` flag:

- browser_monitor
- http_monitor
- synthetic_location

**Expected behavior**
The export utility should produce .tf files for all ressources that support automatic export.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @mattBaumBeneva,

Could you run the export with these three environment variables set?

```
set DYNATRACE_DEBUG=true
set DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
set DYNATRACE_HTTP_RESPONSE=true
```
The export silently skips over resources where it's unable to actually fetch the contents (no matter what reason, authentication, REST API not responding, ...)

The logs would give us a few hints. We couldn't reproduce it locally so far.

**Comment by mattBaumBeneva** [comment]
It seems from the logs that the token we are using is missing some scope...
Has this changed in some way on the API level?

[terraform-provider-dynatrace.export.log](https://github.com/dynatrace-oss/terraform-provider-dynatrace/files/14054173/terraform-provider-dynatrace.export.log)
[terraform-provider-dynatrace.http.err.log](https://github.com/dynatrace-oss/terraform-provider-dynatrace/files/14054174/terraform-provider-dynatrace.http.err.log)
[terraform-provider-dynatrace.http.log](https://github.com/dynatrace-oss/terraform-provider-dynatrace/files/14054175/terraform-provider-dynatrace.http.log)
[terraform-provider-dynatrace.warnings.log](https://github.com/dynatrace-oss/terraform-provider-dynatrace/files/14054176/terraform-provider-dynatrace.warnings.log)
