### ISSUE TITLE
Management Zone Rule - caseSensitive set to false, read as null

### ISSUE THREAD

**Issue by brandonlum** [dynatrace-oss/terraform-provider-dynatrace#394]
**Describe the bug**
When attempting to create a rule for a management zone, receiving the below error: 
`Given property 'caseSensitive' with value: 'null' does not comply with required NonNull of schema`

The configuration of said rule:

     rule {
      type    = "ME"  
      enabled = true
      attribute_rule {
        azure_to_pgpropagation       = true
        azure_to_service_propagation = true
        entity_type                  = "AZURE"
        attribute_conditions {
          condition {
            case_sensitive = false
            key            = "AZURE_ENTITY_NAME"
            operator       = "CONTAINS"
            string_value   = "eastus"
         }
        }
       }
      }

If you were to set the case_sensitive setting to `true` in the above code, it works, but `false` is read as `NULL`

For reference, the configuration block above is a direct copy from the export tool (using the export to copy an existing into MZ to create a new one in state). Also case_sensitive seemingly works elsewhere that it's expected and was able to deploy other rules that had the `false` value, something specific here. Seemingly the difference between the above and other instances of rules using case_sensitive is `azure_to_pgpropagation` and `azure_to_service_propagation`

**To Reproduce**
1. Create management zone module
2. Add rule above
3. ...

**Expected behavior**
Expected rule to be added and show in the portal

Dynatrace Version: [1.48.1]

![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/11163012/1121e7cc-8457-47d9-976d-36c4fc44d5b9)

**Comment by kishikawa12** [comment]
Hi @brandonlum,

Thank you for the feedback, I'm not entirely sure how this was missed during the schema update, but the fix will be included in the next release.

Thanks!
