### ISSUE TITLE
Provider export with -migrate flag fails for dynatrace_json_dashboard

### ISSUE THREAD

**Issue by meierseb** [dynatrace-oss/terraform-provider-dynatrace#395]
While trying to execute export with -migrate flag for dynatrace_json_dashboard, it fails with "unmarshal error"

**To Reproduce**
1. Configure provider
`  required_providers {
    dynatrace = {
      version = "1.49.0"
      source = "dynatrace-oss/dynatrace"
    }`
3. Execute export command
`terraform-provider-dynatrace_v1.49.0.exe -export -migrate dynatrace_json_dashboard`
4. Error occurs
`Downloading "dynatrace_json_dashboard"
Downloading "dynatrace_dashboard_sharing"
Post-Processing Resources ...
[POSTPROCESS] dynatrace_json_dashboard (0 of 725)GET /api/config/v1/calculatedMetrics/service/calc:service.***************: unmarshal error: json: Unmarshal(non-pointer string)
{"metadata":{"configurationVersions":[0],"clusterVersion":"1.283.84.20240122-091713"},"tsmMetricKey":"calc:service.***************","name":"***************","enabled":true,"ignoreMutedRequests":false,"metricDefinition":{"metric":"RESPONSE_TIME","requestAttribute":null},"unit":"MICRO_SECOND","unitDisplayName":"","entityId":null,"managementZones":["CD_***************"],"conditions":[{"attribute":"SERVICE_REQUEST_ATTRIBUTE","comparisonInfo":{"type":"STRING_REQUEST_ATTRIBUTE","comparison":"BEGINS_WITH","value":"***************","values":null,"negate":false,"requestAttribute":"WebRequestURLPath","caseSensitive":false,"matchOnChildCalls":true,"source":{"managementZone":null,"serviceTag":{"context":"CONTEXTLESS","key":"Namespace","value":"svds"}}}}],"dimensionDefinition":null}`

**Expected behavior**
Export with -migrate flag is generating correct TF files.

**Desktop:**
 - OS: Windows 11 Pro
 - Provider Version 1.49.0
 - TF Verison 1.5.5

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @meierseb,

The export seems to have an issue with the Calculated Service Metric this dashboard refers to.
We are planning for a new release still this week. That bug will be taken care of.

**Comment by meierseb** [comment]
Hi @Dynatrace-Reinhard-Pilz 
Thanks!
