### ISSUE TITLE
Modifying dynatrace_notification not possible

### ISSUE THREAD

**Issue by ARZ-SagA** [dynatrace-oss/terraform-provider-dynatrace#4]
Hello!

When I try to modify a dynatrace_notification ressource I get the following error:
`Error: cannot resolve objects of nil type`

The modification will get added to the state, but the configuration change in dynatrace is missing.

Create and destroy of the ressource is possible, it just occurs if you modify it.
Example Resource:
`resource "dynatrace_notification" "test-notification2" {
	web_hook_notification_config {
		name = "Bugtest5"
		type = "WEBHOOK"
		active = true
		alerting_profile = "c21f969b-5f03-333d-83e0-4f8f136e7682" #Default Alerting Profile
		accept_any_certificate = true
        payload = "test"
		url = "https://<webhook-url>"
	}
}`

Provider Version = "1.0.3"
DT Managed Cluster Version = 1.210.108.20210217-151038

Best Regards,

Alex

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks @ARZ-SagA. Bug confirmed. Will be fixed with v1.0.4.
