### ISSUE TITLE
Dashboard seems to be deployed through terraform but does not show up on GUI

### ISSUE THREAD

**Issue by gkdevopsmon** [dynatrace-oss/terraform-provider-dynatrace#401]
**Describe the bug**
terrafrom init/plan/apply runs properly without errors
Dashboard is not showing up on GUI

**To Reproduce**
1. deploy TF file through terraform

**Expected behavior**
Dashboard shows up on GUI

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
exec log:
module.dashboard.dynatrace_json_dashboard.nameoftheapp: Modifying... [id=2ad57cd0-8555-406b-9cee-a43e5535eb98]
module.dashboard.dynatrace_json_dashboard.nameoftheapp: Modifications complete after 1s [id=2ad57cd0-8555-406b-9cee-a43e5535eb98]

To protect our data all info has been anonymized.

[deploys-does-not-show-up-on-gui.tf.txt](https://github.com/dynatrace-oss/terraform-provider-dynatrace/files/14297818/deploys-does-not-show-up-on-gui.tf.txt)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @gkdevopsmon,

Dashboards are by default not getting shared in Dynatrace. You can use the resource `dynatrace_dashboard_sharing` to change that.

The example below will share your dashboard with every authenticated user.

```hcl
resource "dynatrace_dashboard_sharing" "ICES_FestiveMode_PROD_sharing" {
  dashboard_id = dynatrace_json_dashboard.ICES_FestiveMode_PROD.id
  enabled = true
  preset = true
} 
```

You can, of course, also be a bit more specific and just share it with certain users (e.g. just grant them viewer permissions). For that you'll have to specify one or more [permission blocks](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/dashboard_sharing#permissions).

Let me know if that helps,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I'm closing this ticket until further notice. In case you have additional questions, just add a comment and we will re-open it.

**Comment by gkdevopsmon** [comment]
Hi @Dynatrace-Reinhard-Pilz ,

Thanks for your help. We could deploy our dashboards.

Best,
Geza
