### ISSUE TITLE
Support for cluster resources in export utility

### ISSUE THREAD

**Issue by mbrunn** [dynatrace-oss/terraform-provider-dynatrace#402]
**Is your feature request related to a problem? Please describe.**
I wanted to use the Terraform provider to get a continuous backup of the configuration of a Dynatrace Cluster with all its environments and discovered that the export utility does not work with cluster wide resources. 

I get the following error when wanting to export such resources with version 1.49.2 of the provider: 
```
.\terraform-provider-dynatrace_v1.49.2.exe -export -ref -id dynatrace_policy
unknown resource `dynatrace_policy`
```

```
.\terraform-provider-dynatrace_v1.49.2.exe -export dynatrace_user_group     
unknown resource `dynatrace_user_group`
```

**Describe the solution you'd like**
Support for cluster wide resources in the export utility.

**Describe alternatives you've considered**

**Additional context**
The idea is to run the export utility every day at midnight to get the current configuration for each environment. In case of a configuration error or a catastrophic event, one can revert back to a previous state. (By comparing the current state with the previous state to see which resources might need to be deleted, since they are not in the old backed up state.)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @mbrunn,

You're right, we've neglected the export capabilities for cluster resources. Getting that to work comes with a couple of additional challenges (as opposed to settings for environments).

The upcoming release will allow you to export `dynatrace_policy`. The remaining cluster resources will follow in the next couple of weeks - I need to ask for a bit of patience until all of them are covered.

Are there any resources important for your use case apart from the ones listed below?

* `dynatrace_user_group`
* `dynatrace_user`
* `dynatrace_policy`
* `dynatrace_policy_bindings`
* `dynatrace_mgmz_permission`

**Comment by mbrunn** [comment]
Hi @Dynatrace-Reinhard-Pilz,
thanks for the heads up. 
You are right about the resources that would be interesting to us.
What would be interesting additionally are network-zones as these can also be scoped on cluster level.

KR

**Comment by kishikawa12** [comment]
Hi @mbrunn,

Export for the resources `dynatrace_policy`, `dynatrace_user_group`, and `dynatrace_user` is now available in v1.51.0. We'll be working on introducing support for the other resources in the following releases. We'll keep this issue open until we have full coverage of the existing resources and we'll also take a look at network-zones.

**Comment by kishikawa12** [comment]
Hi @mbrunn,

Export support for the remaining resources `dynatrace_policy_bindings` and `dynatrace_mgmz_permission` will be included in the next release.
Also included will be a new resource `dynatrace_managed_network_zones` which will allow you to configure network zones at the Managed cluster level. 

I hope that helps! I'll close this ticket for the time being, please feel free to reopen if you experience any issues.

**Comment by hvad** [comment]
Hi,
Good job. Can you add some doc for case of export dynatrace_user from cluster ? 
Thanks

**Comment by kishikawa12** [comment]
Hi @hvad,

Thank you for the reminder, we'll add some documentation in our next release. 

In the meantime the `dynatrace_user` export can be triggered by setting the `DYNATRACE_CLUSTER_URL` and `DYNATRACE_CLUSTER_API_TOKEN` environment variables and running the following command.
`terraform-provider-dynatrace -export dynatrace_user`

Additional information can be found in our [export utility](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/guides/export-v2) documentation.

I hope that helps!
