### ISSUE TITLE
Missing data source for management zone v2

### ISSUE THREAD

**Issue by alsofr** [dynatrace-oss/terraform-provider-dynatrace#405]
**Is your feature request related to a problem? Please describe.**

I'm assigning a management zone by name to my metrics. Internally this get mapped to a management zone id, the consequence of which is that every time we run the terraform pipeline, there is some change to apply to map back to a management zone name.

The solution would be to use the data source and then reference the id of the zone in the metrics resource.
The `data source` only exists for the old management zones, which require a different token scope called `ReadConfig` (I'm guessing it's the old scope, the one I normally use is `settings.read`).

**Describe the solution you'd like**
The management zone v2 has a `resource` but no `data source`. Would it be possible to add this data source so we don't need two different scopes to handle management zones?

**Describe alternatives you've considered**
Add double scope (both ReadConfig and read.config)

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @alsofr,

Can you provide an example for what you're applying?
Off the top of my head, when reading "assigning a management zone to a metric" I was thinking about `dynatrace_calculated_service_metric`. I just cannot reproduce any non-empty plans using that resource.

thanks,
Reinhard

**Comment by alsofr** [comment]
HI @Dynatrace-Reinhard-Pilz , sure here is an example

```
resource "dynatrace_metric_events" "response_time" {
  for_each                   = var.enabled_features.metric_events ? toset(var.services) : []
  enabled                    = true
  event_entity_dimension_key = "dt.entity.service"
  summary                    = "[${var.team_name}] A metric event that checks response times for service ${each.key}"
  event_template {
    description = "[${var.team_name}] Response time is increasing for service ${each.key}"
    davis_merge = true
    event_type  = "SLOWDOWN"
    title       = "[${var.team_name}] Response time is increasing for service ${each.key}"
  }
  model_properties {
    type               = "STATIC_THRESHOLD"
    alert_condition    = "ABOVE"
    alert_on_no_data   = false
    dealerting_samples = 3
    samples            = 5
    violating_samples  = 3
    threshold = 300
  }
  query_definition {
    type            = "METRIC_SELECTOR"
    metric_selector = "builtin:service.request.response_time_service_aggregation:filter(in(\"dt.entity.service\",entitySelector(\"type(service),entityName.equals(${each.value})\"))):splitBy(\"dt.entity.service\"):percentile(95.0)"
    management_zone = var.management_zone
  }
}
```

This gets reapplied every time I run the terraform pipeline 

```
      ~ query_definition {
          ~ management_zone = "12312312321321" -> "My management zone"
            # (3 unchanged attributes hidden)
        }
```

Which is why I would like to use this instead
```
data "management_zone_v2" "management_zone" {
  name = "My management zone"
}
...
resource "dynatrace_metric_events" "response_time" {
  ...
      management_zone = data.management_zone_v2.management_zone.id
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @alsofr,

If I'm not mistaken the existing datasource [dynatrace_management_zone](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/management_zone) is all you need.

Take a look at the example below.

```hcl
data "dynatrace_management_zone" "my_management_zone" {
  name = var.management_zone
}

resource "dynatrace_metric_events" "response_time" {
  for_each                   = var.enabled_features.metric_events ? toset(var.services) : []
  enabled                    = true
  event_entity_dimension_key = "dt.entity.service"
  summary                    = "[${var.team_name}] A metric event that checks response times for service ${each.key}"
  event_template {
    description = "[${var.team_name}] Response time is increasing for service ${each.key}"
    davis_merge = true
    event_type  = "SLOWDOWN"
    title       = "[${var.team_name}] Response time is increasing for service ${each.key}"
  }
  model_properties {
    type               = "STATIC_THRESHOLD"
    alert_condition    = "ABOVE"
    alert_on_no_data   = false
    dealerting_samples = 3
    samples            = 5
    violating_samples  = 3
    threshold          = 300
  }
  query_definition {
    type            = "METRIC_SELECTOR"
    metric_selector = "builtin:service.request.response_time_service_aggregation:filter(in(\"dt.entity.service\",entitySelector(\"type(service),entityName.equals(${each.value})\"))):splitBy(\"dt.entity.service\"):percentile(95.0)"
    management_zone = data.dynatrace_management_zone.my_management_zone.legacy_id
  }
}
```

For the next release of the provider I updated the documentation for the attribute `management_zone`. I guess he current documentation for that attribute
```
management_zone (String) Management zone
```
leaves plenty of room for confusion.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Just drop a comment in case you have further question and we will re-open this ticket.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
You're correct, your API Token requires the permission `Read Configuration (ReadConfig)` for the data source `dynatrace_management_zone`.

The reason for that is related with this attribute `legacy_id`. It's a bit complicated to explain, but the data source is required to reach out to the Config V1 REST API in order correctly resolve that ID. Management Zones (and a couple of other resources) are available via Config V1 REST API and via Settings 2.0 REST API. To make matters even worse, other resources sometimes refer to management zones via the ID as known by Config V1 and sometimes refer to them as known by Settings 2.0. These IDs are however different.
That's essentially the origin of the attribute `legacy_id` - and it requires the Terraform Provider sometimes to take a couple of detours.

We're regularly  revisiting our data sources as soon as the need for that `legacy_id` doesn't exist anymore. For Management Zones it's unfortunately not the case yet.

Makes sense?

**Comment by alsofr** [comment]
Thanks for the explanation. It's a bit unfortunate.

Is your proposal still to update the document to explain that the legacy_id should be provided when defining a metric event?

`management_zone = data.dynatrace_management_zone.my_management_zone.legacy_id`

What is confusing here is that it also accepts a management zone name, which is how I create the metric.

And since you are trying to get rid of the legacy id, maybe it makes sense that the API returns the Management zone name instead of the legacy id, that would actually solve my problem since there wouldn't be a difference anymore between the stored terraform state and what the API returns.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @alsofr,

I just verified things, you should be good with using `data.dynatrace_management_zone.my_management_zone.id` with the current data source.

But I also have additional news. The upcoming release of the provider will introduced the data source `dynatrace_management_zone_v2` (essentially what you were asking for). That one will only require `settings.read` as the scope for the API Token - the data source is using the Settings 2.0 API.
When using that new data source you WILL however have to use ``data.dynatrace_management_zone.my_management_zone.legacy_id`.

**Comment by alsofr** [comment]
Looking forward to the new release then! Do you have an approximate release date yet by any chance?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
We usually push out releases every Thursday. Sometimes we skip a week or two because we've found some show stoppers. Not the case this week so far, so you can expect to use the new data source by the end of the week.
