### ISSUE TITLE
Terraform unable to apply update boolean settings for dynatrace resource (dynatrace_k8s_cluster_anomalies) 

### ISSUE THREAD

**Issue by nkalvakuntla** [dynatrace-oss/terraform-provider-dynatrace#406]
resource "dynatrace_k8s_cluster_anomalies" "eks-cluster" {
  scope = var.dynatrace_cluster_id
   
  cpu_requests_saturation {
    enabled = var.cpu_requests_saturation_enabled
    configuration {
      observation_period_in_minutes = var.cpu_requests_saturation_observation_period 
      sample_period_in_minutes      = var.cpu_requests_saturation_sample_period 
      threshold                     = var.cpu_requests_saturation_threshold 
    } 
  }

  memory_requests_saturation {
    enabled = var.memory_requests_saturation_enabled
    configuration {
      observation_period_in_minutes = var.memory_requests_saturation_observation_period
      sample_period_in_minutes      = var.memory_requests_saturation_sample_period
      threshold                     = var.memory_requests_saturation_threshold
    } 
  }

  monitoring_issues {
    enabled = var.monitoring_issues_enabled
    configuration {
      observation_period_in_minutes = var.monitoring_issues_observation_period
      sample_period_in_minutes      = var.monitoring_issues_sample_period
    } 
  }

  pods_saturation {
    enabled = var.pods_saturation_enabled
    configuration {
      observation_period_in_minutes = var.pods_saturation_observation_period
      sample_period_in_minutes      = var.pods_saturation_sample_period
      threshold                     = var.pods_saturation_threshold
    } 
  }

  readiness_issues {
    enabled = var.readiness_issues_enabled
    configuration {
      observation_period_in_minutes = var.readiness_issues_observation_period
      sample_period_in_minutes      = var.readiness_issues_sample_period
    } 
  }
}
When applying these settings , get the below error.
Plan: 1 to add, 0 to change, 0 to destroy.
module.dynatrace_k8s_cluster_anomalies.dynatrace_k8s_cluster_anomalies.le1: Creating...
╷
│ Error: Given property 'configuration' should not be set as it does not satisfy the following precondition: enabled = 'true'
│ Given property 'configuration' should not be set as it does not satisfy the following precondition: enabled = 'true'
│ Given property 'configuration' should not be set as it does not satisfy the following precondition: enabled = 'true'
│ 
│   with module.dynatrace_k8s_cluster_anomalies.dynatrace_k8s_cluster_anomalies.le1,
│   on modules/cluster-readiness/main.tf line 13, in resource "dynatrace_k8s_cluster_anomalies" "le1":
│   13: resource "dynatrace_k8s_cluster_anomalies" "le1" {
│ 
╵

**Comment by kishikawa12** [comment]
Hi @nkalvakuntla,

As the error message mentions, the `configuration` block must be omitted if the block is set to `enabled=false`. You should be able to make this work by utilizing [dynamic blocks](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks), I've included a working example below. 

I hope that helps!

```
resource "dynatrace_k8s_cluster_anomalies" "eks-cluster" {
  scope = var.dynatrace_cluster_id

  cpu_requests_saturation {
    enabled = var.cpu_requests_saturation_enabled
    dynamic "configuration" {
      for_each = var.cpu_requests_saturation_enabled == false ? [] : [1]
      content {
        observation_period_in_minutes = var.cpu_requests_saturation_observation_period
        sample_period_in_minutes      = var.cpu_requests_saturation_sample_period
        threshold                     = var.cpu_requests_saturation_threshold
      }
    }
  }

  memory_requests_saturation {
    enabled = var.memory_requests_saturation_enabled
    dynamic "configuration" {
      for_each = var.memory_requests_saturation_enabled == false ? [] : [1]
      content {
        observation_period_in_minutes = var.memory_requests_saturation_observation_period
        sample_period_in_minutes      = var.memory_requests_saturation_sample_period
        threshold                     = var.memory_requests_saturation_threshold
      }
    }
  }

  monitoring_issues {
    enabled = var.monitoring_issues_enabled
    dynamic "configuration" {
      for_each = var.monitoring_issues_enabled == false ? [] : [1]
      content {
        observation_period_in_minutes = var.monitoring_issues_observation_period
        sample_period_in_minutes      = var.monitoring_issues_sample_period
      }
    }
  }

  pods_saturation {
    enabled = var.pods_saturation_enabled
    dynamic "configuration" {
      for_each = var.pods_saturation_enabled == false ? [] : [1]
      content {
        observation_period_in_minutes = var.pods_saturation_observation_period
        sample_period_in_minutes      = var.pods_saturation_sample_period
        threshold                     = var.pods_saturation_threshold
      }
    }
  }

  readiness_issues {
    enabled = var.readiness_issues_enabled
    dynamic "configuration" {
      for_each = var.readiness_issues_enabled == false ? [] : [1]
      content {
        observation_period_in_minutes = var.readiness_issues_observation_period
        sample_period_in_minutes      = var.readiness_issues_sample_period
      }
    }
  }
}
```

**Comment by nkalvakuntla** [comment]
Thanks @kishikawa12 , I did realize that after reporting the issue here. Really appreciate your time on this.
