### ISSUE TITLE
`dynatrace_web_application.meta_data_capture_settings.capture` seems to not allow multiple values

### ISSUE THREAD

**Issue by ketan-mck** [dynatrace-oss/terraform-provider-dynatrace#408]
**Describe the bug**

I have a webapplication that I'm defining as follows:

```terraform
resource "dynatrace_web_application" "web_application" {
  ...
  meta_data_capture_settings {
    capture {
      name              = "VisitTag0"
      type              = "META_TAG"
      capturing_name    = "user-email"
      # public_metadata = false
      unique_id         = 1
      # use_last_value  = false
    }
    capture {
      name              = "VisitTag0"
      type              = "META_TAG"
      capturing_name    = "solution-name"
      # public_metadata = false
      unique_id         = 2
      # use_last_value  = false
    }
  }
 ...
}

```
Upon doing a terraform apply. Terraform always says that it will create the second `meta_data_capture_settings.capture` option that is specified. However, looking at the UI, only the first capture setting is visible.

```
  # module.t0105_qa.dynatrace_web_application.web_application will be updated in-place
  ~ resource "dynatrace_web_application" "web_application" {
        id                                   = "APPLICATION-....."
        name                                 = "..."
        # (5 unchanged attributes hidden)

      ~ meta_data_capture_settings {
          + capture {
              + capturing_name = "solution-name"
              + name           = "VisitTag0"
              + type           = "META_TAG"
              + unique_id      = 2
            }

            # (1 unchanged block hidden)
        }

        # (9 unchanged blocks hidden)
    }
```

**Expected behavior**
I would expect that dynatrace provider creates 2 metadata tag options. However only one option is created.

**Screenshots**

<img width="902" alt="image" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/156782991/2329b4d1-c2de-4b99-9ea1-c857005a6389">

**Desktop (please complete the following information):**
- terraform version `v1.6.2`
- dynatrace provider version - `v1.50.0`
- OS - macos 14.3.1 (Sonoma)

**Comment by kishikawa12** [comment]
Hi @ketan-mck,

Thank you for reaching out. In order for the metadata capture to work for user tags, there's two pieces of configuration that need to be present. The `meta_data_capture_settings` that you provided is one, and the other is the reference to be used as user tags in the `user_tags` block. Are you able to verify that you see both sets defined? The key is to also validate that the IDs reference (eg. 1, 2, etc) match as well. Example below..

```
resource "dynatrace_web_application" "Example" {
  ...
  meta_data_capture_settings {
    capture {
      name              = "VisitTag1"
      type              = "META_TAG"
      capturing_name    = "TerraformTest1"
      unique_id         = 1
    }
    capture {
      name              = "VisitTag0"
      type              = "META_TAG"
      capturing_name    = "TerraformTest2"
      unique_id         = 2
    }
  ...
  user_tags {
    tag {
      metadata_id   = 1
    }
    tag {
      metadata_id   = 2
    }
  ...
}
```

**Comment by ketan-mck** [comment]
This works. The documentation could probably use this hint somewhere. But I'll mark this issue closed for now.
