### ISSUE TITLE
Determine whether Data Source `dynatrace_management_zone` still needs to query Config V1

### ISSUE THREAD

**Issue by Dynatrace-Reinhard-Pilz** [dynatrace-oss/terraform-provider-dynatrace#411]
The Data Source `dynatrace_management_zone` currently queries the Config V1 REST API in order to have the `legacy_id` available.
We may be able to replace that by decoding the Settings 2.0 ID.

Benefit: API token wouldn't require the scope `ReadConfig` anymore.

**Comment by kishikawa12** [comment]
Resolved with commit e50de5c
