### ISSUE TITLE
Migrate Settings 2.0 Resources to use the server side `repairInput` feature

### ISSUE THREAD

**Issue by Dynatrace-Reinhard-Pilz** [dynatrace-oss/terraform-provider-dynatrace#412]
* Repairing Input (i.e. omitting unrecognized attributes) is currently done by the Terraform Provider.
* The feature should now be available on all clusters server side

**Comment by kishikawa12** [comment]
Release [v1.54.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.54.0) includes the `repairInput` lenient validation feature for Settings 2.0 resources. This enhancement is mainly for maintaining schemas and backwards compatibility for older clusters. This is mostly a backend/silent functionality but it will serve the two functions below.
- Omit unrecognized attributes
- Assign default values for missing required attributes
