### ISSUE TITLE
The order of various settings cannot get defined

### ISSUE THREAD

**Issue by Dynatrace-Reinhard-Pilz** [dynatrace-oss/terraform-provider-dynatrace#417]
**Describe the bug**
The Settings 2.0 API offers for various schemas (e.g. `dynatrace_log_processing`) the ability to also define their order. The resources offered by the Terraform Provider don't offer any counterpart.

**Solution**
Resources where the underlying schema in Dynatrace allows for defining an order will get an additional attribute `insert_after`. That feature enables users to define the order exactly in the same fashion as the Settings 2.0 API.

```hcl
resource "dynatrace_log_processing" "rule-a" {
  ...
}
resource "dynatrace_log_processing" "rule-b" {
  insert_after = dynatrace_log_processing.rule-a.id
  ...
}
resource "dynatrace_log_processing" "rule-c" {
  insert_after = dynatrace_log_processing.rule-c.id
  ...
}
```
As an alternative an additional resource `dynatrace_settings_order` allows for defining the order for previously defined resource instances at once.
```hcl
resource "dynatrace_log_processing" "rule-a" {
  ...
}
resource "dynatrace_log_processing" "rule-b" {
  ...
}
resource "dynatrace_log_processing" "rule-c" {
  ...
}
resource "dynatrace_settings_order" "log-processing-order" {
  order = [
    dynatrace_log_processing.rule-a.id,
    dynatrace_log_processing.rule-b.id,
    dynatrace_log_processing.rule-c.id
  ]
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Starting with Release v1.53.0 the resource `dynatrace_log_processing` offers the attribute `insert_after` as described above.

We're keeping this ticket open until all resources, that depend on schemas that are eligible for ordering, will have been enriched with the `insert_after` attribute.

**Comment by seanare** [comment]
Fantastic, thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
We have decided to put the resource `dynatrace_settings_order` on hold until further notice. Implementing ordering that way would introduce various ways for contradictory behavior.

With the upcoming release all currently supported resources that are are able to get ordered will however contain the `insert_after` attribute. If not specified the behavior doesn't change from how it's handled currently - the setting will get appended to the end.
