### ISSUE TITLE
Export utility runtime error on macOS

### ISSUE THREAD

**Issue by pzi** [dynatrace-oss/terraform-provider-dynatrace#426]
**Describe the bug**
Unable to use the export utility on macOS due to runtime error in Go. 

**To Reproduce**
1. Try to run the export utility on macOS

**Expected behavior**
The export happening without error. Works on a Windows environment.

**Desktop:**
 - OS: macOS Ventura 13.6.4
 - PowerShell version 7.4.1
 - Provider version 1.53.0

**Additional context**

When running the same PowerShell script on Windows it's fine. Even if we don't use the PowerShell script and directly call the path  it's calling below, it results in the same error. The PowerShell script purely cobbles together the right path for the plugin to be called based on the OS architecture (windows amd/386 or macos).

```PowerShell
PS /dynatrace-product-configuration/tf> ../scripts/Export-Utility.ps1

Calling /dynatrace-product-configuration/tf/.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.53.0\darwin_amd64\terraform-provider-dynatrace_v1.53.0 -export

Post-Processing Resources ...
Post-Processing Resources - Group child configs with parent configs ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x968da8a]

goroutine 1 [running]:
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export.(*Environment).GetChildResources(...)
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export/environment.go:512
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export.(*Environment).PostProcess(0xc000367e00)
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export/environment.go:385 +0x4ca
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export.(*Environment).Export(0xc000367e00)
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export/environment.go:112 +0x36
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace.runExport()
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export.go:56 +0x5e
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace.Export({0xc00003e040?, 0xc00031ff40?, 0x8d4ee0b?})
	github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export.go:37 +0x6f
main.main()
	github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:110 +0x65
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @pzi,

I've committed a change for the next release that prevents the segmentation fault from happening. But that change just ensures that the export functionality doesn't crash.

Looking at the output you have provided it is pretty clear that no resources of any kind could get exported. That's likely a problem with the credentials you're using.

I am locally able to reproduce the segmentation fault in these situations:
* Specifying an invalid API Token (`DYNATRACE_API_TOKEN`/`DT_API_TOKEN`)
  * The API Token indeed needs to be *invalid*. An API Token that just lacks the proper scopes won't crash the export
* Specifying a malformed URL for the environment (`DYNATRACE_ENV_URL` / `DT_ENV_URL`)
  * example:`https:/#####.live.dynatrace.com`
  * example: `https:/<servername>/e/f98486c8-76ff-47de-9e4f-252b70b81fbd/`
* Specifying an invalid URL for the environment (`DYNATRACE_ENV_URL` / `DT_ENV_URL`)
  * for instance `https://doesnotexist.live.dynatrace.com`
  * example: `https:/<servername>/e/<nonexistentenvironmentid>/`

Could you please re-check the credentials you have set on MacOS?

**Comment by pzi** [comment]
Hi @Dynatrace-Reinhard-Pilz, you were correct, I had an invalid API token.

It now works as expected and I am glad it also won't segfault any longer once your patch has been applied :)
