### ISSUE TITLE
Unable to update mobile_application

### ISSUE THREAD

**Issue by smc87** [dynatrace-oss/terraform-provider-dynatrace#429]
**Describe the bug**
Using the exported terraform from the provider for a mobile_application results in the error:

Error: status code 400 (expected: [204]): {"code":400,"message":"Constraints violated!","constraintViolations":[{"path":"optInModeEnabled","message":"Payload does not include all required properties!","parameterLocation":"PAYLOAD_BODY","location":null}]}

**To Reproduce**
1. export configuration for a mobile_application
2. Import this into your terraform
3. See error

Error: status code 400 (expected: [204]): {"code":400,"message":"Constraints violated!","constraintViolations":[{"path":"optInModeEnabled","message":"Payload does not include all required properties!","parameterLocation":"PAYLOAD_BODY","location":null}]}

**Expected behavior**
mobile_application config is created without issue

**Screenshots**
opt_in_mode and session replay are both set to false. 

![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/6291983/8e0bd961-d893-4dca-b2b6-758d79f68ae0)

**Additional context**
Using v1.54.1

**Comment by smc87** [comment]
`# ID MOBILE_APPLICATION-27378878D0D84DAE
resource "dynatrace_mobile_application" "MY_-_Android_APP" {
  name                    = "UMY - Android APP"
  application_id          = "27378878-d0d8-4dae-a7a7-59152f7ea09b"
  application_type        = "MOBILE_APPLICATION"
  beacon_endpoint_type    = "CLUSTER_ACTIVE_GATE"
  key_user_actions        = [ "Touch on Cancel", "Touch on Find", "Loading ModalActivity", "Touch on Sign in", "Loading HtmlActivity" ]
  opt_in_mode             = false
  session_replay          = false
  session_replay_on_crash = false
  user_session_percentage = 100
  apdex {
    frustrated          = 12000
    frustrated_on_error = true
    tolerable           = 3000
  }
  properties {
    api_value {
      name                            = "bundle_version"
      type                            = "STRING"
      aggregation                     = "LAST"
      # cleanup_rule                  = ""
      display_name                    = "bundle_version"
      key                             = "bundle_version"
      store_as_session_property       = true
      # store_as_user_action_property = false
    }
    api_value {
      name                            = "device_id"
      type                            = "STRING"
      aggregation                     = "LAST"
      # cleanup_rule                  = ""
      display_name                    = "device_id"
      key                             = "device_id"
      store_as_session_property       = true
      # store_as_user_action_property = false
    }
    api_value {
      name                          = "bucket"
      type                          = "STRING"
      aggregation                   = "LAST"
      # cleanup_rule                = ""
      display_name                  = "bucket"
      key                           = "bucket"
      store_as_session_property     = true
      store_as_user_action_property = true
    }
  }
}
`

**Comment by kishikawa12** [comment]
Hi @smc87,

Thank you for raising this issue, the fix will be included in the release planned for this week.
