### ISSUE TITLE
BUG: Download overwrites objects with same name

### ISSUE THREAD

**Issue by colinsidi** [dynatrace-oss/terraform-provider-dynatrace#43]
if objects of same type have the same name in dynatrace, then only one of them is written in the download process
ie: ./terraform-provider-dynatrace download https://xxx.live.dynatrace.com xxxx 

Name is not unique in dynatrace, so plugin executable should use either the object's id in the filename  or a counter.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Release v1.2.2 will contain a solution for this issue.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @colinsidi,

With release [v1.2.2](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.2.2) the resulting `.tf` files will include the unique ID within their names (where possible) in order to avoid overwriting resources with the same name and different unique IDs.
