### ISSUE TITLE
Add support for simulateReturnKey on browser monitor keystroke events

### ISSUE THREAD

**Issue by ifeedsheep** [dynatrace-oss/terraform-provider-dynatrace#430]
**Is your feature request related to a problem? Please describe.**
Keystroke synthetic events within Dynatrace's browser monitors can be configured to simulate the return key being pressed.  Currently, this setting can not be configured via Terraform.  It would be beneficial to be able to leverage this setting via Terraform.

**Describe the solution you'd like**
I would like to be able to configure the simulateReturnKey on keystroke events when building browser monitors.  The solution is to create and manage a simulate_return_key variable similar to how this project manages the simulate_blur_event (simulateBlurEvent) variable.

**Describe alternatives you've considered**

**Additional context**

Dynatrace setting:
"simulateBlurEvent": true,
Simulates pressing the 'Return' key after simulating other keystrokes. For example, to submit a form or trigger a login.

KeyStroke documentation:
https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/browser_monitor#nested-schema-for-scripteventseventkeystrokes

References to "simulate_blur_event":
https://github.com/search?q=repo%3Adynatrace-oss%2Fterraform-provider-dynatrace%20simulate_blur_event&type=code

References to "simulateBlurEvent":
https://github.com/search?q=repo%3Adynatrace-oss%2Fterraform-provider-dynatrace+simulateBlurEvent&type=code

**Comment by kishikawa12** [comment]
Hi @ifeedsheep,

Thank you for the feedback, the field was indeed missing in the schema. The fix to define `simulate_return_key` will be included in the next release.

Thanks!
