### ISSUE TITLE
"terraform plan" shows that "scope" parameter of dynatrace_credentials resource will be deleted

### ISSUE THREAD

**Issue by listomin** [dynatrace-oss/terraform-provider-dynatrace#431]
**Describe the bug**
When we create a [dynatrace_credentials](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/1.54.2/docs/resources/credentials) resource, we should specify "scopes" parameter instead of "scope". For example:
```
resource "dynatrace_credentials" "cred" {
  name              = "my_cred"
  owner_access_only = true
  # scope             = "SYNTHETIC"
  scopes            = ["SYNTHETIC"]
  username          = "user"
  password          = "password"
}
```
If we apply the resource, it'll be created just fine, but if we'll perform "terraform plan" command next time (even without any changes in terraform code), we'll see
```
  # dynatrace_credentials.cred will be updated in-place
  ~ resource "dynatrace_credentials" "cred" {
        id                         = "CREDENTIALS_VAULT-<removed>"
        name                       = "my_cred"
      - scope                      = "SYNTHETIC" -> null
        # (5 unchanged attributes hidden)
    }
```
Also could you please actualize ["Resource Example Usage" paragraph](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/1.54.2/docs/resources/credentials#resource-example-usage) of the resource documentation page? There is still "scope" parameter of the resource instead of "scopes".
**To Reproduce**
1. create dynatrace_credentials resource using "terraform apply"
2. Perform "terraform plan" right after that
3. See the planned changes

**Expected behavior**
There shouldn't be any planned changes

**Desktop (please complete the following information):**
 - Ubuntu 22.04.4
 - Terraform v1.7.4
 - dynatrace-oss/dynatrace v1.54.2

**Additional context**
The latest version of Dynatrace terraform provider which uses "scope" parameter only is 1.47.3, but with this version we hit a dynatrace_webhook_notification resource issue:
```
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.webhook_notification.dynatrace_webhook_notification.somewebhookintegration to
│ include new values learned so far during apply, provider "registry.terraform.io/dynatrace-oss/dynatrace" produced
│ an invalid new value for .headers[0].header: planned set element
│ cty.ObjectVal(map[string]cty.Value{"name":cty.NullVal(cty.String), "secret_value":cty.NullVal(cty.String),
│ "value":cty.StringVal("")}) does not correlate with any element in actual.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
Releasing state lock. This may take a few moments...
```
dynatrace_webhook_notification.somewebhookintegration resource description:
```
resource "dynatrace_webhook_notification" "somewebhookintegration" {
  name                   = "somewebhookintegration"
  active                 = true
  # insecure             = false
  notify_closed_problems = true
  notify_event_merges    = false
  payload                =<<-EOT
    {
        "ImpactedEntity": "{ImpactedEntity}",
        "PID": "{PID}",
        "ProblemDetails": "{ProblemDetailsText}",
        "ProblemDetailsJSON": {ProblemDetailsJSON},
        "ProblemID": "{ProblemID}",
        "ProblemImpact": "{ProblemImpact}",
        "ProblemSeverity": "{ProblemSeverity}",
        "ProblemTitle": "{ProblemTitle}",
        "ProblemURL": "{ProblemURL}",
        "State": "{State}",
        "Tags": "{Tags}",
        "Status":"{State}",
        "Check":"{ProblemTitle}",
        "host":"{ImpactedEntity}"
    }
  EOT
  profile                = var.alerting_profile_id
  url                    = "https://somewebhookintegration.example"
  # url_contains_secret  = false
  headers {
    header {
      name         = "x-app-key"
      secret_value = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)["somewebhookintegration"]
    }
    header {
      name         = "x-auth-token"
      secret_value = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)["somewebhookintegration"]
    }
  }
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @listomin,

Thanks for reporting this issue. The next release won't create any non-empty plans if you specify `scopes`.

Where I'm unsure about is your second issue with `dynatrace_webhook_notification`.
I don't really have access to `aws_secretsmanager_secret_version`, so I was hoping to recreate the behavior by applying a value that changes every time. No luck, unfortunately.
Do you have any additional information about the behavior of `aws_secretsmanager_secret_version`?

**Comment by listomin** [comment]
It's not clear from the description that the second issue occurs during non-first "terraform apply" execution. Also, please note that I see this behavior with old 1.47.3 version of the provider. But I don't think it makes a lot of sense to spend your time on the second issue.
For now we'll use the newest version (1.54.2) despite the "scope" issue. Could you please share the plans for the next release? When would we expect it?
And thanks for the response, Reinhard!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
We're usually pushing out releases on Thursdays - so you can expect your fix to be available on April 11.

Thanks for the clarification about the second issue. Should that one re-emerge somehow, let's handle that in a separate GitHub issue.
