### ISSUE TITLE
Dashboards & Dashboard Presets timing issue

### ISSUE THREAD

**Issue by Dynatrace-Reinhard-Pilz** [dynatrace-oss/terraform-provider-dynatrace#435]
Applying the resource `dynatrace_dashboards_presets` immediately after a `dynatrace_json_dashboard` has been created frequently fails.
It looks like it takes a while until newly created Dashboards are ready to get referenced.

Planned solution: CREATE of `dynatrace_json_dashboard` should wait until attempts to define `dynatrace_dashboards_presets` reliably are getting accepted by the REST API. It's likely not enough to wait for just ONE attempt to be successful - these kinds of timing issues are very often related to cluster nodes not having received the update.

**Comment by kishikawa12** [comment]
Possible solution: Similar to mgmz fix in #437, run a _validate_ call against a generic `dynatrace_dashboards_presets`  of the newly created dashboard until it returns successful. Permissions would be different, so if the token doesn't have permissions the additional validation wouldn't be present.
