### ISSUE TITLE
`dynatrace_json_dashboard` export issues

### ISSUE THREAD

**Issue by kishikawa12** [dynatrace-oss/terraform-provider-dynatrace#444]
**UPDATED**
- **Resolved:** ~~Fix export runtime error `-export -id dynatrace_json_dashboard=XXXXX`~~
- **Resolved:** ~~`-ref` "light" as default behavior for no `-ref` - all three resources in a single file, no references to other resources. This should also address the hard coded `link_id` issue which is currently overwriting existing dashboards.~~
- **Resolved:** ~~Rewrite `json_dashboard_base` to `json_dashboard` internally, folder name to `json_dashboard`~~
- **Resolved:** ~~Remove `content` and `lifecycle` block, create generic template and handle with DiffSuppress~~
- **Resolved:** ~~Generate `json_dashboard_base` only if links from other dashboards exist~~
- **Resolved:** ~~Order dashboard resources in files - `json_dashboard` ->  `dashboard_sharing` -> `json_dashboard_base`~~

- Introduce/Improve documentation around `dynatrace_json_dashboard_base` with the improvements above

**Comment by kishikawa12** [comment]
**Remaining Items**
- Generate `json_dashboard_base` only if links from other dashboards exist
- Order dashboard resources in files - `json_dashboard` ->  `dashboard_sharing` -> `json_dashboard_base`
- Introduce/Improve documentation around `dynatrace_json_dashboard_base` with the improvements above

**Comment by caleb-long-vad2r4** [comment]
@kishikawa12 Does the dynatrace_json_dashboard object only work for creating what Dynatrace now calls "Dashboard Classic" dashboards, or will this resource also work for creating dashboards for the new DQL centered app?

**Comment by kishikawa12** [comment]
Hi @caleb-long-vad2r4,

The `dynatrace_json_dashboard` resource is to manage `Dashboards Classic` dashboards.

To manage dashboards under the new Grail platform, please utilize the [dynatrace_document](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/document) resource. Note that this resource has limitations due to the API - currently it only supports managing your own documents, the resources will be updated once additional functionality is available.

I hope that helps!

**Comment by caleb-long-vad2r4** [comment]
Thanks so much!

**Comment by caleb-long-vad2r4** [comment]
Hey @kishikawa12, as a follow up to this question... there seems to be some issues deploying resources with DQL in them to Dynatrace from a Terraform perspective. Not only with the resource we were discussing here, but also when deploying a Workflow using the associated Terraform resource. One of our contacts from within Dynatrace said that DQL was not supported within Terraform yet. Is there a timeline as to when DQL will be supported?

**Comment by kishikawa12** [comment]
Hi @caleb-long-vad2r4,
Terraform resources utilizing DQL should work as expected (documents, workflows, etc). If you encounter any issues please let us know by creating a new GitHub issue.
Thanks!
