### ISSUE TITLE
Problems tile in dashboard giving "no permissions" error when adding a custom management zone filter

### ISSUE THREAD

**Issue by saadrafique768** [dynatrace-oss/terraform-provider-dynatrace#451]
**Describe the bug**
I used the dynatrace json dashboard resource https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/json_dashboard and the problems tile was filtered for a custom management zone. This gives error due to "no permissions" when deployed.

<img width="990" alt="image" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/115777728/61b7e418-2727-4359-9e72-26e2dcc0a927">

however, I was able to create the same problems tile with custom management zone filter in the same environment without error without using terraform. So it makes me wonder if its due to terraform here.
<img width="990" alt="image" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/115777728/61ee04a5-4f4f-486d-bbec-56a7a4c83495">

**To Reproduce**
1. use https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/json_dashboard to make a dashboard with a problems tile filtered for a management zone.
2. once changes are deployed, it gives error "no permissions" next to management zone
3. below is the json snippet of the tile in terraform 
```hcl
"tiles": [
      {
        "bounds": {
          "height": 152,
          "left": 38,
          "top": 646,
          "width": 266
        },
        "configured": true,
        "name": "Problems (open/all)",
        "tileFilter": {
          "managementZone": {
            "id": "8549387243402376494",
            "name": "team-hawaiian-pizza"
          }
        },
        "tileType": "OPEN_PROBLEMS"
      },
```
**Expected behavior**
There should not be any error on problems tile and i should be able to apply management zone filter on problems tile.

**Screenshots**
all samples attached

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @saadrafique768,

Could you run this snippet here for me?

```hcl
data "dynatrace_management_zone_v2" "team-hawaiian-pizza" {
  name = "team-hawaiian-pizza"
}

output "team-hawaiian-pizza" {
  value = data.dynatrace_management_zone_v2.team-hawaiian-pizza.legacy_id
}
```
Is the output *indeed* saying that `team-hawaiian-pizza` has the ID `8549387243402376494`? Or is it a different ID?
```
Changes to Outputs:
  + team-hawaiian-pizza = "8549387243402376494"
```

**Comment by saadrafique768** [comment]
Yup, they are indeed returning output that matches its corresponding management zone id. Just copy pasting my output result below.

```
Changes to Outputs:
  + team-hawaiian-pizza                 = "8549387243402376494"
```
  
  I also want to give you my local setup info if it helps. I am locally run provider version 1.56.1 and i just added the snippet you shared with me to one of the dynatrace management zone terraform files.

**Comment by saadrafique768** [comment]
any update on this @Dynatrace-Reinhard-Pilz ?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Apologies @saadrafique768, for some reason I didn't notice your response - hence my focus was on other topics.
I'm a bit out of ideas on that issue at the moment. Would you be able to spend 30 minutes on a Zoom call together with me, so we can look at your exact configuration (especially user permissions) together? I've tried out quite a lot of combinations, reduced permissions of a test user drastically, but never got results like the ones you've described.

How about Thursday or Friday? I'm located in Central European Time Zone, therefore a call not too late in the afternoon would be preferrable.

**Comment by saadrafique768** [comment]
No problem @Dynatrace-Reinhard-Pilz , I sent an invite for a teams meeting at 12 pm Central European time. You can suggest alternate times too and I am pretty much free for the rest of day on Thursday (Central European time). Please let me know if there is anything I should do as a prep for this meeting.

 Another point, we are using dynatrace_management_zone (deprecated) instead of v2. Would that cause any issues?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Perfect. See you on the call on Thursday!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Quick summary of our call today:

We've noticed that the Dashboard in question, when exported via WebUI, doesn't contain a tile filter for the Problems Tile at all

Next Steps:
Saadra will configure the CI/CD pipeline so it adds the environment variables  
```
export DYNATRACE_DEBUG=true
export DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
export DYNATRACE_HTTP_RESPONSE=true
```
That will produce a log file `terraform-provider-dynatrace.http.log` with all the HTTP traffic between Terraform and the Dynatrace environment.

Purpose of that log file: We need to get clarification about whether the payload (JSON) sent to Dynatrace still contains the tile filter. If it does, it means that the REST API somehow filters out that tile filter.

In case the payload still DOES contain the tile filter, the next step will be to execute the same POST request using Postman. That's essentially a sanity check. If Terraform isn't involved at all, we can take that exact payload and reach out to Dynatrace R&D for clarification.

@saadrafique768 , if possible, please send me the full contents of that one Dashboard we were working with. We've seen that a reduced down version of that Dashboard *does* work when run against your dev environment. I'd like to build a full blown example locally - perhaps the issue IS reproducible as soon as the full dashboard contents is being used. Feel free to send that .tf file to terraform@dynatrace.com - no need to share that information on GitHub.

**Comment by saadrafique768** [comment]
I ran the cases and here is the outcome:
1 - in the effected env (avg90371), running terraform apply with all necessary environment variables for logging/debugging shows that tile filter indeed includes management zone filter in the POST request to "api/config/v1/dashboards" - > 

`"tileFilter":{"managementZone":{"id":"8549387243402376494","name":"team-hawaiian-pizza"}}
`
Interestingly, my observation is that in that same http.log file there is also a get request for dashboards including the one we just created and the tile filter in it is actually blank. It indicates that the post request is sending correct filtering but changes aren't reflecting as intended after that POST call. Below is the get request and its response showing tile filter value :

`2024/05/17 16:13:01 200 OK {"metadata":{"configurationVersions":[7],"clusterVersion":"1.291.99.20240515-061005"},"id":"342ba10f-7b4a-4bc3-8bb2-c92ae5e309c1","dashboardMetadata":{"name":"test_debug_dashboard","shared":true,"owner":"srafique@kitopi.com","dashboardFilter":null,"preset":true,"tilesNameSize":null,"hasConsistentColors":false},"tiles":[{"name":"Problems (open/all)","nameSize":null,"tileType":"OPEN_PROBLEMS","configured":true,"bounds":{"top":646,"left":38,"width":266,"height":152},"tileFilter":{"timeframe":null,"managementZone":null},"isAutoRefreshDisabled":true,"problemSelector":null,"entitySelector":null,"useBackgroundColor":null},`

2 - I then made a POST request for creating the above dashboard contents without involving terraform. The outcome is same - >
- the tile has permissions error
- exporting the json shows tile filter is empty `"tileFilter": {}`

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @saadrafique768,

The GET request you're seeing is to be expected. After the Terraform Provider has sent settings to the REST API it automatically performs that GET request. The results coming back here are essentially what ends up within the state file. That's our normal workflow.

The results you've gotten confirm indeed that we're dealing with an issue of the REST API itself.
Would you mind sharing the URL of the Tenant you've executed the POST request to? Feel free to send to terraform@dynatrace.com. No need to share that on a public GitHub issue.
Second, could you execute that POST request once again and note down the time you've executed it?
I'm planning to reach out to Dynatrace R&D internally about that. The more information the better.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks Saad, I already have reached out internally to R&D about this. Need to ask for a bit more patience until we know a bit more.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @saadrafique768,

R&D came back with the response, that the observed behavior is usually to be expected when a Tile Filter refers to a Management Zone ID that doesn't exist.

* The payload of for the Dashboard is getting accepted by the REST API
* Within the WebUI the "no permissions" error will be shown
* When requesting the JSON code for the Dashboard any Management Zone Filters that refer to non-existent (according to the ID) Management Zones will get stripped out

R&D therefore validated the ID of `team-hawaiian-pizza` that's being used here. The ID is - at least currently - `-2617003449522831404`.
The value `8549387243402376494` must either be outdated (because `team-hawaiian-pizza` got deleted and re-created at some point) or must originate from a different environment.

Could you please once again run the snippet

```hcl
data "dynatrace_management_zone_v2" "team-hawaiian-pizza" {
  name = "team-hawaiian-pizza"
}

output "team-hawaiian-pizza" {
  value = data.dynatrace_management_zone_v2.team-hawaiian-pizza.legacy_id
}
```
against `https://avg90371.live.dynatrace.com` so we can validate that - at least for your Terraform workspace - the ID `8549387243402376494` is indeed what the Data Source resolves?

thanks,
Reinhard

**Comment by saadrafique768** [comment]
Hi @Dynatrace-Reinhard-Pilz 8549387243402376494 is for dev. In prod (https://avg90371.live.dynatrace.com) it resolves to below, which is matching Dynatrace R&D checks too - > 

```
Changes to Outputs:
  + team-hawaiian-pizza                 = "-2617003449522831404"
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Ok, then let's go one step farther:

When you're applying the Dashboard in PROD with the ID `-2617003449522831404` like this:

```
"tiles": [
      {
        "bounds": {
          "height": 152,
          "left": 38,
          "top": 646,
          "width": 266
        },
        "configured": true,
        "name": "Problems (open/all)",
        "tileFilter": {
          "managementZone": {
            "id": "-2617003449522831404",
            "name": "team-hawaiian-pizza"
          }
        },
        "tileType": "OPEN_PROBLEMS"
      },
```

Does it result in this weird "no permission" issue?

**Comment by saadrafique768** [comment]
actually, the problem is the id indeed ! looking at the payload sent to prod tenant, it is like below

```
2024/05/17 16:13:00 POST https://avg90371.live.dynatrace.com/api/config/v1/dashboards
    {"dashboardMetadata":{"name":"test_debug_dashboard","owner":"srafique@kitopi.com","preset":true,"shared":true},"tiles":[{"assignedEntities":[],"bounds":{"height":152,"left":38,"top":646,"width":266},"configured":true,"customName":"Problems (open/all)","isAutoRefreshDisabled":true,"name":"Problems (open/all)","queriesSettings":{"resolution":""},"query":"","tileFilter":{"managementZone":{"id":"8549387243402376494","name":"team-hawaiian-pizza"}},"tileType":"OPEN_PROBLEMS","type":"NOT_CONFIGURED","visualConfig":null,"visualizationConfig"
```

so the problem is that even in prod tenant, we are sending management zone id of dev environment. This is probably why it works fine in dev and not in prod. This is actually my fault in passing id directly because the management zone id differs by tenant. I used below:

```
"managementZone": {
            "id": dynatrace_management_zone.dev_teams_mgmnt_zone["hawaiian-pizza"].id,
            "name": "team-hawaiian-pizza"
          }
```
and now it works fine in all environments. Thank you for your time and help in this matter. Apologies for inconvenience !

**Comment by Dynatrace-Reinhard-Pilz** [comment]
No worries, I'm glad we finally were able to sort it out. And on the plus side, we are now aware of these symptoms. If another customer stumbles across the same issue, we won't have to start from scratch.
