### ISSUE TITLE
panic in dynatrace_autotag_rules

### ISSUE THREAD

**Issue by dguillencamara** [dynatrace-oss/terraform-provider-dynatrace#452]
**Describe the bug**
in terraform apply add rules with resource dynatrace_autotag_rules appears panic runtime error

terraform apply -auto-approve -no-color -var 'DYNATRACE_ENV_URL=***' -var 'DYNATRACE_API_TOKEN=***'
  shell: /usr/bin/bash -e {0}
  env:
    AWS_DEFAULT_REGION: eu-west-1
    AWS_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/[3](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:3)dd57d84-b683-411d-8465-a0a89b8aaed3
dynatrace_autotag_rules.grupo_soporte: Refreshing state... [id=133fbf3e-c191-[4](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:4)8f0-b242-e72cf8d40bdb]

Error: Plugin did not respond

  with dynatrace_autotag_rules.grupo_soporte,
  on tags.tf line 1, in resource "dynatrace_autotag_rules" "grupo_soporte":
   1: resource "dynatrace_autotag_rules" "grupo_soporte" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

Stack trace from the terraform-provider-dynatrace_v1.[5](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:5)6.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe80ae1]

goroutine 35 [running]:
github.com/dynatrace-oss/terraform-provider-dynatrace/resources/autotagrules.Update({0x177e2f8?, 0xc0007a8c90?}, 0xc000cbe180, {0x11381a0?, 0xc0002a02a0?})
	github.com/dynatrace-oss/terraform-provider-dynatrace/resources/autotagrules/resource.go:152 +0x8c1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000749500, {0x177e2f8, 0xc0007a8c90}, 0xc000cbe180, {0x11381a0, 0xc0002a02a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:812 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000749500, {0x177e2f8, 0xc0007a8c90}, 0xc0007[6](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:6)36c0, 0xc000332a00, {0x11381a0, 0xc0002a02a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0004[7](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:7)8258, {0x177e2f8?, 0xc0007a[8](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:8)bd0?}, 0xc00036aff0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xd5c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000116be0, {0x177e2f8?, 0xc0007a8210?}, 0xc000aab730)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:846 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x14f[9](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:9)3a0, 0xc000116be0}, {0x177e2f8, 0xc0007a82[10](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:10)}, 0xc0001f8800, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e4000, {0x177e2f8, 0xc0007a8150}, {0x1795520, 0xc000196340}, 0xc0008d6000, 0xc00075cc90, 0x2302078, 0x0)
	google.golang.org/grpc@v1.61.1/server.go:1385 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc0000e4000, {0x1795520, 0xc000196340}, 0xc0008d6000)
	google.golang.org/grpc@v1.61.1/server.go:1796 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.61.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine [12](https://github.com/enagas-dynatrace/enagas-configuration-application/actions/runs/8895820304/job/24427078596#step:12:13)
	google.golang.org/grpc@v1.61.1/server.go:1040 +0x125

Error: The terraform-provider-dynatrace_v1.56.1 plugin crashed!

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04.4 LTS
 - Image: ubuntu-22.04
  Version: 20240422.1.0

 node: v20.12.2
  npm: 10.5.0
  yarn: 1.22.22

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @dguillencamara,

Thanks for reporting this issue. Apparently we've kept a series of debug outputs in there that led to this panic.
This will be fixed with the upcoming release.
