### ISSUE TITLE
dynatrace_log_sensitive_data_masking (Resource) matcher ending with wrong attribute.

### ISSUE THREAD

**Issue by DylanYost** [dynatrace-oss/terraform-provider-dynatrace#453]
**Describe the bug**
When using terraform to create a dynatrace_log_sensitive_data_masking (Resource), the resource is created using the log source attribute regardless of the attribute specified (e.g. K8s_deployment_name).

**To Reproduce**
1. Create dynatrace_log_sensitive_data_masking (Resource) in terraform
2. specify the matcher attribute as anything other than log_source

**Expected behavior**
The expected behavior is having a dynatrace_log_sensitive_data_masking (Resource) rule using a K8s Deployment Name as the attribute instead of log source.

**Screenshots**
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/59847946/1391272e-f165-413c-acac-12388b7ec82b)
![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/59847946/8b9178ee-7118-4418-b0c5-1bdbb9f01f3e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @DylanYost,

The documentation for this resource is listing invalid values for matcher attributes. Apparently the REST API DOES accept any value here without complaining - it just falls back to `log.source` as a default value in such a case.
The docs will be updated with the upcoming release. Until then here's a list of valid matcher attributes for you:
* `container.name`
* `dt.entity.container_group`
* `dt.entity.process_group`
* `k8s.container.name`
* `k8s.deployment.name`
* `k8s.namespace.name`
* `log.source`
* `process.technology`
* `host.tag`
