### ISSUE TITLE
I am unable to add scope for "dynatrace custom anomalies" resource using metric selector.

### ISSUE THREAD

**Issue by karty-s** [dynatrace-oss/terraform-provider-dynatrace#456]
**Describe the bug**
Hi team,
I am trying to create dynatrace custom anomaly resource to create a velero backup failure alert using type metric selector. I am getting an error when i add the scope of management zone to alert since we need to create seperate alerts for resources in different management zones, but it is giving issue in terraform
**To Reproduce**
below is main.tf file that i use
```hcl
resource "dynatrace_custom_anomalies" "velero-sep-test" {

  name                  = "velero-iac-test-prod"
  description           = "VELERO FAILURE ALERT PROD \n Velero back up for the schedule {dims:schedule} failed for the cluster {dims:dt.entity.kubernetes_cluster.name}."
  metric_selector       = "velero_backup_failure_total.count:splitBy(\"dt.entity.kubernetes_cluster\"):sort(value(auto,descending))"
  enabled               = true
  primary_dimension_key = "dt.entity.kubernetes_cluster"
  severity              = "CUSTOM_ALERT"
  strategy {
    auto {
      alert_condition          = "ABOVE"
      alerting_on_missing_data = false
      dealerting_samples       = 2
      samples                  = 5
      signal_fluctuations      = 1
      violating_samples        = 1
    }
  }
}
```
and this is the error i am getting

Karthikeyan_Sekar@M-CTJ0Y4P2XM dt-testing-velero % terraform plan
```
│ Error: Conflicting configuration arguments
│ 
│   with dynatrace_custom_anomalies.velero-sep-test,
│   on main.tf line 1, in resource "dynatrace_custom_anomalies" "velero-sep-test":
│    1: resource "dynatrace_custom_anomalies" "velero-sep-test" {
│ 
│ "scopes": conflicts with metric_selector
│ Error: Conflicting configuration arguments
│ 
│   with dynatrace_custom_anomalies.velero-sep-test,
│   on main.tf line 4, in resource "dynatrace_custom_anomalies" "velero-sep-test":
│    4:   metric_selector       = "velero_backup_failure_total.count:splitBy(\"dt.entity.kubernetes_cluster\"):sort(value(auto,descending))"
│ 
│ "metric_selector": conflicts with scopes
╵
```

**Expected behavior**
Kindly help us on scoping the alert with the MZ

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @karty-s,

The limitation you've described originates in the REST API endpoint the Terraform Provider is using for the resource `dynatrace_custom_anomalies`. There's unfortunately nothing the Provider can do to overcome that.

But I believe you're not out of luck. The resource `dynatrace_custom_anomalies` is deprecated for a reason. Dynatrace meanwhile offers an alternative REST endpoint for configuring essentially the same kind of setting. In Terraform you just have to use the resource `dynatrace_metric_events` instead. And here you *are* allowed to configure a Management Zone together with a Metric Selector.

I've configured a small example based on the HCL code you've pasted above for the old resource. This is how it may have to look like.

```hcl
resource "dynatrace_metric_events" "TFTEST" {
  enabled                    = true
  event_entity_dimension_key = "dt.entity.kubernetes_cluster"
  summary                    = "TFTEST_001"
  event_template {
    description = ""
    davis_merge = true
    event_type  = "CUSTOM_ALERT"
    title       = "VELERO FAILURE ALERT PROD \n Velero back up for the schedule {dims:schedule} failed for the cluster {dims:dt.entity.kubernetes_cluster.name}."
  }
  model_properties {
    type               = "AUTO_ADAPTIVE_THRESHOLD"
    alert_condition    = "ABOVE"
    alert_on_no_data   = false
    dealerting_samples = 3
    samples            = 5
    signal_fluctuation = 1
    violating_samples  = 1
  }
  query_definition {
    type            = "METRIC_SELECTOR"
    management_zone = "##########"
    metric_selector = "velero_backup_failure_total.count:splitBy(\"dt.entity.kubernetes_cluster\"):sort(value(auto,descending))"
  }
}
```

But you can actually make your life a bit easier by configuring your Metric Event using the WebUI and then execute
```
terraform-provider-dynatrace.exe -export dynatrace_metric_events
```
on the command line. That will produce a folder `configuration` where it dumps .tf files containing the configuration of all your metric events. Don't forget to authenticate using the environment variables `DYNATRACE_ENV_URL` and `DYNATRACE_API_TOKEN`.

Let me know if that helps,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @karty-s, I'm closing this ticket, assuming that utilizing `dynatrace_metric_events` takes care of your issues. If not, just drop us a message, and I will re-open it.

**Comment by karty-s** [comment]
Hi @Dynatrace-Reinhard-Pilz ,
 this solution worked for us, thanks a bunch for your help.
