### ISSUE TITLE
`dynatrace_document` resources applying successfully through Terraform, but resources are not present when checking in Dynatrace

### ISSUE THREAD

**Issue by caleb-long-vad2r4** [dynatrace-oss/terraform-provider-dynatrace#457]
**Describe the bug**
I'm attempting to use 2 instances of the "dynatrace_document" resource to apply in Terraform. The two instances of this are to deploy a test dashboard and a test notebook respectively. Both of these resources contain DQL elements. My project has been configured with the proper provider token from my SaaS Dynatrace instance, as well as a proper Automation client with the correct scopes. 

The `content` field on both of these resources point to a the location of the json files I'm attempting to deploy (one for a dashboard and one for a notebook, each of which I previously created in the Dynatrace UI, downloaded, and then deleted so that I could deploy them through Terraform).

When running a `terraform apply`, the plan looks to pick up the entire content of the json file, and the run is successful when applying these resources. However, when I go out to my SaaS instance of Dynatrace, the resources are no where to be found.

**To Reproduce**
1. Generate a Terraform project.
2. Configure said Terraform project with a Dynatrace provider containing the proper SaaS token and Automation client with the proper scopes.
3. Have a pre-configured Dashboard or Notebook from said SaaS instance of Dynatrace downloaded as a json file.
4. Add the json file to the project directory.
5. Create a `dynatrace_dashboard` resource within the project, referencing the location of the json file.
6. Run a `terraform apply` and confirm when plan finishes.
7. Once the apply has succeeded, check the SaaS instance to see if the resources have been created in Dynatrace.

**Expected behavior**
The Dashboard or Notebook can be found in the SaaS Dynatrace instance. 

**Screenshots**
<img width="686" alt="Screenshot 2024-05-07 at 2 17 32 PM" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/162204830/3379c64f-f89f-45bc-8295-6daa2386b2f3">
These are the resources within the Terraform file.

<img width="991" alt="Screenshot 2024-05-07 at 2 38 42 PM" src="https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/162204830/53dadcf6-15e3-4203-90f5-71bbd771fedc">
The apply for one of them was successful. A target apply was done in this case to not write over another change within the project, but the same result has occurred while doing a regular apply.

**Desktop (please complete the following information):**
 - OS: iOS 14.4.1 
 - Browser: Chrome
 - IDE: Intellij 2023.3.4 (Ultimate Edition)

**Comment by kishikawa12** [comment]
Hi @caleb-long-vad2r4,

Unfortunately I'm unable to replicate the issue. In my environment, my applies with dashboards/notebooks with DQL are succeeding and properly showing up in my tenant.

To troubleshoot further are you able to set the following environment variables and provide us with the logs at terraform@dynatrace.com?

```
export DYNATRACE_DEBUG=true
export DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
export DYNATRACE_HTTP_RESPONSE=true
```

Thanks!

**Comment by caleb-long-vad2r4** [comment]
Sorry for the delay on this! I've attempted to do set these variables and re-apply. For clarity, where can I find these logs to send you? My provider doesn't seem to have logs within it's plugin folder on my machine. Can these be found within my Dynatrace tenent?

**Comment by kishikawa12** [comment]
No worries! The logs should show up in the directory where you executed Terraform.

**Comment by caleb-long-vad2r4** [comment]
Very strange that I'm not getting logs coming back. Does it make a difference that I'm executing it via IDE (Intellij) or that I'm using Scalr as my Terraform deployment tool rather than TFE?

**Comment by kishikawa12** [comment]
Yeah that's strange, I don't believe that should matter as the logs should still show up in your working directory if the environment variables are set.

That being said, I just realized what could cause this behavior. The OAuth client that was created, was this created with your account? The reason I ask is that this behavior of a document missing in the UI could happen if it deployed but to a different user, hence the successful create but not showing up under your account.

If that's not the case, I'm out of ideas. :) I think it would be helpful to jump on a call to troubleshoot. Taking a look at our availability, we could do Wed 5/29 9-10AM Eastern, or anytime Mon 6/3 or Tues 6/4 in morning Eastern time.

**Comment by caleb-long-vad2r4** [comment]
I think I'll take you up on that meeting time you suggested if that still works? (Wed 5/29 9-10AM Eastern)

**Comment by kishikawa12** [comment]
Sounds good, can you send a quick email to terraform@dynatrace.com? We'll can send you a Zoom invite once we have your email. Talk soon!

**Comment by kishikawa12** [comment]
Summary: Dashboard visibility was related to having a different service user with the OAuth client. Discussed possible workarounds via `dynatrace_direct_shares` resource and `dynatrace_public_document` planned in #448 (targetting next week). 

We'll continue to introduce improvements with dashboard ownership/sharing as they become available via the API. I'll close this ticket for the time being, please feel free to reopen if you continue to run into issues, thanks!
