### ISSUE TITLE
[Bug] Fix required for calculated service metric

### ISSUE THREAD

**Issue by Karthikeyanraman94** [dynatrace-oss/terraform-provider-dynatrace#46]
Could you please try with the below resource, its directly downloaded using your download utility.
There were few errors in downloaded resource such as Vaules block is not available , and it looks to be expected one and few other issue arises while applying as well
```
resource "dynatrace_calculated_service_metric" "TEST_-_FAILURE_COUNT_HTTP_4xx" {
  name = "TEST- FAILURE COUNT HTTP 4xx"
  enabled = true
  metric_key = "calc:service.test_failurecount4xx"
  unit = "COUNT"
  conditions {
    condition {
      attribute = "HTTP_STATUS_CLASS"
      comparison {
        negate = false
        http_status_class {
          operator = "EQUALS"
          value = "C_4XX"
        }
      }
    }
    condition {
      attribute = "PROCESS_GROUP_TAG"
      comparison {
        negate = false
        tag {
          operator = "TAG_KEY_EQUALS"
          value {
            context = "CONTEXTLESS"
            key = "test-services"
          }
        }
      }
    }
  }
  dimension_definition {
    name = "Dimension"
    dimension = "{Request:Name} {HTTP-Method} {HTTP-Status}"
    top_x = 10
    top_x_aggregation = "SUM"
    top_x_direction = "DESCENDING"
  }
  metric_definition {
    metric = "HTTP_4XX_ERROR_COUNT"
  }
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I will take a look at that by tomorrow. I remember something similar happening during implementation and testing. Will push out a hotfix once resolved.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@Karthikeyanraman94 would you be willing to export the Dashboard to JSON via WebUI and share it with me?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Sorry for the delay @Karthikeyanraman94
Tomorrows release will contain a fix for this.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Karthikeyanraman94 ,
[v1.4.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.4.0) should take care of this issue. Please reopen the ticket in case there are still difficulties.
