### ISSUE TITLE
Provider's export ability does not export DQL portions of `dynatrace_automation_workflow` 

### ISSUE THREAD

**Issue by caleb-long-vad2r4** [dynatrace-oss/terraform-provider-dynatrace#460]
**Describe the bug**
While using the Dynatrace Terraform provider's export ability on a `dynatrace_automation_workflow` resource, the exported TF code does not contain any of the DQL portions of the workflow.

According to the documentation regarding this [resource](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/automation_workflow), there seem to be no references to setting up a step that can execute a DQL query. Is DQL supported by this resource?

**To Reproduce**
1. Have a Dynatrace Terraform provider configured with the proper API token and Automation client from the associated Dynatrace SaaS instance.
2. Have a created workflow within said SaaS instance.
3. Run the export command on the provider to export said workflow from Dynatrace SaaS instance.
4. Validate returned TF file and see that no DQL portions are included.

**Expected behavior**
The full workflow including DQL steps should be in the TF file.

**Screenshots**

**Desktop (please complete the following information):**
- OS: iOS 14.4.1
- Browser: Chrome
- IDE: Intellij 2023.3.4 (Ultimate Edition)

**Additional context**

**Comment by kishikawa12** [comment]
Possibly related to #457..

Hey @caleb-long-vad2r4, 

Similar story here as with #457, I'm unfortunately having trouble replicating the issue. Are you able to run an export with the following environment variables set and email us the logs at terraform@dynatrace.com? Just an export of a single workflow with the issue would suffice, and if you can clarify which task/field is missing the DQL in the example that would be very helpful.

```
export DYNATRACE_DEBUG=true
export DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
export DYNATRACE_HTTP_RESPONSE=true
```

Thanks!

**Comment by kishikawa12** [comment]
Joined a troubleshooting session together to take a closer look at this issue. 

Based off the HTTP logs, the API is properly returning the execute DQL tasks, but its missing in the generated TF files. Examples we have in our tenants seem to be working, so customer has kindly agreed to send the problematic workflow example to terraform@dynatrace.com. 

Thanks!

**Comment by kishikawa12** [comment]
Hi @caleb-long-vad2r4,

Just wanted to follow-up if you had a chance to retrieve an example of that problematic workflow yet. Thanks!

**Comment by caleb-long-vad2r4** [comment]
Hey @kishikawa12, I believe that workflow should have been sent to you guys, but it would have come from Monica Chondhury who was in the meeting with us. Let me know if you don't see it and we'll send it over again. Thanks for all your help on this!

**Comment by kishikawa12** [comment]
Hey @caleb-long-vad2r4,

Hmm, I checked my spam folder and don't seem to see it there either. I wonder if it didn't like the attachment extension - possibly blocked by either one of our email servers? Are you able to send it as a .txt?

Thanks!

**Comment by caleb-long-vad2r4** [comment]
Hey @kishikawa12, just checked with Monica this morning and it seems she's gotten it working now. Not sure what's changed but it seems to be working. Feel free to close the ticket with this, and thank you for all your help!
