### ISSUE TITLE
Terraform provider failed with log_custom_source

### ISSUE THREAD

**Issue by pacoporro** [dynatrace-oss/terraform-provider-dynatrace#468]
**Describe the bug**

When using export migrate log_custom_source, we can export from target but not import in source.

`Given property 'values-and-enrichment' with value: '0' violates the following constraint: fell below the collection's lower size limit which was set to 1.`

![image](https://github.com/dynatrace-oss/terraform-provider-dynatrace/assets/77266336/cd74729b-ebdf-4879-bb9c-2a28ed12b345)

**To Reproduce**
terraform-provider-dynatrace -export  -migrate dynatrace_log_custom_source

**Expected behavior**
Expected custom log sources imported.

**Additional context**
Using Terraform provider 1.58.0

**Comment by kishikawa12** [comment]
Hi @pacoporro,

The API endpoint for `dynatrace_log_custom_source` had a schema update with a breaking change in v292. This is why you may be running into an issue where the source environment is on a version prior to v292 and the target environment is on v292+. Unfortunately this configuration isn't backwards compatible and must to changed from the old attribute `values` to the new attribute `values_and_enrichment` (doc [link](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/log_custom_source)). 

We apologize for the inconvience.

**Comment by kishikawa12** [comment]
Resurrecting this issue, due to popular demand we will introduce an adapter that will automatically fix the schema when it sees this error.

**Comment by kishikawa12** [comment]
This adapter will be included in this week's release, thanks!
