### ISSUE TITLE
[Bug] Tag_filter in alerting profile's rules is required, not optional

### ISSUE THREAD

**Issue by pfreund** [dynatrace-oss/terraform-provider-dynatrace#48]
In your documentation : https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/alerting_profile#nested-schema-for-rules

In "Nested Schema for rules"

"tag_filter" is Optional.

I think it's required, because if you don't set it, there is an error saying it's missing.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
You're right. I also checked the OpenAPI Schema of the REST API, and also here it's flagged as required.
I will keep this issue open until it's fixed with the upcoming release.

thanks,
Reinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @pfreund,
[v1.4.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.4.0) should take care of this issue. Please reopen the ticket in case there are still difficulties.
