### ISSUE TITLE
Resource dynatrace_log_storage fails on updates

### ISSUE THREAD

**Issue by Conacious** [dynatrace-oss/terraform-provider-dynatrace#489]
**Describe the bug**
When updating an existing dynatrace_log_storage resource changing the `matchers` atribute to add new `values` on the array, I get the following error:

```
│ Error: Neighbor with key '8b6fb8c3-12b3-31a0-b2ed-20019988d98a' not found for 'builtin:logmonitoring.log-storage-settings'
│ 
│   with dynatrace_log_storage.my_logs_storage,
│   on main.tf line 65, in resource "dynatrace_log_storage" "my_logs_storage":
│   65: resource "dynatrace_log_storage" "my_logs_storage" {
```

**To Reproduce**
1. Create a dynatrace_log_storage resource in Terraform
2. Apply configuration
3. Change dynatrace_log_storage resourece adding new logs on values array.
4. Apply again and see error

**Expected behavior**
Resource dynatrace_log_storage is modified and no error returned.

**Screenshots**

**Additional context**
Using Terraform version `1.5.7` and version of the provider `provider registry.terraform.io/dynatrace-oss/dynatrace v1.59.0` on Dynatrace SaaS environment.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Victor,

If I'm not mistaken it's irrelevant what you're trying to change in your resource block.
What's happening here is, that your resource seems to have the attribute `insert_after` specified.
Am I right with my assumption that it's a hard coded ID, like this
```
insert_after = "vu9U3hXa3q0AAAABACpidWlsdGluOmxvZ21vbml0b3JpbmcubG9nLXN0b3JhZ2Utc2V0dGluZ3MABnRlbmFudAAGdGVuYW50ACQ5YzQyODE4Yy1jZjc0LTMxZDctYTQ0ZS02NDE0NmE4ODQwNje-71TeFdrerQ"
```
and not a reference to another resource like this?
```
insert_after = dynatrace_log_storage.some_resource_name.id
```

At least that's how I can reproduce the issue easily. Apparently there has happened a change with the error messages the REST API responds back with. The provider in general DOES intercept errors that are related to `insert_after` - and as a fallback resends the settings without a specific order.

But the `Neighbor with key` error message is new. With our next release we will take care of that.

In the meantime, can you confirm that you're not running into the issue when omitting `insert_after`?

**Comment by Conacious** [comment]
Hi, thank you for your response.

Yes, I can confirm that I'm not using the `insert_after` field, maybe is autofilled by Dynatrace.

Here's an example of my code:

```
resource "dynatrace_log_custom_source" "my_log_source" {
  name    = "name"
  enabled = true
  scope   = "HOST_GROUP_ID"
  custom_log_source {
    type = "LOG_PATH_PATTERN"
    values_and_enrichment {
      custom_log_source_with_enrichment {
        path = "/something.log"
      }
    }
  }
}
```

This works fine and it's applied without errors, but if I change it adding another log source:

```
resource "dynatrace_log_custom_source" "my_log_source" {
  name    = "name"
  enabled = true
  scope   = "HOST_GROUP_ID"
  custom_log_source {
    type = "LOG_PATH_PATTERN"
    values_and_enrichment {
      custom_log_source_with_enrichment {
        path = "/something.log"
      }
      custom_log_source_with_enrichment {
        path = "/something2.log"
      }
    }
  }
}
```

And apply again, I get the error.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Victor, thanks for confirming.
The upcoming release of the provider will take care of this issue.
