### ISSUE TITLE
[Feature Request] Add support for SLOs

### ISSUE THREAD

**Issue by jonormann** [dynatrace-oss/terraform-provider-dynatrace#49]
We need to create many SLOs and all these across several environments in a managed cluster.
Would be very nice to do that using the terraform provider.

Thanks
Best
Joerg

**Comment by Dynatrace-Reinhard-Pilz** [comment]
SLOs are almost done. I'd like to do a bit more testing right now, but you can expect a release with SLO support early next week.

**Comment by jonormann** [comment]
so nice!!
Thanks

**Comment by vinsontan** [comment]
It would be good if custom event for alerting SLO can be configured using the upcoming expression metric to define error budget alerting

**Comment by ppaltmann** [comment]
I'm also looking forward to that feature!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello folks,

[v1.5.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.5.0) contains support for the resource `dynatrace_slo`.
