### ISSUE TITLE
dynatrace_network_zone resource produces an update on every plan

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#490]
**Describe the bug**
A plan is genereted for dynatrace_network_zone on every plan, because the connected activegate and oneagent fields are set to null.
Since these values are dynamic and fluctuate over time, the provider should ignore them when planning to update resources.

Here is ane example of a plan:

```
~ resource "dynatrace_network_zone" "my_nz" {
    id                                = "my.nz.id"
    name                              = "my.nz.name"
  - num_of_configured_activegates     = 1 -> null
  - num_of_configured_oneagents       = 17 -> null
  - num_of_oneagents_from_other_zones = 48 -> null
  - num_of_oneagents_using            = 62 -> null
    # (2 unchanged attributes hidden)
}
```

**To Reproduce**
1. Configure a NZ with Terraform
2. Connect AGs and Oneagents to the NZ
3. Run Terraform Plan

**Expected behavior**
Changes in these value should not generate an update in the plan. So far as I understand it, these values are informational.

**Additional context**
Tested with provider v1.59.1

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva,

Thank you for the feedback! The fix will be included in the next release.

**Comment by mattBaumBeneva** [comment]
Thanks, @kishikawa12 !
