### ISSUE TITLE
Terraform dynatrace_aws_credentials - Apply error (following Dynatrace API update)

### ISSUE THREAD

**Issue by RML-MS** [dynatrace-oss/terraform-provider-dynatrace#494]
An unexpected change in appearing in our Terraform plan for the resource dynatrace_aws_credentials, since July 15th.  This change is not present in the same plan, of the same unrelated changes earlier on July 15th, or before.

It is removing 'unknowns' block attributes for credentialsEnabled and runningOnDynatraceInfrastructure in the dynatrace_aws_credentials resource.

NOTE:  No provider update or code changes have been made to this resource or associated attributes.

The unexpected change is seen in plan
`
  # module.observability.dynatrace_aws_credentials.aws will be updated in-place
  ~ resource "dynatrace_aws_credentials" "aws" {
        id                                       = "AWS_CREDENTIALS-*******************"
      - unknowns                                 = jsonencode(
            {
              - credentialsEnabled               = true
              - runningOnDynatraceInfrastructure = false
            }
        ) -> null
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
`

The error occurs during apply 
`
│ Error: tagsToMonitor must not be null
│ 
│   with module.observability.dynatrace_aws_credentials.aws,
│   on .terraform/modules/observability/env/metrics.tf line 1, in resource "dynatrace_aws_credentials" "aws":
│    1: resource "dynatrace_aws_credentials" "aws" {
`

Looking at the Dynatrace changelog for aws/credentials, rolled out on 15th July, these 2 attributes appear
https://docs.dynatrace.com/docs/whats-new/release-notes/dynatrace-api/sprint-296#awscredentials

**To Reproduce**
Run a plan for any Terraform using the Dynatrace provider - The updates to 'unknowns' block should be present.  Apply will fail with the error above

**Expected behavior**
No unexpected changes, or if there are, they should not cause apply to fail

**Screenshots**
Code snippet shown above of plan and apply for the relevant resource

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for bringing that issue to our attention. The release of the provider scheduled for today will contain a fix for it.
