### ISSUE TITLE
Credentials Vault allowedEntities support

### ISSUE THREAD

**Issue by stmcx** [dynatrace-oss/terraform-provider-dynatrace#499]
**Is your feature request related to a problem? Please describe.**
No, missing feature

**Describe the solution you'd like**
Support `allowedEntities` https://docs.dynatrace.com/docs/dynatrace-api/environment-api/credential-vault/post-credentials

**Describe alternatives you've considered**
I have to set [owner_access_only](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs#owner_access_only) false for now which is insecure in a shared environment.

**Additional context**
https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/credentials

**Comment by kishikawa12** [comment]
Hi @stmcx,

Thanks for the feedback, the schema update that will introduce `allowedEntities` will be in the next release.
