### ISSUE TITLE
Introduce ability to track settings that are currently not maintained by Terraform

### ISSUE THREAD

**Issue by xoronet** [dynatrace-oss/terraform-provider-dynatrace#502]
It would be very beneficial to have data sources (for every existing resource type) that provide the current number of Dynatrace objects in an environment. This would allow to easily detect if there are objects in the Dynatrace environment that are not managed by Terraform yet. The difference to the current data sources is that they do not return a single specific object but all objects or at least a count value.

So far I use the generic http provider and trigger a call to the Dynatrace REST API. From the response body, I count the entries in the values list. See the example below:
```
data "http" "request_attributes" {
  url             = "${var.dynatrace_env_url}/api/config/v1/service/requestAttributes"
  request_headers = {
      Authorization : "Api-Token ${var.dynatrace_api_token}"
  }
}

output "count" {
  value = length(jsondecode(data.http.request_attributes.response_body)["values"])
}
```

With that, I can check whether new request attributes have been added to Dynatrace environment. The downside is that I have to inject url and token as variables.

It would be much easier to have a dedicated data source `dynatrace_request_attributes`:
```
data "dynatrace_request_attributes" "request_attributes" {
}

output "count" {
  value = data.dynatrace_request_attributes.request_attributes.count
}
```

**An alternative would be a single generic data source that allows to call any REST endpoint and provides the response in a generic "response_body" attribute. This would already simplify the setup because I do not need to use the http provider and inject a token manually as variable.**
```
data "dynatrace_api_call" "request_attributes" {
    uri = "/api/config/v1/service/requestAttributes"
}

output "count" {
  value = length(jsondecode(data.dynatrace_api_call.request_attributes.response_body)["values"])
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @xoronet ,

Is your main objective here to ensure that nobody is creating settings behind your back (i.e. outside of terraform)?
If so, I could give you an outlook on something we're currently working on. The working title of that resource is called `dynatrace_golden_state`.

```hcl
resource "dynatrace_golden_state" "golden_state" {
  request_attributes = [
    dynatrace_request_attribute.att1.id,
    dynatrace_request_attribute.att2.id,
    ...
  ],
  management_zones = [
     ...
  ],
  alerting_profiles = [
     ...
  ],
  ...
}
```
What it does is, that it deletes all the settings that aren't explicitly specified in there.

The data source you're suggesting (or a variant of it) wouldn't be that difficult to implement. But in the end it would just produce  a number - in other words, it wouldn't solve an actual problem.

Is the resource example mentioned above something that's related to what you're trying to achieve?

**Comment by xoronet** [comment]
Hi @Dynatrace-Reinhard-Pilz,

yes indeed, the main objective for me is to recognize if settings and other objects in the Dynatrace environment are created outside of Terraform. For settings and objects that are already covered by Terraform, I can detect them by simply executing terraform plan again. Settings and objects that are entirely unknown to the Terraform state cannot be detected that way. 
The outlook is pretty interesting! Do you have a rough timeline to share more details?

Having a data source publishing "just" a number how many objects exist would be a simple and cheap indicator that something is not covered in Terraform and I can continue investigation. But if your "golden_state" solves the problem in a more professional way, I would definitely be interested.

Thanks

**Comment by xoronet** [comment]
@Dynatrace-Reinhard-Pilz any updates on the timeline you can share?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @xoronet 

Apologies for the delay here.
Coincidentally I was tempted to include a first version into todays release - and decided against it, because I'll be out of office until the end of August. We're talking about a pretty delicate functionality and I don't want my colleague to pay the price in case users run into issues.

The version I'm working locally with covers about 1/3 of the resources. Reason is that we need to onboard every resource here one by one and re-check whether there don't exist any environment wide default settings we would get rid of unintentionally.

What I *can* offer is to provide a custom build for you, in case you're looking for a solution very urgent.

**Comment by xoronet** [comment]
Hi @Dynatrace-Reinhard-Pilz,
no worries and thanks for the update! A custom build is not needed yet.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hi @xoronet 

Apologies for the constant delays here.

Release v1.66.0 scheduled for today will contain a first version of the resource `dynatrace_golden_state`. 

By default the resource is disabled. To enable it, you will have to define the environment variable `DYNATRACE_GOLDEN_STATE_ENABLED` and set the value to `true`. There's no need to keep that switch a secret. We just want to make sure that users who are willing to try out that functionality are directly in contact with us.
It doesn't support all possible resources yet, but quite a lot already.

Any feedback will be VERY welcome.

**Comment by xoronet** [comment]
Hi @Dynatrace-Reinhard-Pilz

no worries, I am anyway on parental leave for the next time. I will most probably give it a try in December. Looking already forward to the final release.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Having a baby in the house will definitely keep you busy - congrats :)

In the interest of avoiding awfully long running tickets, are you ok with me closing this ticket until further notice?
By December you can expect the `dynatrace_golden_state` to support pretty much every resource where it makes sense. In case you're stumbling across any troubles or questions, we can always communicate via a new ticket.

**Comment by xoronet** [comment]
@Dynatrace-Reinhard-Pilz thanks a lot! 

Yes, we can close it for now :)
