### ISSUE TITLE
Export command attempts to index out-of-bounds for the string array containing command line arguments

### ISSUE THREAD

**Issue by BrooklynGabe** [dynatrace-oss/terraform-provider-dynatrace#503]
**Bug Description**
When attempting to use the default export behavior, the utility attempts to access a command line argument that does not exist. This appears to affect versions 1.59 and later.

**Steps to reproduce the behavior:**
1. Follow instructions found at https://docs.dynatrace.com/docs/manage/configuration-as-code/terraform/guides/export-utility to configure Terraform and the Dynatrace provider at latest version
2. Execute the following command (shown for v1.59.3)  
``` sh
> ./.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.59.3/linux_amd64/terraform-provider-dynatrace_v1.59.3 -export
```

**Expected behavior**
Full export is performed for the environment specified by the environment variables set before executing the Terraform provider

**Screenshots**
``` sh
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace.Export({0xc0001a8000, 0x2, 0x40a22b?})
        github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/export.go:39 +0x5aa
main.main()
        github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:110 +0x65
```

**Desktop (please complete the following information):**
``` sh
> uname -a
Linux ... 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

> terraform --version
Terraform v1.9.2
on linux_amd64
+ provider registry.terraform.io/dynatrace-oss/dynatrace v1.59.3 
```

**Additional context**
Support ticket originally opened with Dynatrace, advising to open the GitHub issue
[Golang Error when executing Export using Dynatrace Terraform Provider Ticket# 351368](https://one.dynatrace.com/hc/en-us/requests/351368)

``` go
func Export(args []string) bool {

    if len(args) == 1 {
        return false
    }

    if strings.TrimSpace(args[1]) != "-export" {
        return false
    }

    if len(args) > 1 { // if there are exactly two (2) elements in the string array to use default export behavior, there is no third element
        if strings.TrimSpace(args[2]) == "-list-exclusions" {  // here is where we index out-of-range
            for _, group := range export.GetExcludeListedResourceGroups() {
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @BrooklynGabe, thanks for reporting this issue.
It will be fixed with the upcoming release. Until then a feasible workaround is to invoke `terraform-provider-dynatrace_v1.59.3 -export -id`. That's enough to avoid the out of range error. The only change in behavior would be that the generated `.tf` file contain an additional comment in the beginning.
