### ISSUE TITLE
Dynatrace when migrating all we are not getting custom tags

### ISSUE THREAD

**Issue by Bharatp** [dynatrace-oss/terraform-provider-dynatrace#506]
**Describe the bug**
Dynatrace, when migrating all, we are not getting custom tags, and Using terraform-provider-dynatrace_v1.59.3

**To Reproduce**
/home/xxx/terraform-dynatrace/.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.59.3/linux_amd64/terraform-provider-dynatrace_v1.59.3 -export -migrate

**Expected behavior**
One is -export and -migrate, and the other is -export and -ref. Both combinations could not export dynatrace_custom_tags
When I specified the resource (-export dynatrace_custom_tags), it cloud export custom tags. How can we export all the resources, including custom_tags, with only one command?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Bharatp,

The resource `dynatrace_custom_tags` is excluded by default from the export.

Reasoning behind that is, that this resource is pretty special. Unlike other resources, where the configuration you're applying reflects a single setting, applying custom tags works based on entity selectors - whatever entity matches the given entity selector will get the tags assigned. In other words: Applying Custom Tags to entities doesn't persist HOW the tags got applied - it just results in the fact, that a collection of entities will have these tags assigned.

You *can* export them explicitly using `terraform-provider-dynatrace_v1.59.3 -export dynatrace_custom_tags`, though. Just be aware of the fact, that the configuration it produces will not match the way you've been applying it in the first place.
You will get a `dynatrace_custom_tags` resource block for *every* entity that has tags applied (using the entity selector `entityId(####)`). That will produce the same end result, but it very likely differs from how the tags have been applied originally to these entities.

For migration purposes I would, however, recommend against using the exported `*.tf` files as they are. Aside from the fact, that  you will end up with a considerable amount of HCL code, a lot of your entities on the target environment will have different IDs - therefore won't be covered. 
I would rather go the route of using the exported .tf files for verification.
