### ISSUE TITLE
Data Source `dynatrace_generic_settings`

### ISSUE THREAD

**Issue by Dynatrace-Reinhard-Pilz** [dynatrace-oss/terraform-provider-dynatrace#507]
It is currently not possible (unless when using external providers) to access the value(s) of settings that are currently not maintained by Terraform.
While Config V1 settings require a dedicated data source in such cases, any setting that is available via Settings 2.0 could get easily queried for if a data source `dynatrace_generic_settings` as described blow existed.

```hcl
data "dynatrace_generic_settings" "my-generic-settings" {
  schema = "<schema-id>" # e.g. app:dynatrace.kubernetes.connector:connection
  scope  = "<scope>" # optional, e.g. `environment` or an EntityID
  filter = "<filter" # e.g. value.name='my-setting-name'
}
```

The data source would populate a computed attribute `values` - a list JSON encoded strings representing the value(s).

Also, a possible extension / comfort data source would be a data source `dynatrace_generic_setting`

```hcl
data "dynatrace_generic_setting" "my-generic-setting" {
  schema = "<schema-id>" # e.g. app:dynatrace.kubernetes.connector:connection
  scope  = "<scope>" # optional, e.g. `environment` or an EntityID
  filter = "<filter" # e.g. value.name='my-setting-name'
}
```
data populates a computed attribute `value` with the value of the first setting that matched the given filter/schema/scope.

**Comment by kishikawa12** [comment]
The data sources `dynatrace_generic_settings` and `dynatrace_generic_setting` will be available in the release planned for later this week.
