### ISSUE TITLE
Unable to Migrate between SAAS tenants

### ISSUE THREAD

**Issue by maheshkanna-dyntrace** [dynatrace-oss/terraform-provider-dynatrace#508]
Dear Team,

We are trying to migrate between two SAAS Dynatrace tenants using the below doc and are facing the attached errors.
Currently the export is finishing without any error but the configurations are not imported into the new tenant.
Attached are the details of the error 

Source Tenant : 1 
Destination Tenant : 2 

Docs used : https://docs.dynatrace.com/docs/manage/configuration-as-code/terraform/guides/migration

Please reach out to us separately to get the tenant details.

Error 

SS] dynatrace_json_dashboard_base - Processing Resources - Group child configs with parent configs ...
Finishing touches ...
Writing ___resources___.tf
Writing ___datasources___.tf
Writing main.tf
Writing ___variables___.tf
Writing main ___providers___.tf
Writing modules ___providers___.tf
Remove Non-Referenced Modules ...
Finish Export ...
Terraform executable path:  C:\Terraform\terraform.exe
Executing 'terraform init'
... finished after 415 seconds

C:\Terraform\.terraform\providers\registry.terraform.io\dynatrace-oss\dynatrace\1.61.0\windows_386>cd

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

╷
│ Error: Reference to undeclared module
│
│   on main.tf line 245, in module "report":
│  245:   dynatrace_json_dashboard = module.json_dashboard.resources
│
│ No module call named "json_dashboard" is declared in the root module.
╵

C:\Terraform\.terraform\providers\registry.terraform.io\dynatrace-oss\dynatrace\1.61.0\windows_386\configuration>terraform apply
╷
│ Error: Module not installed
│
│   on main.tf line 126:
│  126: module "json_dashboard_base" {
│
│ This module's local cache directory modules\json_dashboard could not be read. Run "terraform init"
│ to install all modules required by this configuration.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @maheshkanna-dyntrace ,

Can you let us know the exact command line arguments you have executed for running the export?

thanks,
Reinhard

**Comment by maheshkanna-dyntrace** [comment]
Hi Team
Below are the commands that have been executed



set DYNATRACE_SOURCE_ENV_URL=https://

set DYNATRACE_SOURCE_API_TOKEN=

set DYNATRACE_ENV_URL=https://

set DYNATRACE_API_TOKEN=


terraform-provider-dynatrace_v1.61.0.exe -export -migrate

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for that, @maheshkanna-dyntrace.

The command line `terraform-provider-dynatrace_v1.61.0.exe -export -migrate` by default exports everything into a subfolder named `configuration`.
Did that folder already exist before you ran the command - and more importantly, did it contain already data from a previous export?
The export functionality wouldn't recognize that (and also wouldn't be able to "merge" these two exports properly).

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @maheshkanna-dyntrace, I'm closing this ticket until further notice. Just drop us a message if you need further clarification and we will re-open it.
