### ISSUE TITLE
[Bug] Duplicate ressource error after initial download

### ISSUE THREAD

**Issue by ppaltmann** [dynatrace-oss/terraform-provider-dynatrace#51]
I'm getting an error after I try a "terraform plan" 

1. Downloaded full config from env
2. Create a new alerting profile
3. terraform plan
4. Duplicate ressource error for my dashboards which some of them are cloned in Dynatrace

` Error: Duplicate resource "dynatrace_dashboard" configuration
│ 
│   on XXXXX Monitoring-cloned.41f08c69-76f7-40d5-83ff-a96ad706642e..dashboard.tf line 1:
│    1: resource "dynatrace_dashboard" "XXXXX_Monitoring-cloned" {
│ 
│ A dynatrace_dashboard resource named "XXXXX_Monitoring-cloned" was already declared at XXXXX Monitoring-cloned.409725e4-f640-47ef-892c-e226873c3428..dashboard.tf:1,1-62. Resource names must be unique per type in each module.
╵
`

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Especially for Dashboards these symptoms are not unusual. Unfortunately the REST API offers ALL Dashboards regardless of the owner - including some of those that are duplicated.
I will try to find a way to limit the number of Dashboards when the download functionality is getting invoked. Until then I leave this issue open.

**Comment by ppaltmann** [comment]
@Dynatrace-Reinhard-Pilz  I just checked that dashboards again and the problem is the "name" which is equal but the IDs are not equal which would allow to distinguish. 

Dashboard #1
> "id": "5b1cc283-6fc9-4b3d-9c78-189410c2e0c1",
  "dashboardMetadata": {
    "name": "XXXX-XXXX Monitoring-cloned",
    "shared": true,
    "owner": "XXXX",
    "dashboardFilter": {
      "managementZone": {
        "id": "-2086783870824620197",
        "name": "XX_XXXX-XXXX"

Dashboard #2
>   "id": "41f08c69-76f7-40d5-83ff-a96ad706642e",
  "dashboardMetadata": {
    "name": "XXXX-XXXX Monitoring-cloned",
    "shared": true,
    "owner": "XXXX",
    "dashboardFilter": {
      "managementZone": {
        "id": "-2086783870824620197",
        "name": "XX_XXXX-XXXX"

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@ppaltmann with the next release I'll introduce a small change to the download functionality for Dashboards. The Resource Names will contain the ID in addition to the Dashboard Name. It WILL look a bit messy, but it should prevent terraform from complaining.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Philipp,
[v1.5.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.5.0) contains the small change we've talked about. Let me know if that resolves the issues you're currently facing.
