### ISSUE TITLE
OpenPipeline Implementation

### ISSUE THREAD

**Issue by KevinThompsonYCRX** [dynatrace-oss/terraform-provider-dynatrace#516]
OpenPipeline was released in 1.295.0, is there a timeline for when support will be added to the provider? I see they have support for spans/metrics/topology planned, but is there work in place to get log/event pipelines supported in the Terraform provider?

https://docs.dynatrace.com/docs/platform/openpipeline

**Comment by arthurpitman** [comment]
Hi @KevinThompsonYCRX, we are currently targeting the beginning of September 2024 for initial OpenPipeline support in the Terraform provider.
