### ISSUE TITLE
dynatrace_davis_anomaly_detectors get bad request when trying to apply

### ISSUE THREAD

**Issue by mhoang-woolworths-com-au** [dynatrace-oss/terraform-provider-dynatrace#518]
**Describe the bug**
Use of any dynatrace_davis_anomaly_detectors and a api token that has all possible permissions (all write/create) will get http 400 bad request with provider 1.6.4

**To Reproduce**
1. Create a valid block dynatrace_davis_anomaly_detectors that will work with plan
2. Use an api token that has all create/write permissions possible
3. Run apply

Error: status code 400 (expected: 200): oauth token error: {"errorCode":400,"message":"Bad Request","issueId":"Q7P5EUSO5T6AXQYY"}
│ 
│   with dynatrace_davis_anomaly_detectors.Homerun_Mongodb_trigger_errors,
│   on log_alerts.tf line 18, in resource "dynatrace_davis_anomaly_detectors" "my_davis_errors":
│   18: resource "dynatrace_davis_anomaly_detectors" "my_davis_errors" {

**Expected behavior**
It should work

**Screenshots**
![image](https://github.com/user-attachments/assets/9c4f61a2-4666-4321-97fe-8c080bba0ee0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Provider version 1.6.1-1.6.4

**Comment by kishikawa12** [comment]
Hi @mhoang-woolworths-com-au,

The `dynatrace_davis_anomaly_detectors` resource requires an OAuth token client to be configured in addition to the API token, without it you may encounter an error `Bad Request`. 

A guide on how to create an OAuth client is available in our official documentation [here](https://docs.dynatrace.com/docs/manage/configuration-as-code/terraform/guides/create-oauth-client).

Additional information on what OAuth permissions are required is available on the resource documentation page [here](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/davis_anomaly_detectors).

I hope that helps! Please let us know if that resolves your issue.

**Comment by kishikawa12** [comment]
Hi @mhoang-woolworths-com-au,

I'll close this ticket for the time being, please feel free to reopen if the above solution doesn't resolve your issue. 

Thanks!
