### ISSUE TITLE
[Feature Request] Dashbaord sharing

### ISSUE THREAD

**Issue by jonormann** [dynatrace-oss/terraform-provider-dynatrace#52]
Hi,
dashboards are currently nice to use (after fix #50) What does not seems to work are sharing_details -> published = true.
Published is allways false.
But what would be very nice to have is a resource for dashboard_share_settings.

```
resource "dynatrace_dashboard_share_settings" "sharing"{
  dashboard_id = dynatrace_dashboard.myDashbaord.id
  enabled = true
  published = true
  permissions{
    permission{
      type = "all"
      permission = "VIEW"
    }
    permission{
      type = "group"
      id = "groupname"
      permission = "VIEW"
    }
  }
  public_access{
    management_zone = ["zone1", "zone2"]
  }
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
You're right. Dashboard Sharing has changed a few months ago - which rendered the original Sharing Section useless.
Explicit support for Sharing Settings was on my backlog - I just didn't find the time yet to schedule it in.
Thanks for the HCL sample - I'll try stick to it as close as possible when implementing.
This ticket will remain open until support for that resource is available.

**Comment by Karthikeyanraman94** [comment]
we also need this feature

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I am planning to wedge in Dashboard Sharing before focusing on Environment Creation and User Configuration - likely by end of July.

**Comment by Karthikeyanraman94** [comment]
hI @Dynatrace-Reinhard-Pilz : Would be great If this feature is out soon

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everybody,

Release [v1.7.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.7.0) takes care of Dashboard Sharing.
