### ISSUE TITLE
Error: Quantified groups are not allowed. Please solve this in another way.

### ISSUE THREAD

**Issue by smc87** [dynatrace-oss/terraform-provider-dynatrace#524]
Using this code in a web_application resource:

```terraform
 exclude_xhr_regex = "/^(?:https?:\\/\\/)?(?:[a-zA-Z0-9-]+\\.)*(matchone|matchtwo)(?:\\/|$)/i"   
```

and then running an apply job, results in:
Error: Quantified groups are not allowed. Please solve this in another way.

This regex is already applied via the UI and is exported via the terraform export option.

When comparing changes that are about to be made to the resource in the plan stage, exclude_xhr_regex is not listed - since it is the same as the current config.
However when running an apply job the resource fails with the above message.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @smc87, I'm able to reproduce your issue. The REST API apparently insists on restrictions that aren't enforced when using the WebUI. I've already reached out to our developers for clarification - hoping that the solution will be to simply lift that restriction on the REST API.

**Comment by smc87** [comment]
Thanks very much

**Comment by Reinhard-Pilz-Dynatrace** [comment]
@smc87 Dynatrace ONE has reached out to me, about the fact, that you also had a chat open with them about the very same topic, and that you'd prefer to stick to just one communication channel.
I'm closing this ticket therefore. Once R&D gets back with an answer, you'll get notified on the DT1 chat.

In any case, feel free to drop us a message here, and I'll reopen the ticket.
