### ISSUE TITLE
Update single ressource only

### ISSUE THREAD

**Issue by ppaltmann** [dynatrace-oss/terraform-provider-dynatrace#53]
Hi @Dynatrace-Reinhard-Pilz, 

I downloaded the whole config but I try to do only an update of a subset e.g. alerting profile. My understanding was that this will do the trick but it didn't work: 

`tf terraform plan -target=alerting_profile `

Error message: 
> │ Error: Invalid target "alerting_profile"
│ 
│ Resource specification must include a resource type and name.

Is that possible with the current provider to just update a single ressource? 

Thanks for your feedback.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Philipp,

I believe the correct syntax here would be `terraform plan -target dynatrace_alerting_profile.<resourcename>`.
Anyways, we already received feature requests for limiting the resources that are getting downloaded. Right now `terraform-provider-dynatrace download` downloads EVERYTHING. One of the next releases will allow you to just download specific resources.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello Philipp,

[v1.5.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.5.0) allows you to selectively download resources.
Please take a look at the [README.md](https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/README.md) for the syntax of the new `terraform-provider-dynatrace export` functionality.
