### ISSUE TITLE
Failure to issue access token when attempting to configure Site Reliability Guardians

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#530]
**Describe the bug**
This may or may not be linked to recent SaaS updates to v1.300.36, but starting on 2024/09/17, we recieve an error from the provider when attempting to configure a SRG:
`Error: IOException when executing function: Failed to issue access token at authorization server. [caller=com.dynatrace.server.appfunctions.impl.FunctionExecutorServiceImpl.rawPost(FunctionExecutorServiceImpl.java:266), throwable=com.dynatrace.oauth.client.exception.AuthenticationException, reason=Bad Request]`

**To Reproduce**
1. Configure a dynatrace_site_reliability_guardian with Terraform
2. See error

**Expected behavior**
No authorization error should be returned when making this configuration.

**Additional context**
Tested with provider versions 1.66.0 and 1.61.0

**Comment by MaudVandevelde** [comment]
I don't know if you have done something but the problem is now resolved.

**Comment by kishikawa12** [comment]
Hi @mattBaumBeneva and @MaudVandevelde ,

I was just about to respond to your email to see if you are able to try again as I saw there was an emergency fix that was rolled out. This was actually an issue with the recent Dynatrace release and not specifically our provider. There was an erroneous change to the policy/scope which affected the creation/modification of SRGs in certain environments. 

We apologize for the inconvenience.
