### ISSUE TITLE
Missing resources for monitored technologies

### ISSUE THREAD

**Issue by nmarchini** [dynatrace-oss/terraform-provider-dynatrace#536]
**Is your feature request related to a problem?
Not related to a problem

**Describe the solution you'd like**
For the monitored technologies I would like to see the following resources added

- AIX
- Envoy

**Describe alternatives you've considered**
Click OPs and CURL API calls

**Comment by kishikawa12** [comment]
Hi @nmarchini,

The resources for the two actually exist but are somewhat hidden. We typically match naming and categories by the API schema ID, but in this case that made the resources harder to find. We'll review and make improvements in the docs so they're easier to find.

AIX - [dynatrace_aix_extension](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/aix_extension)

Envoy - [dynatrace_monitored_technologies_opentracing](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/monitored_technologies_opentracing)
