### ISSUE TITLE
Dashboard creation failing using json content

### ISSUE THREAD

**Issue by TheLooostOne** [dynatrace-oss/terraform-provider-dynatrace#537]
I would like to create a new dashboard however the creation fails with :
![image](https://github.com/user-attachments/assets/684217e0-553d-4c0b-bcb7-4f007ee54bb9)

I'm not sure what could be the issue on my side that I may have missed. By making the API call manually, the dashboard is created.
Provider version : 1.66.0

**To Reproduce**
1. Create new dynatrace_json_dashboard resource
2. Apply the changes

**Expected behavior**
The dashboard should be created.

**Desktop (please complete the following information):**
- OS: Windows 11 Enterprise
- Browser : chrome
- Version : 23H2

**Comment by kishikawa12** [comment]
Hi @TheLooostOne,

Are you able to double check your credentials and environment variables you have set for the environment URL and API token?
Reference: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs#configure-the-dynatrace-provider

Thanks!

**Comment by TheLooostOne** [comment]
Hi thank you for the response and sorry for the issue. I figured out the issue coming from some typo. Therefore closing the ticket
