### ISSUE TITLE
[Feature] HTTP Monitoring through synthentic

### ISSUE THREAD

**Issue by JayChanggithub** [dynatrace-oss/terraform-provider-dynatrace#543]
Hi Dynatrace Team, 

We would like to use Terraform to implement synthetic monitoring features for checking the health of HTTP requests (healthz). However, after reviewing the [documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/calculated_synthetic_metric), I couldn’t find any relevant modules or resources to accomplish this. If you have any recommendations or suggestions for this implementation, I would greatly appreciate your guidance. 

Here's screenshot show up through manually. If anything possible to do that via terraform? 
<img width="1575" alt="Xnip2024-09-28_16-53-15" src="https://github.com/user-attachments/assets/c3103ecb-d954-49cf-b75a-0fc6a161580a">

**Comment by JayChanggithub** [comment]
I'd should be find out the exactly related feature. https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/http_monitor not sure if anything wrong. Thanks.

**Comment by JayChanggithub** [comment]
@Reinhard-Pilz-Dynatrace  
Thank you for your clear and insightful guidance. Just one more question: even though this was previously done manually, is it possible to adopt this approach? if so i will attempt those. thx.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hi @JayChanggithub 

I'm not sure whether I understand the question "to adopt this approach" correctly.
You've execute the Synthetic Monitor `us.returns.cloud.sap` manually in the past?

**Comment by JayChanggithub** [comment]
@Reinhard-Pilz-Dynatrace  
Sorry caused your misunderstanding. Yes. in the past we do these by manually. Currently we consider to use tf to management. Now I have been successfully to export configuration on my end. Just can closed issue in the meantime. Thanks. 
<img width="952" alt="Xnip2024-10-01_17-57-54" src="https://github.com/user-attachments/assets/fdde45ac-2521-4d4c-8c66-e606f8dcf787">
