### ISSUE TITLE
The `dynatrace_custom_tags` resource does not delete the tag when destroying it.

### ISSUE THREAD

**Issue by GuiuMateu** [dynatrace-oss/terraform-provider-dynatrace#549]
Escribe, el siguiente mensaje, de la manera más entendible para abrir un issue en github. Escribelo en inglés, mejoralo y corrige los errores. Dámelo en formato markdown:

**Describe the bug**
When running `terraform apply` using the `dynatrace_custom_tags` resource [(link)](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/custom_tags) to tag an entity in Dynatrace, the tag is successfully created on the specified entity (verified through the Dynatrace UI). However, when executing `terraform destroy`, the tag is not removed from the entity. Although the Terraform state is updated to reflect the tag deletion, the tag remains visible on the entity in the Dynatrace UI.

**To Reproduce**
1. Obtain an access token with `entities.read` and `entities.write` scopes.
2. Get a Entity ID from your Dynatrace instance.
3. Replace the placeholder `<WRITE_YOUR_ENTITY_ID_HERE>` with your Entity ID in the following code (you can also modify the `key` and `value` for the tag):
```hcl
terraform {
  required_providers {
    dynatrace = {
      source = "dynatrace-oss/dynatrace"
    }
  }
}

resource "dynatrace_custom_tags" "notification_window" {
  entity_selector = "entityId(\"<WRITE_YOUR_ENTITY_ID_HERE>\")"

  tags {
    filter {
      context = "CONTEXTLESS"
      key     = "notification_window"
      value   = "24x7"
    }
  }
}
```
4. Run `terraform apply` and apply the changes
5. Check the Entity in the Dynatrace UI;  the tag will be created as expected.
6. Run `terraform apply -destroy` to destroy the resources.
7. Check the Entity in the Dynatrace UI; the tag is still present.
8. No error are shown in the Terraform output.

**Expected behavior**
When running `terraform destroy`, the tag should be removed from the entity in the Dynatrace UI, in addition to being removed from the Terraform state. The expected behavior is that the tag is completely deleted from both the Dynatrace system and Terraform's state.

**Desktop versions:**
- Device: MacBook Pro
- OS: Sonoma 14.6.1
- Terraform version: v1.5.7 on darwin_arm64
- Dynatrace provider version: v1.68.0 on darwin_arm64

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @GuiuMateu, thanks for reporting. You've stumbled across a regression bug we seem to have introduced with v1.59.0.

The upcoming release of the provider will take care of the issue.
