### ISSUE TITLE
[BUG] Download of panic: unsupported type []float64 

### ISSUE THREAD

**Issue by ppaltmann** [dynatrace-oss/terraform-provider-dynatrace#55]
I got an errror while doing a full export of the environment: 

panic: unsupported type []float64

`➜  emea_prod .terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.5.0/darwin_amd64/terraform-provider-dynatrace_v1.5.0 export
The environment variable DYNATRACE_TARGET_FOLDER has not been set - using folder 'configuration' as default
panic: unsupported type []float64

goroutine 1 [running]:
github.com/dtcookie/hcl.Properties.Encode(0xc000681f20, 0x1a68c86, 0x6, 0x1909000, 0xc0000fc240, 0x100d68d, 0xc000067000)
	github.com/dtcookie/hcl@v0.0.12/properties.go:391 +0x2c55
github.com/dtcookie/hcl.Properties.EncodeAll(0xc000681f20, 0xc00015ca88, 0x1a6ac9e, 0x8, 0xc00015cb70)
	github.com/dtcookie/hcl@v0.0.12/properties.go:213 +0xd0
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service/comparisoninfo.(*Number).MarshalHCL(0xc0001986e0, 0x19f3720, 0xc0001986e0, 0x2796ba8)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/comparisoninfo/number.go:54 +0x2c6
github.com/dtcookie/hcl.Properties.Encode(0xc000681ef0, 0x1a68806, 0x6, 0x19f3720, 0xc0001986e0, 0x0, 0x0)
	github.com/dtcookie/hcl@v0.0.12/properties.go:369 +0xb10
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service/comparisoninfo.(*Wrapper).MarshalHCL(0xc0000fc200, 0x1997ae0, 0xc0000fc200, 0x27f6018)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/comparisoninfo/wrapper.go:217 +0x69d
github.com/dtcookie/hcl.Properties.Encode(0xc000681ec0, 0x1a6c07d, 0xa, 0x1997ae0, 0xc0000fc200, 0x0, 0x0)
	github.com/dtcookie/hcl@v0.0.12/properties.go:369 +0xb10
github.com/dtcookie/hcl.Properties.EncodeAll(0xc000681ec0, 0xc00015d088, 0x1a6ac9e, 0x8, 0xc00015d160)
	github.com/dtcookie/hcl@v0.0.12/properties.go:213 +0xd0
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service.(*Condition).MarshalHCL(0xc000681ad0, 0x19b0900, 0xc000681ad0, 0x27f5f78)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/condition.go:41 +0x26e
github.com/dtcookie/hcl.Properties.EncodeSlice(0xc000681e90, 0x1a6b3f0, 0x9, 0x195c220, 0xc0000fc1c0, 0xfd00000000000000, 0xc00015d300, 0x100a2a3)
	github.com/dtcookie/hcl@v0.0.12/properties.go:195 +0x22b
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service.Conditions.MarshalHCL(...)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/conditions.go:22
github.com/dtcookie/hcl.Properties.Encode(0xc000681e30, 0x1a6c09b, 0xa, 0x195c220, 0xc0000fc160, 0x0, 0x0)
	github.com/dtcookie/hcl@v0.0.12/properties.go:369 +0xb10
github.com/dtcookie/hcl.Properties.EncodeAll(0xc000681e30, 0xc00015d5d8, 0x1a6ac9e, 0x8, 0xc0001d7f08)
	github.com/dtcookie/hcl@v0.0.12/properties.go:213 +0xd0
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service.(*CalculatedServiceMetric).MarshalHCL(0xc00051d680, 0x4e, 0x0, 0x4e)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/calculated_service_metric.go:99 +0x619
github.com/dtcookie/hcl.Export(0x1bb3e20, 0xc00051d680, 0x1bb5fa0, 0xc00000ece8, 0x4e, 0x0)
	github.com/dtcookie/hcl@v0.0.12/export.go:94 +0x35
main.importCalculatedServiceMetrics(0xc000038540, 0x28, 0xc0000300d2, 0x23, 0xc00003a014, 0x60, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/dynatrace-oss/terraform-provider-dynatrace/download.go:842 +0x446
main.downloadWith(0xc0000300d2, 0x23, 0xc00003a014, 0x60, 0x1a6e2ee, 0xd, 0xc00015dc80, 0x0)
	github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:280 +0xd6f
main.export(0xc00000c080, 0x2, 0x2, 0xc00007e058)
	github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:92 +0x6e8
main.main()
	github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:314 +0x49
`
When I try to only download the Calculated metrics the same error happens

.terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.5.0/darwin_amd64/terraform-provider-dynatrace_v1.5.0 export dynatrace_calculated_service_metric 

`panic: unsupported type []float64

goroutine 1 [running]:
github.com/dtcookie/hcl.Properties.Encode(0xc000301b30, 0x1a68c86, 0x6, 0x1909000, 0xc0002524a0, 0x0, 0x0)
	github.com/dtcookie/hcl@v0.0.12/properties.go:391 +0x2c55
github.com/dtcookie/hcl.Properties.EncodeAll(0xc000301b30, 0xc00018ea88, 0x1a6ac9e, 0x8, 0xc00018eb70)
	github.com/dtcookie/hcl@v0.0.12/properties.go:213 +0xd0
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service/comparisoninfo.(*Number).MarshalHCL(0xc00007cfa0, 0x19f3720, 0xc00007cfa0, 0x3211560)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/comparisoninfo/number.go:54 +0x2c6
github.com/dtcookie/hcl.Properties.Encode(0xc000301b00, 0x1a68806, 0x6, 0x19f3720, 0xc00007cfa0, 0x0, 0x0)
	github.com/dtcookie/hcl@v0.0.12/properties.go:369 +0xb10
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service/comparisoninfo.(*Wrapper).MarshalHCL(0xc000252480, 0x1997ae0, 0xc000252480, 0x27c93a0)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/comparisoninfo/wrapper.go:217 +0x69d
github.com/dtcookie/hcl.Properties.Encode(0xc000301ad0, 0x1a6c07d, 0xa, 0x1997ae0, 0xc000252480, 0x0, 0x0)
	github.com/dtcookie/hcl@v0.0.12/properties.go:369 +0xb10
github.com/dtcookie/hcl.Properties.EncodeAll(0xc000301ad0, 0xc00018f088, 0x1a6ac9e, 0x8, 0xc00018f160)
	github.com/dtcookie/hcl@v0.0.12/properties.go:213 +0xd0
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service.(*Condition).MarshalHCL(0xc0003015f0, 0x19b0900, 0xc0003015f0, 0x27c9300)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/condition.go:41 +0x26e
github.com/dtcookie/hcl.Properties.EncodeSlice(0xc000301a10, 0x1a6b3f0, 0x9, 0x195c220, 0xc000252400, 0x980000000195c280, 0xc00018f300, 0x100a2a3)
	github.com/dtcookie/hcl@v0.0.12/properties.go:195 +0x22b
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service.Conditions.MarshalHCL(...)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/conditions.go:22
github.com/dtcookie/hcl.Properties.Encode(0xc000301980, 0x1a6c09b, 0xa, 0x195c220, 0xc000252380, 0x0, 0x0)
	github.com/dtcookie/hcl@v0.0.12/properties.go:369 +0xb10
github.com/dtcookie/hcl.Properties.EncodeAll(0xc000301980, 0xc00018f5d8, 0x1a6ac9e, 0x8, 0xc0002171b8)
	github.com/dtcookie/hcl@v0.0.12/properties.go:213 +0xd0
github.com/dtcookie/dynatrace/api/config/metrics/calculated/service.(*CalculatedServiceMetric).MarshalHCL(0xc0002966e0, 0x52, 0x0, 0x52)
	github.com/dtcookie/dynatrace/api/config/metrics/calculated/service@v1.0.2/calculated_service_metric.go:99 +0x619
github.com/dtcookie/hcl.Export(0x1bb3e20, 0xc0002966e0, 0x1bb5fa0, 0xc00031e118, 0x52, 0x0)
	github.com/dtcookie/hcl@v0.0.12/export.go:94 +0x35
main.importCalculatedServiceMetrics(0xc0001183f0, 0x28, 0xc0000320d2, 0x23, 0xc00003a014, 0x60, 0x0, 0x0, 0x0, 0x250cb78, ...)
	github.com/dynatrace-oss/terraform-provider-dynatrace/download.go:842 +0x446
main.downloadWith(0xc0000320d2, 0x23, 0xc00003a014, 0x60, 0x1a6e2ee, 0xd, 0xc00018fdc8, 0x0)
	github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:280 +0xd6f
main.export(0xc0000301b0, 0x3, 0x3, 0xc00007e058)
	github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:121 +0x684
main.main()
	github.com/dynatrace-oss/terraform-provider-dynatrace/main.go:314 +0x49
`

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thank you for reporting that bug. Affected are Calculated Service Metrics that contain at least one condition with the "equals any of" comparison for numbers.
This bug will be fixed with the release I expect to push out on Monday.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @ppaltmann, this bug has been fixed with [v1.6.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.6.0).

**Comment by ppaltmann** [comment]
Just in time! Thanks! Will try it today.
