### ISSUE TITLE
Unable to export configuration information

### ISSUE THREAD

**Issue by Na-Nakajima** [dynatrace-oss/terraform-provider-dynatrace#550]
Describe the bug
It appears that all information cannot be retrieved by executing the following information.
```
	. /terraform-provider-dynatrace -export
	. /terraform-provider-dynatrace -export -ref
```
Going by one example, I could not get the `dynatrace_host_monitoring_mode`.

Also, I could not get it by executing the following command line.
```
	./terraform-provider-dynatrace -export dynatrace_host_monitoring_mode
```

Expected behavior
```
	./terraform-provider-dynatrace -export
	./terraform-provider-dynatrace -export -ref
```
	→I would like to be able to get all the information at once with any of the above commands.
	At the very least, we would like to be able to retrieve information by executing the commands one line at a time.
	
Desktop versions:
	OS: Ubuntu 22.04.4 LTS
	Terraform version: Terraform v1.9.7 on linux_amd64
	Dynatrace provider version: v1.68.0

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @Na-Nakajima, thanks for making us aware of that issue.
You're indeed correct - the export is currently not producing anything for these settings.

The culprit here is, that these settings are in essence not really settings stored within the environment. Applying a specific Monitoring Mode for a host is technically a remote call issued to OneAgent installed on that host. If that OneAgent is currently not connected to the environment information about the monitoring mode is literally unavailable.

We will have to discuss within the team whether it makes sense to even offer that resource. It's not only the export functionality that's affected. The above mentioned behavior also may lead to non-empty plans without a way to recover from them.

Let me get back to you after we've talked internally about how to move forward here.

thanks,
Reinhard

**Comment by Na-Nakajima** [comment]
Hello Reinhard,thank you for your reply.

I understand that the current specification is that it cannot be exported.
I am sure you will consider changing the specification in the future, but when do you plan to start considering it?
If possible, please let us know.

Thanks

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hi @Na-Nakajima 

The release we're planning to push out by the end of the week will be able to handle 
```
./terraform-provider-dynatrace -export dynatrace_host_monitoring_mode
```
as expected.

Just a few notes about the changes we had to make for that resource:

The export functionality by default just exports configuration for currently connected Agents - hosts that are monitored at the time the export. You can change that by setting the environment variable `DYNATRACE_HOST_MONITORING_OFFLINE` to `true`. Just be aware of the fact, that in that case you will get settings exported for EVERY host that was connected during the last three years

Changing the Monitoring Mode for a Host that is currently not connected to Dynatrace will not have an effect. Terraform will by default not produce any error messages in that case. But you will, of course, have to expect a non-empty plan when you're, for instance, applying configuration like this

```
resource "dynatrace_host_monitoring_mode" "some-name" {
  host_id         = "HOST-E532D48B0DBD5A6B"
  monitoring_mode = "FULL_STACK"
}
```

and the host `HOST-E532D48B0DBD5A6B` is currently not connected to Dynatrace. If that host was previously set to e.g. `INFRA_ONLY` a subsequent `terraform plan` will show that the changes still differ from your configuration. That's a limitation the provider won't be able to work around. In case you want Terraform to print out a warning in such a case, you can set the environment variable `DYNATRACE_HOST_MONITORING_WARNINGS` to `true`. Terraform will then notify you with this warning

```
╷
│ Warning: The host 'HOST-C58D4E43548A36AE' is currently offline - changing the monitoring mode was not possible
│
│   with dynatrace_host_monitoring_mode.HOST-C58D4E43548A36AE,
│   on main.tf line 1, in resource "dynatrace_host_monitoring_mode" "HOST-C58D4E43548A36AE":
│    1: resource "dynatrace_host_monitoring_mode" "HOST-C58D4E43548A36AE" {
│
╵
```

Just leave us a message here, in case that doesn't work out for you and we will re-open the ticket.
