### ISSUE TITLE
Feature request to create oauth client token

### ISSUE THREAD

**Issue by Vijayalakshmi-Yolbhavi** [dynatrace-oss/terraform-provider-dynatrace#554]
Hi,
We were looking for creating oauth client token using terraform. We have feature for creating access token but not oauth client token.
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We would like to have a module for creating oauth client via terraform.

**Describe alternatives you've considered**
None

Thanks,
Vijayalakshmi
**Additional context**
NA

**Comment by kishikawa12** [comment]
Hi @Vijayalakshmi-Yolbhavi,

Thank you for the feedback. Unfortunately this endpoint doesn't exist in the account management API and our provider is bound to what's available via the API. I would recommend to follow-up with the [Product Ideas](https://community.dynatrace.com/t5/Product-ideas/idb-p/DynatraceProductIdeas) forum. 

I'll close this ticket for the time being, but we'll continue to monitor this ticket for any additional discussion.

Thanks!
