### ISSUE TITLE
Module for creating open pipelines: Dynatrace provider

### ISSUE THREAD

**Issue by Vijayalakshmi-Yolbhavi** [dynatrace-oss/terraform-provider-dynatrace#559]
Hi,
We are looking for a module to create open pipelines in Dynatrace. Please let us know if there is already a module available.

Thanks,
Vijayalakshmi

**Comment by kishikawa12** [comment]
Hi @Vijayalakshmi-Yolbhavi, 

The OpenPipeline resources are now available with the new release [v1.69.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.69.0). 

Thanks!
