### ISSUE TITLE
(Enhancement) Break up OpenPipeline resources more

### ISSUE THREAD

**Issue by KevinThompsonYCRX** [dynatrace-oss/terraform-provider-dynatrace#561]
**Is your feature request related to a problem? Please describe.**
In large environments, separate teams will be sending data to their own buckets, and should be able to manage the processors for their own ingestion pipeline. Defining the entire OpenPipeline configuration as a single resource doesn't allow us to manage our own components. 

**Describe the solution you'd like**
It would be preferable if there were a top-level resource to hold the routes (e.g. `dynatrace_openpipeline_routes_logs`), but ideally there would be separate resources to hold each pipeline configuration (e.g. `dynatrace_openpipeline_logs`), and potentially other resources for the processors & data extractors. 

This would allow owners of different buckets to be able to manage their own ingestion patterns more effectively & in a more readable and maintainable pattern.

**Describe alternatives you've considered**
In its current state, the OpenPipeline resources are only really usable by the account admins, which isn't a feasible pattern for us to use in a larger environment.

**Additional context**

I see that the current implementation of the [OpenPipeline API](https://docs.dynatrace.com/docs/platform/openpipeline/reference/openpipeline-api) is pretty limited, so that will probably need to be extended and broken up in a similar way before these changes would be possible. 
I'm not sure where the best place would be to open a request like that. I do believe breaking up the `PUT configuration` call would also help smooth out the experience when making changes through the UI, but obviously that would be a good amount of work.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hi @KevinThompsonYCRX 

Your request doesn't come completely unexpected. You've noticed it yourself already, the OpenPipeline API comes with a couple of limitations. And the resources we've implemented are mirroring these limitations pretty much.

But we're already looking into ways to to improve that. It may take a couple of release cycles, though, so I have to ask for patience.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @KevinThompsonYCRX 

We've taken a closer look into what we could do on short notice to split up the OpenPipeline resources without having to depend on changes of the OpenPipeline API. While we may be able to conjure up something for maintaining pipelines independently, neither routes nor endpoints would be covered.

But the good new is, that Dynatrace R&D had an open ear for changes in the API. That story is unfortunately not yet scheduled in by Product Management, therefore I don't have an ETA. But once the REST API allows for a more fine granular maintenance we will revisit the relevant resources and provide something more useful.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
I'm closing this ticket until further notice. Once we've received an update for the REST API we will focus on splitting up the OpenPipeline resources.

**Comment by pradeepvenkatakrishnan** [comment]
@Reinhard-Pilz-Dynatrace We are UK Retailer account and we are large consumer of dynatrace. We have 12000 log alerts, we have 600 applications, we have to setup pipeline per application and add events using terraform. At the same time, there is a chance that user will add one or 2 events in pipeline in Dynatrace UI. Basically the terraform resources should be granular

**Comment by kishikawa12** [comment]
Hi @pradeepvenkatakrishnan ,

We completely understand you're pain and we apologize for the inconvenience. Unfortunately as developers of the Terraform provider, our hands our tied with what is available via the REST API.

The REST API currently does not offer an option to configure it more granular than what is currently offered via our provider now. 

Since this is a challenge related to the Dynatrace platform, I would recommend to follow-up with a Dynatrace support ticket to provide feedback that this is a requirement by your organization.

**Comment by Olek-Serdiuk** [comment]
Hey guys,
I see in #568 you pointed to this issue, but I believe the #568 issue should not be closed. While I fully understand that the current API uses OpenPipeline Log as a single resource, the behavior during Terraform application is problematic. When Terraform is applied, it does not indicate any changes or deletion of existing resources—it simply adds a new one. However, in reality, it overwrites the existing configuration.

This behavior can lead to significant issues. For instance, if you had 100 pipelines created manually, all of them would be lost, resulting in the loss of a large portion of your monitoring and analytics setup. This can cause severe disruptions and requires immediate attention to improve transparency and prevent unexpected resource overwrites.

From my point of view, the visibility part should be handled correctly by the Terraform provider. As far as I can see, the API includes a GET method, which could be utilized to check for existing configurations before applying changes.
Thanks
