### ISSUE TITLE
dynatrace_openpipeline_logs : data source 

### ISSUE THREAD

**Issue by Vijayalakshmi-Yolbhavi** [dynatrace-oss/terraform-provider-dynatrace#567]
Hi Team,
We are looking for data source for openpipeline.
We are using module "dynatrace_openpipeline_logs" to update the openpipeline. There is an argument "id" where we need to provide the pipeline id. Is there a way to get the pipeline id using data source?

Thanks,
Vijayalakshmi

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @Vijayalakshmi-Yolbhavi I'm closing this ticket until further notice. Just drop us a  message and we will reopen it.
