### ISSUE TITLE
Create New (non-classic) Dynatrace dashboards using environment tokens

### ISSUE THREAD

**Issue by ukho-cfreeman** [dynatrace-oss/terraform-provider-dynatrace#569]
**Is your feature request related to a problem? Please describe.**
I work in a large organisation with many environments, using OAuth tokens that have access to all environments will be a non-starter and very impractical to creating new (non-classic) dashboards in environments, in that users won't be able to self serve their creation with.

See:
https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/dynatrace/api/documents/document/service.go#L55

**Describe the solution you'd like**
The ability to create dashboards using terraform with environment access tokens similar to dashboard classic:
https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/json_dashboard

**Describe alternatives you've considered**
Using dashboard classic terraform and manually upgrading the dashboards

**Additional context**
We would like to know what is on the roadmap so we can plan accordingly.

Many thanks

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @ukho-cfreeman, apologies for the late response here.

Your request is not entirely new. Quite a lot of customers and also Dynatrace internal users have stumbled across the fact, that the subject of an OAuth client currently needs to come with unrealistically high permissions.

All that originates from the fact, that the first REST API of Dynatrace, that required OAuth was the Account Management API. 
There already exists an internal Dynatrace R&D ticket with the topic of lifting requirements here. I just cannot tell you an ETA for that.
When it comes for authentication via environment token for that REST API there is nothing scheduled yet, I'm afraid. We would gladly update the Terraform Provider in case that changes anytime in the future.

You may want to file a support ticket on the Dynatrace portal, if this is an urgent issue for you. Our Support Team is able to fast track topics that are getting reported via Zendesk ticket over and over again. We from the Terraform team unfortunately only have limited influence here.

Just drop us a message here, in case we haven't clarified your request in full. I will gladly re-open the ticket.
