### ISSUE TITLE
[Enhancement] Create alerting-profiles with Management zone name instead of mz_id

### ISSUE THREAD

**Issue by ppaltmann** [dynatrace-oss/terraform-provider-dynatrace#57]
As a user I would like to create a new alerting profile and use a management zone "name" as input. Currently I need to know the mz_id which I just get via the API as it is also not reflected in the management_zones.tf (See [Bug](https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/56)). If I use the id I can't replicate it on several clusters like North America / Europe / China clusters.

**Comment by JosephHobbs** [comment]
Not sure what you're thinking on resolution here.  The Terriform-onic way to do this would be to create a datasource for dynatrace_management_zone that allows you to look up the MZ by name and return the ID as a property of that datasource.

If you've spent any time working with the provider for AWS this is a very common practice and it's REALLY handy.  A good example would be Lambda: <https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_alias>.

This will be really handy/necessary when you get to the point where non-admin tokens can be used.  In that case teams like mine would lay down foundational stuff (like MZs, etc.) and a subsequent team would have their own Terraform project to do more.  In those cases they'll need to be able to reference the objects we created ahead of time as part of their automation.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,

You meanwhile can utilize the data source `dynatrace_management_zone` here. The data source allows you to filter by name.
