### ISSUE TITLE
Documentation: Spelling error in code sample for data source dynatrace_tenant

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [dynatrace-oss/terraform-provider-dynatrace#570]
In the code example on the page: 

* https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/tenant

When the value retrieved from the `data.dynatrace_tenant.tenant.id` is used, it is misspelled as `data.dynarace_tenant.tenant.id`.

**Comment by kishikawa12** [comment]
@jwilliams-shadowsoft Thank you for the heads up, this will be fixed in the upcoming release. Thanks!
