### ISSUE TITLE
dynatrace_http_monitor has no outputs or data resources to perform lookups

### ISSUE THREAD

**Issue by nmarchini** [dynatrace-oss/terraform-provider-dynatrace#572]
**Describe the bug**
The resource **dynatrace_http_monitor** has no defined outputs, I need to get the ID of the created resource to pass elsewhere. There are also no Data Resources to perform a lookup

**To Reproduce**
1. Go to https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/http_monitor
2. Realize there are no outputs or data resources

**Expected behavior**
1. Outputs should be documented
2. Data resources should be present

**Desktop (please complete the following information):**
 - OS: MAC Apple M1 Pro 15.0 (24A335)

**Additional context**
Terraform v1.8.5 on darwin_arm64

**Comment by kishikawa12** [comment]
Hi @nmarchini,

The resource ID can be retrieved by referencing `.id`, for example `dynatrace_http_monitor.monitor.id`.

```
resource "dynatrace_http_monitor" "monitor" {
  name      = "Example"
  frequency = 1
  locations = ["GEOLOCATION-F3E06A526BE3B4C4"]
  anomaly_detection {
    loading_time_thresholds {
    }
    outage_handling {
      global_outage = true
      global_outage_policy {
        consecutive_runs = 1
      }
    }
  }
  no_script = true
}

output "monitor" {
  value = dynatrace_http_monitor.monitor.id
}
```

Hope that helps!

**Comment by kishikawa12** [comment]
Regarding a data source for HTTP monitors, you can utilize the [dynatrace_entity](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/entity) or [dynatrace_entities](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/entities) data sources. 

Example:
```
data "dynatrace_entity" "Test" {
  type = "HTTP_CHECK"
  name = "Example"
}

output "id" {
  value = data.dynatrace_entity.Test.id
}
```

I'll go ahead close this ticket for the time being but please feel free to reopen if you have further questions, thanks!
