### ISSUE TITLE
dynatrace_mobile_application not setting the Application name correctly.

### ISSUE THREAD

**Issue by corym-vermeer** [dynatrace-oss/terraform-provider-dynatrace#573]
**Describe the bug**
dynatrace_mobile_application seems to incorrectly set the Application Name within Dynatrace to the resource name set in Terraform.

**To Reproduce**
```
resource "dynatrace_mobile_application" "TestWpfApplication" {
  name                 = "My Application Name"
  application_id       = ".<hidden>."
  application_type     = "CUSTOM_APPLICATION"
  beacon_endpoint_type = "CLUSTER_ACTIVE_GATE"
  icon_type            = "DESKTOP"
  user_session_percentage = 100
  apdex {
    frustrated          = 12000
    frustrated_on_error = true
    tolerable           = 3000
  }
}
````

**Expected behavior**
Name defined in the resource should result in the actual Application name as defined in resource

**Screenshots**
![image](https://github.com/user-attachments/assets/2ac390ad-f4eb-46d8-bf7c-7363414599a0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kishikawa12** [comment]
Hi @corym-vermeer,

That's interesting, I unfortunately wasn't able to replicate the issue in my environment and don't see anywhere in the code where that could happen on the provider side. Are you able to set the following environment variables and send the collected logs to terraform@dynatrace.com? 

```
export DYNATRACE_DEBUG=true
export DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
export DYNATRACE_HTTP_RESPONSE=true
```

What I would recommend is to test with completely new dummy names for the resource and application name just to be sure we're looking at the correct application.

Thanks!

**Comment by corym-vermeer** [comment]
Thank you! I'm closing this for now as I haven't had a chance to try to reproduce it yet.   Above debugging info will be helpful in the future.
