### ISSUE TITLE
Bindings data source

### ISSUE THREAD

**Issue by Thebridgeman** [dynatrace-oss/terraform-provider-dynatrace#578]
**Is your feature request related to a problem? Please describe.**
I need to be able to detect when a duplicate policy binding is being attempted to be bound to a group when it already exists. This errors in the deploy stage but if we have a data look up we could detect this in the build stage instead which would be better. 

**Describe the solution you'd like**
A data lookup that provides a list of policies bound to a group.

**Describe alternatives you've considered**
Can't really see an alternative way to get this information

**Additional context**
We are using: 

dynatrace_iam_policy - to create the policies
dynatrace_iam_policy_bindings_v2 - to create the bindings

Groups are being manually created in the GUI

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @Thebridgeman 

Would it help if we extended the already existing data source [dynatrace_iam_policies](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/1.69.1/docs/data-sources/iam_policies)?

This code snippet

```hcl
data "dynatrace_iam_policies" "all" {
  accounts     = ["*"]
  environments = ["*"]
  global       = true
  groups       = ["XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"]
}

output "policies" {
  value = data.dynatrace_iam_policies.all.policies
}
```

would then produce these results
```
Changes to Outputs:
  + policies = [
      + {
          + account     = ""
          + environment = "XXXXXXXX"
          + global      = false
          + id          = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX#-#environment#-#XXXXXXXX"
          + name        = "########"
          + uuid        = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
        },
      + {
          + account     = ""
          + environment = ""
          + global      = true
          + id          = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX#-#global#-#global"
          + name        = "########"
          + uuid        = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
        },
    ]
```

The additional attribute `groups` allows you to specify a list of IDs the resulting policies need to be bound to.

That would grant you access to the UUIDs of the policies and to the instance IDs within Terraform.

**Comment by Thebridgeman** [comment]
Hi @Reinhard-Pilz-Dynatrace Thanks for the speedy response. Unfortunately I don't think this will help our use case. The additional attribute of 'Groups" will allow us to specify a list of ID's the resulting policies need to be bound too, but we need a list of policies that are already bound to the group - hopefully that makes sense. Happy for this to go into another data block that you already have, e just need the list.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hi @Thebridgeman 

I believe I wasn't clear enough when explaining the solution.

Specifying the `groups` attribute **will** produce a list of policies that are already bound to the specified groups.

In other words ...

using the data source without the `groups` attribute (like it's possible now)

```hcl
data "dynatrace_iam_policies" "all" {
  accounts     = ["*"]
  environments = ["*"]
  global       = true 
}
```

will produce **all** policies - defined for any account or environment and even the global policies.

.. and using the data source **with** the groups attribute

```hcl
data "dynatrace_iam_policies" "all" {
  accounts     = ["*"]
  environments = ["*"]
  global       = true
  groups       = ["XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"]
}
```
will restrict the results down to the policies that are already bound to these groups.

Or am I still misinterpreting your requirement?

**Comment by Thebridgeman** [comment]
@Reinhard-Pilz-Dynatrace I understand now, that puds like it will work perfectly for us - thanks you very much! When can we expect to be able to use this feature please?
