### ISSUE TITLE
[Bug] donwload custom_services with wrong resource

### ISSUE THREAD

**Issue by jonormann** [dynatrace-oss/terraform-provider-dynatrace#58]
when downloading custom services with the download option of the provider the resource for custom services is "dynatrace_dashboard" but should be "dynatrace_custom_service".
found in version 1.4 and 1.5
Best
Joerg

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for reporting. This bug must have existed from the very beginning without anynone having noticed it.
It'll be fixed with the next release.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @jonormann, this bug has been fixed with [v1.6.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.6.0).
