### ISSUE TITLE
Support for the Account Management API

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#6]
I'd love to see future support for the Account Management API.  Specifically, the management the groups and permissions.

Our use case is for onboarding applications into Dynatrace for monitoring.  In addition to creating resources within the Dynatrace tenant itself (management zones, alerting profiles, etc.) we need to be able to create and entitle groups within the account.

Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
The Cluster REST API is already on our radar.
User Groups and Users will be the first endpoints that are supported.

Thanks!
