### ISSUE TITLE
Undescriptive error message when performing export with environment url containing trailing slash

### ISSUE THREAD

**Issue by joostvz** [dynatrace-oss/terraform-provider-dynatrace#60]
I'm using version 1.5.0 of the provider and tried to run the export command. It failed with the following error message:

> invalid character '<' looking for beginning of value

After some digging I found that I entered the environment url with a trailing slash in the DYNATRACE_ENV_URL environment variable: _https://#######.live.dynatrace.com/_  When I remove the trailing slash, the export command works correctly.

I couldn't capture the outgoing request with Fiddler, but I guess the provider will append "/api/something" to the specified url, which will result in an invalid request to _https://#######.live.dynatrace.com//api/something_. If I run such an API request in Postman, Dynatrace returns an error page in HTML, which starts with '<'.

The provider can be improved in two ways, either:
1. Handle trailing slashes correctly, or
2. Give a better error message when the url is invalid

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for reporting that bug. You're right, we need to add a couple of sanity checks here. I'll keep this ticket open until the changes you've suggested are implemented.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
This issue has been fixed with [Release v1.11.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.11.0).
