### ISSUE TITLE
dynatrace_azure_credentials `label` field is optional but required by API

### ISSUE THREAD

**Issue by Kidsan** [dynatrace-oss/terraform-provider-dynatrace#603]
**Describe the bug**
The dynatrace resource `dynatrace_azure_credentials` has the `label` field as optional and shows no errors in plans. Upon applying, the API responds with an error and the terraform apply fails with just the error `may not be empty`

**To Reproduce**
```
resource "dynatrace_azure_credentials" "#name#" {
  active                       = false
  app_id                       = "ABCDE"
  auto_tagging                 = true
  directory_id                 = "ABCDE"
  key                          = "aaaa"
  monitor_only_tagged_entities = true

  monitor_only_tag_pairs {
    name  = "string"
    value = "string"
  }
  remove_defaults = true
}
```

**Additional context**
Confirmed with API docs: https://docs.dynatrace.com/docs/discover-dynatrace/references/dynatrace-api/configuration-api/azure-credentials-api/post-new-credentials

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @Kidsan, thanks for reporting this bug. It will be taken care of with the next release of the provider.
