### ISSUE TITLE
Implement Data Sources for Country Codes and Region Codes

### ISSUE THREAD

**Issue by Reinhard-Pilz-Dynatrace** [dynatrace-oss/terraform-provider-dynatrace#604]
As mentioned in #601 the basis for accepted Region Codes and Country Codes when creating / updating a Synthetic Location have recently changed.

Initially they could get deducted using the [ISO 3166-2 standard](https://dt-url.net/iso3166-2) and from [FIPS 10-4 codes](https://en.wikipedia.org/wiki/List_of_FIPS_region_codes). 

The new behavior defines the REST endpoints [GET regions of the country](https://dt-url.net/az230x0) and [GET all countries](https://dt-url.net/37030go) for accepted region and country codes.

In order to have these valid codes available conveniently within Terraform Data Sources (e.g. `dynatrace_geo_region` and `dynatrace_geo_country`) will be helpful.

**Comment by kishikawa12** [comment]
The next release will include three new data sources `dynatrace_geo_countries`, `dynatrace_geo_regions`, and `dynatrace_geo_cities` which will address this enhancement.
