### ISSUE TITLE
dynatrace_hub_extension_config requires different API token scopes as documented

### ISSUE THREAD

**Issue by matthias-huber** [dynatrace-oss/terraform-provider-dynatrace#613]
**Describe the bug**
The documentation for resource "Hub Extension Config" (Monitoring configurations) requires more/other API Token scopes as documented on https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/docs/resources/hub_extension_config.md
API tokens extensions.write, extension.read and hub.read result in no export.

**To Reproduce**
1. Create API Token with scopes: extensions.write, extension.read and hub.read
2. A Monitoring configurations has to be available
3. Export with token from 1:  "terraform-provider-dynatrace -export dynatrace_hub_extension_config" => NO monitoring configurations are exported
4. Create API Token with scopes: ??? (I used hub.install and hub.write for testing)
5. Export with token from 4 "terraform-provider-dynatrace -export dynatrace_hub_extension_config" => monitoring configurations are exported

**Expected behavior**
* Documentations provides the necessary API token scopes that are required to use the export.
* Export tool should provide an information/error that necessary API token scopes are missing.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hi @matthias-huber, thanks for bringing this issue to our attention. I've done some local testing. Looks like permissions `extensionConfigurations.read`, `extensionConfigurations.write` are meanwhile necessary for everything to work without problems. 

I've updated the documentation in this repo already. The changes will be visible within the Terraform Registry after our next release.

We also have plans for having the export functionality to print out the exact permissions that are missing for resources that are not getting exported. That will required, however, for a rather drastic refactoring, and will come early next year. It won't be included in this small fix.
