### ISSUE TITLE
dynatrace_automation_workflow task being falsely registered as workflow resource 

### ISSUE THREAD

**Issue by jparrottOneStream** [dynatrace-oss/terraform-provider-dynatrace#615]
**Describe the bug**
When running Terraform import on a dynatrace_automation_workflow resource, Terraform complains that the first task in a list of many tasks is not a workflow resource that already exists within the configuration. It seems to be reading the first task as another missing workflow instead of a task. The other tasks in the list are ignored within this condition.

**To Reproduce**
1.) Export a workflow using the Dynatrace terraform provider and a specific ID to create the *.tf file(s) for your workflow(s).
2.) Run a terraform import on the resource:

`terraform import module.automation_workflow.dynatrace_automation_workflow.SomeWorkflowName 12345678-7104-494b-b5f1-5bae536f5d93`

3.) Observe the following error:
```
Error: resource address "module.automation_workflow.dynatrace_automation_workflow.create_bizevent" does not exist in the configuration.

Before importing this resource, please create its configuration in module.automation_workflow. For example:

resource "dynatrace_automation_workflow" "create_bizevent" {
  `# (resource arguments)
}`
```
**Expected behavior**
The workflow should import with no issues and not expect a task within the "tasks" block to be an additional workflow resource.

**Screenshots**

![image](https://github.com/user-attachments/assets/94e483ca-a730-4b1c-b15c-006b7d7d7c62)
![image](https://github.com/user-attachments/assets/99e18f8f-1918-4568-94da-aea3c62cc3ca)

**Terraform Version**
1.6.6

**Dynatrace Provider Version**
1.70.0

**Additional context**
If I create a blank resource block for the first task in the list of tasks, but I create it as a workflow resource instead, then the referencing workflow imports fine with no errors.

A terraform plan works without errors. It's the import that seems to be where this error comes through.

**Comment by Reinhard-Pilz-Dynatrace** [comment]
Hello @jparrottOneStream 

You must have executed

```
terraform import module.automation_workflow.dynatrace_automation_workflow.create_bizevent ########-####-####-####-############
```

The error message `Error: resource address "module.automation_workflow.dynatrace_automation_workflow.create_bizevent" does not exist in the configuration.` doesn't allow for any other conclusion.

What doesn't add up here is the screenshot you have shared. There resource in there clearly goes by the name `Business_Rule_Span_to_BizEvent_ingest`.

```hcl
# ID ########-####-####-####-############
resource "dynatrace_automation_workflow" "Business_Rule_Span_to_BizEvent_ingest" {
  ...
  tasks {
    task {
      name = "create_bizevent"
      ...
    }
    task {
      name = "business_rule_spans"
      ...
    }
  }
}
```

In that case it is not surprising, that Terraform complains about the fact, that nowhere in your configuration it is able to find a resource of type `dynatrace_automation_workflow` with the name `create_bizevent`. That `create_bizevent` is just the name of a task with in the workflow.

What I believe you _should_ have executed is

```
terraform import module.automation_workflow.dynatrace_automation_workflow.Business_Rule_Span_to_BizEvent_ingest ########-####-####-####-############
```

Let me know if that helps. Perhaps I have misunderstood your issue here.

**Comment by jparrottOneStream** [comment]
Hi @Reinhard-Pilz-Dynatrace. Thank you for this. It helped me take a step back and look at the problem again. We are automating the export/import of Dynatrace resources based on an AZDO pipeline that our end users can use to move resources between environments.

Sure enough, our current code was handling request attributes, custom services, and document types just fine, but automation workflows have a slightly different format to their .tf structure, so our script was inadvertently running an import on any line with a "name="  which would include the tasks.

Problem solved. Thank you!
