### ISSUE TITLE
[Feature Request] Synthetic Monitoring Resource

### ISSUE THREAD

**Issue by cw1797** [dynatrace-oss/terraform-provider-dynatrace#62]
Would be great to be able to be able to have a resource in place for the management of synthetic monitors as currently I dont see this supported currently and we are using the UI to manually created these at the moment.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @cw1797 ,

Synthetic Monitors already have been requested with #54. Currently you can expect `dynatrace_synthetic_monitor` available in September.
I'm closing this ticket as duplicate
