### ISSUE TITLE
[Enhancement] add global request_naming_rule

### ISSUE THREAD

**Issue by jonormann** [dynatrace-oss/terraform-provider-dynatrace#66]
Hi,
please add dynatrace_request_naming_rule.
At a customer we have several global requst naming rule that are currently set using monaco framework or raw API.
Would be nice to do that with terraform as nearly all the other configs are currently moved away from using monaco to terraform.

Best
Joerg

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @jonormann
Sorry for neglecting this request until now. I'll try to squeeze this into the next update.

**Comment by kishikawa12** [comment]
Closing this ticket since the feature/functionality is now available via the resource `dynatrace_request_naming`, thanks!
