### ISSUE TITLE
Getting SLO information causes Bad Request (GET) error

### ISSUE THREAD

**Issue by shahakht** [dynatrace-oss/terraform-provider-dynatrace#67]
Version Info: version = "1.7.0"
    
I am using Dynatrace to create SLOs. SLO is created successfully but then Dynatrace throws following error. I double checked that my token has slo.read and slo.write permission

│ Error: Bad Request (GET) https://Dynatrace-URL/e/tenant-ID/api/v2/slo?sloSelector=id("xxxx")&pageSize=10000&sort=name&timeFrame=CURRENT&pageIdx=1&demo=false&evaluate=false

Running same command using curl and api-token is successful

curl --request GET \
  --url "https://Dynatrace-URL/e/tenant-ID/api/v2/slo?sloSelector=id("xxxxxxx")&pageSize=10000&sort=name&timeFrame=CURRENT&pageIdx=1&demo=false&evaluate=false&api-token=xxxxxxxx"

Response of curl command: 

{"totalCount":1,"pageSize":10000,"slo":[{"id":"xxxxxxx,"enabled":true,"name":"test","description":"","evaluatedPercentage":-1.0,"errorBudget":-1.0,"status":"SUCCESS","error":"NONE","useRateMetric":false,"metricRate":"","metricNumerator":"builtin:service.errors.server.successCount:splitBy()","numeratorValue":-1.0,"metricDenominator":"builtin:service.requestCount.server:splitBy()","denominatorValue":-1.0,"target":95.0,"warning":97.0,"evaluationType":"AGGREGATE","timeframe":"-1h","filter":"type(\"service\"),entityName(xxxx)","relatedOpenProblems":0}]}%

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @shahakht ,

Release 1.7.1 contains a couple of tweaks regarding SLOs. I'm however not entirely sure whether it also takes care of your issues.
Would you be willing to share your configuration in case 1.7.1 still shows the same issues?

thanks,
Reinhard

**Comment by shahakht** [comment]
@Dynatrace-Reinhard-Pilz I will test with 1.7.1 today and will let you know the outcome

**Comment by shahakht** [comment]
@Dynatrace-Reinhard-Pilz unfortunately 1.7.1 did not address the issue. It also shows following warning about parameters being deprecated but 1.7.1 documentation https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/slo does not highlight it

`Warning: Argument is deprecated
│
│    8:   numerator   = var.numerator
│ 
│ `numerator` and `denominator` have been replaced by `metric_expression``

@Dynatrace-Reinhard-Pilz what config info other than the one below would you require ?

Terraform: 1.0.0
Dynatrace module: 1.7.1
API Token capabilities: 

- V1: Read configuration, Write configuration

- V2: Read SLO, Write SLO

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@shahakht I'm hoping to use your exact HCL configuration for the SLOs you're trying to create for local tests.
If the issue you're facing is triggered by a very specific configuration which I'm apparently not testing against, your HCL code would help me pinpoint the root cause. 
The other possibility is, that this only occurs when run against 1.220 of Dynatrace.

If you're running 1.220 on your Dynatrace Server, you please don't worry about the deprecation messages. Starting with 1.224 the REST API will prefer the attribute `metric_expression`. But even then your configuration will get accepted. That's because of an unfortunate change in the REST API I wasn't able to cover better than using deprecated attributes.

Thanks for the hint about the documentation. I forgot to regenerate it before releasing todays version. I'm planning to release 1.7.2 tomorrow where the documentation will be updated.

Thanks,
Reinhard

**Comment by shahakht** [comment]
[slo_work.zip](https://github.com/dynatrace-oss/terraform-provider-dynatrace/files/7155455/slo_work.zip)

@Dynatrace-Reinhard-Pilz  attached is module I created for creating SLO

The way its being called is

module "slos" {
  for_each      = var.availability_slo_services
  source        = "PATH TO MODULE"
  name          = each.value.slo_name
  entity_filter = "type(${each.value.entity_type}),entityName(${each.value.entity_name})"
}

value of **availability_slo_services** is

variable "availability_slo_services" {
  description = "List of services information for which availability SLO shall be created"
  type = map(object({
    slo_name    = string
    entity_name = string
    entity_type = string
  }))
  default = {
    api-gateway = {
      slo_name : "tf-test-slo"
      entity_name : "test-entity"
      entity_type : "service"
    }
  }
}

**Comment by shahakht** [comment]
@Dynatrace-Reinhard-Pilz I also tried with 1.7.2 version but still same issue. SLO is created but get command after it fails. Running same command along with API token works when using curl

Here are snippets from terraform-provider-dynatrace.log after removing confidential information



2021/09/14 16:43:17 POST https://URL/api/v2/slo

2021/09/14 16:43:17   Request Body: {"name":"tf-availability","enabled":true,"useRateMetric":false,"metricRate":"","metricNumerator":"builtin:service.errors.server.successCount","metricDenominator":"builtin:service.requestCount.server","evaluationType":"AGGREGATE","filter":"type(service),entityName(api-gateway)","target":95,"warning":97,"timeframe":"-1w"}
2021/09/14 16:43:17   201 Created

2021/09/14 16:43:17 GET https://URL/api/v2/slo?sloSelector=id("dc40da18-e9ec-374c-a359-5ec06700dabf")&pageSize=10000&sort=name&timeFrame=CURRENT&pageIdx=1&demo=false&evaluate=false
2021/09/14 16:43:18   400 Bad Request
2021/09/14 16:43:18   Response Body: <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thanks for trying it out. Version 1.7.2 did however not contain any changes for your specific issue. It takes care of unpredictable delays after an SLO has been created until it is available via GET request.
I will have to set up a Dynatrace Cluster running on 1.220 in order to diagnose your issue. Right now tapping a bit in the dark, given the fact, that you can execute that GET request manually and it succeeds.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@shahakht are you still experiencing these issues? I have not been able to reproduce this with any cluster version so far.

**Comment by shahakht** [comment]
> @shahakht are you still experiencing these issues? I have not been able to reproduce this with any cluster version so far.

We are now using Dynatrace APIs to create SLOs so we can close this ticket
