### ISSUE TITLE
add terraform import support

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#7]
It would be great if the provider supported the terraform import command.  Currently when I attempt to import a management zone, the command reports that import is not supported.

```
$ terraform import module.mz_poc_sandbox.dynatrace_management_zone.zone 12345
module.mz_poc_sandbox.dynatrace_management_zone.zone: Importing from ID "12345"...

Error: resource dynatrace_management_zone doesn't support import
```

**Comment by Dynatrace-Reinhard-Pilz** [comment]
At the moment just Custom Services support terraform import.
We're currently working on providing the full feature set for all other resources.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
All resources support `terraform import` with [v1.0.5](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.0.5)
