### ISSUE TITLE
[Enhancement] Modify "service level settings" using terraform

### ISSUE THREAD

**Issue by kannanbalaji** [dynatrace-oss/terraform-provider-dynatrace#76]
Hi Team,

### [Modify **Service Settings** ​using terraform.
As a customer, we are trying to create a starter kit for development teams to updated "Service settings".

**Service Settings** = Access any Service >> Edit >> Service settings >>Terraform to (create/edit Naming, Error Detection,Web request naming, Anomaly detection)

Regards,
Balaji

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @kannanbalaji 

Quick update about this topic. Anomaly Detection and Error Detection on Service Level will be available via REST API by the end of March. At this point I'll start implementing the resources within the Terraform Provider.
The REST API for Request Naming has unfortunately gotten pushed back until July - here I need to ask for a bit more patience.

**Comment by kishikawa12** [comment]
Hi @kannanbalaji,

I'll be closing this ticket for the time being as we're currently up-to-date on all service level settings offered by our REST API. We'll continue to add new resources as new API endpoints are introduced.

Thanks!
