### ISSUE TITLE
"dynatrace_azure_credentials" doesn't seem to support when the `monitor_only_tagged_entities` entity is false

### ISSUE THREAD

**Issue by Forcebyte** [dynatrace-oss/terraform-provider-dynatrace#77]
I'm using https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/azure_credentials to attempt to automatically load credentials into Azure - and I'm starting to notice something fairly odd

## Main issue I see:
Here's the parameters of the call I usually make via Postman or cURL:
```
{
  "label": "Really cool Environment",
  "appId": "<removed>",
  "directoryId": "<removed>",
  "key": "<removed>",
  "active": true,
  "autoTagging": true,
  "monitorOnlyTaggedEntities": false,
}
```
^ This works today, however in Terraform:

```
# Azure Integration
resource "dynatrace_azure_credentials" "azure_dyna_integration" {
  # Base Azure Integration
  monitor_only_tagged_entities = false
  label = "Really cool Environment"
  active = true
  auto_tagging = true
  app_id = "<removed>"
  directory_id = "<removed>"
  key = var.dynatrace_azure_token
}
```

I get the following:
```
│ Error: {
│   "code": 400,
│   "message": "Constraints violated.",
│   "constraintViolations": [
│     {
│       "parameterLocation": "PAYLOAD_BODY",
│       "location": "",
│       "message": "must not be null",
│       "path": "monitorOnlyTagPairs"
│     }
│   ]
│ }
│ 
│   with dynatrace_azure_credentials.azure_dyna_integration,
│   on main.tf line 17, in resource "dynatrace_azure_credentials" "azure_dyna_integration":
│   17: resource "dynatrace_azure_credentials" "azure_dyna_integration" {
```

^ This honestly stumped me, so I started to dig into it - the TF docs state:
>monitor_only_tag_pairs (Block List, Max: 10) A list of Azure tags to be monitored. You can specify up to 10 tags. A resource tagged with any of the specified tags is monitored. Only applicable when the monitorOnlyTaggedEntities parameter is set to true (see below for nested schema)

Which is really odd, since we're setting it false via the `monitor_only_tagged_entities = false` param im setting

I suspect that either the API has changed (https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/azure-credentials-api/post-new-credentials/) or the TF operator is always sending in the 'monitorOnlyTaggedEntities' property to always be true - I did some digging and could not find that occuring here - so i'm a bit stumped

**Comment by Forcebyte** [comment]
(for now making a support ticket, figured i'd log here just in case this is expected behavior and i'm doing something totally off)

**Comment by Dynatrace-Reinhard-Pilz** [comment]
@Forcebyte Posting bug reports here is the best channel. I'll take a look at this right now.

**Comment by kamiljsokolowski** [comment]
I've managed to test the above config locally and have observed no such error.

Could you please enable Terraform [debugging](https://www.terraform.io/docs/internals/debugging.html) on your console and attach the generated log file so that we can investigate further?

**Comment by Forcebyte** [comment]
Hey @wojtasskorcz and @kamiljsokolowski, thanks for the follow-up, appreciated

This was fixed by Reinhard's commit here - https://github.com/dtcookie/dynatrace/commit/1b739af5cb42b65b92a533685294803c19ad0832#diff-f0e803bb61cb75d99bf27de2853b5175038a99359bb2fd949d101526a77ccce7R141 - Its more of a misnomer with the Azure Credentials API  - I believe the release of the new version (1.7.3) fixes this

## Before 1.7.3

### Body (ignore the extra var lookup mappings here, just some extra logic):
```
resource "dynatrace_azure_credentials" "azure_dyna_integration" {
  provider = dynatrace.dynatrace-nonp
  # Base Azure Integration
  monitor_only_tagged_entities = false
  label = lookup(var.dynatrace_azure_environment_name_map, "nonp")
  active = true
  auto_tagging = true
  app_id = lookup(var.dynatrace_azure_clientid_map, "nonp")
  directory_id = var.dynatrace_azure_tenantid
  key = lookup(var.dynatrace_azure_clientsecret_map, "nonp")
}
```

### Result from Dynatrace
```
Do you want to perform these actions in workspace "nonp"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

dynatrace_azure_credentials.azure_dyna_integration: Creating...
╷
│ Error: {
│   "code": 400,
│   "message": "Constraints violated.",
│   "constraintViolations": [
│     {
│       "parameterLocation": "PAYLOAD_BODY",
│       "location": "",
│       "message": "must not be null",
│       "path": "monitorOnlyTagPairs"
│     }
│   ]
│ }
│ 
│   with dynatrace_azure_credentials.azure_dyna_integration,
│   on main.tf line 31, in resource "dynatrace_azure_credentials" "azure_dyna_integration":
│   31: resource "dynatrace_azure_credentials" "azure_dyna_integration" {
│ 
```

## After 1.7.3

### Body (ignore the extra var lookup mappings here, just some extra logic):
```
resource "dynatrace_azure_credentials" "azure_dyna_integration" {
  provider = dynatrace.dynatrace-nonp
  # Base Azure Integration
  monitor_only_tagged_entities = false
  label = lookup(var.dynatrace_azure_environment_name_map, "nonp")
  active = true
  auto_tagging = true
  app_id = lookup(var.dynatrace_azure_clientid_map, "nonp")
  directory_id = var.dynatrace_azure_tenantid
  key = lookup(var.dynatrace_azure_clientsecret_map, "nonp")
}
```

### Result from Dynatrace
```
Do you want to perform these actions in workspace "nonp"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

dynatrace_azure_credentials.azure_dyna_integration: Creating...
dynatrace_azure_credentials.azure_dyna_integration: Creation complete after 1s [id=AZURE_CREDENTIALS-86AD59C1FFD0F322]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Thank you again @Dynatrace-Reinhard-Pilz! If I knew GoLang better I'd contribute as much as I can 🙏
