### ISSUE TITLE
add support for aws credential

### ISSUE THREAD

**Issue by JosephHobbs** [dynatrace-oss/terraform-provider-dynatrace#8]
one resource I could really use support for would be the creation and management of aws credentials.  I'm using a generic REST provider to do it right now, but terraform is pretty limited once you start considering additional supported services.

Thank you!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Release v1.0.6 will contain credentials for k8s, PCF, AWS and Azure

**Comment by Satak** [comment]
Any timeline for 1.0.6 release? We are waitong Azure credential creation and environment creation. Can you setup milestone so we can see the track of future releases? Any roadmap for this provider? Please also create examples how to use each resource blocks. Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Satak. Release 1.0.6 will be available early next week.
Focus of 1.0.7 will be primarily SLOs.
Our eventual goal is to cover the full configuration REST API of Dynatrace eventually. The order of which settings to implement earlier than others essentially depends on customer input here on GitHub.
What kinds of configuration settings are currently most important for you?

**Comment by Satak** [comment]
> What kinds of configuration settings are currently most important for you?

Currently setting up new environment and azure credentials and discovery would be a good start.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Fixed with [v1.0.6](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/edit/v1.0.6)
