### ISSUE TITLE
[Enhancement] add synthetic monitors

### ISSUE THREAD

**Issue by kannanbalaji** [dynatrace-oss/terraform-provider-dynatrace#80]
Hi Team,

Please add  synthetic monitors
As a customer, we want to leverage "synthetic monitors" to test our services.
Use cases: 
1. Use them as external health checks.
2. Use them to setup high priority alerts based on the external health check results.

Regards,
Balaji

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @kannanbalaji ,
Good news, I'm hoping to have Synthetic Monitors ready by Friday with Release 2.8.0

**Comment by anshulgargamway** [comment]
@Dynatrace-Reinhard-Pilz Any update on same !! We are waiting for this feature since long.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Again, sorry for the constant delays. I'm happy to announce that [v1.80](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.8.0) covers Synthetic Monitors.
