### ISSUE TITLE
dashboard_sharing fails with "Dashboard does not exist"

### ISSUE THREAD

**Issue by maciej-wilczynski** [dynatrace-oss/terraform-provider-dynatrace#89]
Hi, I'm creating dashboard and dashboard sharing with one apply, and it ends with:
```
dynatrace_dashboard.test: Creating...
dynatrace_dashboard.test: Creation complete after 1s [id=XXXXXXXXXXXXXXXX]
dynatrace_dashboard_sharing.test: Creating...
╷
│ Error: {
│   "code": 400,
│   "message": "Constraints violated.",
│   "constraintViolations": [
│     {
│       "parameterLocation": "PAYLOAD_BODY",
│       "location": "",
│       "message": "Dashboard does not exist",
│       "path": ""
│     }
│   ]
│ }
│ 
│   with dynatrace_dashboard_sharing.test
│   on dynatrace_dashboard_test.tf line 178, in resource "dynatrace_dashboard_sharing" "test":
│  178: resource "dynatrace_dashboard_sharing" "test" {
```

my configuration of dashboard_sharing looks:
```terraform
resource "dynatrace_dashboard_sharing" "test" {
  depends_on   = [dynatrace_dashboard.test]
  enabled      = true
  dashboard_id = dynatrace_dashboard.test.id
  preset       = true
  permissions {
    permission {
      type  = "ALL"
      level = "VIEW"
    }
  }
}
```

even with depends_on it fails. looks like api answers 404 for dashboard when it used to create sharing

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,
We've introduced code now that works around situations like @Forcebyte has described.
In case the Cluster is not yet fully aware of the existence of a newly created dashboard, the resource `dynatrace_dashboard_sharing` retries for up to 100 seconds to configure the share settings.

I wouldn't necessarily call this a fix - any threshold here, no matter how high, may still not be enough on a busy cluster. But the solution we've introduced at least doesn't require any special handling within the HCL code anymore.
