### ISSUE TITLE
Add support for Kubernetes Credential

### ISSUE THREAD

**Issue by jonatan-b-kr** [dynatrace-oss/terraform-provider-dynatrace#9]
Right now we are using the Mastercard REST provider using the `/kubernetes/credentials` endpoint in the Dynatrace API to set this up. 
It would be great to have this as a provider native terraform resource.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Release v1.0.6 will contain credentials for k8s, PCF, AWS and Azure

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Fixed with [v1.0.6](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/edit/v1.0.6)

**Comment by jonatan-b-kr** [comment]
Does this include documentation? i don't see the credential resource in the Dynatrace provider from terraform registry

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Apologies, I forgot to generate documentation before creating the release.
It unfortunately won't be reflected in the documentation on the Terraform Registry, but you can look up the most recent docs 
[here](https://github.com/dynatrace-oss/terraform-provider-dynatrace/tree/main/docs/resources) on GitHub.
