### ISSUE TITLE
dynatrace_http_monitor resource is missing authentication support.

### ISSUE THREAD

**Issue by anshulgargamway** [dynatrace-oss/terraform-provider-dynatrace#90]
Hello All,

After going through the documentation of https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/http_monitor#nestedblock--script--request--configuration unable to support for authentication/authorization option which is availble in UI.
Can you please help here.
![image](https://user-images.githubusercontent.com/86303583/138662284-91d94686-f89d-45b9-a601-f5ba7764606f.png)

Able to find this support in terraform provider for Browser Monitor though

Thanks & Regards
Anshul Garg

**Comment by anshulgargamway** [comment]
@Dynatrace-Reinhard-Pilz  Can you please help here

**Comment by xcheng75** [comment]
> Hi @Dynatrace-Reinhard-Pilz , Please let us know if this is going to be released soon. " associating credentials with following events
> 
> keystrokes click

I am having the same question.

**Comment by msmost** [comment]
Hi @Dynatrace-Reinhard-Pilz we are also interested having this functionality.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,

I'm going to look into that within the next few weeks.

**Comment by ashishamway** [comment]
Hi Team,

Has anyone begun to work on this problem? 
I am keenly waiting for this.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,

Again sorry for the delay here.

Support for Authentication of Requests within HTTP Monitors will definitely be part of the next release. I still have to look into Authentication for Browser Click Paths, but I'm confident adding support here will be very similar.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello everyone,

[Release v1.13.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.13.0) comes with authentication support for `dynatrace_http_monitor`.
