### ISSUE TITLE
Create problem notification using terraform and make the "Authorization header" secret

### ISSUE THREAD

**Issue by kannanbalaji** [dynatrace-oss/terraform-provider-dynatrace#93]
Currently, there is no option to make the "Authorization header" secret using the API or terraform.
Please add the ability to make the "Authorization header" secret.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @kannanbalaji ,

This issue has been addressed with release 1.18.1. Let me know in case it still doesn't work.

**Comment by aakdjkf** [comment]
@Dynatrace-Reinhard-Pilz  Is there document about how should I use this feature in terraform? I didn't see example in this link. https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/webhook_notification#secret_value
Thank you!
