### ISSUE TITLE
dynatrace_dashboard fails with "Constraints violated."

### ISSUE THREAD

**Issue by krkolla** [dynatrace-oss/terraform-provider-dynatrace#95]
Hi, I am trying to create dashboard without "owner". it ends with error below  

`Error: {
  "code": 400,
  "message": "Constraints violated.",
  "constraintViolations": [
    {
      "parameterLocation": "PAYLOAD_BODY",
      "location": "",
      "message": "must not be null",
      "path": "dashboardMetadata.owner"
    }
  ]
}`

Dashboard document says, "owner" is optional variable. 
https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/dashboard
Is this `required` or `optional` variable? Please suggest us. 

Thank you, 
Kolla.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Sorry for the late response - I've been unavailable for quite some time.
You're right, the "owner" is apparently not anymore optional. I've done some research, it looks like the REST API used to accept Dashboards without an owner specified in the past, but that has changed.
I need to ask for patience until coming Friday/Monday for a new version that includes that fix. There is quite some backlog of issues I need to take care of before pushing out a new release.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
The documentation for 1.9.0 now specifies the owner as `required`.
