### ISSUE TITLE
403 Error Message when trying to export

### ISSUE THREAD

**Issue by arnauagithub** [dynatrace-oss/terraform-provider-dynatrace#96]
The following error messages occurs when trying to use:
./terraform-provider-dynatrace export

Error message:
{
  "code": 403,
  "message": "Editing or deleting a non user specific dashboard preset is not allowed. Dashboard bf71f71f-d8ee-4145-b054-3526bb194141",
  "constraintViolations": null
}

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Sorry for the late response here - I've been unavailable for quite some time.
I'm asking for patience until coming Monday, when I'm pushing out a new version of the Provider with several bug fixes.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Release 1.9.0 takes care of this issue
