### ISSUE TITLE
Datasource dynatrace_synthetic_locations is missing cloud_platform values 

### ISSUE THREAD

**Issue by Galileo1** [dynatrace-oss/terraform-provider-dynatrace#97]
Seems like there is no way to distinguish between two locations with same name. If I filter by name "Sydney" it gives me more than one occurrences. I think we would like to be specific with either by name or cloud_platform. cloud_platform is empty string or not being populated at the moment [here](https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/resources/synthetic/locations/data_source.go#L69-L73).

` {
       cloud_platform = ""
       id = "GEOLOCATION-BD97XXXA2DB40EE"
       ips = []
       name = "Sydney"
       stage = ""
       status = ""
       type = "PUBLIC"
},
 {
     cloud_platform = ""
    id = "GEOLOCATION-2FDXXXX4DE4D601"
    ips = []
    name = "Sydney"
    stage = ""
    status = ""
    type = "PUBLIC"
},`

However api does return cloudPlatform field 

`{
         "name" : "Sydney",
         "ips" : [
           "xx.xx.xx.xx"
         ],
         "status" : "ENABLED",
         "cloudPlatform" : "ALIBABA",
         "entityId" : "GEOLOCATION-BD9xxxxxxx2DB40EE",
         "stage" : "BETA",
         "type" : "PUBLIC",
         "capabilities" : [
            "BROWSER",
            "HTTP"
         ]
      },
      {
         "name" : "Sydney",
         "ips" : [
             "XXX.XX.XX.XX"
         ],
         "status" : "ENABLED",
         "cloudPlatform" : "GOOGLE_CLOUD",
         "entityId" : "GEOLOCATION-08BXXXXXDA6",
         "stage" : "GA",
         "type" : "PUBLIC",
         "capabilities" : [
            "BROWSER",
            "HTTP"
         ]
      },
`

https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/data-sources/synthetic_locations

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @Galileo1 
Sorry for the very late response here. I will take a look at that after releasing 1.10.0. A solution is definitely possible, but I won't be able to fit it into the next release.
thanks,
REinhard

**Comment by Dynatrace-Reinhard-Pilz** [comment]
This issue has been fixed with [Release v1.11.0](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.11.0).
