### ISSUE TITLE
Recreating a deleted k8s_credentials resources leads to a 404

### ISSUE THREAD

**Issue by franznemeth** [dynatrace-oss/terraform-provider-dynatrace#98]
We are using the k8s_credentials resource to add our EKS clusters to dynatrace.

When deleting the kubernetes connection outside of terraform, terraform is not able to run through until you recreate it manually.

module.somemodule.kubernetes_service_account.dynatrace_kubernetes_monitoring: Refreshing state... [id=default/dynatrace-kubernetes-monitoring]
This is the output I get from `terraform plan`
```
│ Error: {
│   "code": 404,
│   "message": "Configuration 'KUBERNETES_CLUSTER+SOMEID' not found.",
│   "constraintViolations": null
│ }
│
│
```

This is the terraform configuration in question:
```
resource "dynatrace_k8s_credentials" "this" {
  label                               = var.cluster_name
  active                              = true
  auth_token                          = "sometoken"
  events_integration_enabled          = true
  davis_events_integration_enabled    = true
  certificate_check_enabled           = false
  endpoint_url                        = "someendpoint"
  event_analysis_and_alerting_enabled = true
  prometheus_exporters                = true
  workload_integration_enabled        = true
  events_field_selectors {
    active         = true
    field_selector = "involvedObject.kind=Node"
    label          = "Node events"
  }
  events_field_selectors {
    active         = true
    field_selector = "involvedObject.kind=Pod,type=Warning"
    label          = "Pod warning Events"
  }
}
```

I would expect the terraform module to try to recreate the connection in case it was removed outside of terraform

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @franznemeth 
Configurations running out of sync because of changes outside of Terraform are a known obstacle. Taking care of them is unfortunately not always that simple.
In this case, trying to recreate the configuration would essentially result in Dynatrace creating a new ID for the resource - and at the same time the ID of the resource in your state file remains the same.
I will keep this issue open - perhaps there is a way to circumvent it, but a fix for that won't be easy.

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @franznemeth ,
The issue you've described has been taken care of with release v1.18.1. Any configuration that got deleted outside of Terraform is now getting recreated.
